#!/usr/bin/env bash
# install.sh — one-line install for Motoi Scheme.
#
# Usage:
#   curl -sSL https://raw.githubusercontent.com/Lacuna-Labs/motoi-scheme/main/install.sh | bash
#
# What it does:
#   1. Clones motoi-scheme to $MOTOI_HOME (default: ~/.motoi)
#   2. Runs npm install
#   3. Symlinks bin/motoi to ~/.local/bin/motoi (or prints instructions
#      if that dir isn't in PATH)
#
# Env:
#   MOTOI_HOME   install dir (default: ~/.motoi)
#   MOTOI_REF    git ref to check out (default: main)

set -euo pipefail

MOTOI_HOME="${MOTOI_HOME:-$HOME/.motoi}"
MOTOI_REF="${MOTOI_REF:-main}"
BIN_TARGET="$HOME/.local/bin"
REPO_URL="https://github.com/Lacuna-Labs/motoi-scheme.git"

say() { printf '\033[1;35m[motoi]\033[0m %s\n' "$*"; }
warn() { printf '\033[1;33m[motoi]\033[0m %s\n' "$*"; }
die() { printf '\033[1;31m[motoi]\033[0m %s\n' "$*" >&2; exit 1; }

command -v git >/dev/null 2>&1 || die "git is required. Install git and re-run."
command -v node >/dev/null 2>&1 || die "node is required (>= 20.16). Install Node.js and re-run."
command -v npm >/dev/null 2>&1 || die "npm is required. Install Node.js and re-run."

NODE_MAJOR=$(node -p "process.versions.node.split('.')[0]")
if [ "$NODE_MAJOR" -lt 20 ]; then
  die "node $NODE_MAJOR is too old — need >= 20.16. Update Node and re-run."
fi

say "installing Motoi Scheme to $MOTOI_HOME"

MOTOI_USER="$HOME/motoi"

if [ -d "$MOTOI_HOME/.git" ]; then
  say "existing install found — pulling latest"
  # `npm install` regenerates package-lock.json locally; that shows up as a
  # git modification and blocks `git pull --ff-only`. Discard local
  # modifications to files npm/node manage themselves — they'll be
  # regenerated by the `npm install` step below.
  (cd "$MOTOI_HOME" && \
    git fetch origin && \
    git checkout "$MOTOI_REF" && \
    git checkout -- package-lock.json 2>/dev/null || true; \
    git pull --ff-only)
elif [ -d "$MOTOI_HOME" ]; then
  # $MOTOI_HOME exists but isn't a git checkout — probably a legacy install
  # from before user-data moved to ~/motoi/. Preserve any user files, then
  # remove and clone fresh. Never overwrites files already at ~/motoi/.
  say "preserving legacy user data at ~/motoi/ before re-install"
  mkdir -p "$MOTOI_USER"
  for f in cortex.slat reading-state.slat; do
    if [ -f "$MOTOI_HOME/$f" ] && [ ! -f "$MOTOI_USER/$f" ]; then
      mv "$MOTOI_HOME/$f" "$MOTOI_USER/$f" && say "  moved $f → ~/motoi/"
    fi
  done
  for d in artifacts carts saves; do
    if [ -d "$MOTOI_HOME/$d" ]; then
      mkdir -p "$MOTOI_USER/$d"
      for item in "$MOTOI_HOME/$d"/*; do
        [ -e "$item" ] || continue
        name=$(basename "$item")
        if [ ! -e "$MOTOI_USER/$d/$name" ]; then
          mv "$item" "$MOTOI_USER/$d/$name"
        fi
      done
      say "  merged $d/ → ~/motoi/$d/"
    fi
  done
  say "removing legacy ~/.motoi/ install"
  rm -rf "$MOTOI_HOME"
  say "cloning $REPO_URL"
  git clone --depth 1 --branch "$MOTOI_REF" "$REPO_URL" "$MOTOI_HOME"
else
  say "cloning $REPO_URL"
  git clone --depth 1 --branch "$MOTOI_REF" "$REPO_URL" "$MOTOI_HOME"
fi

say "installing npm dependencies (this is a few seconds)"
(cd "$MOTOI_HOME" && npm install --silent --no-audit --no-fund)

say "linking motoi to $BIN_TARGET/motoi"
mkdir -p "$BIN_TARGET"
ln -sf "$MOTOI_HOME/bin/motoi" "$BIN_TARGET/motoi"

if ! echo ":$PATH:" | grep -q ":$BIN_TARGET:"; then
  warn "$BIN_TARGET is not in your PATH."
  warn "Add this to your shell rc file (~/.zshrc or ~/.bashrc):"
  warn "  export PATH=\"$BIN_TARGET:\$PATH\""
fi

say "done. Try:"
say "  motoi run $MOTOI_HOME/carts/cart-pico8-demo/pico8-dots.scm"
say ""
say "or start the REPL:"
say "  motoi repl"
