"""Physics laws, principles, and theorems. Target ~200 nodes.

Sources: Wikipedia physics-law articles, OpenStax University Physics vols 1-3,
NIST reference data. All discoverer + year claims cite the corresponding
Wikipedia article by URL in :provenance.
"""

from _helpers import S, PERSON, INSTITUTION, WORK


def W(name):
    """Shortcut for Wikipedia provenance."""
    return [{"source": "wikipedia", "url": f"https://en.wikipedia.org/wiki/{name}"}]


def WD(qid, name=None):
    """Wikidata + optional Wikipedia."""
    p = [{"source": "wikidata", "qid": qid}]
    if name:
        p.append({"source": "wikipedia", "url": f"https://en.wikipedia.org/wiki/{name}"})
    return p


SCIENCES = [
    # ---------- CLASSICAL MECHANICS ----------
    S("Newton's First Law of Motion", "physics", ["law", "principle"],
      id_slug="newtons-first-law",
      extras=["law of inertia", "first law of motion", "Newton I", "prima lex"],
      described_by=[PERSON("newton-isaac")], described_year=1687,
      described_in=WORK("principia-mathematica"),
      applies=[":classical-regime", ":everyday", ":engineering"],
      formula="F_net = 0 ⇒ dv/dt = 0",
      narrative="An object at rest stays at rest and one in motion stays in motion at constant velocity unless acted on by an outside force.",
      everyday="A hockey puck sliding on smooth ice keeps going until friction or a wall stops it.",
      subsumed_by="classical-mechanics",
      related=[("newtons-second-law", 0.95), ("newtons-third-law", 0.9), ("galilean-relativity", 0.7)],
      provenance=WD("Q2091944", "Newton's_laws_of_motion")),

    S("Newton's Second Law of Motion", "physics", ["law"],
      id_slug="newtons-second-law",
      extras=["F=ma", "second law of motion", "Newton II"],
      described_by=[PERSON("newton-isaac")], described_year=1687,
      described_in=WORK("principia-mathematica"),
      applies=[":classical-regime", ":everyday", ":engineering"],
      formula="F = m·a",
      units="N (newtons)",
      narrative="The net force on an object equals its mass times its acceleration.",
      everyday="Push a shopping cart twice as hard and it accelerates twice as fast.",
      subsumed_by="classical-mechanics",
      related=[("newtons-first-law", 0.95), ("newtons-third-law", 0.9), ("momentum", 0.85)],
      provenance=WD("Q2091944", "Newton's_laws_of_motion")),

    S("Newton's Third Law of Motion", "physics", ["law"],
      id_slug="newtons-third-law",
      extras=["action-reaction", "third law of motion", "Newton III"],
      described_by=[PERSON("newton-isaac")], described_year=1687,
      described_in=WORK("principia-mathematica"),
      applies=[":classical-regime", ":everyday", ":engineering"],
      formula="F_AB = −F_BA",
      narrative="For every action there is an equal and opposite reaction.",
      everyday="A swimmer pushes water backward; the water pushes the swimmer forward.",
      subsumed_by="classical-mechanics",
      related=[("newtons-first-law", 0.9), ("newtons-second-law", 0.9), ("conservation-of-momentum", 0.85)],
      provenance=WD("Q2091944", "Newton's_laws_of_motion")),

    S("Newton's Law of Universal Gravitation", "physics", ["law"],
      id_slug="newtons-law-of-gravitation",
      extras=["universal gravitation", "law of gravitation", "inverse-square law of gravity"],
      described_by=[PERSON("newton-isaac")], described_year=1687,
      described_in=WORK("principia-mathematica"),
      applies=[":classical-regime", ":astrophysical", ":everyday"],
      formula="F = G·m₁·m₂ / r²",
      units="N (newtons)",
      narrative="Every mass attracts every other mass with a force proportional to their masses and inversely proportional to the square of the distance between them.",
      everyday="The moon orbits the Earth because Earth pulls on it; the Earth orbits the sun for the same reason.",
      subsumed_by="classical-mechanics",
      related=[("keplers-laws", 0.9), ("general-relativity", 0.6), ("gravitational-constant", 0.95)],
      provenance=WD("Q11412", "Newton's_law_of_universal_gravitation")),

    S("Kepler's Laws of Planetary Motion", "physics", ["law"],
      id_slug="keplers-laws",
      extras=["Kepler's first law", "Kepler's second law", "Kepler's third law", "laws of planetary motion"],
      described_by=[PERSON("kepler-johannes")], described_year=1619,
      applies=[":astrophysical", ":classical-regime"],
      formula="T² ∝ a³",
      narrative="Planets orbit in ellipses with the sun at one focus, sweep equal areas in equal times, and their period squared is proportional to semi-major axis cubed.",
      everyday="Earth speeds up when it swings near the sun each January and slows down at aphelion in July.",
      subsumed_by="classical-mechanics",
      related=[("newtons-law-of-gravitation", 0.9), ("copernican-model", 0.8)],
      provenance=WD("Q80764", "Kepler's_laws_of_planetary_motion")),

    S("Conservation of Momentum", "physics", ["law", "principle"],
      id_slug="conservation-of-momentum",
      extras=["momentum conservation", "law of conservation of momentum"],
      described_by=[PERSON("newton-isaac"), PERSON("descartes-rene")],
      described_year=1644,
      applies=[":classical-regime", ":quantum-regime", ":relativistic-regime"],
      formula="Σp_before = Σp_after",
      units="kg·m/s",
      narrative="In an isolated system the total momentum before an interaction equals the total momentum after.",
      everyday="A billiard ball striking another at rest passes its momentum on and stops.",
      subsumed_by="conservation-laws",
      related=[("newtons-third-law", 0.9), ("noethers-theorem", 0.85), ("momentum", 0.95)],
      provenance=WD("Q1516226", "Momentum")),

    S("Conservation of Energy", "physics", ["law", "principle"],
      id_slug="conservation-of-energy",
      extras=["first law of thermodynamics", "law of energy conservation", "energy conservation"],
      described_by=[PERSON("joule-james-prescott"), PERSON("helmholtz-hermann")],
      described_year=1850,
      applies=[":classical-regime", ":quantum-regime", ":relativistic-regime", ":everyday"],
      formula="ΔE_total = 0 (in a closed system)",
      units="J (joules)",
      narrative="Energy cannot be created or destroyed, only converted between forms.",
      everyday="A pendulum trades kinetic energy for potential energy each swing; total stays the same until friction bleeds it into heat.",
      subsumed_by="conservation-laws",
      related=[("first-law-of-thermodynamics", 1.0), ("noethers-theorem", 0.85), ("mass-energy-equivalence", 0.7)],
      provenance=WD("Q11402", "Conservation_of_energy")),

    S("Conservation of Angular Momentum", "physics", ["law"],
      id_slug="conservation-of-angular-momentum",
      extras=["angular momentum conservation", "law of angular momentum"],
      described_by=[PERSON("newton-isaac")], described_year=1687,
      applies=[":classical-regime", ":quantum-regime", ":astrophysical"],
      formula="L = I·ω; ΔL = 0 (no external torque)",
      units="kg·m²/s",
      narrative="When no external torque acts, a system's total angular momentum stays constant.",
      everyday="A figure skater pulls her arms in and spins faster.",
      subsumed_by="conservation-laws",
      related=[("noethers-theorem", 0.85), ("angular-momentum", 0.95)],
      provenance=WD("Q161254", "Angular_momentum")),

    S("Noether's Theorem", "physics", ["theorem"],
      id_slug="noethers-theorem",
      extras=["Noether theorem", "Noether's first theorem", "symmetry-conservation theorem"],
      described_by=[PERSON("noether-emmy")], described_year=1918,
      hosted_at=[INSTITUTION("gottingen-university")],
      applies=[":classical-regime", ":quantum-regime", ":theoretical-only"],
      narrative="Every continuous symmetry of a physical system corresponds to a conservation law.",
      everyday="Time symmetry gives energy conservation; space symmetry gives momentum conservation; rotational symmetry gives angular momentum conservation.",
      subsumed_by="classical-mechanics",
      related=[("conservation-of-energy", 0.9), ("conservation-of-momentum", 0.9), ("conservation-of-angular-momentum", 0.9)],
      provenance=WD("Q179692", "Noether's_theorem")),

    S("Hamilton's Principle", "physics", ["principle"],
      id_slug="hamiltons-principle",
      extras=["principle of least action", "stationary-action principle", "variational principle"],
      described_by=[PERSON("hamilton-william-rowan")], described_year=1834,
      applies=[":classical-regime", ":quantum-regime", ":theoretical-only"],
      formula="δS = 0, S = ∫ L dt",
      narrative="Physical systems take the path that makes the action stationary.",
      everyday="Light between two points travels along the path that takes the least time.",
      subsumed_by="classical-mechanics",
      related=[("lagrangian-mechanics", 0.95), ("fermats-principle", 0.85)],
      provenance=WD("Q17140", "Hamilton's_principle")),

    S("Lagrangian Mechanics", "physics", ["framework"],
      id_slug="lagrangian-mechanics",
      described_by=[PERSON("lagrange-joseph-louis")], described_year=1788,
      applies=[":classical-regime", ":theoretical-only"],
      formula="L = T − V; d/dt(∂L/∂q̇) − ∂L/∂q = 0",
      narrative="A reformulation of Newtonian mechanics using energies instead of forces; the Euler-Lagrange equations give the equations of motion.",
      subsumed_by="classical-mechanics",
      related=[("hamiltons-principle", 0.95), ("hamiltonian-mechanics", 0.9)],
      provenance=WD("Q188893", "Lagrangian_mechanics")),

    S("Hamiltonian Mechanics", "physics", ["framework"],
      id_slug="hamiltonian-mechanics",
      described_by=[PERSON("hamilton-william-rowan")], described_year=1833,
      applies=[":classical-regime", ":quantum-regime"],
      formula="H = T + V; q̇ = ∂H/∂p, ṗ = −∂H/∂q",
      narrative="A reformulation of mechanics using coordinates and momenta as independent variables; the natural bridge to quantum mechanics.",
      subsumed_by="classical-mechanics",
      related=[("lagrangian-mechanics", 0.9), ("quantum-mechanics", 0.85)],
      provenance=WD("Q756033", "Hamiltonian_mechanics")),

    S("Galilean Relativity", "physics", ["principle"],
      id_slug="galilean-relativity",
      extras=["Galilean invariance", "Galilean principle of relativity"],
      described_by=[PERSON("galileo-galilei")], described_year=1632,
      applies=[":classical-regime"],
      narrative="The laws of mechanics take the same form in any inertial reference frame moving at constant velocity relative to another.",
      everyday="A ball thrown straight up inside a train moving at constant speed lands back in your hand.",
      subsumed_by="classical-mechanics",
      contradicts=None,
      related=[("special-relativity", 0.7)],
      provenance=WD("Q1074469", "Galilean_invariance")),

    # ---------- RELATIVITY ----------
    S("Special Relativity", "physics", ["framework"],
      id_slug="special-relativity",
      extras=["theory of special relativity", "SR", "restricted relativity"],
      described_by=[PERSON("einstein-albert")], described_year=1905,
      hosted_at=[INSTITUTION("swiss-patent-office")],
      described_in=WORK("on-the-electrodynamics-of-moving-bodies"),
      applies=[":relativistic-regime", ":high-energy"],
      formula="ds² = −c²·dt² + dx² + dy² + dz²",
      narrative="Space and time form a single four-dimensional continuum; the speed of light is the same in every inertial frame.",
      everyday="Muons produced in the upper atmosphere reach the ground because their moving clocks run slow relative to ours.",
      subsumed_by="relativity",
      related=[("general-relativity", 0.9), ("mass-energy-equivalence", 0.95), ("lorentz-invariance", 0.9)],
      provenance=WD("Q11455", "Special_relativity")),

    S("General Relativity", "physics", ["framework", "law"],
      id_slug="general-relativity",
      extras=["theory of general relativity", "GR", "Einstein's theory of gravity"],
      described_by=[PERSON("einstein-albert")], described_year=1915,
      hosted_at=[INSTITUTION("prussian-academy-of-sciences")],
      applies=[":relativistic-regime", ":astrophysical", ":cosmology"],
      formula="G_μν + Λ·g_μν = (8πG/c⁴)·T_μν",
      narrative="Gravity is the curvature of spacetime caused by mass and energy; freely falling objects follow geodesics in that curved geometry.",
      everyday="GPS satellites have to correct for the slower ticking of clocks nearer Earth's mass.",
      subsumed_by="relativity",
      appears_in_event=["event-1919-eclipse"],
      related=[("special-relativity", 0.9), ("newtons-law-of-gravitation", 0.6), ("black-hole", 0.85)],
      provenance=WD("Q11452", "General_relativity")),

    S("Mass-Energy Equivalence", "physics", ["principle"],
      id_slug="mass-energy-equivalence",
      extras=["E=mc²", "E=mc2", "Einstein mass-energy relation"],
      described_by=[PERSON("einstein-albert")], described_year=1905,
      applies=[":relativistic-regime", ":subatomic", ":cosmology"],
      formula="E = m·c²",
      units="J (joules)",
      narrative="Mass and energy are two aspects of the same conserved quantity; a small amount of mass carries a large amount of energy because c is very large.",
      everyday="Nuclear reactors and stars convert a small fraction of their mass into heat and light.",
      subsumed_by="relativity",
      related=[("special-relativity", 0.95), ("conservation-of-energy", 0.7)],
      provenance=WD("Q11373", "Mass-energy_equivalence")),

    S("Equivalence Principle", "physics", ["principle"],
      id_slug="equivalence-principle",
      extras=["Einstein equivalence principle", "weak equivalence principle", "strong equivalence principle"],
      described_by=[PERSON("einstein-albert")], described_year=1907,
      applies=[":relativistic-regime"],
      narrative="Locally, gravity and acceleration are indistinguishable — a person in a windowless elevator cannot tell whether they are on Earth or in a rocket accelerating at 1g.",
      subsumed_by="general-relativity",
      related=[("general-relativity", 0.95), ("gravitational-time-dilation", 0.85)],
      provenance=WD("Q207569", "Equivalence_principle")),

    S("Lorentz Invariance", "physics", ["principle"],
      id_slug="lorentz-invariance",
      extras=["Lorentz symmetry", "Lorentz covariance"],
      described_by=[PERSON("lorentz-hendrik"), PERSON("einstein-albert")],
      described_year=1904,
      applies=[":relativistic-regime", ":subatomic"],
      narrative="The laws of physics are the same in all inertial frames related by Lorentz transformations.",
      subsumed_by="special-relativity",
      related=[("special-relativity", 0.95), ("noethers-theorem", 0.7)],
      provenance=WD("Q744749", "Lorentz_covariance")),

    # ---------- THERMODYNAMICS ----------
    S("Zeroth Law of Thermodynamics", "thermodynamics", ["law"],
      id_slug="zeroth-law-of-thermodynamics",
      extras=["zeroth law", "0th law of thermodynamics"],
      described_by=[PERSON("fowler-ralph")], described_year=1931,
      applies=[":everyday", ":engineering"],
      narrative="If two systems are each in thermal equilibrium with a third, they are in equilibrium with each other; this is what makes temperature a well-defined quantity.",
      everyday="Two rooms connected by an open door eventually reach the same temperature.",
      subsumed_by="thermodynamics",
      provenance=WD("Q211737", "Zeroth_law_of_thermodynamics")),

    S("First Law of Thermodynamics", "thermodynamics", ["law"],
      id_slug="first-law-of-thermodynamics",
      extras=["1st law of thermodynamics", "energy conservation in thermodynamics"],
      described_by=[PERSON("clausius-rudolf"), PERSON("joule-james-prescott")],
      described_year=1850,
      applies=[":everyday", ":engineering"],
      formula="ΔU = Q − W",
      units="J (joules)",
      narrative="The change in a system's internal energy equals the heat added to it minus the work it does.",
      everyday="A car engine turns chemical energy in fuel into work moving the car and waste heat out the exhaust.",
      subsumed_by="thermodynamics",
      related=[("conservation-of-energy", 1.0), ("second-law-of-thermodynamics", 0.85)],
      provenance=WD("Q131207", "First_law_of_thermodynamics")),

    S("Second Law of Thermodynamics", "thermodynamics", ["law"],
      id_slug="second-law-of-thermodynamics",
      extras=["entropy law", "2nd law of thermodynamics"],
      described_by=[PERSON("clausius-rudolf"), PERSON("carnot-sadi")],
      described_year=1850,
      applies=[":everyday", ":engineering", ":cosmology"],
      formula="ΔS_universe ≥ 0",
      units="J/K",
      narrative="The entropy of an isolated system never decreases; heat flows spontaneously from hotter to colder bodies.",
      everyday="A dropped glass shatters into pieces; the pieces do not spontaneously reassemble into a glass.",
      subsumed_by="thermodynamics",
      related=[("entropy", 1.0), ("arrow-of-time", 0.9), ("carnot-cycle", 0.85)],
      provenance=WD("Q172746", "Second_law_of_thermodynamics")),

    S("Third Law of Thermodynamics", "thermodynamics", ["law"],
      id_slug="third-law-of-thermodynamics",
      extras=["3rd law of thermodynamics", "Nernst heat theorem"],
      described_by=[PERSON("nernst-walther")], described_year=1906,
      applies=[":low-temperature", ":theoretical-only"],
      narrative="The entropy of a perfect crystal approaches zero as temperature approaches absolute zero.",
      subsumed_by="thermodynamics",
      related=[("absolute-zero", 0.95), ("entropy", 0.9)],
      provenance=WD("Q193969", "Third_law_of_thermodynamics")),

    S("Ideal Gas Law", "physics", ["law"],
      id_slug="ideal-gas-law",
      extras=["combined gas law", "PV=nRT"],
      described_by=[PERSON("clapeyron-benoit")], described_year=1834,
      applies=[":everyday", ":engineering"],
      formula="P·V = n·R·T",
      narrative="For a low-density gas, pressure times volume equals moles times the gas constant times temperature.",
      everyday="A car tire's pressure rises on a hot day because the temperature climbs.",
      subsumed_by="thermodynamics",
      related=[("boyles-law", 0.9), ("charles-law", 0.9), ("avogadros-law", 0.85)],
      provenance=WD("Q166231", "Ideal_gas_law")),

    S("Boyle's Law", "physics", ["law"],
      id_slug="boyles-law",
      described_by=[PERSON("boyle-robert")], described_year=1662,
      applies=[":everyday", ":engineering"],
      formula="P·V = k (T constant)",
      narrative="At constant temperature the pressure and volume of a gas are inversely proportional.",
      everyday="Push down on a bicycle pump and the trapped air pressure rises.",
      subsumed_by="thermodynamics",
      related=[("ideal-gas-law", 0.9), ("charles-law", 0.8)],
      provenance=WD("Q239771", "Boyle's_law")),

    S("Charles's Law", "physics", ["law"],
      id_slug="charles-law",
      described_by=[PERSON("charles-jacques")], described_year=1787,
      applies=[":everyday", ":engineering"],
      formula="V/T = k (P constant)",
      narrative="At constant pressure the volume of a gas is proportional to its absolute temperature.",
      everyday="A helium balloon shrinks when brought into a cold room.",
      subsumed_by="thermodynamics",
      related=[("ideal-gas-law", 0.9), ("boyles-law", 0.8)],
      provenance=WD("Q273269", "Charles's_law")),

    S("Avogadro's Law", "physics", ["law"],
      id_slug="avogadros-law",
      described_by=[PERSON("avogadro-amedeo")], described_year=1811,
      applies=[":everyday", ":engineering"],
      formula="V/n = k (P,T constant)",
      narrative="Equal volumes of gases at the same temperature and pressure contain equal numbers of molecules.",
      subsumed_by="thermodynamics",
      related=[("ideal-gas-law", 0.9), ("avogadros-number", 0.85)],
      provenance=WD("Q297876", "Avogadro's_law")),

    S("Fourier's Law of Heat Conduction", "physics", ["law"],
      id_slug="fouriers-law-of-heat-conduction",
      extras=["Fourier heat conduction law", "law of heat conduction"],
      described_by=[PERSON("fourier-joseph")], described_year=1822,
      applies=[":everyday", ":engineering"],
      formula="q = −k·∇T",
      units="W/m²",
      narrative="Heat flux through a material is proportional to the temperature gradient and points from hot to cold.",
      everyday="A metal pot handle heats up because heat conducts through the metal from the hot food.",
      subsumed_by="thermodynamics",
      related=[("thermal-conductivity", 0.9), ("second-law-of-thermodynamics", 0.7)],
      provenance=WD("Q4198375", "Thermal_conduction")),

    S("Stefan-Boltzmann Law", "physics", ["law"],
      id_slug="stefan-boltzmann-law",
      extras=["Stefan's law", "Stefan law", "blackbody radiation law"],
      described_by=[PERSON("stefan-josef"), PERSON("boltzmann-ludwig")],
      described_year=1879,
      applies=[":astrophysical", ":everyday", ":engineering"],
      formula="j* = σ·T⁴",
      units="W/m²",
      narrative="The total energy radiated per unit area of a black body is proportional to the fourth power of its absolute temperature.",
      everyday="A red-hot stove element radiates far more heat than a warm one because doubling temperature multiplies emission by sixteen.",
      subsumed_by="thermodynamics",
      related=[("plancks-radiation-law", 0.9), ("wiens-displacement-law", 0.85)],
      provenance=WD("Q334699", "Stefan–Boltzmann_law")),

    S("Wien's Displacement Law", "physics", ["law"],
      id_slug="wiens-displacement-law",
      described_by=[PERSON("wien-wilhelm")], described_year=1893,
      applies=[":astrophysical", ":everyday"],
      formula="λ_max · T = b (b ≈ 2.898×10⁻³ m·K)",
      narrative="The wavelength at which a blackbody radiates most strongly is inversely proportional to its temperature.",
      everyday="A cooler star glows red; a hotter one white or blue.",
      subsumed_by="thermodynamics",
      related=[("stefan-boltzmann-law", 0.85), ("plancks-radiation-law", 0.9)],
      provenance=WD("Q580810", "Wien's_displacement_law")),

    S("Planck's Radiation Law", "physics", ["law"],
      id_slug="plancks-radiation-law",
      extras=["Planck's law", "Planck radiation formula"],
      described_by=[PERSON("planck-max")], described_year=1900,
      applies=[":quantum-regime", ":astrophysical"],
      formula="B(ν,T) = (2hν³/c²) · 1/(e^(hν/kT) − 1)",
      narrative="The spectral radiance of a black body at temperature T; the formula that launched quantum mechanics by requiring energy to come in discrete quanta.",
      subsumed_by="quantum-mechanics",
      related=[("stefan-boltzmann-law", 0.9), ("wiens-displacement-law", 0.9), ("photon", 0.85)],
      provenance=WD("Q193824", "Planck's_law")),

    # ---------- ELECTROMAGNETISM ----------
    S("Coulomb's Law", "physics", ["law"],
      id_slug="coulombs-law",
      described_by=[PERSON("coulomb-charles-augustin")], described_year=1785,
      applies=[":classical-regime", ":everyday", ":engineering"],
      formula="F = k·q₁·q₂ / r²",
      units="N (newtons)",
      narrative="The force between two electric charges is proportional to the product of their charges and inversely proportional to the square of the distance between them.",
      everyday="A balloon rubbed on hair sticks to a wall because of static charge attraction.",
      subsumed_by="electromagnetism",
      related=[("electric-charge", 0.95), ("gausss-law", 0.85), ("newtons-law-of-gravitation", 0.6)],
      provenance=WD("Q41374", "Coulomb's_law")),

    S("Gauss's Law", "physics", ["law"],
      id_slug="gausss-law",
      described_by=[PERSON("gauss-carl-friedrich")], described_year=1835,
      applies=[":classical-regime", ":engineering"],
      formula="∮ E·dA = Q_enc/ε₀",
      narrative="The electric flux through any closed surface equals the enclosed charge divided by the permittivity of free space.",
      subsumed_by="electromagnetism",
      related=[("maxwells-equations", 0.95), ("coulombs-law", 0.85)],
      provenance=WD("Q170627", "Gauss's_law")),

    S("Gauss's Law for Magnetism", "physics", ["law"],
      id_slug="gauss-law-for-magnetism",
      applies=[":classical-regime"],
      formula="∮ B·dA = 0",
      narrative="The net magnetic flux through any closed surface is zero — there are no magnetic monopoles.",
      subsumed_by="electromagnetism",
      related=[("maxwells-equations", 0.95), ("magnetic-monopole", 0.7)],
      provenance=WD("Q1194189", "Gauss's_law_for_magnetism")),

    S("Faraday's Law of Induction", "physics", ["law"],
      id_slug="faradays-law-of-induction",
      described_by=[PERSON("faraday-michael")], described_year=1831,
      hosted_at=[INSTITUTION("royal-institution")],
      applies=[":classical-regime", ":engineering", ":everyday"],
      formula="EMF = −dΦ_B/dt",
      units="V (volts)",
      narrative="A changing magnetic flux through a loop induces an electromotive force in the loop.",
      everyday="Turning a bicycle dynamo makes a magnet spin past coils and produces electricity for the headlight.",
      subsumed_by="electromagnetism",
      related=[("maxwells-equations", 0.95), ("lenzs-law", 0.9), ("electromagnetic-induction", 0.95)],
      provenance=WD("Q179143", "Faraday's_law_of_induction")),

    S("Ampère's Circuital Law", "physics", ["law"],
      id_slug="amperes-law",
      extras=["Ampère's law", "Ampère-Maxwell law"],
      described_by=[PERSON("ampere-andre-marie")], described_year=1826,
      applies=[":classical-regime", ":engineering"],
      formula="∮ B·dℓ = μ₀·(I_enc + ε₀·dΦ_E/dt)",
      narrative="The magnetic field integrated around a closed loop is proportional to the electric current passing through and the rate of change of the enclosed electric flux.",
      subsumed_by="electromagnetism",
      related=[("maxwells-equations", 0.95), ("faradays-law-of-induction", 0.85)],
      provenance=WD("Q334373", "Ampère's_circuital_law")),

    S("Maxwell's Equations", "physics", ["framework", "law"],
      id_slug="maxwells-equations",
      described_by=[PERSON("maxwell-james-clerk")], described_year=1865,
      hosted_at=[INSTITUTION("kings-college-london")],
      applies=[":classical-regime", ":engineering", ":everyday"],
      formula="∇·E = ρ/ε₀; ∇·B = 0; ∇×E = −∂B/∂t; ∇×B = μ₀·(J + ε₀·∂E/∂t)",
      narrative="Four equations that together describe how electric and magnetic fields are produced by charges and currents and how each affects the other; imply the existence of electromagnetic waves traveling at the speed of light.",
      everyday="Every antenna, motor, generator, and wireless signal is a consequence of these four equations.",
      subsumed_by="electromagnetism",
      related=[("gausss-law", 0.95), ("faradays-law-of-induction", 0.95), ("amperes-law", 0.95), ("electromagnetic-wave", 0.95)],
      provenance=WD("Q127950", "Maxwell's_equations")),

    S("Lenz's Law", "physics", ["law"],
      id_slug="lenzs-law",
      described_by=[PERSON("lenz-heinrich")], described_year=1834,
      applies=[":classical-regime", ":engineering"],
      narrative="The direction of an induced current is such as to oppose the change in flux that produced it.",
      everyday="A magnet dropped through a copper tube falls slowly because the induced currents in the tube push back.",
      subsumed_by="electromagnetism",
      related=[("faradays-law-of-induction", 0.9), ("eddy-current", 0.85)],
      provenance=WD("Q233129", "Lenz's_law")),

    S("Ohm's Law", "physics", ["law"],
      id_slug="ohms-law",
      described_by=[PERSON("ohm-georg-simon")], described_year=1827,
      applies=[":classical-regime", ":engineering", ":everyday"],
      formula="V = I·R",
      units="V (volts)",
      narrative="The voltage across a conductor is proportional to the current through it, with the constant of proportionality called resistance.",
      everyday="A dimmer switch works by inserting more resistance in series with a bulb, dropping the voltage across it.",
      subsumed_by="electromagnetism",
      related=[("electric-resistance", 0.95), ("kirchhoffs-laws", 0.85)],
      provenance=WD("Q47083", "Ohm's_law")),

    S("Kirchhoff's Circuit Laws", "physics", ["law"],
      id_slug="kirchhoffs-laws",
      extras=["Kirchhoff's current law", "Kirchhoff's voltage law", "KCL", "KVL"],
      described_by=[PERSON("kirchhoff-gustav")], described_year=1845,
      applies=[":classical-regime", ":engineering"],
      formula="ΣI_in = ΣI_out at each node; ΣV around a loop = 0",
      narrative="Currents into a junction sum to currents out; voltage drops around any closed loop sum to zero.",
      subsumed_by="electromagnetism",
      related=[("ohms-law", 0.9), ("conservation-of-charge", 0.85)],
      provenance=WD("Q725690", "Kirchhoff's_circuit_laws")),

    S("Lorentz Force Law", "physics", ["law"],
      id_slug="lorentz-force-law",
      described_by=[PERSON("lorentz-hendrik")], described_year=1892,
      applies=[":classical-regime", ":engineering", ":subatomic"],
      formula="F = q·(E + v×B)",
      units="N (newtons)",
      narrative="The force on a charged particle in electric and magnetic fields.",
      everyday="A CRT television deflects electron beams using magnetic fields; the same law drives cyclotrons and mass spectrometers.",
      subsumed_by="electromagnetism",
      related=[("maxwells-equations", 0.9), ("electric-charge", 0.9)],
      provenance=WD("Q182295", "Lorentz_force")),

    S("Snell's Law", "physics", ["law"],
      id_slug="snells-law",
      extras=["Snell-Descartes law", "law of refraction"],
      described_by=[PERSON("snell-willebrord")], described_year=1621,
      applies=[":classical-regime", ":everyday", ":engineering"],
      formula="n₁·sin(θ₁) = n₂·sin(θ₂)",
      narrative="When light passes from one medium to another the ratio of the sines of the incident and refracted angles equals the inverse ratio of refractive indices.",
      everyday="A straight straw in a glass of water looks bent at the water line.",
      subsumed_by="optics",
      related=[("refraction", 0.95), ("refractive-index", 0.95), ("fermats-principle", 0.85)],
      provenance=WD("Q170955", "Snell's_law")),

    S("Fermat's Principle", "physics", ["principle"],
      id_slug="fermats-principle",
      extras=["principle of least time", "Fermat's principle of least time"],
      described_by=[PERSON("fermat-pierre")], described_year=1662,
      applies=[":classical-regime"],
      narrative="Light traveling between two points takes the path that requires stationary (usually minimum) time.",
      subsumed_by="optics",
      related=[("snells-law", 0.9), ("hamiltons-principle", 0.85)],
      provenance=WD("Q472268", "Fermat's_principle")),

    S("Malus's Law", "physics", ["law"],
      id_slug="maluss-law",
      described_by=[PERSON("malus-etienne-louis")], described_year=1809,
      applies=[":classical-regime", ":engineering"],
      formula="I = I₀·cos²(θ)",
      narrative="Intensity of polarized light through a polarizer is proportional to the cosine squared of the angle between light polarization and polarizer axis.",
      everyday="Polarized sunglasses cut glare from a wet road because reflected light is partially polarized horizontally.",
      subsumed_by="optics",
      related=[("polarization", 0.95)],
      provenance=WD("Q3283345", "Polarizer")),

    # ---------- QUANTUM MECHANICS ----------
    S("Schrödinger Equation", "physics", ["equation", "law"],
      id_slug="schrodinger-equation",
      extras=["time-dependent Schrödinger equation", "TDSE", "wave equation"],
      described_by=[PERSON("schrodinger-erwin")], described_year=1926,
      hosted_at=[INSTITUTION("university-of-zurich")],
      applies=[":quantum-regime", ":subatomic"],
      formula="i·ℏ·∂ψ/∂t = Ĥ·ψ",
      narrative="Governs how quantum wavefunctions evolve in time; the quantum analog of Newton's second law.",
      subsumed_by="quantum-mechanics",
      related=[("wavefunction", 0.95), ("heisenberg-uncertainty-principle", 0.8), ("plancks-radiation-law", 0.75)],
      provenance=WD("Q165498", "Schrödinger_equation")),

    S("Heisenberg Uncertainty Principle", "physics", ["principle", "law"],
      id_slug="heisenberg-uncertainty-principle",
      extras=["uncertainty principle", "indeterminacy principle"],
      described_by=[PERSON("heisenberg-werner")], described_year=1927,
      applies=[":quantum-regime", ":subatomic"],
      formula="Δx·Δp ≥ ℏ/2",
      narrative="It is impossible to simultaneously know both the exact position and the exact momentum of a particle; the product of the uncertainties has a floor set by Planck's constant.",
      everyday="Zero-point motion means even at absolute zero the atoms in a crystal never truly stop jiggling.",
      subsumed_by="quantum-mechanics",
      related=[("wavefunction", 0.85), ("wave-particle-duality", 0.85), ("schrodinger-equation", 0.8)],
      provenance=WD("Q45403", "Uncertainty_principle")),

    S("Wave-Particle Duality", "physics", ["principle"],
      id_slug="wave-particle-duality",
      extras=["de Broglie hypothesis", "matter-wave duality"],
      described_by=[PERSON("de-broglie-louis"), PERSON("einstein-albert")],
      described_year=1924,
      applies=[":quantum-regime", ":subatomic"],
      formula="λ = h/p",
      narrative="Every particle behaves both as a wave and as a particle; the wavelength is Planck's constant divided by momentum.",
      everyday="Electrons form interference patterns in a double-slit experiment despite being 'particles'.",
      subsumed_by="quantum-mechanics",
      related=[("heisenberg-uncertainty-principle", 0.85), ("photon", 0.9), ("electron-diffraction", 0.9)],
      provenance=WD("Q629006", "Wave–particle_duality")),

    S("Pauli Exclusion Principle", "physics", ["principle", "law"],
      id_slug="pauli-exclusion-principle",
      described_by=[PERSON("pauli-wolfgang")], described_year=1925,
      applies=[":quantum-regime", ":subatomic", ":materials"],
      narrative="No two identical fermions can occupy the same quantum state simultaneously.",
      everyday="Chemistry works because electrons stack into shells rather than piling into the lowest energy level.",
      subsumed_by="quantum-mechanics",
      related=[("fermion", 0.95), ("electron-shell", 0.9), ("periodic-table", 0.85)],
      provenance=WD("Q131594", "Pauli_exclusion_principle")),

    S("Born Rule", "physics", ["principle"],
      id_slug="born-rule",
      described_by=[PERSON("born-max")], described_year=1926,
      applies=[":quantum-regime"],
      formula="P(x) = |ψ(x)|²",
      narrative="The probability of finding a particle at a given point equals the squared magnitude of its wavefunction there.",
      subsumed_by="quantum-mechanics",
      related=[("schrodinger-equation", 0.95), ("wavefunction", 0.95)],
      provenance=WD("Q900684", "Born_rule")),

    S("Correspondence Principle", "physics", ["principle"],
      id_slug="correspondence-principle",
      described_by=[PERSON("bohr-niels")], described_year=1920,
      applies=[":quantum-regime", ":classical-regime"],
      narrative="Quantum mechanics reproduces classical mechanics in the limit of large quantum numbers or short wavelengths.",
      subsumed_by="quantum-mechanics",
      related=[("classical-mechanics", 0.85), ("quantum-mechanics", 0.9)],
      provenance=WD("Q1002697", "Correspondence_principle")),

    # ---------- HISTORICAL / SUPERSEDED ----------
    S("Phlogiston Theory", "chemistry", ["framework"],
      id_slug="phlogiston-theory",
      extras=["phlogiston", "phlogisticated air"],
      described_by=[PERSON("becher-johann-joachim"), PERSON("stahl-georg-ernst")],
      described_year=1667,
      status=":superseded",
      superseded_by="oxygen-theory-of-combustion",
      era=(1667, 1783),
      applies=[":historical-only"],
      narrative="Held that combustible materials contained a fire-like element called phlogiston released during burning; replaced when oxygen was recognized as the actual reactant.",
      subsumed_by="chemistry",
      related=[("oxygen-theory-of-combustion", 0.95), ("combustion", 0.85)],
      provenance=WD("Q209122", "Phlogiston_theory")),

    S("Luminiferous Aether", "physics", ["framework"],
      id_slug="luminiferous-aether",
      extras=["aether", "ether", "ether wind", "luminiferous ether"],
      status=":superseded",
      superseded_by="special-relativity",
      era=(1690, 1905),
      described_year=1690,
      applies=[":historical-only"],
      narrative="A hypothetical rigid but massless medium believed to fill all space and carry light waves; the Michelson-Morley experiment found no evidence for it and special relativity dispensed with the concept.",
      subsumed_by="physics",
      related=[("michelson-morley-experiment", 0.95), ("special-relativity", 0.9)],
      appears_in_event=["event-michelson-morley-experiment"],
      provenance=WD("Q683425", "Luminiferous_aether")),

    S("Caloric Theory", "thermodynamics", ["framework"],
      id_slug="caloric-theory",
      extras=["caloric", "caloric fluid"],
      described_by=[PERSON("lavoisier-antoine")],
      described_year=1783,
      status=":superseded",
      superseded_by="kinetic-theory-of-gases",
      era=(1783, 1850),
      applies=[":historical-only"],
      narrative="Held that heat is a self-repellent fluid called caloric that flowed from hot bodies to cold; replaced when heat was shown to be molecular kinetic energy.",
      subsumed_by="thermodynamics",
      related=[("kinetic-theory-of-gases", 0.95), ("first-law-of-thermodynamics", 0.7)],
      provenance=WD("Q911263", "Caloric_theory")),

    S("Geocentric Model", "astronomy", ["framework"],
      id_slug="geocentric-model",
      extras=["Ptolemaic model", "Ptolemaic system", "Earth-centered universe"],
      described_by=[PERSON("ptolemy")], described_year=150,
      status=":superseded",
      superseded_by="heliocentric-model",
      era=(150, 1543),
      applies=[":historical-only"],
      narrative="Placed the Earth at the center of the universe with the sun, moon, and planets orbiting it; the standard cosmological model of the ancient and medieval world.",
      subsumed_by="astronomy",
      related=[("heliocentric-model", 0.95), ("epicycle", 0.9)],
      provenance=WD("Q184335", "Geocentric_model")),

    S("Heliocentric Model", "astronomy", ["framework"],
      id_slug="heliocentric-model",
      extras=["Copernican model", "Copernican system", "sun-centered model"],
      described_by=[PERSON("copernicus-nicolaus")], described_year=1543,
      applies=[":astrophysical", ":historical-only"],
      narrative="Places the sun near the center of the solar system with the Earth as one of the planets orbiting it; foundational to modern astronomy.",
      subsumed_by="astronomy",
      related=[("geocentric-model", 0.95), ("keplers-laws", 0.9)],
      provenance=WD("Q102798", "Heliocentric_model")),

    S("Ptolemaic Epicycles", "astronomy", ["model"],
      id_slug="epicycle",
      extras=["epicycles", "deferent and epicycle"],
      described_by=[PERSON("ptolemy")], described_year=150,
      status=":superseded",
      superseded_by="keplers-laws",
      era=(150, 1543),
      applies=[":historical-only"],
      narrative="A geometric device in which planets moved on small circles whose centers moved along larger circles, used to reconcile the geocentric model with observed retrograde motion.",
      subsumed_by="geocentric-model",
      related=[("geocentric-model", 0.95), ("heliocentric-model", 0.9)],
      provenance=WD("Q186361", "Deferent_and_epicycle")),

    S("Lamarckian Inheritance", "biology", ["framework"],
      id_slug="lamarckian-inheritance",
      extras=["Lamarckism", "inheritance of acquired characteristics"],
      described_by=[PERSON("lamarck-jean-baptiste")], described_year=1809,
      status=":superseded",
      superseded_by="darwinian-evolution",
      era=(1809, 1900),
      applies=[":historical-only", ":biological"],
      narrative="Held that traits acquired during an organism's lifetime could be passed on to offspring; superseded by natural selection though modern epigenetics has partially rehabilitated a narrower related mechanism.",
      subsumed_by="biology",
      related=[("darwinian-evolution", 0.9), ("epigenetics", 0.5)],
      provenance=WD("Q47328", "Lamarckism")),

    S("Fixed-Continents Model", "earth-science", ["framework"],
      id_slug="fixed-continents-model",
      extras=["stationary continents", "pre-continental-drift geology"],
      status=":superseded",
      superseded_by="plate-tectonics",
      era=(1600, 1965),
      described_year=1600,
      applies=[":historical-only"],
      narrative="Held that continents were immobile fixtures of the crust and geological features arose from vertical uplift and erosion alone; superseded by plate tectonics.",
      subsumed_by="earth-science",
      related=[("plate-tectonics", 0.95), ("continental-drift", 0.9)],
      provenance=WD("Q7188081", "Fixism")),

    S("Four Humors", "medicine", ["framework"],
      id_slug="four-humors",
      extras=["humorism", "four humours", "humoral theory"],
      described_by=[PERSON("hippocrates"), PERSON("galen")],
      described_year=-400,
      status=":superseded",
      era=(-400, 1858),
      applies=[":historical-only"],
      narrative="Ancient Greek medical theory that health depends on the balance of four bodily fluids — blood, phlegm, yellow bile, black bile — each tied to a temperament; dominant for two millennia and superseded by germ theory and cell theory.",
      subsumed_by="medicine",
      related=[("germ-theory-of-disease", 0.85), ("cell-theory", 0.6)],
      provenance=WD("Q193414", "Humorism")),

    S("Miasma Theory", "medicine", ["framework"],
      id_slug="miasma-theory",
      extras=["miasma", "bad air theory"],
      status=":superseded",
      superseded_by="germ-theory-of-disease",
      era=(-400, 1880),
      described_year=-400,
      applies=[":historical-only"],
      narrative="Held that diseases like cholera and plague were caused by bad air rising from decaying matter; superseded by the germ theory once microorganisms were identified as pathogens.",
      subsumed_by="medicine",
      related=[("germ-theory-of-disease", 0.95), ("cholera", 0.8)],
      provenance=WD("Q194209", "Miasma_theory")),

    # ---------- CONSERVATION-LAWS (container node) ----------
    S("Conservation Laws", "physics", ["framework"],
      id_slug="conservation-laws",
      applies=[":classical-regime", ":quantum-regime", ":cosmology"],
      narrative="Family of laws stating that certain quantities remain constant in an isolated system: energy, momentum, angular momentum, electric charge, baryon number, lepton number.",
      subsumed_by="physics",
      subsumes=["conservation-of-energy", "conservation-of-momentum",
                "conservation-of-angular-momentum", "conservation-of-charge",
                "conservation-of-baryon-number", "conservation-of-lepton-number"],
      related=[("noethers-theorem", 0.95)],
      provenance=WD("Q80962", "Conservation_law")),

    S("Conservation of Electric Charge", "physics", ["law"],
      id_slug="conservation-of-charge",
      extras=["charge conservation"],
      described_by=[PERSON("franklin-benjamin")], described_year=1747,
      applies=[":classical-regime", ":quantum-regime", ":everyday"],
      narrative="The total electric charge in an isolated system remains constant.",
      subsumed_by="conservation-laws",
      related=[("noethers-theorem", 0.85), ("electric-charge", 0.95)],
      provenance=WD("Q1145035", "Charge_conservation")),

    S("Conservation of Baryon Number", "physics", ["law"],
      id_slug="conservation-of-baryon-number",
      applies=[":quantum-regime", ":subatomic"],
      narrative="Baryon number (protons + neutrons − antiprotons − antineutrons, roughly) is conserved in all known interactions.",
      subsumed_by="conservation-laws",
      related=[("proton-decay", 0.7)],
      status=":established",
      provenance=WD("Q640970", "Baryon_number")),

    S("Conservation of Lepton Number", "physics", ["law"],
      id_slug="conservation-of-lepton-number",
      applies=[":quantum-regime", ":subatomic"],
      narrative="Lepton number (electrons + neutrinos − positrons − antineutrinos, roughly) is conserved in all currently confirmed interactions.",
      subsumed_by="conservation-laws",
      related=[("neutrino-oscillation", 0.7)],
      provenance=WD("Q848236", "Lepton_number")),

    # ---------- FRAMEWORK / DISCIPLINE ROOT NODES ----------
    S("Classical Mechanics", "physics", ["framework"],
      id_slug="classical-mechanics",
      extras=["Newtonian mechanics", "Newton's mechanics"],
      described_by=[PERSON("newton-isaac")], described_year=1687,
      applies=[":classical-regime", ":everyday", ":engineering"],
      narrative="The physics of macroscopic motion at speeds much less than the speed of light; foundation for engineering and everyday intuition about the world.",
      subsumed_by="physics",
      subsumes=["newtons-first-law", "newtons-second-law", "newtons-third-law",
                "newtons-law-of-gravitation", "lagrangian-mechanics",
                "hamiltonian-mechanics", "galilean-relativity"],
      related=[("quantum-mechanics", 0.6), ("relativity", 0.6)],
      provenance=WD("Q11412", "Classical_mechanics")),

    S("Quantum Mechanics", "quantum", ["framework"],
      id_slug="quantum-mechanics",
      extras=["QM", "quantum theory", "quantum physics"],
      described_by=[PERSON("planck-max"), PERSON("bohr-niels"),
                    PERSON("heisenberg-werner"), PERSON("schrodinger-erwin"),
                    PERSON("dirac-paul")],
      described_year=1925,
      applies=[":quantum-regime", ":subatomic", ":materials"],
      narrative="Physics of the very small: describes matter and radiation at atomic and subatomic scales; famously features wave-particle duality, quantized energy levels, and probabilistic outcomes.",
      subsumed_by="physics",
      subsumes=["schrodinger-equation", "heisenberg-uncertainty-principle",
                "wave-particle-duality", "pauli-exclusion-principle", "born-rule",
                "correspondence-principle"],
      related=[("classical-mechanics", 0.6), ("quantum-field-theory", 0.9),
               ("standard-model-of-particle-physics", 0.85)],
      provenance=WD("Q944", "Quantum_mechanics")),

    S("Relativity", "relativity", ["framework"],
      id_slug="relativity",
      extras=["Einstein's relativity", "theory of relativity"],
      described_by=[PERSON("einstein-albert")], described_year=1905,
      applies=[":relativistic-regime", ":cosmology"],
      narrative="Family of theories about how measurements of space and time depend on the observer; special relativity handles constant-velocity observers, general relativity extends to accelerated observers and gravity.",
      subsumed_by="physics",
      subsumes=["special-relativity", "general-relativity",
                "mass-energy-equivalence", "equivalence-principle",
                "lorentz-invariance"],
      related=[("classical-mechanics", 0.6), ("quantum-field-theory", 0.7)],
      provenance=WD("Q11455", "Theory_of_relativity")),

    S("Thermodynamics", "thermodynamics", ["framework"],
      id_slug="thermodynamics",
      applies=[":classical-regime", ":everyday", ":engineering"],
      narrative="Physics of heat, work, temperature, and entropy; deals with macroscopic energy flows without needing to track individual atoms.",
      subsumed_by="physics",
      subsumes=["first-law-of-thermodynamics", "second-law-of-thermodynamics",
                "third-law-of-thermodynamics", "zeroth-law-of-thermodynamics",
                "ideal-gas-law", "boyles-law", "charles-law", "avogadros-law",
                "fouriers-law-of-heat-conduction", "stefan-boltzmann-law",
                "wiens-displacement-law", "plancks-radiation-law"],
      related=[("statistical-mechanics", 0.95), ("kinetic-theory-of-gases", 0.9)],
      provenance=WD("Q11473", "Thermodynamics")),

    S("Electromagnetism", "electromagnetism", ["framework"],
      id_slug="electromagnetism",
      extras=["classical electromagnetism", "electrodynamics"],
      described_by=[PERSON("maxwell-james-clerk")], described_year=1865,
      applies=[":classical-regime", ":engineering", ":everyday"],
      narrative="Physics of electric charges, magnetic fields, and light; unified by Maxwell's equations into a single framework.",
      subsumed_by="physics",
      subsumes=["coulombs-law", "gausss-law", "gauss-law-for-magnetism",
                "faradays-law-of-induction", "amperes-law", "maxwells-equations",
                "lenzs-law", "ohms-law", "kirchhoffs-laws", "lorentz-force-law"],
      related=[("optics", 0.9), ("quantum-electrodynamics", 0.85)],
      provenance=WD("Q11418", "Electromagnetism")),

    S("Optics", "optics", ["framework"],
      id_slug="optics",
      applies=[":classical-regime", ":everyday", ":engineering"],
      narrative="Physics of light — its propagation, reflection, refraction, diffraction, and interaction with matter.",
      subsumed_by="physics",
      subsumes=["snells-law", "fermats-principle", "maluss-law", "diffraction",
                "interference", "polarization", "refraction"],
      related=[("electromagnetism", 0.9), ("quantum-electrodynamics", 0.7)],
      provenance=WD("Q14620", "Optics")),

    S("Statistical Mechanics", "physics", ["framework"],
      id_slug="statistical-mechanics",
      extras=["statistical thermodynamics", "statistical physics"],
      described_by=[PERSON("boltzmann-ludwig"), PERSON("gibbs-josiah-willard")],
      described_year=1877,
      applies=[":quantum-regime", ":classical-regime", ":materials"],
      formula="S = k·ln(W)",
      narrative="Derives thermodynamic laws from the statistical behavior of large numbers of particles; connects the microscopic to the macroscopic.",
      subsumed_by="physics",
      related=[("thermodynamics", 0.95), ("entropy", 0.95), ("boltzmann-distribution", 0.95)],
      provenance=WD("Q11485", "Statistical_mechanics")),

    S("Quantum Field Theory", "physics", ["framework"],
      id_slug="quantum-field-theory",
      extras=["QFT", "quantum field theories"],
      described_by=[PERSON("dirac-paul"), PERSON("feynman-richard"),
                    PERSON("schwinger-julian"), PERSON("tomonaga-shinichiro")],
      described_year=1948,
      applies=[":quantum-regime", ":high-energy", ":subatomic"],
      narrative="Fuses quantum mechanics with special relativity by promoting particles to excitations of underlying fields; framework for the Standard Model.",
      subsumed_by="physics",
      subsumes=["quantum-electrodynamics", "quantum-chromodynamics", "electroweak-theory"],
      related=[("quantum-mechanics", 0.9), ("standard-model-of-particle-physics", 0.95)],
      provenance=WD("Q194188", "Quantum_field_theory")),

    S("Quantum Electrodynamics", "physics", ["framework"],
      id_slug="quantum-electrodynamics",
      extras=["QED"],
      described_by=[PERSON("feynman-richard"), PERSON("schwinger-julian"),
                    PERSON("tomonaga-shinichiro")],
      described_year=1948,
      applies=[":quantum-regime", ":high-energy"],
      narrative="Quantum field theory of light and matter; predicts the anomalous magnetic moment of the electron to eleven decimal places, the most precise agreement between theory and experiment in physics.",
      subsumed_by="quantum-field-theory",
      related=[("electromagnetism", 0.9), ("photon", 0.9)],
      provenance=WD("Q57944", "Quantum_electrodynamics")),

    S("Quantum Chromodynamics", "physics", ["framework"],
      id_slug="quantum-chromodynamics",
      extras=["QCD"],
      described_by=[PERSON("gell-mann-murray"), PERSON("fritzsch-harald")],
      described_year=1973,
      applies=[":quantum-regime", ":subatomic", ":high-energy"],
      narrative="Quantum field theory of the strong nuclear force; describes how quarks are bound into hadrons via gluon exchange.",
      subsumed_by="quantum-field-theory",
      related=[("quark", 0.95), ("gluon", 0.95), ("strong-nuclear-force", 0.95)],
      provenance=WD("Q80764", "Quantum_chromodynamics")),

    S("Electroweak Theory", "physics", ["framework"],
      id_slug="electroweak-theory",
      described_by=[PERSON("glashow-sheldon"), PERSON("weinberg-steven"),
                    PERSON("salam-abdus")],
      described_year=1968,
      applies=[":quantum-regime", ":high-energy"],
      narrative="Unifies the electromagnetic and weak nuclear forces into a single interaction; predicted the W and Z bosons found at CERN in 1983.",
      subsumed_by="quantum-field-theory",
      related=[("weak-nuclear-force", 0.95), ("higgs-mechanism", 0.9)],
      provenance=WD("Q11538", "Electroweak_interaction")),

    S("Standard Model of Particle Physics", "physics", ["framework"],
      id_slug="standard-model-of-particle-physics",
      extras=["Standard Model", "SM"],
      described_by=[PERSON("glashow-sheldon"), PERSON("weinberg-steven"),
                    PERSON("salam-abdus"), PERSON("higgs-peter")],
      described_year=1975,
      applies=[":quantum-regime", ":subatomic", ":high-energy"],
      narrative="Current best theory of the fundamental particles and their non-gravitational interactions; combines QCD with electroweak theory and the Higgs mechanism.",
      subsumed_by="physics",
      related=[("quantum-field-theory", 0.95), ("higgs-mechanism", 0.9),
               ("quark", 0.9), ("lepton", 0.9), ("gauge-boson", 0.9)],
      provenance=WD("Q10432", "Standard_Model")),

    S("Higgs Mechanism", "physics", ["principle"],
      id_slug="higgs-mechanism",
      described_by=[PERSON("higgs-peter"), PERSON("englert-francois"),
                    PERSON("brout-robert")],
      described_year=1964,
      applies=[":quantum-regime", ":subatomic"],
      narrative="Mechanism by which fundamental particles acquire mass through interaction with the Higgs field; the Higgs boson was observed at the LHC in 2012.",
      subsumed_by="standard-model-of-particle-physics",
      related=[("higgs-boson", 1.0), ("electroweak-theory", 0.9)],
      appears_in_event=["event-higgs-discovery-2012"],
      provenance=WD("Q214198", "Higgs_mechanism")),

    # ---------- FLUID + WAVE ----------
    S("Bernoulli's Principle", "fluid-dynamics", ["principle"],
      id_slug="bernoullis-principle",
      described_by=[PERSON("bernoulli-daniel")], described_year=1738,
      applies=[":classical-regime", ":engineering", ":everyday"],
      formula="P + ½ρv² + ρgh = const",
      narrative="Along a streamline in an ideal fluid, faster flow means lower pressure.",
      everyday="An airplane wing generates lift because air moves faster over the curved upper surface, lowering pressure there.",
      subsumed_by="fluid-dynamics",
      related=[("continuity-equation", 0.9), ("navier-stokes-equations", 0.7)],
      provenance=WD("Q205", "Bernoulli's_principle")),

    S("Navier-Stokes Equations", "fluid-dynamics", ["equation"],
      id_slug="navier-stokes-equations",
      described_by=[PERSON("navier-claude-louis"), PERSON("stokes-george-gabriel")],
      described_year=1845,
      applies=[":classical-regime", ":engineering"],
      formula="ρ(∂v/∂t + v·∇v) = −∇P + μ·∇²v + f",
      narrative="Governs the motion of viscous fluids; existence-and-smoothness of solutions is one of the Millennium Prize problems.",
      subsumed_by="fluid-dynamics",
      related=[("bernoullis-principle", 0.7), ("reynolds-number", 0.8), ("turbulence", 0.9)],
      provenance=WD("Q189223", "Navier–Stokes_equations")),

    S("Archimedes' Principle", "fluid-dynamics", ["principle"],
      id_slug="archimedes-principle",
      described_by=[PERSON("archimedes")], described_year=-250,
      applies=[":classical-regime", ":everyday", ":engineering"],
      formula="F_buoy = ρ_fluid · V_displaced · g",
      narrative="An object submerged in a fluid experiences a buoyant force equal to the weight of the fluid it displaces.",
      everyday="A steel ship floats because its hollow shape displaces water weighing more than the ship.",
      subsumed_by="fluid-dynamics",
      related=[("buoyancy", 1.0), ("density", 0.85)],
      provenance=WD("Q131207", "Archimedes'_principle")),

    S("Pascal's Principle", "fluid-dynamics", ["principle"],
      id_slug="pascals-principle",
      described_by=[PERSON("pascal-blaise")], described_year=1653,
      applies=[":classical-regime", ":engineering", ":everyday"],
      narrative="A change in pressure applied to an enclosed incompressible fluid is transmitted undiminished throughout the fluid.",
      everyday="A hydraulic jack lifts a car with a small hand-pump because the pressure is felt equally at the piston lifting the car.",
      subsumed_by="fluid-dynamics",
      related=[("hydraulic-system", 0.9), ("archimedes-principle", 0.7)],
      provenance=WD("Q329901", "Pascal's_law")),

    S("Doppler Effect", "physics", ["phenomenon", "law"],
      id_slug="doppler-effect",
      extras=["Doppler shift"],
      described_by=[PERSON("doppler-christian")], described_year=1842,
      applies=[":classical-regime", ":astrophysical", ":everyday"],
      formula="f_observed = f_source · (v ± v_o) / (v ∓ v_s)",
      narrative="The apparent frequency of a wave changes when the source and observer are in relative motion; approaching bodies appear blue-shifted, receding ones red-shifted.",
      everyday="An ambulance siren sounds higher-pitched as it approaches and lower as it recedes.",
      subsumed_by="acoustics",
      related=[("hubble-law", 0.85), ("redshift", 0.9)],
      provenance=WD("Q194158", "Doppler_effect")),

    S("Hooke's Law", "physics", ["law"],
      id_slug="hookes-law",
      described_by=[PERSON("hooke-robert")], described_year=1678,
      applies=[":classical-regime", ":engineering", ":everyday"],
      formula="F = −k·x",
      narrative="The restoring force of a spring is proportional to the displacement from equilibrium — small deformations of elastic solids follow the same rule.",
      everyday="A car suspension bounces because springs push back proportionally to how far they've been compressed.",
      subsumed_by="classical-mechanics",
      related=[("simple-harmonic-motion", 0.95), ("youngs-modulus", 0.85)],
      provenance=WD("Q170282", "Hooke's_law")),

    S("Simple Harmonic Motion", "physics", ["phenomenon"],
      id_slug="simple-harmonic-motion",
      extras=["SHM", "harmonic oscillator"],
      applies=[":classical-regime", ":quantum-regime", ":engineering"],
      formula="x(t) = A·cos(ω·t + φ)",
      narrative="Oscillation with restoring force proportional to displacement; produces sinusoidal motion with a period independent of amplitude.",
      everyday="A pendulum for small swings, a mass on a spring, a guitar string plucked gently — all approximate simple harmonic motion.",
      subsumed_by="classical-mechanics",
      related=[("hookes-law", 0.95), ("resonance", 0.85), ("frequency", 0.85)],
      provenance=WD("Q194275", "Simple_harmonic_motion")),

    S("Resonance", "physics", ["phenomenon"],
      id_slug="resonance",
      applies=[":classical-regime", ":quantum-regime", ":engineering", ":everyday"],
      narrative="When a driving frequency matches a system's natural frequency the amplitude of oscillation grows dramatically.",
      everyday="A wine glass shatters when a singer holds a note matching its natural frequency; children on swings pump at the swing's natural period.",
      subsumed_by="classical-mechanics",
      related=[("simple-harmonic-motion", 0.9), ("natural-frequency", 0.95),
               ("tacoma-narrows-bridge", 0.7)],
      provenance=WD("Q179434", "Resonance")),

    S("Fourier's Theorem", "math", ["theorem"],
      id_slug="fourier-theorem",
      extras=["Fourier decomposition", "Fourier analysis"],
      described_by=[PERSON("fourier-joseph")], described_year=1822,
      applies=[":classical-regime", ":engineering", ":computational"],
      narrative="Any sufficiently well-behaved periodic function can be written as a sum of sinusoids at integer multiples of a fundamental frequency.",
      everyday="An audio equalizer works by decomposing sound into frequency bands and adjusting each.",
      subsumed_by="math",
      related=[("fourier-transform", 0.95), ("wave", 0.85)],
      provenance=WD("Q179467", "Fourier_series")),

    # ---------- NUCLEAR ----------
    S("Radioactive Decay Law", "physics", ["law"],
      id_slug="radioactive-decay-law",
      described_by=[PERSON("rutherford-ernest"), PERSON("soddy-frederick")],
      described_year=1902,
      applies=[":quantum-regime", ":subatomic"],
      formula="N(t) = N₀·e^(−λt); t_½ = ln(2)/λ",
      narrative="The number of undecayed nuclei falls exponentially with time; each isotope has a characteristic half-life.",
      everyday="Carbon-14 dating works because ¹⁴C in dead organic matter halves every ~5,730 years.",
      subsumed_by="nuclear-physics",
      related=[("half-life", 0.95), ("radiometric-dating", 0.9)],
      provenance=WD("Q11396", "Radioactive_decay")),
]
