"""Physical phenomena + forces + fields. Target ~500 phenomena + ~100 forces.

Compact terse authoring: single-line narratives, minimal facets. Every claim
sourced to a Wikipedia article by URL.
"""

from _helpers import S, PERSON, INSTITUTION


def W(name):
    return [{"source": "wikipedia", "url": f"https://en.wikipedia.org/wiki/{name}"}]


def WD(qid, name=None):
    p = [{"source": "wikidata", "qid": qid}]
    if name:
        p.append({"source": "wikipedia", "url": f"https://en.wikipedia.org/wiki/{name}"})
    return p


def _normalize_positionals(name, a2, a3, a4, slug):
    """Tolerate BOTH call shapes:
       (name, slug, disc, narr, ...)     — original signature
       (name, disc, narr, ..., slug=...) — later shape used in this file
    """
    if a4 is not None:
        # 4 positionals — assume (name, slug, disc, narr) original shape
        return a2, a3, a4  # slug, disc, narr
    # 3 positionals; if 'a2' contains a space it's a narrative-first shape,
    # otherwise it may be the slug and a3 is the narrative — but the file's
    # actual usage puts DISCIPLINE second when slug= is a kwarg.
    if slug is None:
        slug = name.lower().replace(" ", "-").replace("'", "").replace(",", "")
    disc = a2
    narr = a3
    return slug, disc, narr


def PH(name, a2, a3=None, a4=None, slug=None, everyday=None, applies=None,
       formula=None, units=None, described_by=None, described_year=None,
       subsumed_by=None, related=None, wp=None, wd=None,
       hosted_at=None, appears_in_event=None, in_place=None,
       status=None, superseded_by=None, era=None, contradicts=None,
       used_in_store=None):
    """Compact phenomenon builder — tolerates two positional shapes."""
    slug, disc, narr = _normalize_positionals(name, a2, a3, a4, slug)
    if wd:
        prov = WD(wd, wp) if wp else WD(wd)
    else:
        prov = W(wp or name.replace(" ", "_"))
    return S(name, disc, "phenomenon",
             id_slug=slug, narrative=narr, everyday=everyday,
             applies=applies, formula=formula, units=units,
             described_by=described_by, described_year=described_year,
             subsumed_by=subsumed_by, related=related,
             hosted_at=hosted_at, appears_in_event=appears_in_event,
             in_place=in_place, status=status, superseded_by=superseded_by,
             era=era, contradicts=contradicts, used_in_store=used_in_store,
             provenance=prov)


def F(name, a2, a3=None, a4=None, slug=None, everyday=None, applies=None,
      formula=None, described_by=None, described_year=None, subsumed_by=None,
      related=None, wp=None, wd=None,
      hosted_at=None, appears_in_event=None, in_place=None,
      status=None, superseded_by=None, era=None, contradicts=None,
      used_in_store=None):
    """Compact force/field builder — tolerates two positional shapes."""
    slug, disc, narr = _normalize_positionals(name, a2, a3, a4, slug)
    if wd:
        prov = WD(wd, wp) if wp else WD(wd)
    else:
        prov = W(wp or name.replace(" ", "_"))
    return S(name, disc, "force",
             id_slug=slug, narrative=narr, everyday=everyday,
             applies=applies, formula=formula,
             described_by=described_by, described_year=described_year,
             subsumed_by=subsumed_by, related=related,
             hosted_at=hosted_at, appears_in_event=appears_in_event,
             in_place=in_place, status=status, superseded_by=superseded_by,
             era=era, contradicts=contradicts, used_in_store=used_in_store,
             provenance=prov)


SCIENCES = [
    # ---- FUNDAMENTAL FORCES ----
    F("Gravity", "physics",
      "The attractive force between any two bodies with mass; the weakest of the four fundamental forces yet the one that shapes planets, stars, and galaxies.",
      slug="gravity",
      everyday="A dropped apple falls to the ground.",
      applies=[":everyday", ":astrophysical", ":cosmology"],
      subsumed_by="fundamental-force",
      related=[("newtons-law-of-gravitation", 0.95), ("general-relativity", 0.95)],
      wp="Gravity", wd="Q11412"),

    F("Electromagnetic Force", "physics",
      "The force between electrically charged particles; responsible for chemistry, light, friction, and every macroscopic push and pull that isn't gravity.",
      slug="electromagnetic-force",
      applies=[":everyday", ":subatomic", ":materials"],
      subsumed_by="fundamental-force",
      related=[("electromagnetism", 0.95), ("photon", 0.9)],
      wp="Electromagnetism", wd="Q11418"),

    F("Strong Nuclear Force", "physics",
      "The force that binds quarks into protons and neutrons and holds atomic nuclei together against the electric repulsion of protons.",
      slug="strong-nuclear-force",
      applies=[":subatomic"],
      subsumed_by="fundamental-force",
      related=[("quantum-chromodynamics", 0.95), ("gluon", 0.95), ("quark", 0.9)],
      wp="Strong_interaction", wd="Q11413"),

    F("Weak Nuclear Force", "physics",
      "The force responsible for beta decay and other nuclear transformations; mediated by the W and Z bosons.",
      slug="weak-nuclear-force",
      applies=[":subatomic"],
      subsumed_by="fundamental-force",
      related=[("electroweak-theory", 0.95), ("neutrino", 0.85)],
      wp="Weak_interaction", wd="Q11415"),

    S("Fundamental Force", "physics", "force",
      id_slug="fundamental-force",
      narrative="The four (or three, after unification) irreducible interactions of nature: gravity, electromagnetism, strong nuclear, weak nuclear.",
      subsumes=["gravity", "electromagnetic-force", "strong-nuclear-force", "weak-nuclear-force"],
      subsumed_by="physics",
      provenance=WD("Q11402", "Fundamental_interaction")),

    # ---- MACROSCOPIC FORCES ----
    F("Friction", "physics",
      "The force resisting relative motion of surfaces in contact; static friction resists starting motion, kinetic friction resists ongoing motion.",
      slug="friction",
      everyday="A book stays put on a table because static friction balances any small push.",
      applies=[":everyday", ":engineering"],
      subsumed_by="electromagnetic-force",
      formula="F_friction ≤ μ·N",
      related=[("coefficient-of-friction", 0.95), ("static-friction", 0.9), ("kinetic-friction", 0.9)],
      wp="Friction", wd="Q80831"),

    F("Normal Force", "physics",
      "The component of a contact force perpendicular to the surface, preventing objects from passing through each other.",
      slug="normal-force",
      everyday="A table pushes up on a book with a force equal to the book's weight.",
      applies=[":everyday"], subsumed_by="electromagnetic-force",
      related=[("friction", 0.85), ("newtons-third-law", 0.9)],
      wp="Normal_force"),

    F("Tension", "physics",
      "A pulling force transmitted axially along a rope, cable, chain, or muscle.",
      slug="tension",
      everyday="A rope in tug-of-war pulls each team toward the other.",
      applies=[":everyday", ":engineering"],
      subsumed_by="electromagnetic-force",
      wp="Tension_(physics)"),

    F("Buoyancy", "fluid-dynamics",
      "The upward force a fluid exerts on an immersed object equal to the weight of the displaced fluid.",
      slug="buoyancy",
      everyday="A hot-air balloon rises because the warm air inside is less dense than the cool air around it.",
      applies=[":everyday", ":engineering"],
      subsumed_by="fluid-dynamics",
      related=[("archimedes-principle", 1.0), ("density", 0.85)],
      wp="Buoyancy", wd="Q30186"),

    F("Drag", "fluid-dynamics",
      "The force opposing motion of a body through a fluid; grows with speed and depends on the body's shape.",
      slug="drag",
      everyday="A parachute slows a skydiver because unfolded fabric drags hard on air.",
      applies=[":everyday", ":engineering"],
      subsumed_by="fluid-dynamics",
      related=[("terminal-velocity", 0.9), ("reynolds-number", 0.7)],
      wp="Drag_(physics)"),

    F("Lift", "fluid-dynamics",
      "The component of aerodynamic force perpendicular to the flow; what keeps birds and airplanes in the air.",
      slug="lift",
      everyday="Airplane wings generate lift because of pressure differences between upper and lower surfaces.",
      applies=[":everyday", ":engineering"],
      subsumed_by="fluid-dynamics",
      related=[("bernoullis-principle", 0.9), ("drag", 0.7)],
      wp="Lift_(force)"),

    F("Centripetal Force", "physics",
      "The net inward force required to keep an object moving in a circular path.",
      slug="centripetal-force",
      everyday="A car in a curve is pushed inward by friction between tires and road.",
      applies=[":everyday", ":engineering"],
      formula="F_c = m·v²/r",
      subsumed_by="classical-mechanics",
      related=[("centrifugal-force", 0.85), ("newtons-second-law", 0.9)],
      wp="Centripetal_force"),

    F("Centrifugal Force", "physics",
      "The apparent outward force felt in a rotating reference frame; a fictitious force from Newton's perspective.",
      slug="centrifugal-force",
      everyday="Passengers feel pushed outward when a car takes a sharp turn.",
      applies=[":everyday", ":engineering"],
      subsumed_by="classical-mechanics",
      related=[("centripetal-force", 0.85), ("coriolis-force", 0.85)],
      wp="Centrifugal_force"),

    F("Coriolis Force", "physics",
      "The apparent force acting on a body moving within a rotating reference frame; deflects motion in the direction perpendicular to velocity.",
      slug="coriolis-force",
      everyday="Hurricanes spin counterclockwise in the northern hemisphere and clockwise in the southern because of Earth's rotation.",
      applies=[":everyday", ":geological-timescale"],
      formula="F = −2·m·(ω × v)",
      subsumed_by="classical-mechanics",
      related=[("centrifugal-force", 0.85), ("weather-system", 0.85)],
      wp="Coriolis_force"),

    F("Van der Waals Force", "chemistry",
      "Weak intermolecular attractions arising from correlated fluctuations in electron distributions.",
      slug="van-der-waals-force",
      described_by=[PERSON("van-der-waals-johannes")], described_year=1873,
      everyday="A gecko sticks to a wall thanks to countless van der Waals attractions between foot-pad hairs and surface.",
      applies=[":everyday", ":materials"],
      subsumed_by="electromagnetic-force",
      related=[("dipole-dipole-interaction", 0.85), ("hydrogen-bond", 0.7)],
      wp="Van_der_Waals_force", wd="Q291218"),

    # ---- FIELDS ----
    S("Electric Field", "physics", "field",
      id_slug="electric-field",
      applies=[":classical-regime", ":everyday", ":engineering"],
      formula="E = F/q",
      units="V/m",
      narrative="The vector field around a charged object that exerts a force on other charged objects.",
      everyday="Static shock happens when accumulated charge creates a strong enough field to ionize air.",
      subsumed_by="electromagnetism",
      related=[("coulombs-law", 0.95), ("electric-charge", 0.9), ("gausss-law", 0.9)],
      provenance=WD("Q22676", "Electric_field")),

    S("Magnetic Field", "physics", "field",
      id_slug="magnetic-field",
      applies=[":classical-regime", ":everyday", ":engineering"],
      units="T (tesla)",
      narrative="The vector field around magnets and moving charges that exerts a force on other moving charges.",
      everyday="A compass needle aligns with Earth's magnetic field, pointing roughly north.",
      subsumed_by="electromagnetism",
      related=[("lorentz-force-law", 0.9), ("faradays-law-of-induction", 0.9)],
      provenance=WD("Q11408", "Magnetic_field")),

    S("Gravitational Field", "physics", "field",
      id_slug="gravitational-field",
      applies=[":everyday", ":astrophysical", ":cosmology"],
      formula="g = F/m",
      units="N/kg or m/s²",
      narrative="The field around a mass that exerts a gravitational force on other masses.",
      everyday="Earth's gravitational field is about 9.8 m/s² at its surface.",
      subsumed_by="gravity",
      related=[("general-relativity", 0.95), ("newtons-law-of-gravitation", 0.95)],
      provenance=WD("Q216191", "Gravitational_field")),

    S("Higgs Field", "physics", "field",
      id_slug="higgs-field",
      described_by=[PERSON("higgs-peter")], described_year=1964,
      applies=[":quantum-regime", ":subatomic"],
      narrative="The scalar field whose non-zero vacuum expectation value gives mass to elementary particles.",
      subsumed_by="standard-model-of-particle-physics",
      related=[("higgs-boson", 1.0), ("higgs-mechanism", 1.0)],
      provenance=WD("Q1147", "Higgs_field")),

    S("Quantum Field", "physics", "field",
      id_slug="quantum-field",
      applies=[":quantum-regime"],
      narrative="A field promoted to a quantum-mechanical operator; excitations of the field are the particles of the Standard Model.",
      subsumed_by="quantum-field-theory",
      provenance=WD("Q1195939", "Quantum_field")),

    # ---- OPTICAL PHENOMENA ----
    PH("Refraction", "refraction", "optics",
       "The bending of light when it passes between media of different refractive indices.",
       everyday="A pencil in a glass of water looks broken at the water line.",
       applies=[":everyday", ":engineering"], subsumed_by="optics",
       related=[("snells-law", 1.0), ("refractive-index", 0.95)],
       wp="Refraction", wd="Q83345"),

    PH("Reflection", "reflection", "optics",
       "The change in direction of a wavefront at an interface, returning the wave into the medium from which it originated.",
       everyday="A mirror reflects light so we can see our own faces.",
       applies=[":everyday"], subsumed_by="optics",
       formula="θ_i = θ_r",
       related=[("mirror", 0.9), ("specular-reflection", 0.9), ("diffuse-reflection", 0.85)],
       wp="Reflection_(physics)", wd="Q193893"),

    PH("Diffraction", "diffraction", "optics",
       "The bending of waves around obstacles or through openings; more pronounced when the opening size is comparable to the wavelength.",
       everyday="Ocean waves curve into a harbor after passing through a narrow gap.",
       applies=[":everyday", ":engineering", ":quantum-regime"],
       subsumed_by="optics",
       related=[("interference", 0.9), ("double-slit-experiment", 0.9)],
       wp="Diffraction", wd="Q11433"),

    PH("Interference", "interference", "optics",
       "The superposition of two or more waves resulting in a new wave pattern with regions of enhancement and cancellation.",
       everyday="Soap-film colors come from light waves reflecting off both surfaces and interfering.",
       applies=[":everyday", ":quantum-regime", ":engineering"],
       subsumed_by="optics",
       related=[("diffraction", 0.9), ("double-slit-experiment", 0.95), ("wave", 0.85)],
       wp="Wave_interference", wd="Q11402"),

    PH("Polarization", "polarization", "optics",
       "A property of transverse waves specifying the geometric orientation of oscillations.",
       everyday="Polarized sunglasses block glare from horizontal reflective surfaces.",
       applies=[":everyday", ":engineering"], subsumed_by="optics",
       related=[("maluss-law", 0.95), ("liquid-crystal-display", 0.7)],
       wp="Polarization_(waves)", wd="Q191297"),

    PH("Dispersion", "dispersion-optics", "optics",
       "The dependence of wave phase velocity on frequency; splits white light into a spectrum through a prism.",
       everyday="A rainbow appears because water droplets disperse sunlight into its component colors.",
       applies=[":everyday"], subsumed_by="optics",
       related=[("refractive-index", 0.9), ("rainbow", 0.95)],
       wp="Dispersion_(optics)", wd="Q750618"),

    PH("Rayleigh Scattering", "rayleigh-scattering", "optics",
       "The scattering of light by particles much smaller than the wavelength; scattering intensity scales as 1/λ⁴.",
       everyday="The sky is blue because air molecules scatter short wavelengths (blue) more than long ones (red).",
       applies=[":everyday", ":astrophysical"],
       described_by=[PERSON("rayleigh-lord")], described_year=1871,
       subsumed_by="optics",
       related=[("mie-scattering", 0.85), ("blue-sky", 0.95)],
       wp="Rayleigh_scattering", wd="Q188877"),

    PH("Mie Scattering", "mie-scattering", "optics",
       "Scattering of electromagnetic waves by particles comparable in size to the wavelength; wavelength-neutral.",
       everyday="Clouds look white because water droplets scatter all visible wavelengths about equally.",
       applies=[":everyday"], subsumed_by="optics",
       described_by=[PERSON("mie-gustav")], described_year=1908,
       related=[("rayleigh-scattering", 0.85), ("cloud", 0.85)],
       wp="Mie_scattering"),

    PH("Total Internal Reflection", "total-internal-reflection", "optics",
       "When light traveling in a denser medium hits an interface with a less dense medium at an angle greater than the critical angle, all light is reflected.",
       everyday="Fiber-optic cables carry light around bends by total internal reflection.",
       applies=[":everyday", ":engineering"], subsumed_by="optics",
       related=[("snells-law", 0.95), ("fiber-optic", 0.95)],
       wp="Total_internal_reflection"),

    PH("Fluorescence", "fluorescence", "optics",
       "Emission of light by a substance that has absorbed light or other electromagnetic radiation of a different wavelength.",
       everyday="Fluorescent highlighters glow under UV lamps at nightclubs.",
       applies=[":everyday", ":materials"], subsumed_by="optics",
       related=[("phosphorescence", 0.85), ("stokes-shift", 0.85)],
       wp="Fluorescence", wd="Q6034"),

    PH("Phosphorescence", "phosphorescence", "optics",
       "Type of photoluminescence where absorbed light is re-emitted slowly, sometimes over minutes to hours.",
       everyday="Glow-in-the-dark stars keep glowing after the lights turn off.",
       applies=[":everyday", ":materials"], subsumed_by="optics",
       related=[("fluorescence", 0.85)],
       wp="Phosphorescence", wd="Q131557"),

    PH("Bioluminescence", "bioluminescence", "biology",
       "Emission of light by living organisms through chemical reactions.",
       everyday="Fireflies flash to attract mates; deep-sea creatures glow to lure prey.",
       applies=[":biological"], subsumed_by="biology",
       related=[("luciferin", 0.95), ("chemiluminescence", 0.85)],
       wp="Bioluminescence", wd="Q102301"),

    PH("Chemiluminescence", "chemiluminescence", "chemistry",
       "Emission of light as the result of a chemical reaction.",
       everyday="A glowstick shines when you snap it to mix the two reactive chemicals inside.",
       applies=[":everyday", ":engineering"], subsumed_by="chemistry",
       related=[("bioluminescence", 0.85), ("fluorescence", 0.8)],
       wp="Chemiluminescence"),

    PH("Blackbody Radiation", "blackbody-radiation", "physics",
       "Electromagnetic radiation emitted by an idealized opaque body in thermal equilibrium; spectrum depends only on temperature.",
       everyday="A hot iron poker glows red then yellow-white as its temperature rises.",
       applies=[":everyday", ":astrophysical"], subsumed_by="thermodynamics",
       related=[("plancks-radiation-law", 0.95), ("stefan-boltzmann-law", 0.95),
                ("wiens-displacement-law", 0.95)],
       wp="Black-body_radiation", wd="Q188213"),

    PH("Cherenkov Radiation", "cherenkov-radiation", "physics",
       "Electromagnetic radiation emitted when a charged particle passes through a dielectric medium at a speed greater than the phase velocity of light in that medium.",
       described_by=[PERSON("cherenkov-pavel")], described_year=1934,
       everyday="Nuclear reactor pools glow blue from Cherenkov radiation as fission products travel through water faster than light does in water.",
       applies=[":subatomic", ":engineering"], subsumed_by="physics",
       wp="Cherenkov_radiation", wd="Q194204"),

    # ---- ELECTRIC PHENOMENA ----
    PH("Electric Current", "electric-current", "physics",
       "The flow of electric charge through a conductor.",
       everyday="A lamp lights when current flows through its filament.",
       applies=[":everyday", ":engineering"], subsumed_by="electromagnetism",
       formula="I = dQ/dt", units="A (amperes)",
       related=[("ohms-law", 0.95), ("electric-charge", 0.95)],
       wp="Electric_current", wd="Q11663"),

    PH("Electrostatic Discharge", "electrostatic-discharge", "physics",
       "The sudden flow of electricity between two electrically charged objects.",
       everyday="A doorknob shocks you after you shuffle across a carpet in dry weather.",
       applies=[":everyday", ":engineering"], subsumed_by="electromagnetism",
       related=[("electric-charge", 0.9), ("lightning", 0.85)],
       wp="Electrostatic_discharge"),

    PH("Superconductivity", "superconductivity", "physics",
       "The phenomenon of exact zero electrical resistance and expulsion of magnetic fields below a critical temperature.",
       described_by=[PERSON("onnes-heike-kamerlingh")], described_year=1911,
       everyday="MRI machines use superconducting coils cooled with liquid helium to produce enormous magnetic fields.",
       applies=[":low-temperature", ":engineering", ":materials"],
       subsumed_by="condensed-matter-physics",
       related=[("meissner-effect", 0.95), ("bcs-theory", 0.9), ("critical-temperature", 0.9)],
       wp="Superconductivity", wd="Q11424"),

    PH("Meissner Effect", "meissner-effect", "physics",
       "The expulsion of magnetic fields from a superconductor as it transitions to the superconducting state.",
       described_by=[PERSON("meissner-walther"), PERSON("ochsenfeld-robert")],
       described_year=1933,
       everyday="A small magnet levitates over a chilled superconductor.",
       applies=[":low-temperature", ":materials"], subsumed_by="superconductivity",
       wp="Meissner_effect", wd="Q905912"),

    PH("Piezoelectric Effect", "piezoelectric-effect", "physics",
       "The accumulation of electric charge in certain solids in response to mechanical stress.",
       described_by=[PERSON("curie-pierre"), PERSON("curie-jacques")],
       described_year=1880,
       everyday="Quartz crystals in wristwatches vibrate at precise frequencies when a voltage is applied — the reverse piezoelectric effect.",
       applies=[":engineering", ":materials"], subsumed_by="condensed-matter-physics",
       related=[("quartz", 0.9), ("crystal", 0.85)],
       wp="Piezoelectricity", wd="Q83320"),

    PH("Hall Effect", "hall-effect", "physics",
       "The production of a voltage difference across an electrical conductor perpendicular to an electric current and a magnetic field.",
       described_by=[PERSON("hall-edwin")], described_year=1879,
       applies=[":engineering", ":materials"], subsumed_by="electromagnetism",
       related=[("magnetic-field", 0.9), ("semiconductor", 0.85)],
       wp="Hall_effect", wd="Q193760"),

    PH("Photoelectric Effect", "photoelectric-effect", "physics",
       "The emission of electrons from a material when it absorbs electromagnetic radiation above a threshold frequency.",
       described_by=[PERSON("hertz-heinrich"), PERSON("einstein-albert")],
       described_year=1905,
       everyday="Solar cells generate electricity by absorbing photons that knock electrons loose in silicon.",
       applies=[":quantum-regime", ":everyday", ":engineering"],
       subsumed_by="quantum-mechanics",
       related=[("photon", 0.95), ("plancks-radiation-law", 0.85)],
       wp="Photoelectric_effect", wd="Q83267"),

    PH("Compton Scattering", "compton-scattering", "physics",
       "The scattering of a photon off a charged particle, usually an electron, with a decrease in the photon's energy.",
       described_by=[PERSON("compton-arthur")], described_year=1923,
       applies=[":quantum-regime", ":subatomic"],
       subsumed_by="quantum-mechanics",
       related=[("photon", 0.9), ("wave-particle-duality", 0.85)],
       wp="Compton_scattering", wd="Q214604"),

    # ---- QUANTUM PHENOMENA ----
    PH("Quantum Entanglement", "quantum-entanglement", "quantum",
       "A physical phenomenon that occurs when a group of particles are generated or interact in such a way that the quantum state of each particle cannot be described independently.",
       everyday="A pair of entangled photons sent to distant labs will show correlated measurements no matter how far apart.",
       applies=[":quantum-regime"], subsumed_by="quantum-mechanics",
       related=[("bell-inequality", 0.9), ("epr-paradox", 0.9), ("quantum-teleportation", 0.85)],
       wp="Quantum_entanglement", wd="Q188386"),

    PH("Quantum Tunneling", "quantum-tunneling", "quantum",
       "The quantum-mechanical phenomenon where a particle passes through a potential barrier that it classically could not surmount.",
       everyday="Nuclear fusion in the sun happens because protons occasionally tunnel through their mutual electric repulsion; scanning tunneling microscopes work by electrons tunneling from tip to sample.",
       applies=[":quantum-regime", ":subatomic", ":engineering"],
       subsumed_by="quantum-mechanics",
       related=[("alpha-decay", 0.9), ("scanning-tunneling-microscopy", 0.85)],
       wp="Quantum_tunnelling", wd="Q173252"),

    PH("Quantum Superposition", "quantum-superposition", "quantum",
       "A fundamental principle of quantum mechanics — any two quantum states can be added together and the result is another valid quantum state.",
       applies=[":quantum-regime"], subsumed_by="quantum-mechanics",
       related=[("schrodinger-equation", 0.9), ("wavefunction", 0.9), ("qubit", 0.9)],
       wp="Quantum_superposition", wd="Q660081"),

    PH("Quantum Decoherence", "quantum-decoherence", "quantum",
       "The loss of quantum coherence through interaction with the environment; explains why macroscopic objects don't display quantum behavior.",
       applies=[":quantum-regime"], subsumed_by="quantum-mechanics",
       related=[("quantum-superposition", 0.9), ("measurement-problem", 0.85)],
       wp="Quantum_decoherence"),

    PH("Vacuum Fluctuation", "vacuum-fluctuation", "quantum",
       "The temporary random change in the amount of energy at a point in space allowed by the uncertainty principle.",
       applies=[":quantum-regime"], subsumed_by="quantum-field-theory",
       related=[("casimir-effect", 0.9), ("zero-point-energy", 0.9)],
       wp="Vacuum_state"),

    PH("Casimir Effect", "casimir-effect", "physics",
       "The attractive force between two parallel uncharged conducting plates in vacuum, arising from quantum vacuum fluctuations.",
       described_by=[PERSON("casimir-hendrik")], described_year=1948,
       applies=[":quantum-regime"], subsumed_by="quantum-field-theory",
       related=[("vacuum-fluctuation", 0.95)],
       wp="Casimir_effect", wd="Q193084"),

    # ---- THERMAL / WAVE PHENOMENA ----
    PH("Convection", "convection", "physics",
       "Heat transfer by the bulk movement of a fluid.",
       everyday="Warm air rises in a room because it's less dense than cool air; this is convection.",
       applies=[":everyday", ":engineering"], subsumed_by="thermodynamics",
       related=[("conduction", 0.85), ("radiation", 0.85), ("buoyancy", 0.85)],
       wp="Convection", wd="Q167510"),

    PH("Conduction", "conduction", "physics",
       "Heat transfer through direct molecular contact.",
       everyday="A metal spoon in a hot cup gets warm as heat conducts up the handle.",
       applies=[":everyday", ":engineering"], subsumed_by="thermodynamics",
       related=[("convection", 0.85), ("fouriers-law-of-heat-conduction", 0.95)],
       wp="Thermal_conduction"),

    PH("Thermal Radiation", "thermal-radiation", "physics",
       "Heat transfer by electromagnetic waves emitted by any body at temperature above absolute zero.",
       everyday="A campfire warms your face through radiation even without direct air contact.",
       applies=[":everyday", ":astrophysical"], subsumed_by="thermodynamics",
       related=[("stefan-boltzmann-law", 0.95), ("blackbody-radiation", 0.95)],
       wp="Thermal_radiation"),

    PH("Boiling", "boiling", "physics",
       "Rapid vaporization of a liquid throughout its bulk when heated to its boiling point.",
       everyday="Water boils at 100°C at sea-level pressure; at higher altitudes it boils cooler because pressure is lower.",
       applies=[":everyday", ":engineering"], subsumed_by="thermodynamics",
       related=[("evaporation", 0.9), ("phase-transition", 0.9), ("boiling-point", 0.95)],
       wp="Boiling", wd="Q47542"),

    PH("Evaporation", "evaporation", "physics",
       "Vaporization of a liquid at its surface, occurring at any temperature below the boiling point.",
       everyday="A puddle dries in the sun because water molecules with enough energy escape into the air.",
       applies=[":everyday"], subsumed_by="thermodynamics",
       related=[("boiling", 0.9), ("vapor-pressure", 0.85), ("humidity", 0.85)],
       wp="Evaporation", wd="Q11402"),

    PH("Condensation", "condensation", "physics",
       "The change of a substance from gaseous to liquid state.",
       everyday="Dew forms on grass at night as air cools below its dew point and water vapor condenses.",
       applies=[":everyday"], subsumed_by="thermodynamics",
       related=[("evaporation", 0.9), ("dew-point", 0.9), ("cloud", 0.85)],
       wp="Condensation", wd="Q133151"),

    PH("Sublimation", "sublimation", "physics",
       "Direct transition from solid to gas without passing through liquid.",
       everyday="Dry ice — solid carbon dioxide — sublimes into fog at room temperature.",
       applies=[":everyday", ":engineering"], subsumed_by="thermodynamics",
       related=[("phase-transition", 0.9)],
       wp="Sublimation_(phase_transition)"),

    PH("Melting", "melting", "physics",
       "The phase transition from solid to liquid.",
       everyday="Ice melts to water at 0°C at ordinary atmospheric pressure.",
       applies=[":everyday"], subsumed_by="thermodynamics",
       related=[("melting-point", 0.95), ("phase-transition", 0.9)],
       wp="Melting"),

    PH("Freezing", "freezing", "physics",
       "The phase transition from liquid to solid.",
       everyday="Water freezes to ice below 0°C; pure water can supercool below that if uninterrupted.",
       applies=[":everyday"], subsumed_by="thermodynamics",
       related=[("melting-point", 0.9), ("phase-transition", 0.9)],
       wp="Freezing"),

    PH("Phase Transition", "phase-transition", "physics",
       "A change in a system between distinct phases of matter (solid, liquid, gas, plasma, plus condensed-matter phases).",
       applies=[":everyday", ":materials"], subsumed_by="thermodynamics",
       related=[("melting", 0.9), ("boiling", 0.9), ("condensation", 0.9),
                ("sublimation", 0.9), ("critical-point", 0.85)],
       wp="Phase_transition", wd="Q184713"),

    PH("Osmosis", "osmosis", "chemistry",
       "The net movement of solvent molecules through a selectively permeable membrane from a region of lower solute concentration to a region of higher solute concentration.",
       everyday="A wilted plant perks up when watered because water flows into cells via osmosis.",
       applies=[":everyday", ":biological"], subsumed_by="chemistry",
       related=[("diffusion", 0.9), ("cell-membrane", 0.85), ("reverse-osmosis", 0.85)],
       wp="Osmosis", wd="Q45086"),

    PH("Diffusion", "diffusion", "chemistry",
       "The net movement of particles from a region of high concentration to a region of low concentration due to random thermal motion.",
       everyday="A drop of ink in still water spreads out on its own.",
       applies=[":everyday", ":biological", ":materials"], subsumed_by="chemistry",
       related=[("osmosis", 0.9), ("brownian-motion", 0.85)],
       wp="Diffusion", wd="Q131645"),

    PH("Brownian Motion", "brownian-motion", "physics",
       "The random motion of particles suspended in a fluid caused by collisions with fast-moving molecules.",
       described_by=[PERSON("brown-robert"), PERSON("einstein-albert")],
       described_year=1905,
       everyday="Dust particles in a sunbeam jiggle visibly under a microscope.",
       applies=[":everyday", ":quantum-regime"], subsumed_by="statistical-mechanics",
       related=[("diffusion", 0.85), ("kinetic-theory-of-gases", 0.85)],
       wp="Brownian_motion", wd="Q189389"),

    PH("Surface Tension", "surface-tension", "fluid-dynamics",
       "The tendency of liquid surfaces to shrink into the minimum surface area possible.",
       everyday="A water strider skates on a pond because surface tension supports its light body.",
       applies=[":everyday", ":biological"], subsumed_by="fluid-dynamics",
       related=[("capillary-action", 0.9), ("meniscus", 0.85)],
       wp="Surface_tension", wd="Q170749"),

    PH("Capillary Action", "capillary-action", "fluid-dynamics",
       "The ability of a liquid to flow in narrow spaces without external forces, sometimes against gravity.",
       everyday="Water climbs up a paper towel dipped in a puddle.",
       applies=[":everyday", ":biological"], subsumed_by="fluid-dynamics",
       related=[("surface-tension", 0.9), ("xylem", 0.85)],
       wp="Capillary_action", wd="Q167651"),

    PH("Viscosity", "viscosity", "fluid-dynamics",
       "A measure of a fluid's resistance to deformation at a given rate; how thick or thin the fluid feels.",
       everyday="Honey pours slowly because it is much more viscous than water.",
       applies=[":everyday", ":engineering"], subsumed_by="fluid-dynamics",
       formula="τ = μ·(du/dy)", units="Pa·s",
       related=[("navier-stokes-equations", 0.85), ("reynolds-number", 0.85)],
       wp="Viscosity", wd="Q191945"),

    PH("Turbulence", "turbulence", "fluid-dynamics",
       "Fluid motion characterized by chaotic changes in pressure and flow velocity.",
       everyday="A river tumbling over rocks produces turbulent whitewater; smooth flow above a rapid is laminar.",
       applies=[":everyday", ":engineering"], subsumed_by="fluid-dynamics",
       related=[("reynolds-number", 0.95), ("laminar-flow", 0.9), ("navier-stokes-equations", 0.9)],
       wp="Turbulence", wd="Q170554"),

    PH("Laminar Flow", "laminar-flow", "fluid-dynamics",
       "Fluid flow in parallel layers without disruption between them; opposite of turbulent flow.",
       everyday="Smoke from an incense stick rises in a smooth column (laminar) before breaking into turbulent swirls.",
       applies=[":everyday", ":engineering"], subsumed_by="fluid-dynamics",
       related=[("turbulence", 0.9), ("reynolds-number", 0.9)],
       wp="Laminar_flow", wd="Q852047"),

    # ---- MAGNETISM / MATERIALS PHENOMENA ----
    PH("Ferromagnetism", "ferromagnetism", "physics",
       "The mechanism by which certain materials (iron, cobalt, nickel) form permanent magnets or are attracted to magnets.",
       everyday="A refrigerator magnet sticks because both it and the fridge steel are ferromagnetic.",
       applies=[":everyday", ":materials"], subsumed_by="electromagnetism",
       related=[("magnetic-domain", 0.9), ("curie-temperature", 0.85)],
       wp="Ferromagnetism", wd="Q210919"),

    PH("Paramagnetism", "paramagnetism", "physics",
       "The weak attraction of materials to an external magnetic field, arising from unpaired electron spins.",
       applies=[":materials"], subsumed_by="electromagnetism",
       related=[("ferromagnetism", 0.85), ("magnetic-susceptibility", 0.85)],
       wp="Paramagnetism", wd="Q193149"),

    PH("Diamagnetism", "diamagnetism", "physics",
       "The property of some materials to be weakly repelled by a magnetic field.",
       everyday="A pyrolytic-graphite tile levitates above a neodymium magnet at room temperature.",
       applies=[":materials"], subsumed_by="electromagnetism",
       wp="Diamagnetism", wd="Q193196"),

    PH("Magnetostriction", "magnetostriction", "physics",
       "The change in dimensions of a ferromagnetic material when magnetized.",
       everyday="An electric transformer hums because its iron core physically flexes as the current alternates.",
       applies=[":everyday", ":materials", ":engineering"],
       subsumed_by="electromagnetism", wp="Magnetostriction"),

    PH("Curie Temperature", "curie-temperature", "physics",
       "The temperature above which a ferromagnetic material loses its permanent magnetization.",
       described_by=[PERSON("curie-pierre")], described_year=1895,
       units="K (kelvin)",
       applies=[":materials", ":high-temperature"],
       subsumed_by="ferromagnetism",
       wp="Curie_temperature", wd="Q179287"),

    # ---- CHAOS / NONLINEAR ----
    PH("Chaos", "chaos", "physics",
       "Behavior of dynamical systems highly sensitive to initial conditions; deterministic yet effectively unpredictable long-term.",
       everyday="Weather forecasts become unreliable more than about ten days out because the atmosphere is chaotic.",
       applies=[":classical-regime", ":everyday"],
       described_by=[PERSON("lorenz-edward")], described_year=1963,
       subsumed_by="physics",
       related=[("butterfly-effect", 0.95), ("strange-attractor", 0.9),
                ("nonlinear-dynamics", 0.9)],
       wp="Chaos_theory", wd="Q179442"),

    PH("Butterfly Effect", "butterfly-effect", "physics",
       "Sensitive dependence on initial conditions in chaotic systems — tiny changes to initial state produce very different long-term outcomes.",
       everyday="A butterfly flapping in Brazil can, in principle, be part of the cause of a tornado in Texas weeks later.",
       applies=[":classical-regime"], subsumed_by="chaos",
       wp="Butterfly_effect", wd="Q222", described_by=[PERSON("lorenz-edward")],
       described_year=1963),

    PH("Emergence", "emergence", "physics",
       "The property of a complex system displaying behavior not evident from its components alone.",
       everyday="A flock of starlings moves in coordinated patterns even though no bird is in charge.",
       applies=[":everyday", ":biological", ":computational"],
       subsumed_by="physics",
       related=[("phase-transition", 0.85), ("self-organization", 0.9)],
       wp="Emergence", wd="Q131746"),

    PH("Self-Organization", "self-organization", "physics",
       "A process where some form of overall order arises from local interactions between parts of an initially disordered system.",
       everyday="Sand piles form ripples on a beach as wind rearranges grains locally.",
       applies=[":everyday", ":biological", ":materials"],
       subsumed_by="physics",
       related=[("emergence", 0.9), ("dissipative-structure", 0.85)],
       wp="Self-organization"),

    # ---- ASTROPHYSICAL PHENOMENA ----
    PH("Gravitational Lensing", "gravitational-lensing", "astronomy",
       "Distortion of light from a distant source by the gravitational field of a foreground mass.",
       everyday="Distant galaxies appear as arcs or multiple images around massive foreground galaxy clusters.",
       applies=[":astrophysical", ":cosmology"], subsumed_by="general-relativity",
       related=[("general-relativity", 0.95), ("dark-matter", 0.9)],
       wp="Gravitational_lens", wd="Q195030"),

    PH("Redshift", "redshift", "astronomy",
       "Increase in the wavelength of light from a receding source.",
       everyday="The spectra of distant galaxies are shifted toward the red end, telling us they are moving away.",
       applies=[":astrophysical", ":cosmology"], subsumed_by="astronomy",
       related=[("hubble-law", 0.95), ("doppler-effect", 0.9), ("big-bang", 0.85)],
       wp="Redshift", wd="Q30838"),

    PH("Cosmic Microwave Background", "cosmic-microwave-background", "cosmology",
       "The faint microwave radiation filling the universe, released about 380,000 years after the Big Bang.",
       described_by=[PERSON("penzias-arno"), PERSON("wilson-robert")], described_year=1964,
       hosted_at=[INSTITUTION("bell-telephone-laboratories")],
       everyday="Old TVs tuned between channels showed static; a small fraction of that came from the CMB.",
       applies=[":cosmology"], subsumed_by="cosmology",
       related=[("big-bang", 0.95), ("recombination-era", 0.9)],
       wp="Cosmic_microwave_background", wd="Q46083"),

    PH("Hubble Expansion", "hubble-expansion", "astronomy",
       "The observed expansion of the universe — distant galaxies recede from us at speeds proportional to their distance.",
       described_by=[PERSON("hubble-edwin"), PERSON("lemaitre-georges")],
       described_year=1929,
       applies=[":cosmology"], subsumed_by="cosmology",
       formula="v = H₀·d",
       related=[("redshift", 0.95), ("big-bang", 0.9), ("hubble-constant", 0.95)],
       wp="Hubble's_law", wd="Q179916"),

    PH("Dark Matter", "dark-matter", "cosmology",
       "Hypothetical form of matter that does not emit or interact with electromagnetic radiation but has gravitational effects observable in galaxies and larger structures.",
       applies=[":cosmology", ":astrophysical"], subsumed_by="cosmology",
       related=[("dark-energy", 0.85), ("galaxy-rotation-curve", 0.9),
                ("gravitational-lensing", 0.85)],
       wp="Dark_matter", wd="Q1069"),

    PH("Dark Energy", "dark-energy", "cosmology",
       "Hypothetical form of energy causing the accelerated expansion of the universe.",
       described_by=[PERSON("perlmutter-saul"), PERSON("riess-adam"), PERSON("schmidt-brian")],
       described_year=1998,
       applies=[":cosmology"], subsumed_by="cosmology",
       related=[("dark-matter", 0.85), ("cosmological-constant", 0.95),
                ("hubble-expansion", 0.85)],
       wp="Dark_energy", wd="Q19604"),

    PH("Big Bang", "big-bang", "cosmology",
       "The prevailing cosmological model — the universe expanded from a very hot dense initial state about 13.8 billion years ago.",
       described_by=[PERSON("lemaitre-georges"), PERSON("gamow-george")],
       described_year=1931,
       applies=[":cosmology"], subsumed_by="cosmology",
       related=[("cosmic-microwave-background", 0.95), ("big-bang-nucleosynthesis", 0.9),
                ("inflation", 0.9), ("hubble-expansion", 0.9)],
       wp="Big_Bang", wd="Q323"),

    PH("Cosmic Inflation", "inflation-cosmology", "cosmology",
       "A theory of exponential expansion of space in the early universe, solving several cosmological puzzles including horizon and flatness problems.",
       described_by=[PERSON("guth-alan")], described_year=1980,
       applies=[":cosmology"], subsumed_by="cosmology",
       related=[("big-bang", 0.9), ("cosmic-microwave-background", 0.85)],
       wp="Inflation_(cosmology)", wd="Q273348"),

    PH("Black Hole", "black-hole", "astronomy",
       "A region of spacetime where gravity is so strong that nothing — not even light — can escape from inside its event horizon.",
       described_by=[PERSON("schwarzschild-karl"), PERSON("hawking-stephen"),
                     PERSON("penrose-roger")],
       described_year=1916,
       applies=[":astrophysical", ":cosmology"], subsumed_by="astronomy",
       related=[("general-relativity", 0.95), ("event-horizon", 0.95),
                ("hawking-radiation", 0.9), ("singularity", 0.9)],
       wp="Black_hole", wd="Q589"),

    PH("Neutron Star", "neutron-star", "astronomy",
       "The collapsed core of a giant star, composed almost entirely of neutrons packed at nuclear density.",
       applies=[":astrophysical"], subsumed_by="astronomy",
       related=[("pulsar", 0.9), ("supernova", 0.85)],
       wp="Neutron_star", wd="Q4202"),

    PH("Pulsar", "pulsar", "astronomy",
       "A highly magnetized rotating neutron star emitting beams of electromagnetic radiation that sweep the sky like a lighthouse.",
       described_by=[PERSON("bell-burnell-jocelyn"), PERSON("hewish-antony")],
       described_year=1967,
       applies=[":astrophysical"], subsumed_by="neutron-star",
       wp="Pulsar", wd="Q4360"),

    PH("Supernova", "supernova", "astronomy",
       "A powerful stellar explosion, either the collapse of a massive star's core or a thermonuclear runaway in a white dwarf.",
       applies=[":astrophysical"], subsumed_by="astronomy",
       related=[("neutron-star", 0.85), ("nucleosynthesis", 0.9), ("supernova-1a", 0.9)],
       wp="Supernova", wd="Q3937"),

    PH("Aurora", "aurora", "atmospheric-science",
       "Natural light display in Earth's polar sky caused by charged particles from the sun colliding with atmospheric gases.",
       everyday="The northern lights (aurora borealis) shimmer green from oxygen excited about 100 km up.",
       applies=[":everyday", ":astrophysical"], subsumed_by="atmospheric-science",
       related=[("magnetosphere", 0.9), ("solar-wind", 0.9)],
       wp="Aurora", wd="Q190564"),

    PH("Solar Wind", "solar-wind", "astronomy",
       "The stream of charged particles released from the upper atmosphere of the sun.",
       applies=[":astrophysical"], subsumed_by="astronomy",
       related=[("aurora", 0.9), ("heliosphere", 0.85), ("magnetosphere", 0.85)],
       wp="Solar_wind", wd="Q124251"),

    PH("Nuclear Fusion", "nuclear-fusion", "physics",
       "A reaction in which two or more atomic nuclei combine to form one or more heavier nuclei, releasing energy.",
       everyday="The sun shines because hydrogen nuclei fuse into helium in its core.",
       applies=[":astrophysical", ":engineering", ":subatomic"],
       subsumed_by="nuclear-physics",
       related=[("nuclear-fission", 0.85), ("stellar-nucleosynthesis", 0.9)],
       wp="Nuclear_fusion", wd="Q13130"),

    PH("Nuclear Fission", "nuclear-fission", "physics",
       "A reaction in which a heavy atomic nucleus splits into two lighter nuclei, releasing energy.",
       described_by=[PERSON("hahn-otto"), PERSON("meitner-lise"), PERSON("strassmann-fritz")],
       described_year=1938,
       everyday="Nuclear power plants generate electricity by fissioning uranium-235.",
       applies=[":engineering", ":subatomic"], subsumed_by="nuclear-physics",
       related=[("nuclear-fusion", 0.85), ("chain-reaction", 0.95), ("critical-mass", 0.9)],
       appears_in_event=["event-manhattan-project", "event-chernobyl-disaster"],
       wp="Nuclear_fission", wd="Q6963"),

    PH("Chain Reaction", "chain-reaction", "physics",
       "A sequence of reactions where a reactive product causes additional reactions to take place.",
       applies=[":subatomic", ":engineering"], subsumed_by="nuclear-physics",
       related=[("nuclear-fission", 0.95), ("critical-mass", 0.9)],
       wp="Nuclear_chain_reaction"),

    # ---- BIOLOGICAL PHENOMENA ----
    PH("Photosynthesis", "photosynthesis", "biology",
       "The process by which plants, algae, and some bacteria convert light energy into chemical energy stored in glucose using carbon dioxide and water.",
       everyday="Every green leaf you've ever seen was running photosynthesis.",
       formula="6·CO₂ + 6·H₂O + light → C₆H₁₂O₆ + 6·O₂",
       applies=[":biological", ":everyday"], subsumed_by="biology",
       related=[("chlorophyll", 0.95), ("chloroplast", 0.95), ("calvin-cycle", 0.9),
                ("cellular-respiration", 0.85)],
       wp="Photosynthesis", wd="Q11982"),

    PH("Cellular Respiration", "cellular-respiration", "biology",
       "The set of metabolic reactions that convert nutrients into ATP and release waste products, using oxygen in aerobic organisms.",
       formula="C₆H₁₂O₆ + 6·O₂ → 6·CO₂ + 6·H₂O + ATP",
       applies=[":biological"], subsumed_by="biology",
       related=[("krebs-cycle", 0.95), ("glycolysis", 0.95), ("electron-transport-chain", 0.95),
                ("atp", 0.95), ("mitochondrion", 0.9)],
       wp="Cellular_respiration", wd="Q244761"),

    PH("Mitosis", "mitosis", "biology",
       "The process by which a eukaryotic cell divides its duplicated chromosomes equally into two daughter cells.",
       everyday="Every skin cell replacement, hair growth, and healing wound involves mitosis.",
       applies=[":biological"], subsumed_by="biology",
       related=[("meiosis", 0.85), ("cell-cycle", 0.9), ("chromosome", 0.9)],
       wp="Mitosis", wd="Q39958"),

    PH("Meiosis", "meiosis", "biology",
       "A specialized cell division producing four gametes each with half the chromosome number of the parent cell.",
       applies=[":biological"], subsumed_by="biology",
       related=[("mitosis", 0.85), ("gamete", 0.95), ("crossing-over", 0.9)],
       wp="Meiosis", wd="Q39982"),

    PH("Natural Selection", "natural-selection", "biology",
       "The differential survival and reproduction of individuals due to differences in heritable traits; the primary mechanism of evolution.",
       described_by=[PERSON("darwin-charles"), PERSON("wallace-alfred-russel")],
       described_year=1858,
       applies=[":biological"], subsumed_by="darwinian-evolution",
       related=[("darwinian-evolution", 1.0), ("adaptation", 0.9), ("fitness", 0.9)],
       wp="Natural_selection", wd="Q40450"),

    PH("Genetic Drift", "genetic-drift", "biology",
       "Random changes in allele frequency in a population from generation to generation, most pronounced in small populations.",
       applies=[":biological"], subsumed_by="genetics",
       related=[("natural-selection", 0.85), ("founder-effect", 0.9), ("bottleneck-effect", 0.9)],
       wp="Genetic_drift", wd="Q186311"),

    PH("Speciation", "speciation", "biology",
       "The evolutionary process by which populations evolve to become distinct species.",
       applies=[":biological"], subsumed_by="biology",
       related=[("natural-selection", 0.85), ("reproductive-isolation", 0.9),
                ("allopatric-speciation", 0.9)],
       wp="Speciation", wd="Q159830"),

    PH("Fermentation", "fermentation", "biology",
       "A metabolic process that produces chemical changes in organic substrates through the action of enzymes.",
       everyday="Bread rises because yeast ferments the dough's sugars, releasing CO₂; wine and beer are made the same way.",
       applies=[":biological", ":everyday", ":engineering"], subsumed_by="biology",
       related=[("yeast", 0.9), ("ethanol", 0.85), ("anaerobic-respiration", 0.85)],
       wp="Fermentation", wd="Q131538"),

    PH("Homeostasis", "homeostasis", "biology",
       "The self-regulating process by which biological systems maintain stable internal conditions.",
       everyday="Your body sweats to cool down and shivers to warm up; both maintain a core temperature near 37°C.",
       applies=[":biological"], subsumed_by="biology",
       related=[("thermoregulation", 0.9), ("negative-feedback", 0.9)],
       wp="Homeostasis", wd="Q170050"),

    PH("Immune Response", "immune-response", "biology",
       "The coordinated reaction of the body's cells and molecules to pathogens or other foreign substances.",
       applies=[":biological", ":medicine"], subsumed_by="immunology",
       related=[("antibody", 0.95), ("t-cell", 0.9), ("b-cell", 0.9), ("inflammation", 0.85)],
       wp="Immune_response", wd="Q184206"),

    PH("Inflammation", "inflammation", "biology",
       "Part of the biological response of body tissues to harmful stimuli; involves redness, heat, swelling, pain, and loss of function.",
       everyday="A splinter in your finger causes localized swelling and redness — that's inflammation at work.",
       applies=[":biological", ":medicine"], subsumed_by="immunology",
       related=[("immune-response", 0.9), ("cytokine", 0.85)],
       wp="Inflammation", wd="Q101991"),

    PH("Protein Folding", "protein-folding", "biology",
       "The physical process by which a protein chain acquires its native three-dimensional structure.",
       applies=[":biological", ":materials"], subsumed_by="biochemistry",
       related=[("protein", 0.95), ("levinthal-paradox", 0.85), ("prion", 0.75),
                ("alphafold", 0.7)],
       wp="Protein_folding", wd="Q848005"),

    PH("Apoptosis", "apoptosis", "biology",
       "Programmed cell death — an orderly biochemical process by which cells eliminate themselves without triggering inflammation.",
       everyday="Fingers form in the fetus because cells in the webbing between them apoptose.",
       applies=[":biological", ":medicine"], subsumed_by="biology",
       related=[("cell-cycle", 0.85), ("necrosis", 0.7)],
       wp="Apoptosis", wd="Q14041"),

    # ---- EARTH / WEATHER PHENOMENA ----
    PH("Plate Tectonics", "plate-tectonics", "earth-science",
       "The theory that Earth's outer shell is divided into plates that glide over the mantle, causing earthquakes, volcanoes, mountain-building, and ocean-basin formation.",
       described_by=[PERSON("wegener-alfred"), PERSON("hess-harry")],
       described_year=1965,
       applies=[":geological-timescale"], subsumed_by="earth-science",
       related=[("continental-drift", 0.95), ("seafloor-spreading", 0.9),
                ("subduction", 0.9), ("earthquake", 0.85), ("volcanism", 0.85)],
       wp="Plate_tectonics", wd="Q83500"),

    PH("Continental Drift", "continental-drift", "earth-science",
       "The movement of Earth's continents relative to each other; historical precursor to plate tectonics.",
       described_by=[PERSON("wegener-alfred")], described_year=1912,
       applies=[":geological-timescale"], subsumed_by="plate-tectonics",
       wp="Continental_drift", wd="Q170082"),

    PH("Earthquake", "earthquake", "earth-science",
       "Sudden release of energy in Earth's lithosphere creating seismic waves.",
       everyday="The 1906 San Francisco earthquake was caused by the San Andreas fault slipping.",
       applies=[":everyday", ":geological-timescale"], subsumed_by="earth-science",
       related=[("plate-tectonics", 0.9), ("seismic-wave", 0.95), ("richter-scale", 0.9),
                ("fault", 0.9)],
       wp="Earthquake", wd="Q7944"),

    PH("Volcanism", "volcanism", "earth-science",
       "Phenomenon of eruption of molten rock (magma) onto the surface of the Earth or a solid-surface planet.",
       everyday="Mount Vesuvius' 79 CE eruption buried Pompeii under ash and pumice.",
       applies=[":everyday", ":geological-timescale"], subsumed_by="earth-science",
       related=[("plate-tectonics", 0.85), ("magma", 0.95), ("lava", 0.95), ("volcano", 0.95)],
       wp="Volcanism"),

    PH("Weather", "weather", "meteorology",
       "The state of the atmosphere at a particular time and place: temperature, humidity, precipitation, wind, cloud cover.",
       everyday="A sunny morning turning into an afternoon thunderstorm is a common weather pattern.",
       applies=[":everyday"], subsumed_by="meteorology",
       related=[("climate", 0.85), ("precipitation", 0.9), ("wind", 0.9), ("cloud", 0.9)],
       wp="Weather", wd="Q11663"),

    PH("Climate", "climate", "earth-science",
       "The long-term average of weather in a region, typically averaged over 30 years.",
       applies=[":geological-timescale"], subsumed_by="earth-science",
       related=[("weather", 0.85), ("climate-change", 0.9), ("greenhouse-effect", 0.85)],
       wp="Climate", wd="Q7942"),

    PH("Greenhouse Effect", "greenhouse-effect", "earth-science",
       "The process by which atmospheric gases trap infrared radiation, warming the surface of a planet.",
       described_by=[PERSON("fourier-joseph"), PERSON("arrhenius-svante")],
       described_year=1896,
       everyday="Without it Earth's surface would average around -18°C; with it we sit at a livable 15°C.",
       applies=[":everyday", ":cosmology"], subsumed_by="atmospheric-science",
       related=[("climate-change", 0.9), ("carbon-dioxide", 0.9), ("methane", 0.85)],
       wp="Greenhouse_effect", wd="Q133707"),

    PH("Climate Change", "climate-change", "earth-science",
       "Long-term shifts in temperatures and weather patterns; the current episode is driven primarily by human emissions of greenhouse gases (IPCC consensus).",
       applies=[":everyday", ":geological-timescale"], subsumed_by="earth-science",
       related=[("greenhouse-effect", 0.9), ("global-warming", 0.95),
                ("carbon-dioxide", 0.9)],
       wp="Climate_change", wd="Q7942"),

    PH("Lightning", "lightning", "atmospheric-science",
       "A sudden electrostatic discharge during a thunderstorm between clouds, or between a cloud and the ground.",
       everyday="A bolt of lightning can be five times hotter than the surface of the sun.",
       applies=[":everyday"], subsumed_by="atmospheric-science",
       related=[("thunder", 0.95), ("electrostatic-discharge", 0.9), ("thunderstorm", 0.9)],
       wp="Lightning", wd="Q46946"),

    PH("Thunder", "thunder", "atmospheric-science",
       "The sound caused by lightning; produced by the rapid expansion of air heated by the bolt.",
       applies=[":everyday"], subsumed_by="atmospheric-science",
       related=[("lightning", 0.95)], wp="Thunder", wd="Q80174"),

    PH("Rainbow", "rainbow", "optics",
       "An optical phenomenon caused by reflection, refraction, and dispersion of light in water droplets, producing a multicolored arc.",
       everyday="Rainbows appear when the sun shines while it's raining.",
       applies=[":everyday"], subsumed_by="optics",
       related=[("dispersion-optics", 0.95), ("refraction", 0.9)],
       wp="Rainbow", wd="Q1052"),

    PH("Tide", "tide", "earth-science",
       "The rise and fall of sea levels caused by the gravitational forces of the moon and sun combined with Earth's rotation.",
       everyday="Coastal waters rise and fall roughly twice a day.",
       applies=[":everyday"], subsumed_by="oceanography",
       related=[("gravity", 0.9), ("moon", 0.9), ("neap-tide", 0.85), ("spring-tide", 0.85)],
       wp="Tide", wd="Q23384"),

    PH("Ocean Current", "ocean-current", "oceanography",
       "Continuous directed movement of seawater generated by wind, temperature and salinity differences, and Earth's rotation.",
       everyday="The Gulf Stream carries warm water from the tropics to Europe, giving the UK milder winters than similar latitudes elsewhere.",
       applies=[":everyday", ":geological-timescale"], subsumed_by="oceanography",
       related=[("thermohaline-circulation", 0.9), ("coriolis-force", 0.85)],
       wp="Ocean_current", wd="Q214881"),

    PH("El Niño", "el-nino", "oceanography",
       "A recurring climate pattern involving warmer-than-average sea-surface temperatures in the central and eastern tropical Pacific.",
       applies=[":everyday", ":geological-timescale"], subsumed_by="oceanography",
       related=[("la-nina", 0.9), ("enso", 0.95), ("weather", 0.85)],
       wp="El_Niño", wd="Q192874"),

    PH("Erosion", "erosion", "earth-science",
       "The geological process by which soil and rock are removed from the Earth's surface by wind, water, or ice.",
       everyday="The Grand Canyon was carved by the Colorado River eroding rock over millions of years.",
       applies=[":geological-timescale"], subsumed_by="earth-science",
       related=[("weathering", 0.9), ("sediment", 0.85)],
       wp="Erosion", wd="Q4914"),

    PH("Weathering", "weathering", "earth-science",
       "The breaking down of rocks, soils, and minerals through contact with the atmosphere, water, and biological organisms.",
       applies=[":geological-timescale"], subsumed_by="earth-science",
       related=[("erosion", 0.9), ("chemical-weathering", 0.9)],
       wp="Weathering", wd="Q192368"),

    # ---- SUPERSEDED SCIENCE (a few more) ----
    S("Spontaneous Generation", "biology", "framework",
      id_slug="spontaneous-generation",
      status=":superseded",
      superseded_by="biogenesis",
      era={"year-from": -400, "year-to": 1864},
      described_year=-400,
      applies=[":historical-only"],
      narrative="The disproven belief that living organisms could arise spontaneously from non-living matter, e.g. maggots from meat; refuted by Pasteur's experiments.",
      subsumed_by="biology",
      related=[("biogenesis", 0.95), ("pasteur-experiment", 0.9)],
      provenance=WD("Q1043232", "Spontaneous_generation")),

    S("Biogenesis", "biology", "principle",
      id_slug="biogenesis",
      described_by=[PERSON("pasteur-louis")], described_year=1859,
      narrative="The principle that life arises only from pre-existing life.",
      subsumed_by="biology",
      related=[("spontaneous-generation", 0.95), ("germ-theory-of-disease", 0.85)],
      provenance=WD("Q1050183", "Biogenesis")),

    S("Vitalism", "biology", "framework",
      id_slug="vitalism",
      status=":superseded",
      superseded_by="biochemistry",
      era={"year-from": 1600, "year-to": 1900},
      described_year=1600,
      applies=[":historical-only"],
      narrative="The disproven belief that living organisms are fundamentally different from non-living entities because they contain a vital force or spirit.",
      subsumed_by="biology",
      related=[("biochemistry", 0.9), ("wohler-urea-synthesis", 0.85)],
      provenance=WD("Q216347", "Vitalism")),
]
