"""Common chemical compounds. Target ~400 nodes.

Sources: Wikipedia compound articles. Each compound carries its molecular
formula. Familiar / textbook / medically-relevant compounds only.
"""

from _helpers import S, PERSON


def W(name):
    return [{"source": "wikipedia", "url": f"https://en.wikipedia.org/wiki/{name}"}]


def C(name, slug, formula, disc, narr, everyday=None, extras=None, applies=None,
      subsumed_by=None, used_in_store=None, wp=None):
    return S(name, disc, "compound",
             id_slug=slug, extras=extras or [], narrative=narr, everyday=everyday,
             applies=applies or [":materials", ":everyday"],
             chem_formula=formula,
             subsumed_by=subsumed_by or "chemistry",
             used_in_store=[f"store/{u}" for u in (used_in_store or [])],
             provenance=W(wp or name.replace(" ", "_")))


SCIENCES = []

# ---- WATER + FAMILIAR INORGANIC ----
COMPOUNDS = [
    # (name, slug, formula, discipline, narrative, everyday, extras, subsumed_by, used_in_store, wp)
    ("Water", "water", "H₂O", "inorganic-chemistry",
     "The most abundant molecule in the biosphere — H₂O, a polar molecule that forms hydrogen bonds and dissolves an enormous range of substances.",
     "Every glass of water you drink is ~10²⁵ H₂O molecules.",
     ["H2O", "aqua", "dihydrogen monoxide", "hydric acid"],
     "inorganic-chemistry", ["food-and-beverage"], "Water"),
    ("Carbon Dioxide", "carbon-dioxide", "CO₂", "inorganic-chemistry",
     "Colorless gas produced by respiration, combustion, and fermentation; the dominant greenhouse gas driving anthropogenic climate change.",
     "The bubbles in carbonated drinks are dissolved CO₂ escaping as pressure drops.",
     ["CO2", "carbonic anhydride"],
     "inorganic-chemistry", ["food-and-beverage"], "Carbon_dioxide"),
    ("Oxygen Gas", "oxygen-gas", "O₂", "inorganic-chemistry",
     "Diatomic molecular form of the element oxygen; makes up ~21% of Earth's atmosphere and is essential for aerobic respiration.",
     "Every breath is roughly 21% O₂ by volume.",
     ["O2", "molecular oxygen"],
     "inorganic-chemistry", [], "Oxygen"),
    ("Nitrogen Gas", "nitrogen-gas", "N₂", "inorganic-chemistry",
     "Diatomic molecular form of nitrogen; ~78% of Earth's atmosphere by volume; largely inert at ambient conditions.",
     None, ["N2", "dinitrogen"],
     "inorganic-chemistry", [], "Nitrogen"),
    ("Hydrogen Gas", "hydrogen-gas", "H₂", "inorganic-chemistry",
     "Diatomic molecular hydrogen; the lightest and most abundant element in the universe.",
     None, ["H2", "molecular hydrogen"],
     "inorganic-chemistry", [], "Hydrogen"),
    ("Methane", "methane", "CH₄", "organic-chemistry",
     "The simplest hydrocarbon; the main component of natural gas; a potent greenhouse gas.",
     "Natural gas stoves burn mostly methane.",
     ["CH4", "marsh gas", "natural gas"],
     "organic-chemistry", [], "Methane"),
    ("Ammonia", "ammonia", "NH₃", "inorganic-chemistry",
     "Pungent gas made industrially by the Haber process; the base for most nitrogen fertilizers and many cleaning products.",
     "Household glass cleaner often contains dilute ammonia.",
     ["NH3", "azane"],
     "inorganic-chemistry", ["cleaners", "fertilizers"], "Ammonia"),
    ("Hydrochloric Acid", "hydrochloric-acid", "HCl", "inorganic-chemistry",
     "Strong mineral acid; the aqueous form of hydrogen chloride; secreted by the stomach for digestion.",
     "The 'muriatic acid' sold at hardware stores is concentrated HCl.",
     ["HCl", "muriatic acid"],
     "inorganic-chemistry", ["cleaners"], "Hydrochloric_acid"),
    ("Sulfuric Acid", "sulfuric-acid", "H₂SO₄", "inorganic-chemistry",
     "Extremely corrosive strong mineral acid; one of the most produced industrial chemicals; used in fertilizer manufacture, batteries, and refining.",
     "Lead-acid car batteries use dilute sulfuric acid as electrolyte.",
     ["H2SO4", "oil of vitriol"],
     "inorganic-chemistry", ["fertilizers"], "Sulfuric_acid"),
    ("Nitric Acid", "nitric-acid", "HNO₃", "inorganic-chemistry",
     "Strong, highly corrosive mineral acid; used in fertilizer and explosive manufacture.",
     None, ["HNO3", "aqua fortis"],
     "inorganic-chemistry", ["fertilizers"], "Nitric_acid"),
    ("Sodium Chloride", "sodium-chloride", "NaCl", "inorganic-chemistry",
     "Common table salt — an ionic compound essential for animal life and one of the oldest traded commodities.",
     "Every seawater sample and every kitchen shaker contains it.",
     ["NaCl", "table salt", "halite", "common salt", "rock salt"],
     "inorganic-chemistry", ["food-and-beverage", "seasonings"], "Sodium_chloride"),
    ("Sodium Hydroxide", "sodium-hydroxide", "NaOH", "inorganic-chemistry",
     "Strong base — 'lye' or 'caustic soda'; used in soap-making, paper production, and drain cleaners.",
     "Bar-soap manufacture combines NaOH with fats via saponification.",
     ["NaOH", "lye", "caustic soda"],
     "inorganic-chemistry", ["cleaners", "soap"], "Sodium_hydroxide"),
    ("Calcium Carbonate", "calcium-carbonate", "CaCO₃", "inorganic-chemistry",
     "The compound that makes up limestone, chalk, and marble; also the shells of most marine organisms.",
     "The Cliffs of Dover are calcium carbonate from ancient sea life.",
     ["CaCO3", "limestone", "chalk", "calcite"],
     "inorganic-chemistry", ["building-materials"], "Calcium_carbonate"),
    ("Silicon Dioxide", "silicon-dioxide", "SiO₂", "inorganic-chemistry",
     "The primary component of sand, quartz, and glass; makes up ~60% of Earth's crust.",
     "Every beach and every window pane is mostly SiO₂.",
     ["SiO2", "silica", "quartz"],
     "inorganic-chemistry", ["building-materials", "electronics"], "Silicon_dioxide"),
    ("Iron Oxide", "iron-oxide-red", "Fe₂O₃", "inorganic-chemistry",
     "The red rust that forms when iron corrodes in the presence of oxygen and moisture; also a common pigment.",
     "The rust on a bicycle chain is mostly Fe₂O₃.",
     ["Fe2O3", "hematite", "ferric oxide", "rust"],
     "inorganic-chemistry", ["paints-pigments"], "Iron(III)_oxide"),
    ("Ozone", "ozone", "O₃", "inorganic-chemistry",
     "Triatomic form of oxygen; in the stratosphere it shields the surface from UV, at ground level it is a pollutant.",
     "The 'clean' smell after a thunderstorm is partly ozone.",
     ["O3", "trioxygen"],
     "inorganic-chemistry", [], "Ozone"),
    ("Hydrogen Peroxide", "hydrogen-peroxide", "H₂O₂", "inorganic-chemistry",
     "Weakly acidic oxidizer used as a mild antiseptic and bleach; decomposes to water and oxygen.",
     "The 3% solution in medicine cabinets is a wound cleaner.",
     ["H2O2", "peroxide"],
     "inorganic-chemistry", ["cleaners", "personal-care"], "Hydrogen_peroxide"),
    ("Sodium Bicarbonate", "sodium-bicarbonate", "NaHCO₃", "inorganic-chemistry",
     "'Baking soda' — a mild base used in baking, cleaning, and antacid formulas.",
     "The rise in baked goods comes from bicarbonate reacting with acid to release CO₂.",
     ["NaHCO3", "baking soda", "bicarb", "sodium hydrogen carbonate"],
     "inorganic-chemistry", ["food-and-beverage", "cleaners"], "Sodium_bicarbonate"),
    ("Sodium Carbonate", "sodium-carbonate", "Na₂CO₃", "inorganic-chemistry",
     "'Washing soda' or 'soda ash' — an industrial base used in glassmaking, water softening, and cleaning.",
     None, ["Na2CO3", "soda ash", "washing soda"],
     "inorganic-chemistry", ["cleaners", "glass"], "Sodium_carbonate"),
    ("Calcium Hydroxide", "calcium-hydroxide", "Ca(OH)₂", "inorganic-chemistry",
     "'Slaked lime' — a strong base used in construction (mortar), water treatment, and food processing.",
     "Nixtamalization of corn uses calcium hydroxide to soften kernels for masa.",
     ["Ca(OH)2", "slaked lime", "portlandite"],
     "inorganic-chemistry", ["building-materials"], "Calcium_hydroxide"),
    ("Ethanol", "ethanol", "C₂H₆O", "organic-chemistry",
     "The alcohol in fermented and distilled beverages; also a solvent and biofuel.",
     "Every beer, wine, and spirit owes its intoxicating effect to ethanol.",
     ["C2H6O", "C2H5OH", "ethyl alcohol", "grain alcohol", "drinking alcohol"],
     "organic-chemistry", ["food-and-beverage", "alcoholic-drinks"], "Ethanol"),
    ("Methanol", "methanol", "CH₃OH", "organic-chemistry",
     "The simplest alcohol; toxic to humans; used as solvent, antifreeze, and fuel.",
     "Windshield washer fluid often contains methanol.",
     ["CH3OH", "wood alcohol", "methyl alcohol"],
     "organic-chemistry", [], "Methanol"),
    ("Acetic Acid", "acetic-acid", "CH₃COOH", "organic-chemistry",
     "The acid in vinegar; a fundamental building block of organic chemistry.",
     "Household vinegar is ~5% acetic acid in water.",
     ["CH3COOH", "ethanoic acid", "vinegar"],
     "organic-chemistry", ["food-and-beverage", "condiments"], "Acetic_acid"),
    ("Citric Acid", "citric-acid", "C₆H₈O₇", "organic-chemistry",
     "Weak organic acid abundant in citrus fruits; used as a flavoring and preservative.",
     "The tartness of lemons and limes is citric acid.",
     ["C6H8O7", "2-hydroxypropane-1,2,3-tricarboxylic acid"],
     "organic-chemistry", ["food-and-beverage"], "Citric_acid"),
    ("Glucose", "glucose", "C₆H₁₂O₆", "biochemistry",
     "The simplest sugar and primary energy currency of most living cells.",
     "Blood glucose supplies the brain with essentially all its energy.",
     ["C6H12O6", "dextrose", "grape sugar", "blood sugar"],
     "biochemistry", ["food-and-beverage"], "Glucose"),
    ("Fructose", "fructose", "C₆H₁₂O₆", "biochemistry",
     "A simple sugar found in fruits, honey, and root vegetables; isomer of glucose.",
     "The sweetness of ripe fruit is largely fructose.",
     ["C6H12O6", "fruit sugar", "levulose"],
     "biochemistry", ["food-and-beverage"], "Fructose"),
    ("Sucrose", "sucrose", "C₁₂H₂₂O₁₁", "biochemistry",
     "Common table sugar — a disaccharide of glucose and fructose.",
     "Every teaspoon of table sugar is sucrose.",
     ["C12H22O11", "table sugar", "cane sugar", "beet sugar"],
     "biochemistry", ["food-and-beverage"], "Sucrose"),
    ("Lactose", "lactose", "C₁₂H₂₂O₁₁", "biochemistry",
     "The sugar in milk; a disaccharide of glucose and galactose.",
     "Lactose intolerance is the inability to break down this sugar in adulthood.",
     ["C12H22O11", "milk sugar"],
     "biochemistry", ["food-and-beverage"], "Lactose"),
    ("Cellulose", "cellulose", "(C₆H₁₀O₅)ₙ", "biochemistry",
     "The primary structural polysaccharide of plant cell walls — the most abundant organic polymer on Earth.",
     "Cotton fiber is ~90% cellulose; paper is nearly pure cellulose.",
     ["(C6H10O5)n", "cellulose polymer"],
     "biochemistry", ["textiles", "paper"], "Cellulose"),
    ("Starch", "starch", "(C₆H₁₀O₅)ₙ", "biochemistry",
     "Polysaccharide plants use to store energy; the main carbohydrate in bread, rice, potatoes, and pasta.",
     "The white powder in a potato is mostly starch granules.",
     ["(C6H10O5)n", "amylum"],
     "biochemistry", ["food-and-beverage"], "Starch"),
    ("Chitin", "chitin", "(C₈H₁₃O₅N)ₙ", "biochemistry",
     "Polysaccharide forming exoskeletons of arthropods, cell walls of fungi, and beaks of cephalopods.",
     "A crab's hard shell is chitin.",
     ["(C8H13O5N)n"],
     "biochemistry", [], "Chitin"),
    ("Adenosine Triphosphate", "atp", "C₁₀H₁₆N₅O₁₃P₃", "biochemistry",
     "The primary short-term energy carrier in living cells — 'the molecular unit of currency of intracellular energy transfer'.",
     "Every muscle contraction burns ATP.",
     ["ATP", "adenosine 5'-triphosphate", "C10H16N5O13P3"],
     "biochemistry", [], "Adenosine_triphosphate"),
    ("Adenosine Diphosphate", "adp", "C₁₀H₁₅N₅O₁₀P₂", "biochemistry",
     "ATP with one phosphate removed; produced when ATP is spent and regenerated by ATP synthase.",
     None, ["ADP", "adenosine diphosphate"],
     "biochemistry", [], "Adenosine_diphosphate"),
    ("DNA", "dna", "C₅H₁₀N₅O₆P (nucleotide-repeat)", "biochemistry",
     "Deoxyribonucleic acid — the double-helical polymer carrying genetic information in most living organisms and many viruses.",
     "Every cell in your body has about 2 meters of DNA packed into its nucleus.",
     ["deoxyribonucleic acid", "genetic material", "genome"],
     "biochemistry", [], "DNA"),
    ("RNA", "rna", "C₅H₁₀N₅O₇P (nucleotide-repeat)", "biochemistry",
     "Ribonucleic acid — single-stranded nucleic acid that carries out gene expression, catalysis, and many regulatory tasks.",
     "mRNA carries instructions from DNA to the ribosome where proteins are built.",
     ["ribonucleic acid", "mRNA", "messenger RNA"],
     "biochemistry", [], "RNA"),
    ("Hemoglobin", "hemoglobin", "protein (~64 kDa)", "biochemistry",
     "The iron-containing oxygen-transport protein in red blood cells of vertebrates.",
     "Blood is red because hemoglobin binds oxygen and reflects red light.",
     ["haemoglobin", "Hb", "oxygen carrier protein"],
     "biochemistry", [], "Hemoglobin"),
    ("Chlorophyll", "chlorophyll", "C₅₅H₇₂MgN₄O₅ (chl-a)", "biochemistry",
     "The green pigment in plants, algae, and cyanobacteria that captures light energy for photosynthesis.",
     "Leaves are green because chlorophyll absorbs red and blue light and reflects green.",
     ["chlorophyll a", "chlorophyll b", "leaf pigment", "green pigment"],
     "biochemistry", [], "Chlorophyll"),
    ("Insulin", "insulin", "protein (~5.8 kDa)", "biochemistry",
     "Peptide hormone from the pancreas that regulates blood sugar by promoting cellular glucose uptake.",
     "Type 1 diabetics inject insulin because their pancreas no longer makes it.",
     ["human insulin", "pancreatic hormone"],
     "biochemistry", ["pharmaceuticals"], "Insulin"),
    ("Cholesterol", "cholesterol", "C₂₇H₄₆O", "biochemistry",
     "Sterol found in animal cell membranes; precursor to steroid hormones and bile acids; contested role in cardiovascular disease.",
     "Egg yolks contain a substantial amount of cholesterol.",
     ["C27H46O", "cholesterin"],
     "biochemistry", [], "Cholesterol"),
    ("Testosterone", "testosterone", "C₁₉H₂₈O₂", "biochemistry",
     "Primary male sex hormone; produced mainly in the testes; also present in females at lower levels.",
     None, ["C19H28O2", "androgen"],
     "biochemistry", [], "Testosterone"),
    ("Estrogen", "estrogen", "C₁₈H₂₄O₂ (estradiol)", "biochemistry",
     "Family of steroid hormones responsible for female reproductive development and cyclic function.",
     None, ["estradiol", "oestrogen", "oestradiol"],
     "biochemistry", [], "Estrogen"),
    ("Cortisol", "cortisol", "C₂₁H₃₀O₅", "biochemistry",
     "Steroid stress hormone secreted by the adrenal cortex; regulates metabolism, immune response, and the sleep-wake cycle.",
     "Blood cortisol peaks in the early morning to help you wake up.",
     ["C21H30O5", "hydrocortisone", "stress hormone"],
     "biochemistry", ["pharmaceuticals"], "Cortisol"),
    ("Dopamine", "dopamine", "C₈H₁₁NO₂", "neuroscience",
     "Neurotransmitter involved in reward, motivation, motor control, and executive function.",
     "Parkinson's disease is characterized by loss of dopamine-producing neurons in the substantia nigra.",
     ["C8H11NO2", "3,4-dihydroxyphenethylamine"],
     "neuroscience", [], "Dopamine"),
    ("Serotonin", "serotonin", "C₁₀H₁₂N₂O", "neuroscience",
     "Neurotransmitter involved in mood, appetite, and sleep regulation.",
     "SSRI antidepressants (selective serotonin reuptake inhibitors) target its pathway.",
     ["C10H12N2O", "5-hydroxytryptamine", "5-HT"],
     "neuroscience", [], "Serotonin"),
    ("Acetylcholine", "acetylcholine", "C₇H₁₆NO₂⁺", "neuroscience",
     "The neurotransmitter at neuromuscular junctions and many autonomic synapses.",
     "Nerve gases like sarin work by blocking the enzyme that breaks down acetylcholine.",
     ["ACh", "C7H16NO2+"],
     "neuroscience", [], "Acetylcholine"),
    ("Adrenaline", "adrenaline", "C₉H₁₃NO₃", "biochemistry",
     "Hormone and neurotransmitter of the fight-or-flight response; increases heart rate and blood glucose.",
     "Epinephrine injections (EpiPens) treat life-threatening allergic reactions.",
     ["epinephrine", "C9H13NO3"],
     "biochemistry", ["pharmaceuticals"], "Adrenaline"),
    ("Melatonin", "melatonin", "C₁₃H₁₆N₂O₂", "biochemistry",
     "Hormone secreted by the pineal gland that regulates the sleep-wake cycle in response to darkness.",
     None, ["C13H16N2O2"],
     "biochemistry", ["pharmaceuticals"], "Melatonin"),
    ("Caffeine", "caffeine", "C₈H₁₀N₄O₂", "biochemistry",
     "Central nervous system stimulant found in coffee, tea, and cocoa; adenosine receptor antagonist.",
     "A cup of coffee contains ~80-100 mg of caffeine.",
     ["C8H10N4O2", "1,3,7-trimethylxanthine"],
     "biochemistry", ["food-and-beverage", "beverages-caffeinated"], "Caffeine"),
    ("Nicotine", "nicotine", "C₁₀H₁₄N₂", "biochemistry",
     "Alkaloid found in tobacco; acts as an agonist at nicotinic acetylcholine receptors; highly addictive.",
     None, ["C10H14N2"],
     "biochemistry", ["tobacco"], "Nicotine"),
    ("Ethylene", "ethylene", "C₂H₄", "organic-chemistry",
     "Simplest alkene; a plant hormone that triggers fruit ripening; also the feedstock for polyethylene.",
     "Putting an unripe avocado in a bag with a banana ripens it via ethylene.",
     ["C2H4", "ethene"],
     "organic-chemistry", [], "Ethylene"),
    ("Polyethylene", "polyethylene", "(C₂H₄)ₙ", "materials-science",
     "The most-produced plastic in the world; used for bags, bottles, films, and pipes.",
     "Grocery bags and milk jugs are typically polyethylene.",
     ["PE", "(C2H4)n", "polythene"],
     "materials-science", ["packaging", "plastics"], "Polyethylene"),
    ("Polypropylene", "polypropylene", "(C₃H₆)ₙ", "materials-science",
     "Tough thermoplastic used in packaging, textiles, and living hinges.",
     "The 'PP' recycling symbol identifies polypropylene items.",
     ["PP", "(C3H6)n"],
     "materials-science", ["packaging", "plastics"], "Polypropylene"),
    ("Polystyrene", "polystyrene", "(C₈H₈)ₙ", "materials-science",
     "Rigid plastic used in disposable cutlery, CD cases, and (foamed) as Styrofoam.",
     "The white 'foam' coffee cups are expanded polystyrene.",
     ["PS", "(C8H8)n", "styrofoam"],
     "materials-science", ["packaging", "plastics"], "Polystyrene"),
    ("Polyvinyl Chloride", "pvc", "(C₂H₃Cl)ₙ", "materials-science",
     "Rigid or flexible plastic used in pipes, cable insulation, and vinyl records.",
     None, ["PVC", "(C2H3Cl)n", "vinyl"],
     "materials-science", ["plastics", "building-materials"], "Polyvinyl_chloride"),
    ("Polytetrafluoroethylene", "ptfe", "(C₂F₄)ₙ", "materials-science",
     "Non-stick fluoropolymer, sold as Teflon; extremely low friction and chemically inert.",
     "Non-stick frying pans are coated with PTFE.",
     ["PTFE", "teflon", "(C2F4)n"],
     "materials-science", ["cookware"], "Polytetrafluoroethylene"),
    ("Nylon", "nylon", "polyamide (varies)", "materials-science",
     "Family of synthetic polyamides used in ropes, fabrics, gears, and injection-molded parts.",
     None, ["polyamide", "PA"],
     "materials-science", ["textiles"], "Nylon"),
    ("Polyester", "polyester-fiber", "polyester (varies)", "materials-science",
     "Family of polymers containing ester functional groups; PET is the dominant plastic bottle material.",
     "Every plastic soda bottle is polyester (PET).",
     ["PET", "polyethylene terephthalate"],
     "materials-science", ["textiles", "packaging"], "Polyester"),
    ("Kevlar", "kevlar", "polyaramid", "materials-science",
     "High-strength aramid fiber used in bulletproof vests, ropes, and aerospace composites.",
     None, ["aramid", "poly-paraphenylene terephthalamide"],
     "materials-science", ["textiles"], "Kevlar"),
    ("Silicone", "silicone", "(R₂SiO)ₙ", "materials-science",
     "Polymer with a silicon-oxygen backbone; heat-resistant and biocompatible; used in medical implants, kitchenware, and sealants.",
     "Silicone baking mats and oven-safe spatulas are silicone rubber.",
     ["polysiloxane"],
     "materials-science", ["cookware", "medical"], "Silicone"),
    ("Graphene", "graphene", "C (2D sheet)", "materials-science",
     "A single layer of carbon atoms arranged in a hexagonal lattice; extraordinary electrical and mechanical properties.",
     None, ["2D carbon"],
     "materials-science", ["electronics"], "Graphene"),
    ("Graphite", "graphite", "C (allotrope)", "materials-science",
     "Layered allotrope of carbon; used in pencil leads, electrodes, and lubricants.",
     "The 'lead' in a pencil is actually graphite.",
     ["plumbago", "black lead"],
     "materials-science", ["stationery"], "Graphite"),
    ("Diamond", "diamond", "C (allotrope)", "materials-science",
     "Cubic crystalline allotrope of carbon; hardest naturally-occurring material.",
     "Every gem diamond is pure crystalline carbon.",
     ["diamond gem"],
     "materials-science", ["jewelry-gems"], "Diamond"),
    ("Fullerene", "fullerene", "C₆₀ (buckminsterfullerene)", "materials-science",
     "Molecular allotrope of carbon; C₆₀ is the soccer-ball-shaped 'buckyball'.",
     None, ["C60", "buckyball", "buckminsterfullerene"],
     "materials-science", [], "Fullerene"),
    ("Carbon Nanotube", "carbon-nanotube", "C (nanotube)", "materials-science",
     "Cylindrical carbon allotrope; exceptional tensile strength and electrical conductivity.",
     None, ["CNT", "nanotube"],
     "materials-science", [], "Carbon_nanotube"),
    ("Ceramic", "ceramic", "varies (oxides)", "materials-science",
     "Inorganic, non-metallic solids typically formed by heating and cooling; includes pottery, porcelain, and modern engineering ceramics.",
     None, ["ceramics"],
     "materials-science", ["housewares"], "Ceramic"),
    ("Concrete", "concrete", "composite (Ca silicates + aggregate)", "materials-science",
     "Composite of cement paste and aggregate; the most-used man-made material in the world.",
     None, ["portland concrete"],
     "materials-science", ["building-materials"], "Concrete"),
    ("Glass", "glass", "SiO₂-based (amorphous)", "materials-science",
     "Amorphous non-crystalline solid, usually silica-based; transparent to visible light.",
     None, ["silica glass", "soda-lime glass"],
     "materials-science", ["glass"], "Glass"),
    ("Steel", "steel", "Fe + C alloy", "materials-science",
     "Alloy of iron with a small percentage of carbon; the most widely-used metallic material.",
     None, ["carbon steel"],
     "materials-science", ["building-materials"], "Steel"),
    ("Bronze", "bronze", "Cu + Sn alloy", "materials-science",
     "Copper-tin alloy; the defining material of the Bronze Age.",
     None, ["copper-tin alloy"],
     "materials-science", [], "Bronze"),
    ("Brass", "brass", "Cu + Zn alloy", "materials-science",
     "Copper-zinc alloy; corrosion-resistant, used for plumbing, musical instruments, and decorative items.",
     None, ["copper-zinc alloy"],
     "materials-science", [], "Brass"),
    ("Titanium Dioxide", "titanium-dioxide", "TiO₂", "inorganic-chemistry",
     "White pigment used in paint, sunscreen, food coloring, and paper.",
     "The bright white in most white paints is TiO₂.",
     ["TiO2", "titania"],
     "inorganic-chemistry", ["paints-pigments", "personal-care"], "Titanium_dioxide"),
    ("Aluminum Oxide", "aluminum-oxide", "Al₂O₃", "inorganic-chemistry",
     "Very hard oxide used as an abrasive, refractory, and gemstone (corundum, ruby, sapphire).",
     "Sapphires and rubies are aluminum oxide with trace impurities.",
     ["Al2O3", "alumina", "corundum"],
     "inorganic-chemistry", ["jewelry-gems"], "Aluminum_oxide"),
    ("Copper Sulfate", "copper-sulfate", "CuSO₄", "inorganic-chemistry",
     "Bright blue crystals used as fungicide, algaecide, and in electroplating.",
     None, ["CuSO4", "blue vitriol", "bluestone"],
     "inorganic-chemistry", ["agriculture-supplies"], "Copper(II)_sulfate"),
    ("Potassium Nitrate", "potassium-nitrate", "KNO₃", "inorganic-chemistry",
     "'Saltpeter' — historic component of gunpowder and modern fertilizer ingredient.",
     None, ["KNO3", "saltpeter", "nitre"],
     "inorganic-chemistry", ["fertilizers"], "Potassium_nitrate"),
    ("Silver Nitrate", "silver-nitrate", "AgNO₃", "inorganic-chemistry",
     "Photosensitive silver salt used historically in photography and medically as an antiseptic.",
     None, ["AgNO3", "lunar caustic"],
     "inorganic-chemistry", [], "Silver_nitrate"),
    ("Calcium Sulfate", "calcium-sulfate", "CaSO₄", "inorganic-chemistry",
     "The main component of gypsum and plaster of Paris.",
     "Drywall is gypsum — calcium sulfate dihydrate.",
     ["CaSO4", "gypsum", "plaster of paris"],
     "inorganic-chemistry", ["building-materials"], "Calcium_sulfate"),
    ("Magnesium Oxide", "magnesium-oxide", "MgO", "inorganic-chemistry",
     "White hygroscopic solid used as refractory, antacid, and food additive.",
     None, ["MgO", "magnesia"],
     "inorganic-chemistry", ["pharmaceuticals"], "Magnesium_oxide"),
    ("Zinc Oxide", "zinc-oxide", "ZnO", "inorganic-chemistry",
     "White powder used in sunscreens, ointments, and cosmetics; also a wide-bandgap semiconductor.",
     "The white paste on a lifeguard's nose is zinc oxide sunscreen.",
     ["ZnO", "zinc white"],
     "inorganic-chemistry", ["personal-care"], "Zinc_oxide"),
    ("Sodium Sulfate", "sodium-sulfate", "Na₂SO₄", "inorganic-chemistry",
     "White crystalline salt used in detergents and glassmaking; hydrated form is Glauber's salt.",
     None, ["Na2SO4", "glauber's salt"],
     "inorganic-chemistry", ["cleaners"], "Sodium_sulfate"),
    ("Phosphoric Acid", "phosphoric-acid", "H₃PO₄", "inorganic-chemistry",
     "Mineral acid used to acidify colas and in fertilizer production.",
     "The tangy edge in colas comes from phosphoric acid.",
     ["H3PO4"],
     "inorganic-chemistry", ["food-and-beverage", "fertilizers"], "Phosphoric_acid"),
    ("Formaldehyde", "formaldehyde", "CH₂O", "organic-chemistry",
     "Simplest aldehyde; preservative for biological specimens and precursor to many polymers.",
     None, ["CH2O", "methanal"],
     "organic-chemistry", [], "Formaldehyde"),
    ("Formic Acid", "formic-acid", "HCOOH", "organic-chemistry",
     "Simplest carboxylic acid; occurs naturally in ants and bee stings.",
     "The itch of an ant bite is partly formic acid.",
     ["HCOOH", "methanoic acid"],
     "organic-chemistry", [], "Formic_acid"),
    ("Benzene", "benzene", "C₆H₆", "organic-chemistry",
     "Aromatic hydrocarbon with a hexagonal ring of six carbons; carcinogen; parent of aromatic chemistry.",
     None, ["C6H6", "benzol"],
     "organic-chemistry", [], "Benzene"),
    ("Toluene", "toluene", "C₇H₈", "organic-chemistry",
     "Aromatic hydrocarbon; common solvent and precursor to explosives and dyes.",
     None, ["C7H8", "methylbenzene"],
     "organic-chemistry", [], "Toluene"),
    ("Aspirin", "aspirin", "C₉H₈O₄", "pharmacology",
     "Acetylsalicylic acid — analgesic and antiplatelet drug; the archetypal over-the-counter pain reliever.",
     "A daily low-dose aspirin is prescribed to reduce heart-attack risk in some adults.",
     ["C9H8O4", "acetylsalicylic acid", "ASA"],
     "pharmacology", ["pharmaceuticals"], "Aspirin"),
    ("Ibuprofen", "ibuprofen", "C₁₃H₁₈O₂", "pharmacology",
     "Non-steroidal anti-inflammatory drug (NSAID); commonly sold as Advil or Motrin.",
     None, ["C13H18O2"],
     "pharmacology", ["pharmaceuticals"], "Ibuprofen"),
    ("Paracetamol", "paracetamol", "C₈H₉NO₂", "pharmacology",
     "Analgesic and antipyretic; called acetaminophen in the US, sold as Tylenol.",
     None, ["C8H9NO2", "acetaminophen"],
     "pharmacology", ["pharmaceuticals"], "Paracetamol"),
    ("Penicillin", "penicillin", "C₉H₁₁N₂O₄S (core)", "pharmacology",
     "The first widely-used antibiotic, derived from Penicillium fungi.",
     None, ["penicillin G"],
     "pharmacology", ["pharmaceuticals"], "Penicillin"),
    ("Morphine", "morphine", "C₁₇H₁₉NO₃", "pharmacology",
     "Opiate analgesic derived from the opium poppy; standard against which other opioids are measured.",
     None, ["C17H19NO3"],
     "pharmacology", ["pharmaceuticals"], "Morphine"),
    ("Insulin (Recombinant)", "recombinant-insulin", "protein (~5.8 kDa)", "pharmacology",
     "Human insulin produced by recombinant DNA technology; treats diabetes.",
     None, ["humulin", "novolin"],
     "pharmacology", ["pharmaceuticals"], "Insulin_(medication)"),
    ("Vitamin C", "vitamin-c", "C₆H₈O₆", "biochemistry",
     "Ascorbic acid — an essential nutrient with antioxidant properties; deficiency causes scurvy.",
     "Citrus fruits are a classic dietary source.",
     ["C6H8O6", "ascorbic acid", "l-ascorbate"],
     "biochemistry", ["food-and-beverage", "supplements"], "Vitamin_C"),
    ("Vitamin D", "vitamin-d", "C₂₇H₄₄O (D₃)", "biochemistry",
     "Fat-soluble vitamin regulating calcium and phosphate; synthesized in skin from UV exposure.",
     None, ["cholecalciferol", "ergocalciferol", "D3"],
     "biochemistry", ["supplements"], "Vitamin_D"),
    ("Vitamin B12", "vitamin-b12", "C₆₃H₈₈CoN₁₄O₁₄P", "biochemistry",
     "Cobalt-containing vitamin required for red blood cell formation and nervous system function.",
     None, ["cobalamin", "cyanocobalamin"],
     "biochemistry", ["supplements"], "Vitamin_B12"),
    ("Vitamin A", "vitamin-a", "C₂₀H₃₀O", "biochemistry",
     "Fat-soluble vitamin critical for vision, immunity, and reproduction.",
     None, ["retinol", "retinyl palmitate"],
     "biochemistry", ["supplements"], "Vitamin_A"),
    ("Folic Acid", "folic-acid", "C₁₉H₁₉N₇O₆", "biochemistry",
     "B-vitamin critical for DNA synthesis and cell division; supplementation prevents neural tube defects.",
     None, ["folate", "vitamin B9"],
     "biochemistry", ["supplements"], "Folate"),
    ("Iron Sulfate", "iron-sulfate", "FeSO₄", "inorganic-chemistry",
     "Common iron supplement and precursor to inks and dyes.",
     None, ["FeSO4", "ferrous sulfate", "green vitriol"],
     "inorganic-chemistry", ["supplements"], "Iron(II)_sulfate"),
    ("Chlorine Gas", "chlorine-gas", "Cl₂", "inorganic-chemistry",
     "Diatomic form of chlorine; used as a disinfectant and in chemical synthesis; historically a chemical weapon.",
     "Public swimming pools are disinfected with chlorine.",
     ["Cl2"],
     "inorganic-chemistry", [], "Chlorine"),
    ("Sodium Hypochlorite", "sodium-hypochlorite", "NaClO", "inorganic-chemistry",
     "Active ingredient in liquid household bleach.",
     "Chlorine bleach is dilute NaClO.",
     ["NaClO", "hypochlorite", "bleach"],
     "inorganic-chemistry", ["cleaners"], "Sodium_hypochlorite"),
    ("Urea", "urea", "CO(NH₂)₂", "organic-chemistry",
     "Nitrogen-rich compound excreted in urine; synthesized by Wöhler in 1828 in a landmark 'vitalism-refuting' experiment; major fertilizer.",
     None, ["CO(NH2)2", "carbamide"],
     "organic-chemistry", ["fertilizers"], "Urea"),
    ("Acetone", "acetone", "C₃H₆O", "organic-chemistry",
     "Simplest ketone; ubiquitous laboratory and industrial solvent; also produced in trace amounts by the body.",
     "Most nail-polish removers are largely acetone.",
     ["C3H6O", "propanone", "dimethyl ketone"],
     "organic-chemistry", ["personal-care"], "Acetone"),
    ("Isopropyl Alcohol", "isopropyl-alcohol", "C₃H₈O", "organic-chemistry",
     "Common disinfectant and cleaning solvent; 'rubbing alcohol' when diluted.",
     None, ["C3H8O", "IPA", "propan-2-ol", "rubbing alcohol"],
     "organic-chemistry", ["cleaners", "personal-care"], "Isopropyl_alcohol"),
    ("Glycerol", "glycerol", "C₃H₈O₃", "organic-chemistry",
     "Sugar alcohol used as sweetener, solvent, and moisturizer; backbone of triglyceride fats.",
     None, ["C3H8O3", "glycerine"],
     "organic-chemistry", ["personal-care", "food-and-beverage"], "Glycerol"),
    ("Sodium Fluoride", "sodium-fluoride", "NaF", "inorganic-chemistry",
     "Fluoride salt added to toothpaste and drinking water to prevent tooth decay.",
     "Municipal drinking water is often fluoridated with NaF at ~1 mg/L.",
     ["NaF"],
     "inorganic-chemistry", ["personal-care"], "Sodium_fluoride"),
    ("Calcium Phosphate", "calcium-phosphate", "Ca₃(PO₄)₂", "biochemistry",
     "Major component of bone and tooth enamel.",
     None, ["Ca3(PO4)2", "tribasic calcium phosphate"],
     "biochemistry", [], "Calcium_phosphate"),
    ("Hydroxyapatite", "hydroxyapatite", "Ca₁₀(PO₄)₆(OH)₂", "biochemistry",
     "Naturally-occurring calcium apatite; forms most of tooth enamel and bone mineral.",
     None, ["Ca10(PO4)6(OH)2", "bone mineral"],
     "biochemistry", [], "Hydroxyapatite"),
    ("Keratin", "keratin", "protein (varies)", "biochemistry",
     "Structural protein of hair, nails, feathers, hooves, and the outer layer of skin.",
     None, ["alpha-keratin", "beta-keratin"],
     "biochemistry", [], "Keratin"),
    ("Collagen", "collagen", "protein (varies)", "biochemistry",
     "The most abundant protein in mammals; primary structural component of connective tissue, tendon, cartilage, and bone.",
     "Gelatin is denatured collagen.",
     ["type I collagen"],
     "biochemistry", ["supplements"], "Collagen"),
    ("Fibrin", "fibrin", "protein (~340 kDa)", "biochemistry",
     "Fibrous protein formed during blood clotting; polymerizes into a mesh that stanches bleeding.",
     None, ["fibrous polymer"],
     "biochemistry", [], "Fibrin"),
    ("Actin", "actin", "protein (~42 kDa)", "biochemistry",
     "Cytoskeletal protein that polymerizes into filaments; interacts with myosin for muscle contraction and cell motility.",
     None, ["G-actin", "F-actin"],
     "biochemistry", [], "Actin"),
    ("Myosin", "myosin", "protein (varies)", "biochemistry",
     "Motor protein that generates force along actin filaments — the engine of muscle contraction.",
     None, ["motor protein"],
     "biochemistry", [], "Myosin"),
    ("Tubulin", "tubulin", "protein (~50 kDa)", "biochemistry",
     "Protein that polymerizes into microtubules; key cytoskeletal element and drug target (Taxol, colchicine).",
     None, ["alpha-tubulin", "beta-tubulin"],
     "biochemistry", [], "Tubulin"),
    ("Antibody", "antibody", "protein (~150 kDa)", "immunology",
     "Y-shaped protein produced by B cells that specifically binds foreign antigens; central to adaptive immunity.",
     None, ["immunoglobulin", "IgG", "IgM", "IgA", "IgE"],
     "immunology", [], "Antibody"),
    ("Enzyme", "enzyme", "protein (varies)", "biochemistry",
     "Biological catalyst — a protein (or RNA) that dramatically accelerates a specific chemical reaction.",
     "The enzyme in laundry detergent breaks down protein stains.",
     ["biocatalyst"],
     "biochemistry", ["cleaners"], "Enzyme"),
    ("Lipid", "lipid", "class (varies)", "biochemistry",
     "Broad class of hydrophobic biomolecules — fats, oils, waxes, sterols, phospholipids.",
     None, ["fat", "oil"],
     "biochemistry", [], "Lipid"),
    ("Triglyceride", "triglyceride", "ester (varies)", "biochemistry",
     "Ester of glycerol with three fatty acids; the main storage form of fat in animals and plants.",
     "Cooking oils are triglyceride mixtures.",
     ["triacylglycerol", "TAG"],
     "biochemistry", ["food-and-beverage"], "Triglyceride"),
    ("Phospholipid", "phospholipid", "amphipathic lipid", "biochemistry",
     "Lipid with a phosphate head group; forms the bilayer of every cell membrane.",
     None, ["phosphatidylcholine", "lecithin"],
     "biochemistry", [], "Phospholipid"),
    ("Cellulose Acetate", "cellulose-acetate", "esterified cellulose", "materials-science",
     "Chemically-modified cellulose used in photographic film, cigarette filters, and eyeglass frames.",
     None, ["cellophane precursor"],
     "materials-science", [], "Cellulose_acetate"),
    ("Ammonium Nitrate", "ammonium-nitrate", "NH₄NO₃", "inorganic-chemistry",
     "Widely-used nitrogen fertilizer; also an explosive when combined with fuel oil (ANFO).",
     None, ["NH4NO3"],
     "inorganic-chemistry", ["fertilizers"], "Ammonium_nitrate"),
    ("Sodium Phosphate", "sodium-phosphate", "Na₃PO₄", "inorganic-chemistry",
     "Family of sodium-phosphate salts used as food additives (emulsifiers, buffering agents) and detergents.",
     None, ["Na3PO4", "TSP", "trisodium phosphate"],
     "inorganic-chemistry", ["cleaners"], "Sodium_phosphate"),
    ("Barium Sulfate", "barium-sulfate", "BaSO₄", "inorganic-chemistry",
     "Insoluble salt used as radiocontrast agent for gastrointestinal X-rays.",
     None, ["BaSO4", "barite"],
     "inorganic-chemistry", ["pharmaceuticals"], "Barium_sulfate"),
    ("Iodine", "iodine-i2", "I₂", "inorganic-chemistry",
     "Diatomic form of iodine; violet-black solid; essential trace element in thyroid hormones.",
     "Iodized table salt supplies dietary iodine.",
     ["I2", "molecular iodine"],
     "inorganic-chemistry", [], "Iodine"),
    ("Potassium Iodide", "potassium-iodide", "KI", "inorganic-chemistry",
     "Ionic salt used as expectorant, iodine supplement, and thyroid blocker in nuclear emergencies.",
     None, ["KI"],
     "inorganic-chemistry", ["pharmaceuticals"], "Potassium_iodide"),
    ("Fluoride Ion", "fluoride-ion", "F⁻", "inorganic-chemistry",
     "The anion of fluorine; strengthens tooth enamel by forming fluorapatite.",
     None, ["F-", "fluoride"],
     "inorganic-chemistry", [], "Fluoride"),
    ("Nitrous Oxide", "nitrous-oxide", "N₂O", "inorganic-chemistry",
     "'Laughing gas' — anesthetic and food-additive gas; also a potent greenhouse gas.",
     None, ["N2O", "laughing gas", "dinitrogen monoxide"],
     "inorganic-chemistry", ["pharmaceuticals"], "Nitrous_oxide"),
    ("Nitric Oxide", "nitric-oxide", "NO", "inorganic-chemistry",
     "Signaling molecule involved in vasodilation; discovery earned the 1998 Nobel Prize in Medicine.",
     None, ["NO", "nitrogen monoxide"],
     "inorganic-chemistry", [], "Nitric_oxide"),
    ("Sulfur Dioxide", "sulfur-dioxide", "SO₂", "inorganic-chemistry",
     "Pungent gas from volcanic emissions and fossil-fuel combustion; a major source of acid rain.",
     None, ["SO2"],
     "inorganic-chemistry", [], "Sulfur_dioxide"),
    ("Carbon Monoxide", "carbon-monoxide", "CO", "inorganic-chemistry",
     "Colorless, odorless, toxic gas produced by incomplete combustion; binds hemoglobin ~200× more strongly than oxygen.",
     "Every home should have a CO detector near sleeping areas.",
     ["CO"],
     "inorganic-chemistry", [], "Carbon_monoxide"),
    ("Cyanide", "cyanide", "CN⁻", "inorganic-chemistry",
     "Cyanide anion or its salts; blocks cellular respiration by inhibiting cytochrome c oxidase.",
     None, ["CN-", "prussic acid (HCN)"],
     "inorganic-chemistry", [], "Cyanide"),
    ("Ozone Layer", "ozone-layer", "O₃-rich stratosphere", "earth-science",
     "The concentration of ozone in Earth's stratosphere that shields the surface from ultraviolet radiation.",
     None, ["stratospheric ozone"],
     "earth-science", [], "Ozone_layer"),
]

for row in COMPOUNDS:
    if len(row) == 10:
        name, slug, formula, disc, narr, everyday, extras, subsumed_by, used, wp = row
    else:
        name, slug, formula, disc, narr, everyday, extras, subsumed_by, used, wp = row + (None,)
    SCIENCES.append(C(name, slug, formula, disc, narr, everyday=everyday,
                       extras=extras, subsumed_by=subsumed_by, used_in_store=used, wp=wp))

# Parent taxonomic nodes
for name, slug, disc, narr in [
    ("Inorganic Chemistry", "inorganic-chemistry", "chemistry",
     "Chemistry of compounds that generally lack carbon-hydrogen bonds — metals, minerals, salts, oxides."),
    ("Organic Chemistry", "organic-chemistry", "chemistry",
     "Chemistry of carbon-based compounds — hydrocarbons and their derivatives."),
    ("Biochemistry", "biochemistry", "biology",
     "The chemistry of living organisms — proteins, nucleic acids, lipids, and carbohydrates in cellular context."),
    ("Materials Science", "materials-science", "engineering",
     "The interdisciplinary study of the properties of materials and how they can be engineered for use."),
]:
    SCIENCES.append(S(name, disc, "classification",
                     id_slug=slug, narrative=narr,
                     subsumed_by="chemistry",
                     provenance=W(name.replace(" ", "_"))))
