"""Cell types, biological processes, cycles, organelles. Target ~700 nodes."""

from _helpers import S, PERSON


def W(name):
    return [{"source": "wikipedia", "url": f"https://en.wikipedia.org/wiki/{name}"}]


def WD(qid, name=None):
    p = [{"source": "wikidata", "qid": qid}]
    if name:
        p.append({"source": "wikipedia", "url": f"https://en.wikipedia.org/wiki/{name}"})
    return p


def B(name, slug, kind, narr, everyday=None, extras=None, applies=None,
      subsumed_by=None, described_by=None, described_year=None, related=None,
      wp=None, wd=None, taxon=None, status=None):
    prov = WD(wd, wp) if wd else W(wp or name.replace(" ", "_"))
    return S(name, "biology", kind,
             id_slug=slug, extras=extras or [], narrative=narr,
             everyday=everyday,
             applies=applies or [":biological"],
             described_by=described_by, described_year=described_year,
             subsumed_by=subsumed_by,
             related=[(r, w) for r, w in (related or [])],
             taxon=taxon, status=status,
             provenance=prov)


SCIENCES = []

# ============ CELL TYPES ============
CELLS = [
    ("Neuron", "neuron", "Electrically-excitable cell of the nervous system; conducts signals via action potentials.",
     "Every thought is neurons firing action potentials in patterns.",
     ["nerve cell", "neurocyte"],
     [("action-potential", 0.9), ("synapse", 0.9)],
     "Neuron", "Q42574"),
    ("Red Blood Cell", "red-blood-cell", "Anucleate cell filled with hemoglobin; carries oxygen from lungs to tissues.",
     None, ["erythrocyte", "RBC"],
     [("hemoglobin", 1.0), ("blood", 0.9)],
     "Red_blood_cell", "Q37187"),
    ("White Blood Cell", "white-blood-cell", "Any of several nucleated blood cell types involved in immune defense.",
     None, ["leukocyte", "WBC"],
     [("immune-system", 0.95)],
     "White_blood_cell", "Q37501"),
    ("Platelet", "platelet", "Small anucleate cell fragment that aggregates at wounds to form clots.",
     None, ["thrombocyte"],
     [("coagulation", 0.95), ("fibrin", 0.9)],
     "Platelet", "Q37166"),
    ("T Cell", "t-cell", "Type of lymphocyte central to cell-mediated adaptive immunity; matures in the thymus.",
     None, ["T lymphocyte", "CD4 cell", "CD8 cell"],
     [("adaptive-immunity", 0.95)],
     "T_cell", "Q212809"),
    ("B Cell", "b-cell", "Type of lymphocyte that produces antibodies; central to humoral immunity.",
     None, ["B lymphocyte", "plasma cell precursor"],
     [("antibody", 1.0), ("adaptive-immunity", 0.95)],
     "B_cell", "Q212843"),
    ("Macrophage", "macrophage", "Large phagocytic immune cell that engulfs pathogens and cellular debris.",
     None, ["histiocyte"],
     [("innate-immunity", 0.95), ("phagocytosis", 0.9)],
     "Macrophage", "Q188345"),
    ("Neutrophil", "neutrophil", "Most abundant white blood cell; first responder to bacterial infection.",
     None, ["polymorphonuclear leukocyte", "PMN"],
     [("innate-immunity", 0.9)],
     "Neutrophil", "Q47408"),
    ("Dendritic Cell", "dendritic-cell", "Antigen-presenting cell that bridges innate and adaptive immunity.",
     None, ["DC"],
     [("adaptive-immunity", 0.9)],
     "Dendritic_cell", "Q272257"),
    ("Sperm", "sperm-cell", "Male gamete; motile haploid cell that fertilizes an egg.",
     None, ["spermatozoon", "sperm cell"],
     [("fertilization", 0.95)],
     "Spermatozoon", "Q131172"),
    ("Egg Cell", "egg-cell", "Female gamete; large haploid cell that becomes a zygote upon fertilization.",
     None, ["ovum", "oocyte"],
     [("fertilization", 0.95)],
     "Egg_cell", "Q11248"),
    ("Zygote", "zygote", "The single cell formed at fertilization; contains the full diploid genome.",
     None, ["fertilized egg"],
     [("fertilization", 1.0), ("embryonic-development", 0.95)],
     "Zygote", "Q159566"),
    ("Stem Cell", "stem-cell", "Undifferentiated cell capable of self-renewal and differentiation into specialized cell types.",
     None, ["pluripotent cell"],
     [("cell-differentiation", 0.95)],
     "Stem_cell", "Q48196"),
    ("Muscle Cell", "muscle-cell", "Contractile cell responsible for skeletal, smooth, or cardiac muscle function.",
     None, ["myocyte", "muscle fiber"],
     [("actin", 0.9), ("myosin", 0.9), ("muscle-contraction", 0.95)],
     "Myocyte", "Q422082"),
    ("Skeletal Muscle Cell", "skeletal-muscle-cell", "Multinucleated striated muscle cell under voluntary control.",
     None, ["skeletal muscle fiber", "myofibre"],
     [("muscle-contraction", 0.95)],
     "Skeletal_muscle", "Q7365"),
    ("Cardiac Muscle Cell", "cardiac-muscle-cell", "Striated muscle cell of the heart; involuntary; connected by intercalated discs.",
     None, ["cardiomyocyte"],
     [("heart", 0.95)],
     "Cardiac_muscle_cell", "Q1155404"),
    ("Smooth Muscle Cell", "smooth-muscle-cell", "Non-striated involuntary muscle cell of hollow organs and blood vessels.",
     None, ["smooth muscle fiber"],
     [], "Smooth_muscle_tissue", "Q179700"),
    ("Adipocyte", "adipocyte", "Fat cell — stores lipid in a large droplet and releases fatty acids for energy.",
     None, ["fat cell", "lipocyte"],
     [], "Adipocyte", "Q188432"),
    ("Osteoblast", "osteoblast", "Cell that synthesizes new bone matrix.",
     None, ["bone-forming cell"],
     [("bone", 0.95)],
     "Osteoblast", "Q416787"),
    ("Osteoclast", "osteoclast", "Multinucleated cell that resorbs bone tissue during growth and remodeling.",
     None, ["bone-resorbing cell"],
     [("bone", 0.95)],
     "Osteoclast", "Q131408"),
    ("Chondrocyte", "chondrocyte", "The only cell type found in healthy cartilage; produces the cartilage matrix.",
     None, ["cartilage cell"],
     [("cartilage", 0.95)],
     "Chondrocyte", "Q898820"),
    ("Fibroblast", "fibroblast", "Connective-tissue cell that produces collagen and extracellular matrix.",
     None, ["connective tissue cell"],
     [("collagen", 0.95), ("connective-tissue", 0.9)],
     "Fibroblast", "Q463967"),
    ("Hepatocyte", "hepatocyte", "The main functional cell of the liver; performs metabolism, detoxification, and protein synthesis.",
     None, ["liver cell"],
     [("liver", 0.95)],
     "Hepatocyte", "Q1145979"),
    ("Astrocyte", "astrocyte", "Star-shaped glial cell of the central nervous system; supports neurons and forms the blood-brain barrier.",
     None, ["astroglia"],
     [("nervous-system", 0.9)],
     "Astrocyte", "Q243927"),
    ("Oligodendrocyte", "oligodendrocyte", "Glial cell that produces the myelin sheath around CNS axons.",
     None, ["oligodendroglia"],
     [("myelin", 0.95)],
     "Oligodendrocyte", "Q911394"),
    ("Schwann Cell", "schwann-cell", "Peripheral-nervous-system glial cell that produces myelin around PNS axons.",
     None, ["neurolemmocyte"],
     [("myelin", 0.95)],
     "Schwann_cell", "Q1345018"),
    ("Microglia", "microglia", "Resident immune cell of the central nervous system.",
     None, ["CNS macrophage"],
     [("nervous-system", 0.85)],
     "Microglia", "Q1132158"),
    ("Photoreceptor Cell", "photoreceptor-cell", "Specialized retinal neuron that converts light into electrical signals — rods and cones.",
     None, ["rod cell", "cone cell"],
     [("retina", 0.95), ("vision", 0.95)],
     "Photoreceptor_cell", "Q1424013"),
    ("Hair Cell", "hair-cell", "Sensory receptor cell in the inner ear that converts mechanical vibration into neural signals.",
     None, ["inner ear hair cell"],
     [("hearing", 0.95)],
     "Hair_cell", "Q841390"),
    ("Enterocyte", "enterocyte", "Absorptive cell of the small intestine lining.",
     None, ["intestinal absorptive cell"],
     [("small-intestine", 0.95)],
     "Enterocyte", "Q1345291"),
    ("Goblet Cell", "goblet-cell", "Mucus-secreting epithelial cell of the digestive and respiratory tracts.",
     None, ["mucus-secreting cell"],
     [("mucus", 0.95)],
     "Goblet_cell", "Q904313"),
    ("Alveolar Cell", "alveolar-cell", "Cell of the lung alveoli — type I are the gas-exchange surface, type II produce surfactant.",
     None, ["pneumocyte", "type I pneumocyte", "type II pneumocyte"],
     [("alveolus", 1.0)],
     "Pulmonary_alveolus", "Q120600"),
    ("Beta Cell", "beta-cell", "Insulin-producing cell of the pancreatic islets of Langerhans.",
     None, ["islet beta cell", "pancreatic beta cell"],
     [("insulin", 1.0), ("pancreas", 0.95)],
     "Beta_cell", "Q1006733"),
    ("Alpha Cell (pancreas)", "alpha-cell", "Glucagon-producing cell of the pancreatic islets.",
     None, ["islet alpha cell", "pancreatic alpha cell"],
     [("pancreas", 0.95)],
     "Alpha_cell", "Q3608321"),
    ("Melanocyte", "melanocyte", "Pigment-producing cell that synthesizes melanin.",
     None, ["pigment cell"],
     [], "Melanocyte", "Q464355"),
    ("Keratinocyte", "keratinocyte", "The primary cell type of the epidermis; produces keratin.",
     None, ["epidermal cell"],
     [("keratin", 1.0), ("skin", 0.95)],
     "Keratinocyte", "Q1417775"),
    ("Bacterium", "bacterium", "Single-celled prokaryote lacking a nucleus; enormously diverse and abundant across ecosystems.",
     None, ["bacterial cell"],
     [], "Bacteria", "Q10876"),
    ("Archaeon", "archaeon", "Single-celled prokaryote distinct from bacteria in membrane lipids and molecular machinery.",
     None, ["archaea"],
     [], "Archaea", "Q10872"),
    ("Yeast", "yeast", "Single-celled fungus used in baking, brewing, and molecular biology.",
     "Bread rises because yeast fermentation produces CO₂.",
     ["Saccharomyces cerevisiae"],
     [("fermentation", 0.95)],
     "Yeast", "Q23392"),
    ("Amoeba", "amoeba", "Single-celled eukaryote that moves by extending pseudopodia.",
     None, ["amoeboid"],
     [], "Amoeba", "Q49478"),
    ("Paramecium", "paramecium", "Ciliated freshwater protozoan; a model organism in cell biology teaching.",
     None, ["ciliate"],
     [], "Paramecium", "Q192724"),
]
for row in CELLS:
    if len(row) == 7:
        name, slug, narr, everyday, extras, rel, wp = row
        wd = None
    else:
        name, slug, narr, everyday, extras, rel, wp, wd = row
    SCIENCES.append(B(name, slug, "cell-type", narr, everyday=everyday, extras=extras,
                      subsumed_by="cell-biology", related=rel, wp=wp, wd=wd))

# ============ ORGANELLES ============
ORGANELLES = [
    ("Cell Nucleus", "cell-nucleus", "The membrane-bound organelle containing a eukaryotic cell's chromosomes.",
     ["nucleus"], "Cell_nucleus", "Q40260"),
    ("Mitochondrion", "mitochondrion", "The 'powerhouse of the cell' — organelle that generates most of the cell's ATP via oxidative phosphorylation.",
     ["mitochondria", "powerhouse of the cell"], "Mitochondrion", "Q39572"),
    ("Chloroplast", "chloroplast", "Plant/algal organelle that performs photosynthesis; contains chlorophyll and its own DNA.",
     ["plastid"], "Chloroplast", "Q47089"),
    ("Ribosome", "ribosome", "Molecular machine that translates messenger RNA into protein.",
     ["70S ribosome", "80S ribosome"], "Ribosome", "Q160835"),
    ("Endoplasmic Reticulum", "endoplasmic-reticulum", "Membrane network involved in protein and lipid synthesis; rough ER has ribosomes attached, smooth ER does not.",
     ["ER", "rough ER", "smooth ER"], "Endoplasmic_reticulum", "Q131317"),
    ("Golgi Apparatus", "golgi-apparatus", "Organelle that modifies, sorts, and packages proteins and lipids for secretion or use inside the cell.",
     ["Golgi complex", "Golgi body", "dictyosome"], "Golgi_apparatus", "Q45242"),
    ("Lysosome", "lysosome", "Membrane-bound organelle containing digestive enzymes; the cell's recycling and waste-disposal center.",
     ["cell stomach"], "Lysosome", "Q193742"),
    ("Peroxisome", "peroxisome", "Small organelle that oxidizes long-chain fatty acids and metabolizes hydrogen peroxide.",
     ["microbody"], "Peroxisome", "Q184611"),
    ("Vacuole", "vacuole", "Fluid-filled organelle; prominent in plant cells, where it maintains turgor pressure.",
     ["central vacuole"], "Vacuole", "Q83483"),
    ("Cytoplasm", "cytoplasm", "The gel-like substance filling a cell, excluding the nucleus; contains cytosol and organelles.",
     ["cytosol"], "Cytoplasm", "Q79899"),
    ("Cell Membrane", "cell-membrane", "The phospholipid bilayer surrounding every cell that regulates what enters and leaves.",
     ["plasma membrane", "phospholipid bilayer"], "Cell_membrane", "Q79832"),
    ("Cell Wall", "cell-wall", "Rigid outer layer of plant, fungal, algal, and bacterial cells; provides structure and protection.",
     [], "Cell_wall", "Q193395"),
    ("Nucleolus", "nucleolus", "Dense region within the cell nucleus where ribosomal RNA is transcribed and ribosome subunits assembled.",
     [], "Nucleolus", "Q193657"),
    ("Cytoskeleton", "cytoskeleton", "Network of protein filaments providing cell shape, internal transport, and movement — microtubules, microfilaments, intermediate filaments.",
     [], "Cytoskeleton", "Q192942"),
    ("Centrosome", "centrosome", "Microtubule-organizing center of animal cells; consists of two centrioles.",
     [], "Centrosome", "Q476704"),
    ("Centriole", "centriole", "Barrel-shaped microtubule structure inside the centrosome; templates cilia and flagella.",
     [], "Centriole", "Q332591"),
    ("Flagellum", "flagellum", "Whip-like appendage that provides motility in cells such as bacteria and sperm.",
     [], "Flagellum", "Q184150"),
    ("Cilium", "cilium", "Short hair-like organelle projecting from a cell; can be motile or serve as a sensor.",
     ["cilia"], "Cilium", "Q192764"),
    ("Chromosome", "chromosome", "Long DNA molecule packaged with proteins into a compact structure; humans have 46.",
     [], "Chromosome", "Q37772"),
    ("Chromatin", "chromatin", "The complex of DNA and histone proteins that packages the eukaryotic genome inside the nucleus.",
     [], "Chromatin", "Q209982"),
    ("Nuclear Envelope", "nuclear-envelope", "Double membrane surrounding the nucleus, perforated by nuclear pores.",
     ["nuclear membrane"], "Nuclear_envelope", "Q319218"),
    ("Nuclear Pore", "nuclear-pore", "Large protein complex spanning the nuclear envelope that controls molecular transport in and out of the nucleus.",
     ["nuclear pore complex", "NPC"], "Nuclear_pore", "Q414530"),
    ("Synapse", "synapse", "Junction between two neurons or between a neuron and its target cell across which signals are transmitted.",
     ["neuronal synapse", "chemical synapse"], "Synapse", "Q188907"),
]
for row in ORGANELLES:
    name, slug, narr, extras, wp, wd = row
    SCIENCES.append(B(name, slug, "structure", narr, extras=extras,
                      subsumed_by="cell-biology", wp=wp, wd=wd))

# ============ BIOLOGICAL PROCESSES ============
PROCESSES = [
    ("Photosynthesis", "photosynthesis", "The process by which plants, algae, and some bacteria convert light energy into chemical energy stored in sugars, releasing oxygen as a byproduct.",
     "The oxygen you breathe was mostly produced by photosynthesis.",
     ["light-dependent reactions", "Calvin cycle"], "Photosynthesis", "Q11982", None, None),
    ("Cellular Respiration", "cellular-respiration", "The metabolic process by which cells extract energy from glucose by oxidizing it to carbon dioxide and water.",
     None, ["aerobic respiration"], "Cellular_respiration", "Q133381", None, None),
    ("Glycolysis", "glycolysis", "Ten-step pathway that breaks glucose into two pyruvate molecules, netting 2 ATP.",
     None, ["Embden-Meyerhof pathway"], "Glycolysis", "Q179856", "embden-gustav", 1940),
    ("Krebs Cycle", "krebs-cycle", "The cyclic sequence of reactions in mitochondria that oxidizes acetyl-CoA to CO₂ while generating NADH and FADH₂.",
     None, ["citric acid cycle", "TCA cycle", "tricarboxylic acid cycle"], "Citric_acid_cycle", "Q194152", "krebs-hans", 1937),
    ("Electron Transport Chain", "electron-transport-chain", "Chain of protein complexes in the mitochondrial inner membrane that transfers electrons and pumps protons, powering ATP synthesis.",
     None, ["ETC", "respiratory chain"], "Electron_transport_chain", "Q207061", None, None),
    ("Oxidative Phosphorylation", "oxidative-phosphorylation", "The metabolic pathway that uses energy from the electron transport chain to phosphorylate ADP into ATP.",
     None, ["OXPHOS"], "Oxidative_phosphorylation", "Q217361", "mitchell-peter", 1961),
    ("Calvin Cycle", "calvin-cycle", "The light-independent reactions of photosynthesis that fix atmospheric CO₂ into organic carbon.",
     None, ["dark reactions", "carbon fixation cycle"], "Calvin_cycle", "Q210120", "calvin-melvin", 1950),
    ("Fermentation", "fermentation", "Anaerobic metabolic process that converts sugar to acids, gases, or alcohol.",
     "Wine, beer, yogurt, sourdough — all use fermentation.",
     ["anaerobic metabolism"], "Fermentation", "Q41287", "pasteur-louis", 1857),
    ("Transcription", "transcription", "The process by which DNA is copied into messenger RNA by RNA polymerase.",
     None, ["gene transcription", "mRNA synthesis"], "Transcription_(biology)", "Q210443", None, None),
    ("Translation", "translation", "The process by which ribosomes read mRNA to synthesize proteins.",
     None, ["protein synthesis", "polypeptide synthesis"], "Translation_(biology)", "Q188572", None, None),
    ("DNA Replication", "dna-replication", "The process by which a DNA double helix is copied before cell division.",
     None, ["genome replication"], "DNA_replication", "Q911663", None, None),
    ("Mitosis", "mitosis", "Cell division producing two genetically-identical daughter cells; how the body grows and repairs tissue.",
     None, ["nuclear division", "cell division"], "Mitosis", "Q37187", None, None),
    ("Meiosis", "meiosis", "Two-stage cell division that produces four haploid gametes from one diploid cell.",
     None, ["reduction division", "gametogenesis"], "Meiosis", "Q184145", None, None),
    ("Apoptosis", "apoptosis", "Programmed cell death — an orderly self-destruction removing damaged or unneeded cells.",
     None, ["programmed cell death", "type I PCD"], "Apoptosis", "Q159557", "kerr-john", 1972),
    ("Autophagy", "autophagy", "The cell's self-eating process that recycles damaged organelles and misfolded proteins; earned Ohsumi the 2016 Nobel.",
     None, ["cellular self-eating"], "Autophagy", "Q191768", "ohsumi-yoshinori", 1988),
    ("Endocytosis", "endocytosis", "The process by which cells engulf external material by invaginating the cell membrane.",
     None, ["phagocytosis", "pinocytosis"], "Endocytosis", "Q212659", None, None),
    ("Phagocytosis", "phagocytosis", "'Cell eating' — the engulfment of large particles by cells such as macrophages.",
     None, ["cellular eating"], "Phagocytosis", "Q192827", None, None),
    ("Exocytosis", "exocytosis", "The process by which cells transport materials out via vesicle fusion with the plasma membrane.",
     None, [], "Exocytosis", "Q212639", None, None),
    ("Meiotic Recombination", "meiotic-recombination", "The exchange of genetic material between homologous chromosomes during meiosis; the source of gametic diversity.",
     None, ["crossing over", "homologous recombination"], "Genetic_recombination", "Q485094", None, None),
    ("Cell Signaling", "cell-signaling", "Communication between cells and within cells through molecular signals — endocrine, paracrine, autocrine.",
     None, ["signal transduction"], "Cell_signaling", "Q205921", None, None),
    ("Muscle Contraction", "muscle-contraction", "The sliding-filament interaction of actin and myosin driven by ATP hydrolysis.",
     None, ["sliding filament theory"], "Muscle_contraction", "Q1136306", "huxley-andrew", 1954),
    ("Nerve Impulse", "action-potential", "The rapid, self-propagating change in membrane potential that transmits a signal along a neuron.",
     None, ["nerve impulse", "spike"], "Action_potential", "Q79785", "hodgkin-alan", 1952),
    ("Blood Coagulation", "coagulation", "The cascade of enzyme reactions that converts liquid blood into a gel-like clot to stop bleeding.",
     "The scab on a cut is coagulated blood.",
     ["hemostasis", "clotting cascade"], "Coagulation", "Q212763", None, None),
    ("Digestion", "digestion", "The breakdown of food into absorbable nutrients by mechanical and enzymatic action.",
     None, ["gastrointestinal digestion"], "Digestion", "Q9548", None, None),
    ("Absorption (nutrients)", "nutrient-absorption", "The uptake of digested nutrients across the intestinal lining into blood or lymph.",
     None, ["intestinal absorption"], "Absorption_(pharmacology)", "Q1096770", None, None),
    ("Respiration (breathing)", "breathing", "The mechanical process of moving air into and out of the lungs.",
     None, ["ventilation", "pulmonary ventilation"], "Breathing", "Q11235", None, None),
    ("Gas Exchange", "gas-exchange", "The diffusion of oxygen from air into blood and CO₂ from blood into air across the alveolar surface.",
     None, ["pulmonary gas exchange"], "Gas_exchange", "Q1074500", None, None),
    ("Circulation", "circulation", "The movement of blood through the heart and blood vessels, delivering oxygen and nutrients and removing wastes.",
     None, ["blood circulation", "circulatory system function"], "Circulatory_system", "Q9648", "harvey-william", 1628),
    ("Filtration (kidney)", "kidney-filtration", "The initial step of urine formation in the kidney — plasma is filtered across the glomerulus.",
     None, ["glomerular filtration"], "Renal_physiology", "Q1478835", None, None),
    ("Homeostasis", "homeostasis", "The self-regulating process by which biological systems maintain stability while adjusting to changing conditions.",
     "Sweating when hot and shivering when cold both maintain core temperature.",
     ["biological equilibrium"], "Homeostasis", "Q167312", "cannon-walter", 1926),
    ("Fertilization", "fertilization", "The fusion of male and female gametes to form a zygote.",
     None, ["conception"], "Fertilisation", "Q193292", None, None),
    ("Embryonic Development", "embryonic-development", "The sequence of changes from a single-celled zygote to a multi-tissue embryo.",
     None, ["embryogenesis"], "Embryonic_development", "Q131594", None, None),
    ("Gastrulation", "gastrulation", "Early embryonic process forming the three germ layers — ectoderm, mesoderm, endoderm.",
     None, [], "Gastrulation", "Q211364", None, None),
    ("Neurulation", "neurulation", "The folding process that creates the neural tube, precursor to the brain and spinal cord.",
     None, [], "Neurulation", "Q1958074", None, None),
    ("Puberty", "puberty", "The physical process of sexual maturation, driven by rising sex-hormone levels.",
     None, ["sexual maturation"], "Puberty", "Q133507", None, None),
    ("Menstruation", "menstruation", "The monthly shedding of the uterine lining in reproductive-age humans and other primates when pregnancy does not occur.",
     None, ["period", "menstrual cycle"], "Menstruation", "Q47912", None, None),
    ("Pregnancy", "pregnancy", "The period from conception to birth during which a fetus develops in the uterus.",
     None, ["gestation"], "Pregnancy", "Q11995", None, None),
    ("Lactation", "lactation", "Milk production and secretion by the mammary glands.",
     None, ["breastfeeding", "milk secretion"], "Lactation", "Q160477", None, None),
    ("Aging", "aging", "The gradual accumulation of cellular damage and reduction of physiological function over time.",
     None, ["senescence", "biological aging"], "Ageing", "Q184559", None, None),
    ("Natural Selection", "natural-selection", "The differential survival and reproduction of individuals due to variations in their traits — the mechanism of adaptive evolution.",
     "Bacterial populations evolve antibiotic resistance in weeks via natural selection.",
     ["survival of the fittest"], "Natural_selection", "Q40551", "darwin-charles", 1859),
    ("Evolution", "evolution", "The change in inherited characteristics of biological populations across generations.",
     None, ["biological evolution", "organic evolution"], "Evolution", "Q1063", "darwin-charles", 1859),
    ("Speciation", "speciation", "The evolutionary process by which new species arise, typically through reproductive isolation.",
     None, ["species formation"], "Speciation", "Q19086", None, None),
    ("Adaptive Radiation", "adaptive-radiation", "Rapid diversification of a lineage into many species occupying different ecological niches.",
     "Darwin's finches on the Galápagos are the canonical example.",
     [], "Adaptive_radiation", "Q750604", None, None),
    ("Genetic Drift", "genetic-drift", "Random changes in allele frequency in a population, especially significant in small populations.",
     None, ["random drift"], "Genetic_drift", "Q45813", "wright-sewall", 1929),
    ("Gene Flow", "gene-flow", "The transfer of genetic variation between populations through migration and interbreeding.",
     None, ["migration"], "Gene_flow", "Q485831", None, None),
    ("Sexual Selection", "sexual-selection", "Selection driven by competition for mates or by mate choice; produces traits like the peacock's tail.",
     None, [], "Sexual_selection", "Q193762", "darwin-charles", 1871),
    ("Symbiosis", "symbiosis", "Any close, long-term biological interaction between two different species — includes mutualism, commensalism, parasitism.",
     None, [], "Symbiosis", "Q184189", "de-bary-anton", 1879),
    ("Mutualism", "mutualism", "Symbiotic interaction where both species benefit.",
     "Bees pollinate flowers; flowers feed bees.",
     [], "Mutualism_(biology)", "Q192050", None, None),
    ("Parasitism", "parasitism", "Symbiotic interaction where one species benefits at the expense of another.",
     None, [], "Parasitism", "Q188828", None, None),
    ("Commensalism", "commensalism", "Symbiotic interaction where one species benefits and the other is unaffected.",
     None, [], "Commensalism", "Q207687", None, None),
    ("Predation", "predation", "The killing and eating of one organism by another.",
     None, ["predator-prey interaction"], "Predation", "Q54968", None, None),
    ("Nitrogen Fixation", "nitrogen-fixation", "The conversion of atmospheric N₂ into ammonia by certain bacteria; the entry point of nitrogen into biology.",
     None, ["N2 fixation"], "Nitrogen_fixation", "Q158744", None, None),
    ("Carbon Cycle", "carbon-cycle", "The biogeochemical cycle by which carbon moves between the atmosphere, biosphere, oceans, and geosphere.",
     None, [], "Carbon_cycle", "Q211031", None, None),
    ("Water Cycle", "water-cycle", "The continuous movement of water through evaporation, condensation, precipitation, runoff, and infiltration.",
     None, ["hydrological cycle"], "Water_cycle", "Q7942", None, None),
    ("Nitrogen Cycle", "nitrogen-cycle", "The biogeochemical cycle of nitrogen through fixation, nitrification, assimilation, ammonification, and denitrification.",
     None, [], "Nitrogen_cycle", "Q45912", None, None),
    ("Phosphorus Cycle", "phosphorus-cycle", "The biogeochemical cycle of phosphorus through geosphere, hydrosphere, and biosphere.",
     None, [], "Phosphorus_cycle", "Q1116267", None, None),
    ("Sulfur Cycle", "sulfur-cycle", "The biogeochemical cycle of sulfur through various oxidation states.",
     None, [], "Sulfur_cycle", "Q1050176", None, None),
    ("Oxygen Cycle", "oxygen-cycle", "The biogeochemical cycle of oxygen through the atmosphere, biosphere, and lithosphere.",
     None, [], "Oxygen_cycle", "Q1146252", None, None),
    ("Menstrual Cycle", "menstrual-cycle", "The monthly hormonal cycle preparing the uterus for possible pregnancy.",
     None, [], "Menstrual_cycle", "Q11185", None, None),
    ("Circadian Rhythm", "circadian-rhythm", "The ~24-hour internal biological cycle governing sleep, hormones, temperature, and many other physiological variables.",
     "Jet lag is the mismatch between local clock time and your circadian rhythm.",
     ["24-hour rhythm", "body clock"], "Circadian_rhythm", "Q179888", "halberg-franz", 1959),
    ("Sleep", "sleep", "A recurrent, reversible state of reduced consciousness and metabolic activity essential for memory consolidation and immune function.",
     None, ["slumber"], "Sleep", "Q35831", None, None),
    ("REM Sleep", "rem-sleep", "Rapid eye movement sleep — the sleep stage during which most vivid dreaming occurs.",
     None, ["paradoxical sleep"], "Rapid_eye_movement_sleep", "Q193544", "aserinsky-eugene", 1953),
    ("Immune Response", "immune-response", "The coordinated response of the immune system to pathogens or foreign substances.",
     None, ["immunity"], "Immune_response", "Q179380", None, None),
    ("Inflammation", "inflammation", "The tissue response to injury or infection — redness, heat, swelling, pain, loss of function.",
     "A red swollen ankle after a sprain is inflammation.",
     [], "Inflammation", "Q101991", None, None),
    ("Vaccination", "vaccination", "Deliberate exposure to a weakened or inactivated antigen to induce protective immunity.",
     None, ["immunization"], "Vaccination", "Q135767", "jenner-edward", 1796),
    ("Metabolism", "metabolism", "The set of life-sustaining chemical reactions in organisms — catabolism breaks down, anabolism builds up.",
     None, ["biochemical metabolism"], "Metabolism", "Q1057", None, None),
    ("Osmosis", "osmosis", "The net movement of water across a semipermeable membrane from low-solute to high-solute regions.",
     "Slugs shrivel from salt because of osmosis pulling water out of their cells.",
     [], "Osmosis", "Q102098", None, None),
    ("Diffusion", "diffusion", "The net movement of particles from regions of high concentration to low concentration.",
     "Perfume spreads across a room by diffusion.",
     [], "Molecular_diffusion", "Q3454869", None, None),
    ("Active Transport", "active-transport", "The energy-requiring movement of molecules across a membrane against a concentration gradient.",
     None, [], "Active_transport", "Q380717", None, None),
    ("Cell Cycle", "cell-cycle", "The ordered series of events that lead to cell division — G1, S, G2, M phases.",
     None, [], "Cell_cycle", "Q184546", None, None),
]
for row in PROCESSES:
    name, slug, narr = row[:3]
    everyday = row[3]
    extras = row[4]
    wp = row[5]
    wd = row[6] if len(row) > 6 else None
    disc_who = row[7] if len(row) > 7 else None
    year = row[8] if len(row) > 8 else None
    SCIENCES.append(B(name, slug, "process", narr,
                     everyday=everyday, extras=extras,
                     described_by=[f"person-{disc_who}"] if disc_who else None,
                     described_year=year,
                     subsumed_by="biology",
                     wp=wp, wd=wd))

# ============ CELL BIOLOGY parent + GENETICS ============
GENETICS = [
    ("Gene", "gene", "A unit of heredity — a DNA sequence encoding a functional product (protein or RNA).",
     None, ["hereditary unit"], "Gene", "Q7187"),
    ("Genome", "genome", "The complete set of genetic material in an organism.",
     None, [], "Genome", "Q7020"),
    ("Genotype", "genotype", "The genetic constitution of an individual — the specific alleles inherited.",
     None, [], "Genotype", "Q145596"),
    ("Phenotype", "phenotype", "The set of observable characteristics resulting from a genotype's interaction with environment.",
     None, [], "Phenotype", "Q104053"),
    ("Allele", "allele", "One of two or more variants of a gene at a given locus.",
     None, [], "Allele", "Q170348"),
    ("Mutation", "mutation", "A change in the nucleotide sequence of DNA; the ultimate source of genetic variation.",
     None, ["genetic mutation"], "Mutation", "Q42918"),
    ("Point Mutation", "point-mutation", "A mutation affecting a single nucleotide base.",
     None, ["single nucleotide variant", "SNV"], "Point_mutation", "Q42918"),
    ("Genetic Code", "genetic-code", "The set of rules mapping RNA codons to amino acids — nearly universal across life.",
     None, [], "Genetic_code", "Q42982"),
    ("Codon", "codon", "A three-nucleotide sequence specifying an amino acid or a stop signal.",
     None, ["nucleotide triplet"], "Genetic_code", "Q42982"),
    ("Ribosomal RNA", "rrna", "The RNA component of the ribosome; catalyzes peptide-bond formation.",
     None, ["rRNA", "23S rRNA", "18S rRNA"], "Ribosomal_RNA", "Q207473"),
    ("Transfer RNA", "trna", "Small RNA that carries an amino acid to the ribosome and recognizes the mRNA codon via its anticodon.",
     None, ["tRNA"], "Transfer_RNA", "Q207491"),
    ("Messenger RNA", "mrna", "RNA that carries the coding sequence for a protein from DNA to the ribosome.",
     None, ["mRNA"], "Messenger_RNA", "Q188928"),
    ("Non-coding RNA", "ncrna", "Any RNA that does not encode a protein but has regulatory or catalytic roles — includes miRNA, lncRNA, snRNA, snoRNA.",
     None, ["ncRNA", "regulatory RNA"], "Non-coding_RNA", "Q427087"),
    ("Chromosome (human)", "human-chromosome", "One of 23 pairs of DNA molecules that carry the human genome.",
     None, [], "Chromosome", "Q37772"),
    ("Sex Chromosome", "sex-chromosome", "Chromosome that determines biological sex — XX or XY in humans.",
     None, ["allosome"], "Sex_chromosome", "Q192161"),
    ("Autosome", "autosome", "Any chromosome that is not a sex chromosome — humans have 22 pairs.",
     None, [], "Autosome", "Q212800"),
    ("Dominant Trait", "dominant-trait", "A trait whose allele masks the expression of a corresponding recessive allele.",
     None, ["dominant allele"], "Dominance_(genetics)", "Q192923"),
    ("Recessive Trait", "recessive-trait", "A trait that is only expressed when both inherited alleles are recessive.",
     None, ["recessive allele"], "Dominance_(genetics)", "Q192923"),
    ("Heterozygous", "heterozygous", "Having two different alleles at a given locus.",
     None, ["heterozygote"], "Zygosity", "Q243982"),
    ("Homozygous", "homozygous", "Having two identical alleles at a given locus.",
     None, ["homozygote"], "Zygosity", "Q243982"),
    ("Punnett Square", "punnett-square", "A tabular device for predicting the genotype ratios of offspring from a cross.",
     None, [], "Punnett_square", "Q1417543"),
    ("Mendelian Inheritance", "mendelian-inheritance", "The pattern of trait inheritance following Mendel's laws of segregation and independent assortment.",
     None, ["classical genetics"], "Mendelian_inheritance", "Q179085"),
    ("Epigenetics", "epigenetics", "The study of heritable changes in gene expression that do not involve changes to the DNA sequence — DNA methylation, histone modification.",
     None, ["epigenetic inheritance"], "Epigenetics", "Q195310"),
    ("DNA Methylation", "dna-methylation", "Addition of methyl groups to DNA that typically represses gene expression; a key epigenetic mark.",
     None, ["methylation"], "DNA_methylation", "Q194318"),
    ("Genetic Engineering", "genetic-engineering", "Direct modification of an organism's genome using biotechnology.",
     None, ["GMO technology", "recombinant DNA"], "Genetic_engineering", "Q42973"),
    ("CRISPR", "crispr", "A family of DNA sequences and associated proteins that let cells 'remember' viral DNA and cut it; adapted as the CRISPR-Cas9 gene-editing tool.",
     None, ["CRISPR-Cas9", "Cas9"], "CRISPR", "Q2401299"),
    ("Polymerase Chain Reaction", "pcr", "Technique to amplify a specific DNA sequence to detectable quantities using temperature cycling and a heat-stable polymerase.",
     None, ["PCR"], "Polymerase_chain_reaction", "Q176996"),
    ("DNA Sequencing", "dna-sequencing", "Determining the order of nucleotides in a DNA molecule; the basis of the Human Genome Project.",
     None, [], "DNA_sequencing", "Q189218"),
    ("Human Genome", "human-genome", "The complete set of nucleic acid sequences for Homo sapiens — approximately 3 billion base pairs.",
     None, [], "Human_genome", "Q474810"),
    ("Gene Expression", "gene-expression", "The process by which the information in a gene directs the synthesis of a functional gene product.",
     None, [], "Gene_expression", "Q170406"),
]
for row in GENETICS:
    name, slug, narr, everyday, extras, wp, wd = row
    SCIENCES.append(B(name, slug, "process" if slug in ("gene-expression", "dna-methylation", "genetic-engineering", "dna-sequencing") else "object",
                     narr, everyday=everyday, extras=extras,
                     subsumed_by="genetics", wp=wp, wd=wd))

# ============ ECOSYSTEMS + ECOLOGY ============
ECOLOGY = [
    ("Ecosystem", "ecosystem", "A community of living organisms together with the non-living components of their environment.",
     None, [], "Ecosystem", "Q37813"),
    ("Biome", "biome", "A large ecological area on Earth's surface characterized by its climate and dominant vegetation — tundra, desert, rainforest, etc.",
     None, [], "Biome", "Q101998"),
    ("Habitat", "habitat", "The environmental home of a particular species; where an organism lives.",
     None, [], "Habitat", "Q52105"),
    ("Niche", "ecological-niche", "The role and position of a species in its environment — how it makes a living.",
     None, ["ecological niche"], "Ecological_niche", "Q167277"),
    ("Food Chain", "food-chain", "A linear sequence of feeding relationships from producers through consumers.",
     None, [], "Food_chain", "Q188572"),
    ("Food Web", "food-web", "The interconnected network of food chains in an ecosystem.",
     None, [], "Food_web", "Q484440"),
    ("Producer (ecology)", "producer", "An organism that synthesizes food from inorganic compounds — plants and algae are the primary producers.",
     None, ["primary producer", "autotroph"], "Autotroph", "Q189956"),
    ("Consumer (ecology)", "consumer", "An organism that obtains energy by eating other organisms — herbivores, carnivores, omnivores.",
     None, ["heterotroph"], "Heterotroph", "Q1015324"),
    ("Decomposer", "decomposer", "An organism that breaks down dead organic material — bacteria, fungi.",
     None, ["saprotroph"], "Decomposer", "Q193089"),
    ("Population", "population", "A group of individuals of the same species living in the same area at the same time.",
     None, ["biological population"], "Population", "Q7365"),
    ("Community (ecology)", "biological-community", "All the interacting populations of species in a shared environment.",
     None, ["biocenosis"], "Community_(ecology)", "Q42207"),
    ("Trophic Level", "trophic-level", "The position an organism occupies in a food chain — producer, primary consumer, secondary consumer, etc.",
     None, [], "Trophic_level", "Q193928"),
    ("Biodiversity", "biodiversity", "The variety of life in a habitat or ecosystem, at genetic, species, and ecosystem levels.",
     None, ["biological diversity"], "Biodiversity", "Q46587"),
    ("Extinction", "extinction", "The end of a species — the death of its last individual.",
     None, [], "Extinction", "Q47528"),
    ("Endangered Species", "endangered-species", "A species at serious risk of extinction due to declining numbers or shrinking habitat.",
     None, [], "Endangered_species", "Q13084"),
    ("Invasive Species", "invasive-species", "A non-native species whose introduction causes harm to the environment or economy.",
     None, [], "Invasive_species", "Q159061"),
    ("Keystone Species", "keystone-species", "A species with a disproportionately large effect on its environment relative to its abundance.",
     None, [], "Keystone_species", "Q272697"),
    ("Ecological Succession", "ecological-succession", "The process by which the mix of species in a community changes over time after a disturbance.",
     None, [], "Ecological_succession", "Q381508"),
    ("Climax Community", "climax-community", "A relatively stable ecological community reached by succession.",
     None, [], "Climax_community", "Q1088228"),
    ("Carrying Capacity", "carrying-capacity", "The maximum population size of a species that an environment can sustainably support.",
     None, [], "Carrying_capacity", "Q1097899"),
]
for row in ECOLOGY:
    name, slug, narr, everyday, extras, wp, wd = row
    SCIENCES.append(B(name, slug, "object" if slug in ("ecosystem", "biome", "habitat", "niche", "population", "biological-community") else "process",
                     narr, everyday=everyday, extras=extras,
                     subsumed_by="ecology", wp=wp, wd=wd))

# Parent nodes
for name, slug, narr, subs in [
    ("Cell Biology", "cell-biology", "The branch of biology studying the structure, function, and behavior of cells.", "biology"),
    ("Genetics", "genetics", "The branch of biology studying heredity and the variation of inherited characteristics.", "biology"),
    ("Ecology", "ecology", "The branch of biology studying interactions between organisms and their environment.", "biology"),
    ("Molecular Biology", "molecular-biology", "The branch of biology concerned with the structure and function of the biological macromolecules essential to life.", "biology"),
]:
    SCIENCES.append(S(name, "biology", "classification",
                     id_slug=slug, narrative=narr,
                     subsumed_by=subs,
                     provenance=W(name.replace(" ", "_"))))
