"""Anatomy, organ systems, diseases, medical concepts. Target ~700 nodes."""

from _helpers import S, PERSON


def W(name):
    return [{"source": "wikipedia", "url": f"https://en.wikipedia.org/wiki/{name}"}]


def WD(qid, name=None):
    p = [{"source": "wikidata", "qid": qid}]
    if name:
        p.append({"source": "wikipedia", "url": f"https://en.wikipedia.org/wiki/{name}"})
    return p


SCIENCES = []

# ============ ORGAN SYSTEMS ============
SYSTEMS = [
    ("Nervous System", "nervous-system", "The network of nerves, brain, and spinal cord that carries signals throughout the body and coordinates behavior.",
     "nervous-system", None),
    ("Central Nervous System", "central-nervous-system", "The brain and spinal cord.", "nervous-system", "Central_nervous_system"),
    ("Peripheral Nervous System", "peripheral-nervous-system", "The nerves outside the brain and spinal cord.", "nervous-system", "Peripheral_nervous_system"),
    ("Autonomic Nervous System", "autonomic-nervous-system", "The subdivision of the peripheral nervous system that controls involuntary functions.", "nervous-system", "Autonomic_nervous_system"),
    ("Sympathetic Nervous System", "sympathetic-nervous-system", "The autonomic subdivision responsible for the fight-or-flight response.", "autonomic-nervous-system", "Sympathetic_nervous_system"),
    ("Parasympathetic Nervous System", "parasympathetic-nervous-system", "The autonomic subdivision responsible for rest-and-digest functions.", "autonomic-nervous-system", "Parasympathetic_nervous_system"),
    ("Circulatory System", "circulatory-system", "The heart and blood vessels that transport blood, nutrients, and gases through the body.",
     "circulatory-system", None),
    ("Cardiovascular System", "cardiovascular-system", "The heart, arteries, veins, and capillaries — the machinery of circulation.", "circulatory-system", "Cardiovascular_system"),
    ("Lymphatic System", "lymphatic-system", "Network of vessels and organs that carries lymph, part of the immune system.", "circulatory-system", "Lymphatic_system"),
    ("Respiratory System", "respiratory-system", "The lungs, airways, and diaphragm — the machinery of breathing and gas exchange.",
     "respiratory-system", None),
    ("Digestive System", "digestive-system", "The mouth, esophagus, stomach, intestines, liver, and pancreas — the machinery of digestion.",
     "digestive-system", None),
    ("Gastrointestinal Tract", "gi-tract", "The continuous tube from mouth to anus through which food passes.", "digestive-system", "Gastrointestinal_tract"),
    ("Urinary System", "urinary-system", "The kidneys, ureters, bladder, and urethra — the machinery of urine formation and excretion.",
     "urinary-system", None),
    ("Endocrine System", "endocrine-system", "The network of glands secreting hormones directly into the bloodstream.",
     "endocrine-system", None),
    ("Reproductive System", "reproductive-system", "The organs involved in producing gametes and, in females, gestating offspring.",
     "reproductive-system", None),
    ("Skeletal System", "skeletal-system", "The 206 bones (in adult humans) plus cartilage and ligaments that form the body's framework.",
     "skeletal-system", None),
    ("Muscular System", "muscular-system", "The ~600+ skeletal muscles plus smooth and cardiac muscle that produce movement and heat.",
     "muscular-system", None),
    ("Integumentary System", "integumentary-system", "The skin, hair, nails, and associated glands — the body's outer covering.",
     "integumentary-system", None),
    ("Immune System", "immune-system", "The cells, tissues, and organs that defend the body against pathogens and abnormal cells.",
     "immune-system", None),
    ("Vestibular System", "vestibular-system", "The inner-ear system providing the sense of balance and spatial orientation.",
     "vestibular-system", None),
]
for name, slug, narr, subs, wp in SYSTEMS:
    SCIENCES.append(S(
        name, ["anatomy", "physiology"], "organ-system",
        id_slug=slug,
        extras=[name.lower(), f"{name.split()[0].lower()} system"],
        narrative=narr,
        subsumed_by=subs if subs != slug else "human-anatomy",
        provenance=W(wp or name.replace(" ", "_")),
    ))

# ============ ORGANS ============
ORGANS = [
    ("Brain", "brain", "nervous-system", "The central organ of the nervous system; ~86 billion neurons in the adult human.",
     "Every thought and every muscle command originates in the brain.",
     ["cerebrum"], "Brain"),
    ("Cerebrum", "cerebrum", "nervous-system", "The largest part of the brain; controls voluntary movement, sensation, language, and higher cognition.",
     None, [], "Cerebrum"),
    ("Cerebellum", "cerebellum", "nervous-system", "The 'little brain' at the back of the skull that coordinates movement and balance.",
     None, ["little brain"], "Cerebellum"),
    ("Brainstem", "brainstem", "nervous-system", "The stalk-like region connecting cerebrum to spinal cord; controls basic life functions.",
     None, [], "Brainstem"),
    ("Cerebral Cortex", "cerebral-cortex", "nervous-system", "The outer layer of the cerebrum — the folded gray matter where higher cognition happens.",
     None, ["gray matter", "neocortex"], "Cerebral_cortex"),
    ("Frontal Lobe", "frontal-lobe", "nervous-system", "The forward lobe of the cerebral cortex; involved in planning, decision-making, and personality.",
     None, [], "Frontal_lobe"),
    ("Parietal Lobe", "parietal-lobe", "nervous-system", "The upper-rear lobe of the cerebral cortex; integrates sensory information.",
     None, [], "Parietal_lobe"),
    ("Temporal Lobe", "temporal-lobe", "nervous-system", "The lower-side lobe of the cerebral cortex; involved in hearing and memory.",
     None, [], "Temporal_lobe"),
    ("Occipital Lobe", "occipital-lobe", "nervous-system", "The rearmost lobe of the cerebral cortex; the primary visual processing area.",
     None, [], "Occipital_lobe"),
    ("Hippocampus", "hippocampus", "nervous-system", "A brain region critical for forming new episodic memories.",
     None, [], "Hippocampus"),
    ("Amygdala", "amygdala", "nervous-system", "Almond-shaped brain region processing emotion, especially fear.",
     None, [], "Amygdala"),
    ("Thalamus", "thalamus", "nervous-system", "Central relay for sensory and motor signals to the cerebral cortex.",
     None, [], "Thalamus"),
    ("Hypothalamus", "hypothalamus", "nervous-system", "Brain region controlling autonomic functions and hormone release via the pituitary.",
     None, [], "Hypothalamus"),
    ("Pituitary Gland", "pituitary-gland", "endocrine-system", "'Master gland' of the endocrine system; secretes hormones that regulate other glands.",
     None, [], "Pituitary_gland"),
    ("Pineal Gland", "pineal-gland", "endocrine-system", "Small endocrine gland producing melatonin; regulates the sleep-wake cycle.",
     None, [], "Pineal_gland"),
    ("Thyroid Gland", "thyroid-gland", "endocrine-system", "Butterfly-shaped gland in the neck producing thyroid hormones that regulate metabolism.",
     None, [], "Thyroid"),
    ("Parathyroid Glands", "parathyroid-glands", "endocrine-system", "Four small glands behind the thyroid regulating blood calcium via parathyroid hormone.",
     None, [], "Parathyroid_gland"),
    ("Adrenal Glands", "adrenal-glands", "endocrine-system", "Small glands atop each kidney producing cortisol, aldosterone, and adrenaline.",
     None, ["suprarenal glands"], "Adrenal_gland"),
    ("Pancreas", "pancreas", "digestive-system", "Organ that secretes digestive enzymes into the duodenum and hormones (insulin, glucagon) into the blood.",
     None, [], "Pancreas"),
    ("Liver", "liver", "digestive-system", "Largest internal organ; performs ~500 metabolic functions including detoxification, protein synthesis, and bile production.",
     None, [], "Liver"),
    ("Gallbladder", "gallbladder", "digestive-system", "Small organ storing bile produced by the liver.",
     None, [], "Gallbladder"),
    ("Stomach", "stomach", "digestive-system", "Muscular sac that mixes food with acid and enzymes to begin protein digestion.",
     None, [], "Stomach"),
    ("Small Intestine", "small-intestine", "digestive-system", "Long tube where most nutrient absorption occurs; ~6-7 meters in adults.",
     None, ["small bowel"], "Small_intestine"),
    ("Large Intestine", "large-intestine", "digestive-system", "~1.5-meter tube where water is absorbed and stool is formed.",
     None, ["colon", "large bowel"], "Large_intestine"),
    ("Rectum", "rectum", "digestive-system", "Final section of the large intestine, storing stool before defecation.",
     None, [], "Rectum"),
    ("Esophagus", "esophagus", "digestive-system", "The muscular tube conveying food from throat to stomach.",
     None, ["oesophagus", "food pipe"], "Esophagus"),
    ("Kidneys", "kidneys", "urinary-system", "Bean-shaped organs that filter blood to form urine, regulating water, electrolytes, and blood pressure.",
     None, [], "Kidney"),
    ("Ureters", "ureters", "urinary-system", "Tubes carrying urine from kidney to bladder.",
     None, [], "Ureter"),
    ("Bladder", "urinary-bladder", "urinary-system", "Muscular sac storing urine until it is voided.",
     None, ["urinary bladder"], "Urinary_bladder"),
    ("Urethra", "urethra", "urinary-system", "Tube conveying urine from bladder out of the body.",
     None, [], "Urethra"),
    ("Heart", "heart", "circulatory-system", "Muscular four-chambered pump that circulates blood through the body.",
     "A resting human heart beats about 100,000 times a day.",
     [], "Heart"),
    ("Aorta", "aorta", "circulatory-system", "Largest artery in the body, carrying oxygenated blood from the heart to the systemic circulation.",
     None, [], "Aorta"),
    ("Artery", "artery", "circulatory-system", "Blood vessel carrying oxygenated blood away from the heart to the tissues.",
     None, [], "Artery"),
    ("Vein", "vein", "circulatory-system", "Blood vessel carrying deoxygenated blood back to the heart.",
     None, [], "Vein"),
    ("Capillary", "capillary", "circulatory-system", "The smallest blood vessels; site of gas and nutrient exchange with tissues.",
     None, [], "Capillary"),
    ("Lungs", "lungs", "respiratory-system", "Paired organs where gas exchange between air and blood occurs.",
     None, [], "Lung"),
    ("Trachea", "trachea", "respiratory-system", "The windpipe — the airway connecting larynx to bronchi.",
     None, ["windpipe"], "Trachea"),
    ("Bronchi", "bronchi", "respiratory-system", "The two main airways branching from the trachea into the lungs.",
     None, [], "Bronchus"),
    ("Alveolus", "alveolus", "respiratory-system", "Tiny air sacs in the lungs where gas exchange occurs; ~500 million per adult lung.",
     None, ["alveoli"], "Pulmonary_alveolus"),
    ("Diaphragm", "diaphragm-muscle", "respiratory-system", "Dome-shaped muscle beneath the lungs whose contraction drives inhalation.",
     None, [], "Thoracic_diaphragm"),
    ("Skin", "skin", "integumentary-system", "The body's largest organ; ~1.5-2 m² in adults; barrier, thermoregulator, and sensor.",
     None, ["dermis + epidermis"], "Skin"),
    ("Epidermis", "epidermis", "integumentary-system", "The outermost keratinized layer of the skin.",
     None, [], "Epidermis"),
    ("Dermis", "dermis", "integumentary-system", "The middle layer of skin containing hair follicles, sweat glands, and nerves.",
     None, [], "Dermis"),
    ("Bone", "bone", "skeletal-system", "Rigid connective tissue composing the skeleton; matrix of collagen and hydroxyapatite.",
     None, [], "Bone"),
    ("Femur", "femur", "skeletal-system", "The thigh bone; longest and strongest bone in the human body.",
     None, ["thigh bone"], "Femur"),
    ("Humerus", "humerus", "skeletal-system", "The upper arm bone from shoulder to elbow.",
     None, [], "Humerus"),
    ("Cranium", "cranium", "skeletal-system", "The eight bones enclosing the brain; the neurocranium.",
     None, ["skull"], "Cranium"),
    ("Vertebra", "vertebra", "skeletal-system", "One of the 33 bones stacked into the spinal column.",
     None, [], "Vertebra"),
    ("Rib", "rib", "skeletal-system", "One of the 12 pairs of curved bones enclosing the thoracic cavity.",
     None, [], "Rib"),
    ("Cartilage", "cartilage", "skeletal-system", "Flexible connective tissue found in joints, ears, nose, and airways.",
     None, [], "Cartilage"),
    ("Ligament", "ligament", "skeletal-system", "Fibrous connective tissue connecting bones at joints.",
     None, [], "Ligament"),
    ("Tendon", "tendon", "muscular-system", "Fibrous connective tissue connecting muscle to bone.",
     None, [], "Tendon"),
    ("Joint", "joint", "skeletal-system", "The junction between two or more bones — hinge, ball-and-socket, pivot, etc.",
     None, ["articulation"], "Joint"),
    ("Muscle (Biceps)", "biceps", "muscular-system", "Two-headed skeletal muscle at the front of the upper arm.",
     None, ["biceps brachii"], "Biceps"),
    ("Muscle (Triceps)", "triceps", "muscular-system", "Three-headed skeletal muscle at the back of the upper arm.",
     None, ["triceps brachii"], "Triceps"),
    ("Muscle (Deltoid)", "deltoid", "muscular-system", "Triangular muscle of the shoulder.",
     None, [], "Deltoid_muscle"),
    ("Muscle (Quadriceps)", "quadriceps", "muscular-system", "Four-headed muscle group at the front of the thigh.",
     None, ["quadriceps femoris"], "Quadriceps_femoris_muscle"),
    ("Muscle (Hamstring)", "hamstring", "muscular-system", "Three-muscle group at the back of the thigh.",
     None, [], "Hamstring"),
    ("Muscle (Gastrocnemius)", "gastrocnemius", "muscular-system", "The large calf muscle.",
     None, ["calf muscle"], "Gastrocnemius_muscle"),
    ("Eye", "eye", "nervous-system", "The organ of vision; converts light into neural signals.",
     None, [], "Eye"),
    ("Retina", "retina", "nervous-system", "The light-sensitive layer at the back of the eye containing photoreceptor cells.",
     None, [], "Retina"),
    ("Cornea", "cornea", "nervous-system", "The transparent front layer of the eye that provides most of its focusing power.",
     None, [], "Cornea"),
    ("Lens (eye)", "lens-eye", "nervous-system", "Flexible transparent structure that fine-focuses light onto the retina.",
     None, ["crystalline lens"], "Lens_(anatomy)"),
    ("Iris", "iris", "nervous-system", "Pigmented ring controlling pupil size and thus how much light enters the eye.",
     None, [], "Iris_(anatomy)"),
    ("Pupil", "pupil", "nervous-system", "The opening in the center of the iris through which light enters the eye.",
     None, [], "Pupil"),
    ("Ear", "ear", "nervous-system", "The organ of hearing and balance.",
     None, [], "Ear"),
    ("Cochlea", "cochlea", "nervous-system", "The spiral-shaped inner-ear structure that converts sound vibration to neural signals.",
     None, [], "Cochlea"),
    ("Eardrum", "eardrum", "nervous-system", "Thin membrane transmitting sound vibrations from the ear canal to the middle-ear bones.",
     None, ["tympanic membrane"], "Eardrum"),
    ("Semicircular Canals", "semicircular-canals", "nervous-system", "Three fluid-filled loops in the inner ear providing rotational balance information.",
     None, [], "Semicircular_canals"),
    ("Tongue", "tongue", "digestive-system", "Muscular organ used in tasting, chewing, and speech.",
     None, [], "Tongue"),
    ("Nose", "nose", "respiratory-system", "The organ of smell and the primary route of air into the respiratory system.",
     None, [], "Nose"),
    ("Ovary", "ovary", "reproductive-system", "Female reproductive organ producing eggs and sex hormones.",
     None, [], "Ovary"),
    ("Uterus", "uterus", "reproductive-system", "Muscular organ where a fetus gestates.",
     None, ["womb"], "Uterus"),
    ("Fallopian Tube", "fallopian-tube", "reproductive-system", "Tube connecting ovary to uterus, where fertilization typically occurs.",
     None, ["oviduct", "uterine tube"], "Fallopian_tube"),
    ("Testis", "testis", "reproductive-system", "Male reproductive organ producing sperm and testosterone.",
     None, ["testicle"], "Testicle"),
    ("Penis", "penis", "reproductive-system", "Male copulatory organ and urinary outlet.",
     None, [], "Penis"),
    ("Vagina", "vagina", "reproductive-system", "Female copulatory canal, birth canal, and menstrual outflow.",
     None, [], "Vagina"),
    ("Prostate", "prostate", "reproductive-system", "Male gland surrounding the urethra that secretes seminal fluid components.",
     None, [], "Prostate"),
    ("Spleen", "spleen", "immune-system", "Abdominal organ that filters blood, recycles old red cells, and stores platelets.",
     None, [], "Spleen"),
    ("Thymus", "thymus", "immune-system", "Gland in the upper chest where T cells mature; large in childhood, atrophies in adulthood.",
     None, [], "Thymus"),
    ("Lymph Node", "lymph-node", "immune-system", "Small immune organ filtering lymph and hosting adaptive immune responses.",
     None, [], "Lymph_node"),
    ("Bone Marrow", "bone-marrow", "immune-system", "Soft tissue inside bones where blood cells are produced.",
     None, [], "Bone_marrow"),
    ("Tonsils", "tonsils", "immune-system", "Lymphoid tissue at the back of the throat that samples pathogens entering through the mouth and nose.",
     None, ["palatine tonsils"], "Tonsil"),
    ("Appendix", "appendix", "digestive-system", "Small finger-shaped pouch attached to the cecum; contains lymphoid tissue; can become inflamed.",
     None, ["vermiform appendix"], "Appendix_(anatomy)"),
    ("Cecum", "cecum", "digestive-system", "Pouch-like start of the large intestine.",
     None, [], "Cecum"),
    ("Duodenum", "duodenum", "digestive-system", "First and shortest part of the small intestine, receiving stomach contents and pancreatic/biliary secretions.",
     None, [], "Duodenum"),
    ("Jejunum", "jejunum", "digestive-system", "Middle section of the small intestine.",
     None, [], "Jejunum"),
    ("Ileum", "ileum", "digestive-system", "Final section of the small intestine.",
     None, [], "Ileum"),
    ("Larynx", "larynx", "respiratory-system", "The voice box — houses the vocal folds and connects pharynx to trachea.",
     None, ["voice box"], "Larynx"),
    ("Pharynx", "pharynx", "digestive-system", "The throat — a muscular tube behind the mouth serving both respiratory and digestive tracts.",
     None, ["throat"], "Pharynx"),
    ("Spinal Cord", "spinal-cord", "nervous-system", "Long bundle of nerves inside the vertebral column connecting brain to peripheral nerves.",
     None, [], "Spinal_cord"),
    ("Optic Nerve", "optic-nerve", "nervous-system", "The cranial nerve carrying visual information from retina to brain.",
     None, ["cranial nerve II"], "Optic_nerve"),
    ("Vagus Nerve", "vagus-nerve", "nervous-system", "The longest cranial nerve, controlling much of the parasympathetic nervous system.",
     None, ["cranial nerve X"], "Vagus_nerve"),
]
for row in ORGANS:
    if len(row) == 7:
        name, slug, system, narr, everyday, extras, wp = row
    else:
        name, slug, system, narr, everyday, extras, wp = row
    SCIENCES.append(S(
        name, ["anatomy", "physiology"], "organ",
        id_slug=slug, extras=extras + [f"the {name.lower()}"], narrative=narr, everyday=everyday,
        subsumed_by=system,
        provenance=W(wp or name.replace(" ", "_")),
    ))

# ============ TISSUES ============
TISSUES = [
    ("Epithelial Tissue", "epithelium", "The layer of cells covering surfaces and lining cavities in the body."),
    ("Connective Tissue", "connective-tissue", "Tissue that supports, binds, and separates other tissues — includes fat, bone, cartilage, blood."),
    ("Muscle Tissue", "muscle-tissue", "Tissue specialized for contraction — skeletal, smooth, cardiac."),
    ("Nervous Tissue", "nervous-tissue", "Tissue composed of neurons and glial cells; forms brain, spinal cord, and nerves."),
    ("Blood", "blood", "Fluid connective tissue transporting oxygen, nutrients, hormones, and waste."),
    ("Lymph", "lymph", "Clear fluid in the lymphatic system, resembling blood plasma minus red cells."),
    ("Adipose Tissue", "adipose-tissue", "Fat tissue — stores energy and provides insulation."),
    ("Bone Tissue", "bone-tissue", "Rigid connective tissue forming bones — matrix of collagen and hydroxyapatite."),
    ("Cartilage Tissue", "cartilage-tissue", "Flexible avascular connective tissue found in joints, ears, and airways."),
    ("Skeletal Muscle Tissue", "skeletal-muscle-tissue", "Voluntary striated muscle attached to bones."),
    ("Smooth Muscle Tissue", "smooth-muscle-tissue", "Involuntary non-striated muscle of hollow organs and vessels."),
    ("Cardiac Muscle Tissue", "cardiac-muscle-tissue", "Involuntary striated muscle of the heart."),
    ("Mucous Membrane", "mucous-membrane", "Moist epithelial linings of body cavities open to the outside — gut, airways, urogenital tract."),
    ("Serous Membrane", "serous-membrane", "Thin membranes lining internal cavities — pleura, pericardium, peritoneum."),
]
for name, slug, narr in TISSUES:
    SCIENCES.append(S(
        name, "anatomy", "tissue",
        id_slug=slug, narrative=narr,
        subsumed_by="human-anatomy",
        provenance=W(name.replace(" ", "_")),
    ))

# ============ DISEASES ============
DISEASES = [
    # (name, slug, disc, narr, everyday, extras, icd, mesh, wp)
    ("Cancer", "cancer", "medicine", "A group of diseases characterized by uncontrolled cell growth with the ability to invade or spread to other parts of the body.",
     None, ["malignancy", "malignant neoplasm", "tumor"], "ICD-11 2A00-2F9Z", "D009369", "Cancer"),
    ("Breast Cancer", "breast-cancer", "medicine", "Cancer that develops from breast tissue — the most common cancer in women worldwide.",
     None, ["mammary carcinoma"], "ICD-11 2C60-2C6Z", "D001943", "Breast_cancer"),
    ("Lung Cancer", "lung-cancer", "medicine", "Malignant tumor of the lung; strongly linked to tobacco smoking.",
     None, ["bronchogenic carcinoma"], "ICD-11 2C25", "D008175", "Lung_cancer"),
    ("Prostate Cancer", "prostate-cancer", "medicine", "Cancer of the prostate gland — common in older men.",
     None, [], "ICD-11 2C82", "D011471", "Prostate_cancer"),
    ("Colon Cancer", "colon-cancer", "medicine", "Malignant tumor of the colon; often preceded by adenomatous polyps.",
     None, ["colorectal cancer"], "ICD-11 2B90-2B93", "D015179", "Colorectal_cancer"),
    ("Leukemia", "leukemia", "medicine", "Cancer of blood-forming tissues, producing abnormal white blood cells.",
     None, ["blood cancer"], "ICD-11 2A60-2A6Z", "D007938", "Leukemia"),
    ("Lymphoma", "lymphoma", "medicine", "Cancer originating in lymphocytes — Hodgkin and non-Hodgkin varieties.",
     None, [], "ICD-11 2A70-2B2Z", "D008223", "Lymphoma"),
    ("Melanoma", "melanoma", "medicine", "Aggressive skin cancer arising from melanocytes.",
     None, [], "ICD-11 2C30", "D008545", "Melanoma"),
    ("Diabetes Mellitus", "diabetes-mellitus", "medicine", "Group of metabolic disorders characterized by high blood sugar over a prolonged period.",
     None, ["diabetes", "high blood sugar"], "ICD-11 5A10-5A14", "D003920", "Diabetes"),
    ("Type 1 Diabetes", "type-1-diabetes", "medicine", "Autoimmune destruction of pancreatic beta cells, resulting in insulin deficiency.",
     None, ["insulin-dependent diabetes", "juvenile diabetes"], "ICD-11 5A10", "D003922", "Type_1_diabetes"),
    ("Type 2 Diabetes", "type-2-diabetes", "medicine", "Metabolic disorder characterized by insulin resistance and often preventable by lifestyle.",
     None, ["non-insulin-dependent diabetes", "adult-onset diabetes"], "ICD-11 5A11", "D003924", "Type_2_diabetes"),
    ("Hypertension", "hypertension", "medicine", "Chronic elevated blood pressure — a major risk factor for stroke and heart attack.",
     "'The silent killer' because it often has no symptoms.",
     ["high blood pressure", "HTN"], "ICD-11 BA00-BA04", "D006973", "Hypertension"),
    ("Coronary Artery Disease", "coronary-artery-disease", "medicine", "Narrowing of coronary arteries due to atherosclerosis; the leading cause of death worldwide.",
     None, ["CAD", "ischemic heart disease"], "ICD-11 BA40-BA6Z", "D003324", "Coronary_artery_disease"),
    ("Myocardial Infarction", "myocardial-infarction", "medicine", "Death of heart muscle from prolonged interruption of blood supply — a heart attack.",
     None, ["heart attack", "MI"], "ICD-11 BA41", "D009203", "Myocardial_infarction"),
    ("Stroke", "stroke", "medicine", "Sudden loss of brain function due to disturbance of blood supply — ischemic or hemorrhagic.",
     None, ["cerebrovascular accident", "CVA"], "ICD-11 8B00-8B26", "D020521", "Stroke"),
    ("Alzheimer's Disease", "alzheimers-disease", "medicine", "Progressive neurodegenerative disorder and most common cause of dementia.",
     None, ["Alzheimer disease", "AD"], "ICD-11 8A20", "D000544", "Alzheimer%27s_disease"),
    ("Parkinson's Disease", "parkinsons-disease", "medicine", "Progressive nervous-system disorder marked by tremor, rigidity, and bradykinesia due to loss of dopaminergic neurons.",
     None, ["PD", "paralysis agitans"], "ICD-11 8A00", "D010300", "Parkinson%27s_disease"),
    ("Multiple Sclerosis", "multiple-sclerosis", "medicine", "Autoimmune demyelinating disease of the central nervous system.",
     None, ["MS"], "ICD-11 8A40", "D009103", "Multiple_sclerosis"),
    ("Amyotrophic Lateral Sclerosis", "als", "medicine", "Progressive motor-neuron disease also known as Lou Gehrig's disease.",
     None, ["ALS", "Lou Gehrig's disease", "motor neuron disease"], "ICD-11 8B60", "D000690", "Amyotrophic_lateral_sclerosis"),
    ("Epilepsy", "epilepsy", "medicine", "Neurological disorder characterized by recurrent unprovoked seizures.",
     None, ["seizure disorder"], "ICD-11 8A61", "D004827", "Epilepsy"),
    ("Migraine", "migraine", "medicine", "Recurrent throbbing headache, often with visual aura and nausea.",
     None, [], "ICD-11 8A80", "D008881", "Migraine"),
    ("Asthma", "asthma", "medicine", "Chronic inflammatory disease of the airways, causing episodes of wheezing and breathlessness.",
     None, [], "ICD-11 CA07", "D001249", "Asthma"),
    ("COPD", "copd", "medicine", "Chronic obstructive pulmonary disease — progressive airflow limitation, usually from smoking.",
     None, ["chronic obstructive pulmonary disease", "emphysema", "chronic bronchitis"], "ICD-11 CA22", "D029424", "Chronic_obstructive_pulmonary_disease"),
    ("Pneumonia", "pneumonia", "medicine", "Infection inflaming the alveoli in one or both lungs.",
     None, [], "ICD-11 CA40", "D011014", "Pneumonia"),
    ("Tuberculosis", "tuberculosis", "medicine", "Bacterial infection primarily affecting the lungs, caused by Mycobacterium tuberculosis.",
     None, ["TB", "consumption", "phthisis"], "ICD-11 1B10-1B14", "D014376", "Tuberculosis"),
    ("Influenza", "influenza", "medicine", "Contagious respiratory illness caused by influenza viruses.",
     None, ["flu", "grippe"], "ICD-11 1E30-1E32", "D007251", "Influenza"),
    ("COVID-19", "covid-19", "medicine", "Respiratory disease caused by SARS-CoV-2, first identified in 2019.",
     None, ["coronavirus disease", "SARS-CoV-2 infection"], "ICD-11 RA01", "D000086382", "COVID-19"),
    ("HIV Infection", "hiv-infection", "medicine", "Chronic retroviral infection with human immunodeficiency virus; progresses to AIDS without treatment.",
     None, ["HIV", "human immunodeficiency virus"], "ICD-11 1C60", "D015658", "HIV/AIDS"),
    ("AIDS", "aids", "medicine", "Acquired immunodeficiency syndrome — advanced HIV infection with opportunistic infections and low CD4 count.",
     None, ["acquired immune deficiency syndrome"], "ICD-11 1C62", "D000163", "HIV/AIDS"),
    ("Malaria", "malaria", "medicine", "Mosquito-borne disease caused by Plasmodium parasites; a major cause of death in tropical regions.",
     None, [], "ICD-11 1F40-1F45", "D008288", "Malaria"),
    ("Hepatitis B", "hepatitis-b", "medicine", "Viral infection of the liver caused by hepatitis B virus.",
     None, ["HBV"], "ICD-11 1E51", "D006509", "Hepatitis_B"),
    ("Hepatitis C", "hepatitis-c", "medicine", "Viral infection of the liver caused by hepatitis C virus.",
     None, ["HCV"], "ICD-11 1E51", "D006526", "Hepatitis_C"),
    ("Cirrhosis", "cirrhosis", "medicine", "Late-stage scarring of the liver caused by many forms of chronic liver disease.",
     None, ["liver cirrhosis"], "ICD-11 DB93", "D008103", "Cirrhosis"),
    ("Chronic Kidney Disease", "chronic-kidney-disease", "medicine", "Progressive loss of kidney function over time.",
     None, ["CKD"], "ICD-11 GB61", "D051436", "Chronic_kidney_disease"),
    ("Obesity", "obesity", "medicine", "Excessive body-fat accumulation presenting a risk to health.",
     None, [], "ICD-11 5B81", "D009765", "Obesity"),
    ("Malnutrition", "malnutrition", "medicine", "Deficiencies, excesses, or imbalances in energy or nutrient intake.",
     None, [], "ICD-11 5B50-5B7Y", "D044342", "Malnutrition"),
    ("Anemia", "anemia", "medicine", "Reduction in the number or function of red blood cells; causes fatigue and pallor.",
     None, ["low red blood cell count"], "ICD-11 3A00-3A9Z", "D000740", "Anemia"),
    ("Sickle Cell Anemia", "sickle-cell-anemia", "medicine", "Genetic disorder producing abnormal hemoglobin that distorts red cells into a sickle shape.",
     None, ["sickle cell disease", "SCD"], "ICD-11 3A51.0", "D000755", "Sickle_cell_disease"),
    ("Hemophilia", "hemophilia", "medicine", "Inherited bleeding disorder caused by deficient clotting factor.",
     None, ["hemophilia A", "hemophilia B"], "ICD-11 3B10-3B14", "D006467", "Haemophilia"),
    ("Cystic Fibrosis", "cystic-fibrosis", "medicine", "Genetic disorder affecting mucus and sweat glands, primarily impairing lungs and pancreas.",
     None, ["CF"], "ICD-11 CA25", "D003550", "Cystic_fibrosis"),
    ("Rheumatoid Arthritis", "rheumatoid-arthritis", "medicine", "Autoimmune inflammatory disease primarily affecting joints.",
     None, ["RA"], "ICD-11 FA20", "D001172", "Rheumatoid_arthritis"),
    ("Osteoarthritis", "osteoarthritis", "medicine", "Degenerative joint disease from cartilage breakdown, the most common form of arthritis.",
     None, ["OA", "wear-and-tear arthritis"], "ICD-11 FA00-FA05", "D010003", "Osteoarthritis"),
    ("Osteoporosis", "osteoporosis", "medicine", "Reduced bone density with increased fracture risk.",
     None, [], "ICD-11 FB83", "D010024", "Osteoporosis"),
    ("Lupus", "lupus", "medicine", "Systemic lupus erythematosus — autoimmune disease affecting multiple organ systems.",
     None, ["SLE", "systemic lupus erythematosus"], "ICD-11 4A40", "D008180", "Systemic_lupus_erythematosus"),
    ("Psoriasis", "psoriasis", "medicine", "Chronic autoimmune skin condition producing scaly red plaques.",
     None, [], "ICD-11 EA90", "D011565", "Psoriasis"),
    ("Eczema", "eczema", "medicine", "Group of conditions producing inflamed, itchy skin — atopic dermatitis is most common.",
     None, ["atopic dermatitis"], "ICD-11 EA80-EA82", "D003876", "Atopic_dermatitis"),
    ("Acne", "acne", "medicine", "Common skin condition from clogged pores producing pimples and cysts.",
     None, ["acne vulgaris"], "ICD-11 ED80", "D000152", "Acne_vulgaris"),
    ("Migraine (chronic)", "chronic-migraine", "medicine", "Frequent recurring migraine headaches occurring on more than half of days per month.",
     None, [], "ICD-11 8A80.2", "D008881", "Migraine"),
    ("Depression", "major-depression", "medicine", "Persistent low mood and loss of interest severe enough to impair daily function.",
     None, ["major depressive disorder", "clinical depression", "MDD"], "ICD-11 6A70", "D003866", "Major_depressive_disorder"),
    ("Anxiety Disorder", "anxiety-disorder", "medicine", "Group of mental disorders characterized by significant feelings of anxiety and fear.",
     None, ["GAD", "generalized anxiety"], "ICD-11 6B00-6B0Z", "D001008", "Anxiety_disorder"),
    ("Bipolar Disorder", "bipolar-disorder", "medicine", "Mood disorder featuring alternating manic and depressive episodes.",
     None, ["manic-depressive illness"], "ICD-11 6A60-6A61", "D001714", "Bipolar_disorder"),
    ("Schizophrenia", "schizophrenia", "medicine", "Chronic mental disorder characterized by disorganized thought, delusions, and hallucinations.",
     None, [], "ICD-11 6A20", "D012559", "Schizophrenia"),
    ("Autism Spectrum Disorder", "autism-spectrum-disorder", "medicine", "Neurodevelopmental condition characterized by challenges with social communication and by restricted or repetitive behaviors.",
     None, ["ASD", "autism"], "ICD-11 6A02", "D000067877", "Autism_spectrum"),
    ("ADHD", "adhd", "medicine", "Attention-deficit / hyperactivity disorder — persistent inattention and/or hyperactivity-impulsivity.",
     None, ["attention deficit hyperactivity disorder"], "ICD-11 6A05", "D001289", "Attention_deficit_hyperactivity_disorder"),
    ("PTSD", "ptsd", "medicine", "Post-traumatic stress disorder — anxiety condition triggered by trauma exposure.",
     None, ["post-traumatic stress disorder"], "ICD-11 6B40", "D013313", "Post-traumatic_stress_disorder"),
    ("OCD", "ocd", "medicine", "Obsessive-compulsive disorder — recurrent intrusive thoughts and repetitive rituals aimed at relieving anxiety.",
     None, ["obsessive-compulsive disorder"], "ICD-11 6B20", "D009771", "Obsessive%E2%80%93compulsive_disorder"),
    ("Dementia", "dementia", "medicine", "Progressive decline in cognitive function severe enough to interfere with daily life.",
     None, [], "ICD-11 6D80-6D8Z", "D003704", "Dementia"),
    ("Migraine (episodic)", "episodic-migraine", "medicine", "Migraine occurring on fewer than 15 days per month.",
     None, [], "ICD-11 8A80.0", "D008881", "Migraine"),
    ("Kidney Stones", "kidney-stones", "medicine", "Solid mineral deposits forming in the urinary tract, often causing severe flank pain.",
     None, ["nephrolithiasis", "renal calculi"], "ICD-11 GB70", "D007669", "Kidney_stone_disease"),
    ("Gallstones", "gallstones", "medicine", "Solid deposits forming in the gallbladder, most commonly of cholesterol.",
     None, ["cholelithiasis"], "ICD-11 DC11", "D002769", "Gallstone"),
    ("Ulcer (peptic)", "peptic-ulcer", "medicine", "Break in the lining of stomach or duodenum, often due to H. pylori infection or NSAIDs.",
     None, [], "ICD-11 DA61", "D010437", "Peptic_ulcer_disease"),
    ("Irritable Bowel Syndrome", "ibs", "medicine", "Functional gastrointestinal disorder producing abdominal pain and altered bowel habits.",
     None, ["IBS"], "ICD-11 DD91", "D043183", "Irritable_bowel_syndrome"),
    ("Crohn's Disease", "crohns-disease", "medicine", "Chronic inflammatory bowel disease that can affect any part of the GI tract.",
     None, [], "ICD-11 DD70", "D003424", "Crohn%27s_disease"),
    ("Ulcerative Colitis", "ulcerative-colitis", "medicine", "Chronic inflammatory bowel disease limited to the colon and rectum.",
     None, [], "ICD-11 DD71", "D003093", "Ulcerative_colitis"),
    ("Celiac Disease", "celiac-disease", "medicine", "Autoimmune disorder in which gluten damages the small intestine lining.",
     None, ["coeliac disease", "gluten enteropathy"], "ICD-11 DA95", "D002446", "Coeliac_disease"),
    ("Anemia (iron deficiency)", "iron-deficiency-anemia", "medicine", "Anemia due to insufficient iron for hemoglobin production; the most common anemia worldwide.",
     None, [], "ICD-11 3A00", "D018798", "Iron-deficiency_anemia"),
    ("Thyroid Disorder — Hypothyroidism", "hypothyroidism", "medicine", "Underactive thyroid producing insufficient thyroid hormone.",
     None, ["underactive thyroid", "myxedema"], "ICD-11 5A00", "D007037", "Hypothyroidism"),
    ("Thyroid Disorder — Hyperthyroidism", "hyperthyroidism", "medicine", "Overactive thyroid producing excess thyroid hormone.",
     None, ["overactive thyroid"], "ICD-11 5A02", "D006980", "Hyperthyroidism"),
    ("Graves' Disease", "graves-disease", "medicine", "Autoimmune hyperthyroidism with distinctive eye findings.",
     None, [], "ICD-11 5A02.0", "D006111", "Graves%27_disease"),
    ("Hashimoto Thyroiditis", "hashimoto-thyroiditis", "medicine", "Autoimmune destruction of the thyroid, common cause of hypothyroidism.",
     None, [], "ICD-11 5A03.0", "D050031", "Hashimoto%27s_thyroiditis"),
    ("Down Syndrome", "down-syndrome", "medicine", "Chromosomal condition caused by an extra copy of chromosome 21.",
     None, ["trisomy 21"], "ICD-11 LD40", "D004314", "Down_syndrome"),
    ("Sickle Cell Trait", "sickle-cell-trait", "medicine", "Heterozygous state for the sickle cell mutation, usually asymptomatic but carrying reproductive implications.",
     None, [], "ICD-11 3A51.1", "D012805", "Sickle_cell_trait"),
    ("Chickenpox", "chickenpox", "medicine", "Highly contagious viral infection caused by varicella-zoster virus, producing itchy vesicular rash.",
     None, ["varicella"], "ICD-11 1E90", "D002644", "Chickenpox"),
    ("Measles", "measles", "medicine", "Highly contagious viral infection causing high fever and a characteristic rash; largely preventable by vaccination.",
     None, ["morbilli", "rubeola"], "ICD-11 1F03", "D008457", "Measles"),
    ("Mumps", "mumps", "medicine", "Viral infection causing painful swelling of the parotid glands.",
     None, ["epidemic parotitis"], "ICD-11 1D80", "D009107", "Mumps"),
    ("Rubella", "rubella", "medicine", "Viral infection causing a mild rash; dangerous in pregnancy due to birth defects.",
     None, ["German measles"], "ICD-11 1F02", "D012409", "Rubella"),
    ("Whooping Cough", "whooping-cough", "medicine", "Highly contagious respiratory disease caused by Bordetella pertussis, with characteristic 'whoop' after coughing.",
     None, ["pertussis"], "ICD-11 1C12", "D014917", "Whooping_cough"),
    ("Common Cold", "common-cold", "medicine", "Viral upper respiratory tract infection, usually rhinovirus.",
     None, ["cold", "acute rhinitis"], "ICD-11 CA00", "D003139", "Common_cold"),
    ("Meningitis", "meningitis", "medicine", "Inflammation of the meninges, the membranes surrounding brain and spinal cord.",
     None, [], "ICD-11 1C24", "D008581", "Meningitis"),
    ("Encephalitis", "encephalitis", "medicine", "Inflammation of the brain, usually from viral infection.",
     None, [], "ICD-11 1C21", "D004660", "Encephalitis"),
    ("Sepsis", "sepsis", "medicine", "Life-threatening organ dysfunction from a dysregulated response to infection.",
     None, ["septicemia"], "ICD-11 1G40-1G41", "D018805", "Sepsis"),
    ("Anaphylaxis", "anaphylaxis", "medicine", "Severe, life-threatening allergic reaction with airway compromise and shock.",
     None, [], "ICD-11 4A84", "D000707", "Anaphylaxis"),
    ("Allergy", "allergy", "medicine", "Hypersensitive immune response to substances normally harmless.",
     None, ["hypersensitivity"], "ICD-11 4A80-4A85", "D006967", "Allergy"),
    ("Concussion", "concussion", "medicine", "Mild traumatic brain injury from a blow to the head or violent movement.",
     None, ["mild TBI"], "ICD-11 NA07", "D001924", "Concussion"),
]
for row in DISEASES:
    if len(row) == 9:
        name, slug, disc, narr, everyday, extras, icd, mesh, wp = row
    SCIENCES.append(S(
        name, disc, "disease",
        id_slug=slug, extras=extras + [name.lower()], narrative=narr, everyday=everyday,
        icd=icd, mesh=mesh,
        subsumed_by="disease-classification",
        provenance=W(wp),
    ))

# ============ PARENT NODES ============
for name, slug, narr, disc in [
    ("Human Anatomy", "human-anatomy", "The study of the structural organization of the human body — from organ systems down to cells.", "anatomy"),
    ("Human Physiology", "human-physiology", "The study of the mechanical, physical, and biochemical functions of the human body.", "physiology"),
    ("Disease Classification", "disease-classification", "The organized categorization of illnesses — used clinically and epidemiologically (ICD-11, DSM).", "medicine"),
]:
    SCIENCES.append(S(name, disc, "classification",
                     id_slug=slug, narrative=narr, subsumed_by="medicine" if disc == "medicine" else "biology",
                     provenance=W(name.replace(" ", "_"))))
