"""Pathogens, viruses, notable taxa, drug classes. Target ~350 nodes."""

from _helpers import S


def W(name):
    return [{"source": "wikipedia", "url": f"https://en.wikipedia.org/wiki/{name}"}]


SCIENCES = []

# ---- PATHOGENS / VIRUSES ----
PATHOGENS = [
    # (name, slug, kind, disc, narr, extras, taxon)
    ("SARS-CoV-2", "sars-cov-2", "virology", "The coronavirus responsible for the COVID-19 pandemic first identified in 2019.",
     ["novel coronavirus", "2019-nCoV"], {"family": "Coronaviridae", "genus": "Betacoronavirus"}),
    ("Influenza A Virus", "influenza-a-virus", "virology", "The most virulent flu virus type; subtypes named for hemagglutinin and neuraminidase (H1N1, H3N2, etc.).",
     ["flu A", "orthomyxovirus"], {"family": "Orthomyxoviridae", "genus": "Alphainfluenzavirus"}),
    ("HIV", "hiv-virus", "virology", "Human immunodeficiency virus — a retrovirus that attacks CD4+ T cells and, untreated, progresses to AIDS.",
     ["human immunodeficiency virus", "HIV-1", "HIV-2"], {"family": "Retroviridae", "genus": "Lentivirus"}),
    ("Ebola Virus", "ebola-virus", "virology", "Filovirus causing severe hemorrhagic fever with high mortality.",
     ["EBOV", "Zaire ebolavirus"], {"family": "Filoviridae", "genus": "Ebolavirus"}),
    ("Marburg Virus", "marburg-virus", "virology", "Filovirus related to Ebola causing hemorrhagic fever.",
     ["MARV"], {"family": "Filoviridae", "genus": "Marburgvirus"}),
    ("Herpes Simplex Virus", "hsv", "virology", "Family of DNA viruses causing oral (HSV-1) and genital (HSV-2) herpes.",
     ["HSV-1", "HSV-2"], {"family": "Herpesviridae"}),
    ("Varicella-Zoster Virus", "vzv", "virology", "Herpesvirus causing chickenpox on primary infection and shingles on reactivation.",
     ["VZV", "human herpesvirus 3"], {"family": "Herpesviridae"}),
    ("Epstein-Barr Virus", "ebv", "virology", "Herpesvirus that infects >90% of adults; causes mononucleosis and is associated with several cancers.",
     ["EBV", "human herpesvirus 4"], {"family": "Herpesviridae"}),
    ("Cytomegalovirus", "cmv", "virology", "Common herpesvirus that establishes lifelong latent infection; dangerous in immunocompromised and congenital settings.",
     ["CMV", "human herpesvirus 5"], {"family": "Herpesviridae"}),
    ("Rhinovirus", "rhinovirus", "virology", "The most common viral infectious agent in humans and the predominant cause of the common cold.",
     [], {"family": "Picornaviridae", "genus": "Enterovirus"}),
    ("Poliovirus", "poliovirus", "virology", "Enterovirus causing poliomyelitis; near-eradicated by vaccination.",
     [], {"family": "Picornaviridae"}),
    ("Rotavirus", "rotavirus", "virology", "Common cause of severe diarrhea among infants and young children.",
     [], {"family": "Reoviridae"}),
    ("Hepatitis A Virus", "hepatitis-a-virus", "virology", "Picornavirus causing acute liver infection; transmitted fecal-oral.",
     ["HAV"], {"family": "Picornaviridae"}),
    ("Hepatitis B Virus", "hepatitis-b-virus", "virology", "DNA virus causing acute and chronic liver infection.",
     ["HBV"], {"family": "Hepadnaviridae"}),
    ("Hepatitis C Virus", "hepatitis-c-virus", "virology", "RNA virus causing chronic liver infection; leading cause of liver cirrhosis and cancer worldwide.",
     ["HCV"], {"family": "Flaviviridae"}),
    ("Rabies Virus", "rabies-virus", "virology", "Neurotropic virus causing rabies, nearly always fatal once symptoms appear.",
     [], {"family": "Rhabdoviridae"}),
    ("Zika Virus", "zika-virus", "virology", "Mosquito-borne flavivirus associated with birth defects when contracted during pregnancy.",
     [], {"family": "Flaviviridae"}),
    ("Dengue Virus", "dengue-virus", "virology", "Mosquito-borne flavivirus causing dengue fever.",
     ["DENV"], {"family": "Flaviviridae"}),
    ("West Nile Virus", "west-nile-virus", "virology", "Mosquito-borne flavivirus that can cause encephalitis.",
     [], {"family": "Flaviviridae"}),
    ("Yellow Fever Virus", "yellow-fever-virus", "virology", "Mosquito-borne flavivirus causing yellow fever.",
     [], {"family": "Flaviviridae"}),
    ("Measles Virus", "measles-virus", "virology", "Paramyxovirus causing measles; one of the most contagious viruses known.",
     [], {"family": "Paramyxoviridae"}),
    ("Norovirus", "norovirus", "virology", "Highly-contagious cause of acute gastroenteritis, often in cruise ships and institutions.",
     [], {"family": "Caliciviridae"}),
    ("HPV", "human-papillomavirus", "virology", "Human papillomavirus — DNA viruses causing warts and, for high-risk types, cervical and other cancers.",
     ["human papillomavirus"], {"family": "Papillomaviridae"}),
    ("Prion", "prion", "biology", "Misfolded protein that induces normal versions of the same protein to misfold, causing transmissible spongiform encephalopathies.",
     ["misfolded protein"], None),
    # Bacteria
    ("Escherichia coli", "e-coli", "microbiology", "Gram-negative bacterium; most strains are harmless gut commensals, but some cause food poisoning.",
     ["E. coli"], {"family": "Enterobacteriaceae", "genus": "Escherichia", "species": "coli"}),
    ("Staphylococcus aureus", "staph-aureus", "microbiology", "Gram-positive bacterium causing skin infections, pneumonia, and sepsis; methicillin-resistant (MRSA) is a major hospital problem.",
     ["staph"], {"genus": "Staphylococcus", "species": "aureus"}),
    ("Streptococcus pyogenes", "strep-pyogenes", "microbiology", "Group A streptococcus causing strep throat, scarlet fever, and necrotizing fasciitis.",
     ["group A strep"], {"genus": "Streptococcus", "species": "pyogenes"}),
    ("Streptococcus pneumoniae", "strep-pneumoniae", "microbiology", "Leading cause of community-acquired pneumonia, meningitis, and otitis media.",
     ["pneumococcus"], {"genus": "Streptococcus", "species": "pneumoniae"}),
    ("Mycobacterium tuberculosis", "m-tuberculosis", "microbiology", "Slow-growing acid-fast bacterium causing tuberculosis.",
     ["TB bacillus"], {"genus": "Mycobacterium", "species": "tuberculosis"}),
    ("Salmonella", "salmonella", "microbiology", "Genus of gram-negative bacteria including major causes of food poisoning and typhoid fever.",
     [], {"genus": "Salmonella"}),
    ("Helicobacter pylori", "h-pylori", "microbiology", "Bacterium infecting the stomach lining; primary cause of peptic ulcers and gastric cancer.",
     ["H. pylori"], {"genus": "Helicobacter", "species": "pylori"}),
    ("Clostridium difficile", "c-difficile", "microbiology", "Bacterium causing severe diarrhea, often after antibiotic disruption of gut flora.",
     ["C. diff"], {"genus": "Clostridioides", "species": "difficile"}),
    ("Clostridium botulinum", "c-botulinum", "microbiology", "Anaerobic bacterium producing botulinum toxin, the most potent toxin known.",
     [], {"genus": "Clostridium", "species": "botulinum"}),
    ("Clostridium tetani", "c-tetani", "microbiology", "Bacterium producing tetanospasmin, causing tetanus.",
     [], {"genus": "Clostridium", "species": "tetani"}),
    ("Yersinia pestis", "y-pestis", "microbiology", "Bacterium causing plague; responsible for the Black Death in the 14th century.",
     ["plague bacillus"], {"genus": "Yersinia", "species": "pestis"}),
    ("Vibrio cholerae", "v-cholerae", "microbiology", "Bacterium causing cholera, an acute diarrheal disease.",
     [], {"genus": "Vibrio", "species": "cholerae"}),
    ("Bordetella pertussis", "b-pertussis", "microbiology", "Bacterium causing whooping cough.",
     [], {"genus": "Bordetella", "species": "pertussis"}),
    ("Chlamydia trachomatis", "chlamydia-trachomatis", "microbiology", "Intracellular bacterium causing chlamydia, one of the most common sexually-transmitted infections.",
     [], {"genus": "Chlamydia", "species": "trachomatis"}),
    ("Neisseria gonorrhoeae", "n-gonorrhoeae", "microbiology", "Bacterium causing gonorrhea.",
     ["gonococcus"], {"genus": "Neisseria", "species": "gonorrhoeae"}),
    ("Treponema pallidum", "t-pallidum", "microbiology", "Spirochete bacterium causing syphilis.",
     [], {"genus": "Treponema", "species": "pallidum"}),
    ("Borrelia burgdorferi", "b-burgdorferi", "microbiology", "Spirochete bacterium causing Lyme disease.",
     [], {"genus": "Borrelia", "species": "burgdorferi"}),
    ("Plasmodium falciparum", "p-falciparum", "microbiology", "Protozoan parasite causing the most severe form of malaria.",
     [], {"genus": "Plasmodium", "species": "falciparum"}),
    ("Toxoplasma gondii", "t-gondii", "microbiology", "Intracellular parasite of warm-blooded animals; extremely widespread; causes toxoplasmosis.",
     [], {"genus": "Toxoplasma", "species": "gondii"}),
    ("Giardia lamblia", "giardia-lamblia", "microbiology", "Flagellated protozoan parasite causing diarrhea (giardiasis).",
     [], {"genus": "Giardia", "species": "lamblia"}),
    ("Candida albicans", "candida-albicans", "microbiology", "Yeast fungus that is a common commensal but can cause thrush and systemic candidiasis.",
     [], {"kingdom": "Fungi", "genus": "Candida", "species": "albicans"}),
    ("Aspergillus", "aspergillus", "microbiology", "Genus of molds including species that cause aspergillosis in immunocompromised patients.",
     [], {"kingdom": "Fungi", "genus": "Aspergillus"}),
    ("Penicillium", "penicillium", "microbiology", "Genus of molds important in food (blue cheese), industry, and as source of penicillin.",
     [], {"kingdom": "Fungi", "genus": "Penicillium"}),
]

for row in PATHOGENS:
    name, slug, disc, narr, extras, taxon = row
    kind = "pathogen"
    SCIENCES.append(S(name, disc, kind,
                     id_slug=slug, extras=extras + [name.lower()], narrative=narr,
                     applies=[":biological"],
                     subsumed_by="pathogen-classification",
                     taxon=taxon,
                     provenance=W(name.replace(" ", "_"))))

# ---- NOTABLE TAXA (organism kinds) ----
TAXA = [
    ("Homo sapiens", "homo-sapiens", "biology", "Modern human — the only extant species of the genus Homo.",
     ["human", "modern human"], {"kingdom": "Animalia", "phylum": "Chordata", "class": "Mammalia", "order": "Primates", "family": "Hominidae", "genus": "Homo", "species": "sapiens"}),
    ("Chimpanzee", "chimpanzee", "biology", "Great ape and one of humans' closest living relatives, sharing ~98.8% of our genome.",
     ["chimp"], {"kingdom": "Animalia", "class": "Mammalia", "family": "Hominidae", "genus": "Pan", "species": "troglodytes"}),
    ("Bonobo", "bonobo", "biology", "Great ape closely related to the chimpanzee; lives only in the Congo.",
     ["pygmy chimpanzee"], {"family": "Hominidae", "genus": "Pan", "species": "paniscus"}),
    ("Gorilla", "gorilla", "biology", "Largest living primate; two species (western and eastern) in equatorial African forests.",
     [], {"family": "Hominidae", "genus": "Gorilla"}),
    ("Orangutan", "orangutan", "biology", "Great ape of Southeast Asia; three species, all critically endangered.",
     [], {"family": "Hominidae", "genus": "Pongo"}),
    ("Dog", "dog", "biology", "Domesticated descendant of the gray wolf; the first domesticated species.",
     ["domestic dog", "Canis familiaris"], {"kingdom": "Animalia", "family": "Canidae", "genus": "Canis", "species": "lupus familiaris"}),
    ("Cat", "cat", "biology", "Domesticated small carnivorous mammal.",
     ["domestic cat", "Felis catus"], {"family": "Felidae", "genus": "Felis", "species": "catus"}),
    ("Horse", "horse", "biology", "Large odd-toed ungulate domesticated ~4000 BCE.",
     [], {"family": "Equidae", "genus": "Equus", "species": "caballus"}),
    ("Cow", "cow-bovine", "biology", "Domestic cattle — bovine mammals raised for meat, milk, and hide.",
     ["cattle", "Bos taurus"], {"family": "Bovidae", "genus": "Bos", "species": "taurus"}),
    ("Sheep", "sheep", "biology", "Domesticated ruminant kept for wool, meat, and milk.",
     [], {"family": "Bovidae", "genus": "Ovis", "species": "aries"}),
    ("Pig", "pig", "biology", "Domesticated omnivorous even-toed ungulate.",
     ["swine", "hog"], {"family": "Suidae", "genus": "Sus", "species": "scrofa domesticus"}),
    ("Chicken", "chicken", "biology", "Domesticated fowl — the most numerous bird in the world.",
     [], {"family": "Phasianidae", "genus": "Gallus", "species": "gallus"}),
    ("Fruit Fly", "drosophila-melanogaster", "biology", "Drosophila melanogaster — a classical model organism for genetics.",
     ["Drosophila", "fruit fly"], {"family": "Drosophilidae", "genus": "Drosophila", "species": "melanogaster"}),
    ("Zebrafish", "zebrafish", "biology", "Danio rerio — a model organism for vertebrate development.",
     [], {"family": "Cyprinidae", "genus": "Danio", "species": "rerio"}),
    ("Nematode C. elegans", "c-elegans", "biology", "Caenorhabditis elegans — a soil nematode; the first animal to have its genome fully sequenced.",
     ["C. elegans"], {"family": "Rhabditidae", "genus": "Caenorhabditis", "species": "elegans"}),
    ("Honeybee", "honeybee", "biology", "Apis mellifera — social bee critical for pollination.",
     ["Apis mellifera"], {"family": "Apidae", "genus": "Apis", "species": "mellifera"}),
    ("Mosquito (Aedes aegypti)", "aedes-aegypti", "biology", "Yellow-fever mosquito; primary vector of dengue, Zika, chikungunya, yellow fever.",
     [], {"family": "Culicidae", "genus": "Aedes", "species": "aegypti"}),
    ("Mosquito (Anopheles gambiae)", "anopheles-gambiae", "biology", "African malaria mosquito; primary vector of Plasmodium falciparum.",
     [], {"family": "Culicidae", "genus": "Anopheles", "species": "gambiae"}),
    ("Elephant (African)", "african-elephant", "biology", "Largest living land animal; two extant species, Loxodonta africana (savanna) and L. cyclotis (forest).",
     [], {"family": "Elephantidae", "genus": "Loxodonta"}),
    ("Whale (blue)", "blue-whale", "biology", "Largest animal ever known — up to 30 m long, 200 tonnes.",
     ["Balaenoptera musculus"], {"family": "Balaenopteridae", "genus": "Balaenoptera", "species": "musculus"}),
    ("Dolphin (bottlenose)", "bottlenose-dolphin", "biology", "Most familiar dolphin species; highly intelligent and playful marine mammal.",
     ["Tursiops truncatus"], {"family": "Delphinidae", "genus": "Tursiops", "species": "truncatus"}),
    ("Octopus", "octopus", "biology", "Highly-intelligent cephalopod with eight arms and remarkable problem-solving ability.",
     [], {"class": "Cephalopoda", "order": "Octopoda"}),
    ("Squid", "squid", "biology", "Cephalopod with eight arms plus two longer tentacles; some deep-sea species reach 13 m.",
     [], {"class": "Cephalopoda", "order": "Teuthida"}),
    ("Coral", "coral", "biology", "Marine invertebrate that builds reef structures from calcium carbonate skeletons.",
     [], {"class": "Anthozoa"}),
    ("Jellyfish", "jellyfish", "biology", "Free-swimming marine invertebrate with an umbrella-shaped bell and trailing tentacles.",
     [], {"phylum": "Cnidaria"}),
    ("Earthworm", "earthworm", "biology", "Terrestrial annelid that aerates and enriches soil.",
     [], {"phylum": "Annelida", "class": "Clitellata"}),
    ("Spider (tarantula)", "tarantula", "biology", "Large hairy arachnid, many species popular in the pet trade.",
     [], {"family": "Theraphosidae"}),
    ("Butterfly (monarch)", "monarch-butterfly", "biology", "North American butterfly known for its multi-generational continental migration.",
     ["Danaus plexippus"], {"family": "Nymphalidae", "genus": "Danaus", "species": "plexippus"}),
    ("Frog (poison dart)", "poison-dart-frog", "biology", "Brightly-colored Central and South American amphibians; some species produce potent skin toxins.",
     [], {"family": "Dendrobatidae"}),
    ("Alligator (American)", "american-alligator", "biology", "Large reptile native to the southeastern United States; conservation success story.",
     [], {"family": "Alligatoridae", "genus": "Alligator", "species": "mississippiensis"}),
    ("Salmon (Atlantic)", "atlantic-salmon", "biology", "Anadromous fish that migrates from ocean to freshwater to spawn.",
     ["Salmo salar"], {"family": "Salmonidae", "genus": "Salmo", "species": "salar"}),
    ("Oak Tree", "oak-tree", "biology", "Any tree of genus Quercus — deciduous or evergreen hardwoods with characteristic lobed leaves and acorns.",
     [], {"family": "Fagaceae", "genus": "Quercus"}),
    ("Pine Tree", "pine-tree", "biology", "Coniferous evergreen of genus Pinus; ~120 species worldwide.",
     [], {"family": "Pinaceae", "genus": "Pinus"}),
    ("Rose", "rose-plant", "biology", "Woody perennial flowering plant of the genus Rosa; family Rosaceae.",
     [], {"family": "Rosaceae", "genus": "Rosa"}),
    ("Wheat", "wheat", "biology", "Cereal grass of genus Triticum; second only to maize in global production.",
     [], {"family": "Poaceae", "genus": "Triticum"}),
    ("Rice", "rice-plant", "biology", "Oryza sativa (Asian rice) — staple food for over half the world's population.",
     [], {"family": "Poaceae", "genus": "Oryza"}),
    ("Corn (Maize)", "corn-maize", "biology", "Zea mays — cereal grain first domesticated in southern Mexico ~10,000 years ago.",
     ["maize"], {"family": "Poaceae", "genus": "Zea", "species": "mays"}),
    ("Sunflower", "sunflower", "biology", "Helianthus annuus — annual plant with distinctive large flower heads.",
     [], {"family": "Asteraceae", "genus": "Helianthus", "species": "annuus"}),
    ("Bacterium (E. coli reference)", "e-coli-reference", "biology", "Escherichia coli — the primary model organism for bacterial genetics.",
     [], {"kingdom": "Bacteria", "genus": "Escherichia", "species": "coli"}),
    ("Trilobite", "trilobite", "biology", "Extinct group of marine arthropods that dominated Cambrian and Ordovician seas.",
     [], {"class": "Trilobita"}),
    ("Dinosaur", "dinosaur", "biology", "Diverse clade of reptiles that dominated terrestrial ecosystems from ~230 to 65 million years ago; birds are their surviving descendants.",
     [], {"clade": "Dinosauria"}),
    ("Tyrannosaurus rex", "t-rex", "biology", "Large theropod dinosaur that lived in North America during the Late Cretaceous.",
     ["T. rex", "T-Rex"], {"clade": "Dinosauria", "genus": "Tyrannosaurus", "species": "rex"}),
    ("Mammoth", "mammoth", "biology", "Extinct genus of elephants of the Pleistocene; the woolly mammoth survived until ~4000 years ago.",
     [], {"family": "Elephantidae", "genus": "Mammuthus"}),
    ("Saber-Toothed Cat", "saber-toothed-cat", "biology", "Any of several extinct groups of large cats with elongated canines — Smilodon fatalis is the most famous.",
     ["Smilodon"], {"family": "Felidae"}),
]

for row in TAXA:
    name, slug, disc, narr, extras, taxon = row
    kind = "taxon"
    status = ":extinct" if slug in ("trilobite", "dinosaur", "t-rex", "mammoth", "saber-toothed-cat") else None
    SCIENCES.append(S(name, disc, kind,
                     id_slug=slug, extras=extras + [name.lower()], narrative=narr,
                     applies=[":biological"],
                     subsumed_by="biological-taxa",
                     taxon=taxon, status=status,
                     provenance=W(name.replace(" ", "_"))))

# ---- DRUG CLASSES + PHARMACOLOGY ----
PHARMA = [
    ("Antibiotic", "antibiotic-class", "A drug class that kills or inhibits bacteria; only effective against bacterial infections."),
    ("Beta-Lactam Antibiotic", "beta-lactam-antibiotic", "Antibiotic containing a beta-lactam ring — includes penicillins and cephalosporins."),
    ("Cephalosporin", "cephalosporin", "Beta-lactam antibiotic class effective against a wide range of bacterial infections."),
    ("Macrolide", "macrolide", "Antibiotic class including erythromycin, azithromycin; blocks bacterial protein synthesis."),
    ("Fluoroquinolone", "fluoroquinolone", "Broad-spectrum antibiotic class including ciprofloxacin and levofloxacin."),
    ("Tetracycline", "tetracycline", "Broad-spectrum antibiotic class; inhibits bacterial protein synthesis."),
    ("Antiviral Drug", "antiviral-drug", "Medication used to treat viral infections — different classes target different viral processes."),
    ("Antifungal Drug", "antifungal-drug", "Medication used to treat fungal infections."),
    ("Antimalarial Drug", "antimalarial-drug", "Medication to prevent or treat malaria — includes chloroquine, artemisinin."),
    ("Vaccine", "vaccine", "A biological preparation providing active acquired immunity to a specific infectious disease."),
    ("mRNA Vaccine", "mrna-vaccine", "Vaccine using synthetic messenger RNA to instruct cells to produce a viral protein triggering immunity."),
    ("Analgesic", "analgesic", "Pain-relieving drug — includes opioids, NSAIDs, and paracetamol."),
    ("Opioid", "opioid-drug", "Class of pain-relieving drugs including morphine, oxycodone, fentanyl; highly addictive."),
    ("NSAID", "nsaid", "Non-steroidal anti-inflammatory drug — includes ibuprofen, naproxen, aspirin."),
    ("Antidepressant", "antidepressant-drug", "Medication used to treat depression and related mood disorders."),
    ("SSRI", "ssri", "Selective serotonin reuptake inhibitor — a class of antidepressants including fluoxetine and sertraline."),
    ("Antipsychotic", "antipsychotic-drug", "Medication used to treat psychosis, primarily schizophrenia and bipolar disorder."),
    ("Anxiolytic", "anxiolytic-drug", "Medication used to reduce anxiety — benzodiazepines are the most familiar class."),
    ("Benzodiazepine", "benzodiazepine", "Class of anxiolytic drugs including diazepam and alprazolam; act on GABA receptors."),
    ("Antihypertensive", "antihypertensive-drug", "Medication used to treat high blood pressure — many classes with different mechanisms."),
    ("Beta Blocker", "beta-blocker", "Antihypertensive class blocking beta-adrenergic receptors — includes propranolol and metoprolol."),
    ("ACE Inhibitor", "ace-inhibitor", "Antihypertensive class inhibiting the angiotensin-converting enzyme."),
    ("Statin", "statin", "Class of drugs lowering blood cholesterol by inhibiting HMG-CoA reductase."),
    ("Diuretic", "diuretic-drug", "Medication increasing urine output; used to treat hypertension and edema."),
    ("Insulin Analog", "insulin-analog", "Chemically-modified insulins used in diabetes management — rapid-acting, long-acting."),
    ("Corticosteroid", "corticosteroid", "Class of steroid hormones and synthetic analogs used as anti-inflammatories and immunosuppressants."),
    ("Chemotherapy Drug", "chemotherapy-drug", "Cytotoxic medication used to treat cancer by killing rapidly-dividing cells."),
    ("Immunotherapy", "immunotherapy-drug", "Cancer treatment that harnesses or modifies the patient's immune system to fight tumor cells."),
    ("Monoclonal Antibody", "monoclonal-antibody", "Laboratory-produced antibody targeting a specific antigen; used therapeutically and diagnostically."),
    ("Anticoagulant", "anticoagulant-drug", "Medication that reduces blood clotting — includes warfarin, heparin, direct oral anticoagulants."),
    ("Antihistamine", "antihistamine-drug", "Medication that blocks histamine receptors, reducing allergic symptoms."),
    ("Bronchodilator", "bronchodilator", "Medication that opens airways by relaxing bronchial smooth muscle; used in asthma and COPD."),
    ("Anticonvulsant", "anticonvulsant", "Medication used to prevent or reduce seizures in epilepsy."),
    ("Anesthetic (general)", "general-anesthetic", "Drug producing loss of consciousness for surgery."),
    ("Anesthetic (local)", "local-anesthetic", "Drug producing loss of sensation in a specific area without affecting consciousness."),
    ("Vasopressor", "vasopressor", "Drug that raises blood pressure by constricting blood vessels; used in shock."),
]

for name, slug, narr in PHARMA:
    SCIENCES.append(S(name, "pharmacology", "framework",
                     id_slug=slug, extras=[name.lower()], narrative=narr,
                     applies=[":medicine"],
                     subsumed_by="pharmacology",
                     provenance=W(name.replace(" ", "_"))))

# ---- Parent taxonomic nodes ----
for name, slug, disc, narr in [
    ("Pathogen Classification", "pathogen-classification", "microbiology", "Organized categorization of disease-causing organisms."),
    ("Biological Taxa", "biological-taxa", "biology", "Named groups of organisms — species, genera, families up through domains."),
    ("Pharmacology", "pharmacology", "pharmacology", "The study of drugs and their effects on living organisms."),
    ("Virology", "virology", "virology", "The study of viruses and virus-like agents."),
    ("Microbiology", "microbiology", "microbiology", "The study of microscopic organisms — bacteria, archaea, protozoa, algae, fungi."),
    ("Immunology", "immunology", "immunology", "The study of the immune system in all organisms."),
]:
    SCIENCES.append(S(name, disc, "classification",
                     id_slug=slug, narrative=narr,
                     subsumed_by="biology" if disc in ("biology", "virology", "microbiology", "immunology") else "medicine",
                     provenance=W(name.replace(" ", "_"))))
