"""Supplementary science nodes to broaden coverage.

More phenomena, more medical, more computing/security, superseded frameworks.
Target ~250 nodes to comfortably clear the 2,000-node graph target.
"""

from _helpers import S


def W(name):
    return [{"source": "wikipedia", "url": f"https://en.wikipedia.org/wiki/{name}"}]


SCIENCES = []

# ---- SUPERSEDED SCIENCE (keep as first-class) ----
SUPERSEDED = [
    ("Phlogiston Theory", "phlogiston-theory", "chemistry", "framework",
     "Discredited 17th-18th century theory that combustion released a hypothetical fire-like element called phlogiston; superseded by Lavoisier's oxygen theory of combustion.",
     "oxygen-theory-of-combustion", ":superseded", (1667, 1783), "stahl-georg-ernst", 1667),
    ("Caloric Theory", "caloric-theory", "physics", "framework",
     "Discredited theory that heat consisted of an invisible fluid called caloric; superseded by the kinetic theory of heat.",
     "kinetic-theory-of-heat", ":superseded", (1783, 1850), "lavoisier-antoine", 1783),
    ("Luminiferous Aether", "luminiferous-aether", "physics", "framework",
     "The hypothetical medium once believed to fill space and carry electromagnetic waves; disproved by the Michelson-Morley experiment.",
     "special-relativity", ":superseded", (1690, 1905), None, 1690),
    ("Geocentric Model", "geocentric-model", "astronomy", "framework",
     "The Ptolemaic view that Earth sat motionless at the center of the universe with all celestial bodies orbiting it; superseded by heliocentrism.",
     "heliocentric-model", ":superseded", (150, 1543), "ptolemy", 150),
    ("Four Humors Theory", "four-humors", "medicine", "framework",
     "Ancient medical theory that health depends on the balance of blood, phlegm, black bile, and yellow bile; superseded by modern physiology.",
     "modern-physiology", ":superseded", (-400, 1858), "hippocrates", -400),
    ("Lamarckian Inheritance", "lamarckian-inheritance", "biology", "framework",
     "Discredited theory that acquired characteristics can be inherited; superseded by Mendelian genetics and natural selection (except in narrow epigenetic senses).",
     "mendelian-inheritance", ":superseded", (1809, 1900), "lamarck-jean-baptiste", 1809),
    ("Steady State Theory", "steady-state-theory", "cosmology", "framework",
     "The cosmological model in which the universe has no beginning or end and continually creates new matter; superseded by Big Bang cosmology after the CMB discovery.",
     "big-bang", ":superseded", (1948, 1965), "hoyle-fred", 1948),
    ("Miasma Theory", "miasma-theory", "medicine", "framework",
     "Pre-germ-theory belief that diseases were caused by 'bad air'; superseded by germ theory after Pasteur and Koch.",
     "germ-theory-of-disease", ":superseded", (-400, 1880), None, -400),
    ("Continental Fixity", "continental-fixity", "geology", "framework",
     "The pre-plate-tectonic assumption that the continents had always been where they are; superseded by plate tectonics.",
     "plate-tectonics", ":superseded", (1600, 1965), None, 1600),
    ("Ptolemaic Epicycles", "ptolemaic-epicycles", "astronomy", "framework",
     "Geometric device in the geocentric model where planets moved on small circles (epicycles) whose centers moved on larger circles (deferents); superseded by elliptical orbits.",
     "keplers-laws", ":superseded", (150, 1609), "ptolemy", 150),
    ("Oxygen Theory of Combustion", "oxygen-theory-of-combustion", "chemistry", "principle",
     "Lavoisier's insight that combustion is a chemical reaction with oxygen — the theory that replaced phlogiston.",
     None, ":established", None, "lavoisier-antoine", 1777),
    ("Kinetic Theory of Heat", "kinetic-theory-of-heat", "physics", "principle",
     "The insight that heat is the kinetic energy of molecular motion — replaced caloric theory.",
     None, ":established", None, "clausius-rudolf", 1857),
    ("Heliocentric Model", "heliocentric-model", "astronomy", "framework",
     "Copernican model with the Sun at the center of the solar system — replaced the geocentric model.",
     None, ":established", None, "copernicus-nicolaus", 1543),
    ("Germ Theory of Disease", "germ-theory-of-disease", "medicine", "principle",
     "The scientific theory that many diseases are caused by microorganisms — replaced miasma theory.",
     None, ":established", None, "pasteur-louis", 1861),
]
for row in SUPERSEDED:
    name, slug, disc, kind, narr, superseded_by, status, era, disc_who, year = row
    SCIENCES.append(S(name, disc, kind,
                     id_slug=slug, extras=[name.lower()],
                     narrative=narr, status=status,
                     superseded_by=superseded_by,
                     era={"year-from": era[0], "year-to": era[1]} if era else None,
                     described_by=[f"person-{disc_who}"] if disc_who else None,
                     described_year=year,
                     applies=[":historical-only"] if status == ":superseded" else None,
                     subsumed_by=disc + "-history" if status == ":superseded" else disc,
                     provenance=W(name.replace(" ", "_"))))

# ---- MORE PHYSICS PHENOMENA ----
EXTRA_PHYS = [
    ("Doppler Effect", "doppler-effect", "physics", "The change in frequency or wavelength of a wave in relation to an observer moving relative to the source.",
     "An ambulance siren sounds higher-pitched as it approaches you and lower as it recedes."),
    ("Cherenkov Radiation", "cherenkov-radiation", "physics", "Electromagnetic radiation emitted when a charged particle travels through a dielectric medium faster than the phase velocity of light in that medium.",
     "The blue glow around underwater nuclear reactor cores."),
    ("Superconductivity", "superconductivity", "physics", "The phenomenon where certain materials conduct electricity with zero resistance below a critical temperature.",
     "MRI machines use superconducting magnets cooled with liquid helium."),
    ("Superfluidity", "superfluidity", "physics", "The property of certain fluids to flow without viscosity when cooled below a characteristic temperature.",
     "Superfluid helium climbs the walls of its container."),
    ("Bose-Einstein Condensate", "bec", "physics", "A state of matter in which bosons cooled to near absolute zero occupy the same quantum ground state.", None),
    ("Fermi Degenerate Matter", "degenerate-matter", "physics", "State of matter with density so high that pressure comes primarily from the Pauli exclusion principle — as in white dwarfs and neutron stars.", None),
    ("Plasma (state)", "plasma-state", "physics", "The fourth state of matter — an ionized gas where electrons are separated from nuclei; the state of most visible matter in the universe.",
     "The sun and lightning are plasmas."),
    ("Rayleigh Scattering", "rayleigh-scattering", "physics", "Elastic scattering of light by particles much smaller than its wavelength; explains why the sky is blue.",
     "The sky is blue because air molecules scatter blue light more than red."),
    ("Mie Scattering", "mie-scattering", "physics", "Scattering of light by particles comparable in size to its wavelength; explains white color of clouds and fog.", None),
    ("Total Internal Reflection", "total-internal-reflection", "physics", "The reflection of light or other waves back into a denser medium when they hit the boundary with a less dense medium at greater than the critical angle.",
     "Optical fibers work by total internal reflection along their length."),
    ("Snell's Law", "snells-law", "physics", "sin θ₁ / sin θ₂ = n₂ / n₁ — the law of refraction relating angles of incidence and refraction to refractive indices.", None),
    ("Bernoulli's Principle", "bernoullis-principle", "physics", "Along a streamline in an inviscid flow, an increase in speed corresponds to a decrease in pressure.",
     "An airplane wing generates lift partly because air flows faster above than below."),
    ("Faraday's Law", "faradays-law", "physics", "A changing magnetic flux through a circuit induces an electromotive force.",
     "Every electric generator works by Faraday's law."),
    ("Lenz's Law", "lenz-law", "physics", "The induced current in a circuit opposes the change in magnetic flux that produced it — a consequence of energy conservation.", None),
    ("Ampère's Law", "amperes-law", "physics", "Relates the integrated magnetic field around a closed loop to the electric current passing through the loop.", None),
    ("Gauss's Law (electric)", "gauss-law-electric", "physics", "The electric flux through any closed surface equals the enclosed charge divided by ε₀.", None),
    ("Gauss's Law (magnetic)", "gauss-law-magnetic", "physics", "The magnetic flux through any closed surface is zero — there are no magnetic monopoles.", None),
    ("Poynting Vector", "poynting-vector", "physics", "S = E × H / μ₀ — the directional energy flux of an electromagnetic field.", None),
    ("Uncertainty Relation (energy-time)", "energy-time-uncertainty", "physics", "ΔE·Δt ≥ ℏ/2 — a form of the uncertainty principle relating energy and time.", None),
    ("Bragg's Law", "braggs-law", "physics", "nλ = 2d·sin θ — the condition for constructive interference of X-rays scattered by crystal planes.", None),
    ("Meissner Effect", "meissner-effect", "physics", "A superconductor expels magnetic fields from its interior when transitioning to the superconducting state — the basis of magnetic levitation demonstrations.", None),
    ("Josephson Effect", "josephson-effect", "physics", "The phenomenon of supercurrent tunneling through a thin insulating barrier between two superconductors — used in extremely sensitive magnetometers.", None),
    ("Hall Effect", "hall-effect", "physics", "The production of a voltage difference across an electrical conductor transverse to an electric current and an applied magnetic field.", None),
    ("Photoelectric Effect", "photoelectric-effect", "physics", "The emission of electrons from a material when light of sufficient frequency shines on it; explaining it earned Einstein the 1921 Nobel.", None),
    ("Compton Effect", "compton-effect", "physics", "The shift in wavelength of X-rays scattered by electrons — evidence for the particle nature of light.", None),
    ("Zeeman Effect", "zeeman-effect", "physics", "The splitting of a spectral line into several components in the presence of a magnetic field.", None),
    ("Stark Effect", "stark-effect", "physics", "The shifting and splitting of spectral lines in the presence of an electric field — the electric analog of the Zeeman effect.", None),
    ("Piezoelectric Effect", "piezoelectric-effect", "physics", "The accumulation of electric charge in certain solid materials in response to applied mechanical stress; used in quartz watches and lighters.",
     "A gas grill igniter uses a piezoelectric crystal to make a spark."),
    ("Triboelectric Effect", "triboelectric-effect", "physics", "The generation of static electric charge by contact and separation of materials.",
     "A balloon rubbed on hair picks up charge by the triboelectric effect."),
    ("Kirchhoff's Circuit Laws", "kirchhoff-circuit-laws", "physics", "Two laws for analyzing electrical circuits: current conservation at nodes and voltage sum around loops.", None),
]
for row in EXTRA_PHYS:
    name, slug, disc, narr, everyday = row
    SCIENCES.append(S(name, disc, "phenomenon" if "effect" in slug or "scattering" in slug or slug in ("superconductivity", "superfluidity", "plasma-state", "total-internal-reflection") else ("law" if "law" in slug else "principle"),
                     id_slug=slug, extras=[name.lower()],
                     narrative=narr, everyday=everyday,
                     applies=[":subatomic" if slug in ("superconductivity", "superfluidity", "degenerate-matter", "bec") else ":everyday"],
                     subsumed_by="physics",
                     provenance=W(name.replace(" ", "_").replace("'", ""))))

# ---- MORE CHEMISTRY: REACTIONS + CONCEPTS ----
CHEM_REACT = [
    ("Combustion", "combustion", "chemistry", "reaction",
     "The high-temperature exothermic redox reaction between a fuel and an oxidant, typically producing heat, light, and oxidized products.",
     "A candle flame is combustion of paraffin wax."),
    ("Oxidation-Reduction", "redox-reaction", "chemistry", "reaction",
     "A chemical reaction involving the transfer of electrons between two species — one oxidized, the other reduced.",
     "Rusting is the oxidation of iron by oxygen."),
    ("Neutralization Reaction", "neutralization-reaction", "chemistry", "reaction",
     "A chemical reaction between an acid and a base yielding water and a salt.",
     "Antacids neutralize excess stomach acid."),
    ("Precipitation Reaction", "precipitation-reaction", "chemistry", "reaction",
     "A reaction where two soluble salts form an insoluble product that falls out of solution.", None),
    ("Hydrolysis", "hydrolysis", "chemistry", "reaction",
     "The chemical breakdown of a compound due to reaction with water.", None),
    ("Condensation Reaction", "condensation-reaction", "chemistry", "reaction",
     "A reaction in which two molecules combine to form a larger molecule with elimination of a small molecule such as water.", None),
    ("Polymerization", "polymerization", "chemistry", "reaction",
     "The process of combining many small monomer molecules into a chain or network — the basis of all synthetic plastics.",
     "PET plastic bottles are made by polymerization of terephthalate and ethylene glycol."),
    ("Esterification", "esterification", "chemistry", "reaction",
     "The reaction of a carboxylic acid with an alcohol to form an ester and water — how many fragrances are made.", None),
    ("Saponification", "saponification", "chemistry", "reaction",
     "The hydrolysis of triglycerides with a strong base to produce soap and glycerol.",
     "Making bar soap is saponification of fats with lye."),
    ("Fermentation (chemistry)", "fermentation-chem", "chemistry", "reaction",
     "Metabolic process converting sugar to acids, gases, or alcohol in the absence of oxygen — beer, wine, yogurt, sourdough all rely on it.", None),
    ("Endothermic Reaction", "endothermic-reaction", "chemistry", "reaction",
     "A chemical reaction that absorbs energy from surroundings, typically as heat.", None),
    ("Exothermic Reaction", "exothermic-reaction", "chemistry", "reaction",
     "A chemical reaction that releases energy to surroundings, typically as heat.", None),
    ("Catalysis", "catalysis", "chemistry", "phenomenon",
     "The acceleration of a chemical reaction by a substance that is not consumed in the reaction.", None),
    ("Enzyme Catalysis", "enzyme-catalysis", "biochemistry", "phenomenon",
     "The catalysis of chemical reactions by protein or RNA enzymes in living organisms.", None),
    ("Le Chatelier's Principle", "le-chateliers-principle", "chemistry", "principle",
     "A system at equilibrium disturbed by a change in conditions shifts to counteract the change.", None),
    ("pH Scale", "ph-scale", "chemistry", "measurement",
     "A logarithmic scale of hydrogen-ion activity — acids are low pH (below 7), bases high pH (above 7), pure water is neutral at 7.",
     "Lemon juice has pH ~2 (acidic); household ammonia ~11 (basic)."),
    ("Molarity", "molarity", "chemistry", "quantity",
     "The concentration of a substance in solution measured in moles of solute per liter of solution.", None),
    ("Mole (chemistry)", "mole-chemistry", "chemistry", "unit",
     "The SI base unit of amount of substance — 6.02214076×10²³ elementary entities (Avogadro's number).", None),
    ("Chemical Equilibrium", "chemical-equilibrium", "chemistry", "phenomenon",
     "The state in a reversible chemical reaction where the rates of the forward and reverse reactions are equal.", None),
    ("Activation Energy", "activation-energy", "chemistry", "quantity",
     "The minimum energy needed to initiate a chemical reaction.", None),
]
for row in CHEM_REACT:
    name, slug, disc, kind, narr, everyday = row
    SCIENCES.append(S(name, disc, kind,
                     id_slug=slug, extras=[name.lower()],
                     narrative=narr, everyday=everyday,
                     applies=[":materials", ":everyday"],
                     subsumed_by="chemistry",
                     provenance=W(name.replace(" ", "_").replace("'", ""))))

# ---- ADDITIONAL BIOLOGY (traits, senses, systems) ----
EXTRA_BIO = [
    ("Genome-Wide Association Study", "gwas", "genetics", "method",
     "A research approach identifying genetic variants across many genomes associated with a trait or disease.", None),
    ("Gene Regulation", "gene-regulation", "molecular-biology", "process",
     "The control of when, how much, and where a gene is expressed.", None),
    ("Signal Transduction", "signal-transduction", "biology", "process",
     "The cascade of molecular events by which a cell converts an external signal into a functional response.", None),
    ("Circulatory Pressure", "blood-pressure", "physiology", "quantity",
     "The pressure exerted by circulating blood on the walls of blood vessels; measured as systolic over diastolic.", None),
    ("Hormonal Feedback", "hormonal-feedback", "physiology", "process",
     "The regulation of hormone secretion by the effects of the hormone itself or downstream products, typically negative feedback.", None),
    ("Thermoregulation", "thermoregulation", "physiology", "process",
     "The maintenance of a stable body temperature independent of surrounding conditions.",
     "Sweating cools the body by evaporation."),
    ("Osmoregulation", "osmoregulation", "physiology", "process",
     "The active regulation of osmotic pressure of an organism's body fluids.", None),
    ("Excretion", "excretion", "physiology", "process",
     "The process by which waste products of metabolism are eliminated from the body.", None),
    ("Reproduction (biology)", "reproduction", "biology", "process",
     "The biological process by which new individual organisms are produced from their parents — sexual or asexual.", None),
    ("Vision (physiology)", "vision", "physiology", "process",
     "The sensory perception of light and pattern by the eye and interpretation by the visual cortex.", None),
    ("Hearing (audition)", "hearing", "physiology", "process",
     "The sensory perception of sound by the ear and interpretation by the auditory cortex.", None),
    ("Olfaction", "olfaction", "physiology", "process",
     "The sense of smell — chemical detection of airborne molecules by receptors in the nasal epithelium.", None),
    ("Gustation", "gustation", "physiology", "process",
     "The sense of taste — chemical detection of dissolved molecules by taste buds on the tongue.", None),
    ("Somatosensation", "somatosensation", "physiology", "process",
     "The body's sense of touch, temperature, pain, and proprioception.", None),
    ("Proprioception", "proprioception", "physiology", "process",
     "The sense of the position, movement, and equilibrium of parts of the body.", None),
    ("Sneezing Reflex", "sneezing-reflex", "physiology", "process",
     "The forceful expulsion of air from the lungs through the nose and mouth, usually triggered by irritation of the nasal mucosa.", None),
    ("Cough Reflex", "cough-reflex", "physiology", "process",
     "The rapid expulsion of air from the lungs to clear irritants from the airway.", None),
    ("Vomiting Reflex", "vomiting-reflex", "physiology", "process",
     "The involuntary expulsion of gastric contents through the mouth, coordinated by the brainstem vomiting center.", None),
    ("Hiccup", "hiccup", "physiology", "phenomenon",
     "An involuntary contraction of the diaphragm followed by sudden closure of the vocal folds.", None),
    ("Yawn", "yawn", "physiology", "phenomenon",
     "An involuntary reflex of simultaneous inhalation of air and stretching, often associated with tiredness or boredom.", None),
]
for row in EXTRA_BIO:
    name, slug, disc, kind, narr, everyday = row
    SCIENCES.append(S(name, disc, kind,
                     id_slug=slug, extras=[name.lower()],
                     narrative=narr, everyday=everyday,
                     applies=[":biological", ":everyday"],
                     subsumed_by=disc,
                     provenance=W(name.replace(" ", "_"))))

# ---- ADDITIONAL COMPUTING/SECURITY ----
EXTRA_CS = [
    ("Cache Line", "cache-line", "computing", "abstraction",
     "The unit of data transfer between main memory and cache — typically 64 bytes on modern CPUs.", None),
    ("Instruction Set Architecture", "isa", "computing", "abstraction",
     "The abstract model of a computer defining the supported data types, registers, hardware operations, and instructions.",
     ["ISA"]),
    ("RISC", "risc", "computing", "architecture",
     "Reduced Instruction Set Computer — an architecture with a small set of simple instructions optimized for pipelining.", None),
    ("CISC", "cisc", "computing", "architecture",
     "Complex Instruction Set Computer — an architecture with many multi-step instructions.", None),
    ("Pipeline (CPU)", "cpu-pipeline", "computing", "architecture",
     "A processing technique that overlaps the execution of multiple instructions.", None),
    ("Superscalar Execution", "superscalar", "computing", "architecture",
     "A processor architecture that executes more than one instruction per clock cycle by dispatching to multiple execution units.", None),
    ("Branch Predictor", "branch-predictor", "computing", "architecture",
     "A digital circuit that guesses which way a branch will go before it is known, keeping the pipeline full.", None),
    ("Speculative Execution", "speculative-execution", "computing", "architecture",
     "The processor optimization of doing work that might not be needed to keep the pipeline productive; central to the Spectre/Meltdown vulnerability class.", None),
    ("Interrupt", "interrupt", "computing", "abstraction",
     "A signal to the processor indicating an event that requires immediate attention, causing suspension of the current program.", None),
    ("Direct Memory Access", "dma", "computing", "abstraction",
     "A feature allowing hardware devices to access main memory independently of the CPU.", None),
    ("Buffer Overflow", "buffer-overflow", "computing", "phenomenon",
     "A vulnerability where a program writes data beyond the boundary of an allocated buffer, corrupting adjacent memory.", None),
    ("SQL Injection", "sql-injection", "computing", "phenomenon",
     "A code injection technique exploiting a security vulnerability in an application's SQL layer.", None),
    ("Cross-Site Scripting", "xss", "computing", "phenomenon",
     "A web-security vulnerability enabling injection of client-side scripts into pages viewed by other users.", None),
    ("Denial of Service Attack", "dos-attack", "computing", "phenomenon",
     "A cyber-attack rendering a machine or network resource unavailable to intended users.", None),
    ("Distributed Denial of Service", "ddos-attack", "computing", "phenomenon",
     "A denial-of-service attack in which the traffic flooding the target originates from many different sources.", None),
    ("Phishing", "phishing", "computing", "phenomenon",
     "A social-engineering attack tricking users into revealing credentials by impersonating a trusted entity.", None),
    ("Malware", "malware", "computing", "phenomenon",
     "Software intentionally designed to cause damage to a computer, server, or network — viruses, worms, trojans, ransomware, spyware.", None),
    ("Ransomware", "ransomware", "computing", "phenomenon",
     "A type of malware that threatens to publish the victim's data or perpetually block access to it unless a ransom is paid.", None),
    ("Zero-Day Vulnerability", "zero-day", "computing", "phenomenon",
     "A software security flaw unknown to the vendor and unpatched at the time of exploitation.", None),
    ("Sandbox", "sandbox", "computing", "abstraction",
     "A security mechanism that separates running programs to limit their access to system resources.", None),
    ("Authentication", "authentication", "computing", "abstraction",
     "The process of verifying that someone or something is who or what it claims to be.", None),
    ("Authorization", "authorization", "computing", "abstraction",
     "The process of determining what an authenticated identity is allowed to do.", None),
    ("Two-Factor Authentication", "2fa", "computing", "abstraction",
     "An authentication scheme requiring two independent pieces of evidence — something you know plus something you have.", None),
    ("Hashing (crypto)", "cryptographic-hash", "computing", "algorithm",
     "A one-way function producing a fixed-size digest of arbitrary-sized input; used for integrity checks and password storage.", None),
    ("Salt (cryptography)", "cryptographic-salt", "computing", "abstraction",
     "Random data added to a password before hashing to defeat rainbow-table attacks.", None),
    ("Digital Signature", "digital-signature", "computing", "algorithm",
     "A cryptographic scheme providing authentication, integrity, and non-repudiation for a digital message.", None),
    ("Certificate Authority", "certificate-authority", "computing", "abstraction",
     "An entity that issues digital certificates binding public keys to identities.", None),
    ("Version Control", "version-control", "computing", "framework",
     "A system that records changes to a file or set of files over time, letting you recall earlier versions.", None),
    ("Distributed Version Control", "distributed-version-control", "computing", "framework",
     "A version-control approach where every clone is a full copy of the repository with complete history.", None),
    ("Continuous Integration", "continuous-integration", "computing", "framework",
     "A software development practice where developers frequently merge their changes into a shared repository, verified by automated build and tests.", None),
    ("Test-Driven Development", "tdd", "computing", "framework",
     "A software development process relying on the repetition of a very short development cycle: write a test, make it pass, refactor.", None),
    ("Agile Software Development", "agile", "computing", "framework",
     "An iterative, incremental approach to software development emphasizing collaboration and adaptation over big up-front planning.", None),
    ("Design Pattern", "design-pattern", "computing", "abstraction",
     "A reusable solution to a commonly-occurring problem within a given context in software design.", None),
    ("Observer Pattern", "observer-pattern", "computing", "abstraction",
     "A design pattern where an object maintains a list of dependents and notifies them of state changes.", None),
    ("Factory Pattern", "factory-pattern", "computing", "abstraction",
     "A design pattern that provides an interface for creating objects without specifying their concrete classes.", None),
    ("Singleton Pattern", "singleton-pattern", "computing", "abstraction",
     "A design pattern that restricts the instantiation of a class to one single instance.", None),
    ("MVC", "mvc", "computing", "architecture",
     "Model-View-Controller — a software design pattern separating an application into three interconnected components.", None),
    ("Event Loop", "event-loop", "computing", "architecture",
     "A programming construct that waits for and dispatches events or messages in a program.", None),
    ("Middleware", "middleware", "computing", "abstraction",
     "Software glue between an operating system or database and applications, especially on a network.", None),
    ("API", "api", "computing", "abstraction",
     "Application Programming Interface — a set of definitions and protocols for building and integrating software.", None),
    ("Webhook", "webhook", "computing", "abstraction",
     "An HTTP callback triggered by an event, allowing web applications to notify each other of updates in near-real time.", None),
    ("Rate Limiting", "rate-limiting", "computing", "abstraction",
     "A strategy for limiting network traffic to protect a service from abuse and manage resource use.", None),
    ("Circuit Breaker Pattern", "circuit-breaker-pattern", "computing", "architecture",
     "A design pattern that stops the flow of requests to a failing service to give it time to recover.", None),
    ("Backpressure", "backpressure", "computing", "abstraction",
     "The signaling mechanism whereby a slow consumer tells fast producers to slow down.", None),
    ("Idempotency", "idempotency", "computing", "principle",
     "A property of operations where performing them multiple times has the same effect as performing them once.", None),
]
for row in EXTRA_CS:
    name, slug, disc, kind, narr, everyday = row
    SCIENCES.append(S(name, disc, kind,
                     id_slug=slug, extras=[name.lower()] + (everyday if isinstance(everyday, list) else []),
                     narrative=narr,
                     applies=[":computational"],
                     subsumed_by="computing",
                     provenance=W(name.replace(" ", "_").replace("(crypto)", "").strip())))

# ---- MORE DISEASES + MEDICAL CONCEPTS ----
EXTRA_MED = [
    ("Anaphylactic Shock", "anaphylactic-shock", "Life-threatening systemic allergic reaction with airway compromise and cardiovascular collapse.", "ICD-11 4A84", "D000707"),
    ("Shock (medical)", "medical-shock", "A life-threatening condition of inadequate tissue perfusion; hypovolemic, cardiogenic, distributive, obstructive.", "ICD-11 MG44", "D012769"),
    ("Chronic Fatigue Syndrome", "cfs", "A long-term illness characterized by extreme fatigue not relieved by rest, cognitive impairment, and post-exertional malaise.", "ICD-11 8E49", "D015673"),
    ("Fibromyalgia", "fibromyalgia", "A syndrome of widespread musculoskeletal pain accompanied by fatigue, sleep, memory, and mood issues.", "ICD-11 MG30.01", "D005356"),
    ("Endometriosis", "endometriosis", "A disorder in which tissue resembling the uterine lining grows outside the uterus, often causing pain and infertility.", "ICD-11 GA10", "D004715"),
    ("Polycystic Ovary Syndrome", "pcos", "A hormonal disorder common among women of reproductive age, with enlarged ovaries and small cysts.", "ICD-11 5A80.1", "D011085"),
    ("Anorexia Nervosa", "anorexia-nervosa", "An eating disorder characterized by restricted food intake, intense fear of weight gain, and distorted body image.", "ICD-11 6B80", "D000856"),
    ("Bulimia Nervosa", "bulimia-nervosa", "An eating disorder characterized by binge eating followed by compensatory behaviors such as vomiting or fasting.", "ICD-11 6B81", "D052018"),
    ("Binge Eating Disorder", "binge-eating-disorder", "An eating disorder characterized by recurrent episodes of eating large amounts of food, feeling out of control.", "ICD-11 6B82", "D056912"),
    ("Chronic Pain", "chronic-pain", "Persistent pain lasting beyond the normal course of an acute illness or injury, typically defined as >3 months.", "ICD-11 MG30", "D059350"),
    ("Insomnia", "insomnia", "A sleep disorder marked by persistent difficulty falling or staying asleep.", "ICD-11 7A00", "D007319"),
    ("Sleep Apnea", "sleep-apnea", "A sleep disorder in which breathing repeatedly stops and starts.", "ICD-11 7A41", "D012891"),
    ("Restless Legs Syndrome", "rls", "A condition causing uncomfortable sensations in the legs and an irresistible urge to move them, especially at rest.", "ICD-11 8A05", "D012148"),
    ("Narcolepsy", "narcolepsy", "A chronic sleep disorder characterized by overwhelming daytime drowsiness and sudden attacks of sleep.", "ICD-11 7A20", "D009290"),
    ("Autism (Rett Syndrome)", "rett-syndrome", "A rare genetic neurological disorder that occurs almost exclusively in girls and leads to severe cognitive and physical impairments.", "ICD-11 LD90.4", "D015518"),
    ("Fragile X Syndrome", "fragile-x-syndrome", "A genetic condition causing intellectual disability, from a mutation in the FMR1 gene on the X chromosome.", "ICD-11 LD55", "D005600"),
    ("Duchenne Muscular Dystrophy", "dmd", "A severe X-linked muscular dystrophy caused by dystrophin gene mutations.", "ICD-11 8C70.0", "D020388"),
    ("Huntington's Disease", "huntingtons-disease", "A hereditary neurodegenerative disease from a CAG repeat expansion in the HTT gene.", "ICD-11 8A01.1", "D006816"),
    ("Marfan Syndrome", "marfan-syndrome", "A genetic disorder of connective tissue affecting the skeletal, cardiovascular, and ocular systems.", "ICD-11 LD28.0", "D008382"),
    ("Ehlers-Danlos Syndrome", "eds", "A group of genetic connective-tissue disorders characterized by joint hypermobility and skin extensibility.", "ICD-11 LD28.1", "D004535"),
    ("Cerebral Palsy", "cerebral-palsy", "A group of permanent movement disorders appearing in early childhood from injury to the developing brain.", "ICD-11 8D20", "D002547"),
    ("Spina Bifida", "spina-bifida", "A birth defect where the spine and spinal cord do not form properly.", "ICD-11 LA02", "D016135"),
    ("Cleft Lip and Palate", "cleft-lip-palate", "A birth defect where the tissue forming the lip or palate does not fully join before birth.", "ICD-11 LA43", "D002971"),
    ("Congenital Heart Defect", "chd-congenital", "A structural heart abnormality present at birth.", "ICD-11 LA80-LA88", "D006330"),
    ("Anemia (aplastic)", "aplastic-anemia", "Failure of the bone marrow to produce enough blood cells.", "ICD-11 3A70", "D000741"),
    ("Thalassemia", "thalassemia", "Inherited blood disorder causing reduced hemoglobin production.", "ICD-11 3A50", "D013789"),
    ("Deep Vein Thrombosis", "dvt", "A blood clot in a deep vein, usually of the leg — can embolize to the lungs.", "ICD-11 BD70", "D020246"),
    ("Pulmonary Embolism", "pulmonary-embolism", "Blockage of an artery in the lungs, usually by a blood clot that traveled from the legs.", "ICD-11 BB00", "D011655"),
    ("Aortic Aneurysm", "aortic-aneurysm", "Abnormal bulging of the aorta that can rupture catastrophically.", "ICD-11 BD50", "D001014"),
    ("Atrial Fibrillation", "atrial-fibrillation", "The most common cardiac arrhythmia — irregular and often rapid heart rate raising stroke risk.", "ICD-11 BC81.3", "D001281"),
    ("Heart Failure", "heart-failure", "A syndrome in which the heart is unable to pump enough blood to meet the body's needs.", "ICD-11 BD10", "D006333"),
    ("Cardiomyopathy", "cardiomyopathy", "Disease of the heart muscle that makes it harder for the heart to pump blood.", "ICD-11 BC43", "D009202"),
    ("Endocarditis", "endocarditis", "Inflammation of the inner lining of the heart, usually from infection.", "ICD-11 BB40", "D004696"),
]
for row in EXTRA_MED:
    name, slug, narr, icd, mesh = row
    SCIENCES.append(S(name, "medicine", "disease",
                     id_slug=slug, extras=[name.lower()],
                     narrative=narr, icd=icd, mesh=mesh,
                     subsumed_by="disease-classification",
                     provenance=W(name.replace(" ", "_").replace("(", "").replace(")", ""))))

# ---- LAW OF SCIENCE PARENTS ----
for name, slug in [
    ("Physics", "physics"),
    ("Chemistry", "chemistry"),
    ("Biology", "biology"),
    ("Astronomy (root)", "astronomy"),
    ("Medicine", "medicine"),
    ("Computing (root)", "computing"),
    ("Science", "science"),
    ("Chemistry (history)", "chemistry-history"),
    ("Physics (history)", "physics-history"),
    ("Astronomy (history)", "astronomy-history"),
    ("Biology (history)", "biology-history"),
    ("Medicine (history)", "medicine-history"),
    ("Geology (history)", "geology-history"),
    ("Cosmology (history)", "cosmology-history"),
]:
    disc = "physics" if slug in ("physics", "physics-history") else \
           "chemistry" if slug in ("chemistry", "chemistry-history") else \
           "biology" if slug in ("biology", "biology-history") else \
           "astronomy" if slug in ("astronomy", "astronomy-history") else \
           "medicine" if slug in ("medicine", "medicine-history") else \
           "computing" if slug in ("computing",) else \
           "geology" if slug == "geology-history" else \
           "cosmology" if slug == "cosmology-history" else \
           "cross-discipline"
    SCIENCES.append(S(name.replace(" (root)", "").replace(" (history)", " — Superseded"),
                     disc, "classification",
                     id_slug=slug,
                     narrative=f"Root classification node for {name}.",
                     provenance=W(name.split(" (")[0].replace(" ", "_"))))
