"""Body parts — human + general vertebrate + insect + plant + tree body parts.
Target: ~300 nodes. Faceted with :has-part / :part-of / :used-for.
"""

from _helpers import node, wikidata, wordnet, authored

# ---------------------------------------------------------------------------
# HUMAN / VERTEBRATE BODY PARTS
# ---------------------------------------------------------------------------

HUMAN = [
    # Head + face
    ("head", "the whole", ["skull"], ["face", "scalp", "hair", "brain-container"],
        ["cognition", "sensing"], ["cap", "hat", "helmet"], "Q23906"),
    ("skull", "head", None, ["forehead", "temple", "occipital-bone"],
        ["brain-protection"], None, "Q41500"),
    ("face", "head", ["skull"], ["eye", "nose", "mouth", "cheek", "chin",
        "forehead", "eyebrow", "eyelash", "lip", "jaw"],
        ["expression", "identity"], None, "Q37017"),
    ("forehead", "face", None, None, None, None, "Q216862"),
    ("temple", "head", None, None, ["temple-massage"], None, "Q9605009"),
    ("scalp", "head", None, ["hair"], None, None, "Q211457"),
    ("hair", "scalp", None, None, ["warmth", "identity"],
        ["hat", "headband", "hair-clip"], "Q28472"),
    ("eyebrow", "face", None, None, ["expression"], None, "Q52943"),
    ("eyelash", "eye", None, None, ["dust-protection"], None, "Q188673"),
    ("eye", "face", ["skull"], ["pupil", "iris", "cornea", "eyelid",
        "retina", "lens", "sclera"],
        ["seeing"], ["glasses", "eye-patch", "goggles"], "Q7364"),
    ("pupil", "eye", None, None, ["light-admission"], None, "Q79899"),
    ("iris", "eye", None, None, ["color", "aperture-control"], None, "Q188803"),
    ("cornea", "eye", None, None, ["light-refraction"], None, "Q191159"),
    ("eyelid", "eye", None, ["eyelash"], ["eye-protection", "blinking"], None, "Q147144"),
    ("retina", "eye", None, None, ["light-sensing"], None, "Q173417"),
    ("lens", "eye", None, None, ["focusing"], None, "Q49080"),
    ("sclera", "eye", None, None, ["eye-structure"], None, "Q194192"),
    ("nose", "face", None, ["nostril", "septum", "bridge-of-nose"],
        ["smell", "breathing"], ["face-mask"], "Q7363"),
    ("nostril", "nose", None, None, ["breathing"], None, "Q1077805"),
    ("mouth", "face", None, ["lip", "tongue", "teeth", "palate", "gum"],
        ["eating", "speaking", "breathing"], ["face-mask", "lipstick"], "Q9635"),
    ("lip", "mouth", None, None, ["speaking", "kissing", "sealing-mouth"],
        ["lipstick", "lip-balm"], "Q47217"),
    ("tongue", "mouth", None, ["taste-bud"], ["taste", "speech", "chewing"],
        None, "Q9614"),
    ("taste-bud", "tongue", None, None, ["taste-sensing"], None, "Q191518"),
    ("teeth", "mouth", None, ["incisor", "canine", "molar", "premolar"],
        ["chewing", "biting", "speech"], ["braces", "toothbrush"], "Q40984"),
    ("tooth", "mouth", None, None, ["chewing"], None, "Q11386"),
    ("incisor", "teeth", None, None, ["cutting"], None, "Q622441"),
    ("canine-tooth", "teeth", None, None, ["tearing"], None, "Q193338"),
    ("molar", "teeth", None, None, ["grinding"], None, "Q191826"),
    ("premolar", "teeth", None, None, ["grinding"], None, "Q1146152"),
    ("gum", "mouth", None, None, ["tooth-support"], None, "Q186946"),
    ("palate", "mouth", None, None, ["mouth-roof"], None, "Q193083"),
    ("cheek", "face", None, None, ["expression"], None, "Q147990"),
    ("chin", "face", None, None, None, None, "Q47488"),
    ("jaw", "face", None, ["jawbone", "mandible"], ["chewing", "speaking"], None, "Q193514"),
    ("mandible", "jaw", None, None, ["chewing"], None, "Q205347"),
    ("ear", "head", None, ["earlobe", "eardrum", "outer-ear", "inner-ear", "auricle"],
        ["hearing", "balance"], ["earring", "headphone", "hearing-aid"], "Q7362"),
    ("earlobe", "ear", None, None, None, ["earring"], "Q1075293"),
    ("eardrum", "ear", None, None, ["hearing"], None, "Q193472"),
    ("outer-ear", "ear", None, ["earlobe", "auricle"], ["hearing"], None, "Q189773"),
    ("inner-ear", "ear", None, ["cochlea"], ["hearing", "balance"], None, "Q193291"),
    ("auricle", "ear", None, None, ["sound-collection"], None, "Q80063"),
    ("cochlea", "inner-ear", None, None, ["hearing-transduction"], None, "Q188725"),

    # Neck + torso
    ("neck", "the whole", None, ["throat", "nape"],
        ["head-support", "swallowing"], ["scarf", "necklace"], "Q7386"),
    ("throat", "neck", None, ["larynx", "pharynx", "vocal-cords"],
        ["swallowing", "breathing", "speaking"], None, "Q9635"),
    ("nape", "neck", None, None, None, None, "Q1074386"),
    ("larynx", "throat", None, ["vocal-cords"], ["voice-production"], None, "Q42237"),
    ("pharynx", "throat", None, None, ["swallowing"], None, "Q131018"),
    ("vocal-cords", "larynx", None, None, ["speech"], None, "Q220487"),
    ("shoulder", "torso", None, ["shoulder-blade", "collarbone"],
        ["arm-articulation"], ["shirt", "epaulette"], "Q4837"),
    ("shoulder-blade", "shoulder", None, None, ["arm-anchor"], None, "Q173036"),
    ("collarbone", "shoulder", None, None, ["shoulder-frame"], None, "Q131630"),
    ("torso", "the whole", ["ribcage", "spine"], ["chest", "back", "abdomen", "waist"],
        ["organ-protection"], ["shirt", "jacket"], "Q118863"),
    ("chest", "torso", ["ribcage"], ["breast", "sternum"],
        ["breathing", "heart-protection"], ["shirt"], "Q129813"),
    ("breast", "chest", None, ["nipple"], ["nursing", "identity"], ["bra"], "Q9103"),
    ("nipple", "breast", None, None, ["nursing"], None, "Q170956"),
    ("sternum", "chest", None, None, ["breastbone"], None, "Q193870"),
    ("ribcage", "torso", None, ["rib"], ["organ-protection"], None, "Q193342"),
    ("rib", "ribcage", None, None, ["organ-protection"], None, "Q131144"),
    ("back", "torso", ["spine", "shoulder-blade"], None,
        ["support", "muscle-power"], ["backpack"], "Q1069"),
    ("spine", "back", ["vertebra"], ["cervical-spine", "thoracic-spine", "lumbar-spine"],
        ["body-support", "nerve-highway"], None, "Q1501"),
    ("vertebra", "spine", None, None, ["spinal-segment"], None, "Q191154"),
    ("cervical-spine", "spine", None, None, None, None, "Q470286"),
    ("thoracic-spine", "spine", None, None, None, None, "Q470293"),
    ("lumbar-spine", "spine", None, None, None, None, "Q470288"),
    ("waist", "torso", None, None, None, ["belt", "waistband"], "Q188634"),
    ("abdomen", "torso", None, ["belly", "navel", "hip"],
        ["digestion", "core-strength"], ["shirt"], "Q1148"),
    ("belly", "abdomen", None, None, None, None, "Q189017"),
    ("navel", "abdomen", None, None, ["fetal-heritage"], None, "Q158773"),
    ("hip", "torso", ["pelvis"], None, ["leg-articulation"], ["belt", "pants"], "Q131048"),
    ("pelvis", "hip", None, None, ["leg-anchor"], None, "Q127349"),

    # Arm + hand
    ("arm", "the whole", None, ["upper-arm", "forearm", "elbow", "hand", "armpit"],
        ["reaching", "carrying"], ["sleeve", "bracelet"], "Q37501"),
    ("upper-arm", "arm", ["humerus"], ["bicep", "tricep"], ["lifting"], None, "Q1470083"),
    ("humerus", "upper-arm", None, None, ["arm-bone"], None, "Q131265"),
    ("bicep", "upper-arm", None, None, ["arm-flexion"], None, "Q216615"),
    ("tricep", "upper-arm", None, None, ["arm-extension"], None, "Q1231585"),
    ("elbow", "arm", None, None, ["arm-hinge"], ["elbow-pad"], "Q186133"),
    ("forearm", "arm", ["radius-bone", "ulna"], ["wrist"],
        ["hand-support"], None, "Q216221"),
    ("radius-bone", "forearm", None, None, None, None, "Q189302"),
    ("ulna", "forearm", None, None, None, None, "Q188824"),
    ("armpit", "arm", None, None, None, None, "Q80054"),
    ("wrist", "arm", None, None, ["hand-articulation"], ["watch", "bracelet"], "Q133279"),
    ("hand", "arm", None, ["palm", "finger", "thumb", "knuckle", "fingernail"],
        ["grasping", "manipulation", "gesture"], ["glove", "ring", "watch"], "Q33767"),
    ("palm", "hand", None, None, ["grasping"], None, "Q191183"),
    ("finger", "hand", None, ["fingernail", "knuckle"],
        ["fine-manipulation", "pointing"], ["ring"], "Q620779"),
    ("thumb", "hand", None, ["fingernail"], ["grasping"], None, "Q80019"),
    ("index-finger", "hand", None, None, ["pointing"], None, "Q192809"),
    ("middle-finger", "hand", None, None, None, None, "Q192908"),
    ("ring-finger", "hand", None, None, None, ["wedding-ring"], "Q191762"),
    ("pinky-finger", "hand", None, None, None, None, "Q193346"),
    ("knuckle", "finger", None, None, ["finger-joint"], None, "Q3195311"),
    ("fingernail", "finger", None, None, ["scratching", "protection"], None, "Q76220"),

    # Leg + foot
    ("leg", "the whole", None, ["thigh", "knee", "shin", "calf", "ankle", "foot"],
        ["locomotion", "support"], ["pants", "sock"], "Q184600"),
    ("thigh", "leg", ["femur"], None, ["walking", "kicking"], None, "Q9612"),
    ("femur", "thigh", None, None, ["thigh-bone"], None, "Q191055"),
    ("knee", "leg", ["kneecap"], None, ["leg-hinge"], ["knee-pad"], "Q245672"),
    ("kneecap", "knee", None, None, ["knee-protection"], None, "Q118279"),
    ("shin", "leg", ["tibia"], None, ["support"], ["shin-guard"], "Q1245570"),
    ("tibia", "shin", None, None, ["shin-bone"], None, "Q131399"),
    ("fibula", "leg", None, None, None, None, "Q194414"),
    ("calf", "leg", None, ["calf-muscle"], ["walking-power"], None, "Q131400"),
    ("ankle", "leg", None, None, ["foot-articulation"], ["anklet"], "Q160736"),
    ("foot", "leg", None, ["toe", "heel", "arch-of-foot", "sole", "instep", "toenail"],
        ["walking", "standing", "kicking"], ["shoe", "sock", "sandal"], "Q9707"),
    ("toe", "foot", None, ["toenail"], ["balance"], None, "Q83313"),
    ("big-toe", "foot", None, None, ["balance"], None, "Q3411851"),
    ("heel", "foot", None, None, ["walking"], None, "Q193612"),
    ("arch-of-foot", "foot", None, None, ["weight-distribution"], None, "Q1345"),
    ("sole", "foot", None, None, ["ground-contact"], None, "Q1155876"),
    ("instep", "foot", None, None, None, None, "Q3477146"),
    ("toenail", "toe", None, None, ["toe-protection"], None, "Q189789"),

    # Skin + connective + interfaces
    ("skin", "the whole", None, ["epidermis", "dermis", "pore", "sweat-gland"],
        ["barrier", "temperature-regulation", "sensation"],
        ["clothing", "sunscreen"], "Q1074"),
    ("epidermis", "skin", None, None, ["outer-barrier"], None, "Q170779"),
    ("dermis", "skin", None, None, None, None, "Q193517"),
    ("pore", "skin", None, None, ["sweat-emission"], None, "Q193462"),
    ("sweat-gland", "skin", None, None, ["cooling"], None, "Q211732"),
    ("goosebump", "skin", None, None, ["cold-response"], None, "Q1076105"),
    ("mole", "skin", None, None, None, None, "Q193782"),
    ("freckle", "skin", None, None, None, None, "Q207159"),
    ("scar", "skin", None, None, ["wound-remnant"], None, "Q80056"),
    ("wrinkle", "skin", None, None, ["age-marker"], None, "Q47517"),
    ("beard", "face", None, None, ["expression", "identity"], None, "Q42804"),
    ("moustache", "face", None, None, ["expression"], None, "Q194159"),
    ("bone", "the whole", None, ["marrow"], ["structure", "protection"], None, "Q265868"),
    ("marrow", "bone", None, None, ["blood-cell-production"], None, "Q179888"),
    ("joint", "the whole", None, None, ["articulation"], None, "Q80071"),
    ("muscle", "the whole", None, ["tendon"], ["movement"], None, "Q7365"),
    ("tendon", "muscle", None, None, ["muscle-to-bone"], None, "Q193083"),
    ("ligament", "the whole", None, None, ["bone-to-bone"], None, "Q131258"),
    ("cartilage", "the whole", None, None, ["cushion"], None, "Q131254"),
    ("blood", "the whole", None, ["red-blood-cell", "white-blood-cell", "platelet", "plasma"],
        ["oxygen-transport", "immunity"], None, "Q7873"),
    ("red-blood-cell", "blood", None, None, ["oxygen-transport"], None, "Q37187"),
    ("white-blood-cell", "blood", None, None, ["immunity"], None, "Q186477"),
    ("platelet", "blood", None, None, ["clotting"], None, "Q192124"),
    ("plasma", "blood", None, None, ["fluid-transport"], None, "Q319902"),
    ("vein", "the whole", None, None, ["blood-return"], None, "Q9609"),
    ("artery", "the whole", None, None, ["blood-delivery"], None, "Q9655"),
    ("capillary", "the whole", None, None, ["blood-tissue-exchange"], None, "Q1074983"),
    ("nerve", "the whole", None, None, ["signaling"], None, "Q47331"),
    ("lymph-node", "the whole", None, None, ["immunity"], None, "Q189946"),

    # Organs
    ("brain", "head", None, ["cerebrum", "cerebellum", "brainstem", "cortex"],
        ["cognition", "control"], None, "Q1073"),
    ("cerebrum", "brain", None, ["cortex"], ["higher-cognition"], None, "Q3057262"),
    ("cerebellum", "brain", None, None, ["motor-coordination"], None, "Q123993"),
    ("brainstem", "brain", None, None, ["autonomic-control"], None, "Q193291"),
    ("cortex", "cerebrum", None, None, ["thought"], None, "Q47201"),
    ("heart", "torso", None, ["heart-chamber", "heart-valve"],
        ["blood-pumping"], None, "Q1072"),
    ("heart-chamber", "heart", None, None, None, None, "Q1233729"),
    ("heart-valve", "heart", None, None, ["blood-flow-control"], None, "Q3131338"),
    ("lung", "chest", None, ["bronchus", "alveolus", "diaphragm"],
        ["breathing", "gas-exchange"], None, "Q7886"),
    ("bronchus", "lung", None, None, ["air-passage"], None, "Q131174"),
    ("alveolus", "lung", None, None, ["gas-exchange"], None, "Q193285"),
    ("diaphragm", "chest", None, None, ["breathing"], None, "Q188681"),
    ("liver", "abdomen", None, None, ["filtering", "bile"], None, "Q9368"),
    ("kidney", "abdomen", None, None, ["waste-filtering"], None, "Q9377"),
    ("stomach", "abdomen", None, None, ["digestion"], None, "Q1029907"),
    ("intestine", "abdomen", None, ["small-intestine", "large-intestine"],
        ["digestion", "absorption"], None, "Q9394"),
    ("small-intestine", "intestine", None, None, ["nutrient-absorption"], None, "Q9639"),
    ("large-intestine", "intestine", None, ["colon", "rectum"],
        ["water-absorption"], None, "Q131152"),
    ("colon", "large-intestine", None, None, None, None, "Q192923"),
    ("rectum", "large-intestine", None, None, None, None, "Q80305"),
    ("pancreas", "abdomen", None, None, ["insulin", "digestion"], None, "Q37868"),
    ("spleen", "abdomen", None, None, ["blood-filtering"], None, "Q193583"),
    ("gallbladder", "abdomen", None, None, ["bile-storage"], None, "Q46246"),
    ("bladder", "abdomen", None, None, ["urine-storage"], None, "Q46373"),
    ("appendix", "intestine", None, None, None, None, "Q131035"),
    ("thyroid", "neck", None, None, ["metabolism"], None, "Q193509"),
    ("adrenal-gland", "abdomen", None, None, ["stress-response"], None, "Q193286"),

    # Reproductive (kept clinical + short)
    ("womb", "abdomen", None, None, ["gestation"], None, "Q11266"),
    ("ovary", "abdomen", None, None, None, None, "Q9631"),
    ("testicle", "the whole", None, None, None, None, "Q9384"),
    ("umbilical-cord", "the whole", None, None, ["fetal-nutrition"], None, "Q193196"),
    ("placenta", "the whole", None, None, ["fetal-support"], None, "Q193260"),
]

NODES = []
for canon, part_of_hint, has_parts, sub_parts, used, worn_on_things, qid in HUMAN:
    n = node(canon, "body-part",
             synonyms=[canon.replace("-", " "), canon.replace("-", "")],
             part_of=[part_of_hint] if part_of_hint and part_of_hint != "the whole" else None,
             has_part=(has_parts or []) + (sub_parts or []) if (has_parts or sub_parts) else None,
             used_for=used,
             kid_friendly=True,
             provenance=[wikidata(qid)] if qid else [authored()])
    NODES.append(n)


# ---------------------------------------------------------------------------
# GENERAL VERTEBRATE / ANIMAL BODY PARTS (non-human specifics)
# ---------------------------------------------------------------------------

ANIMAL = [
    ("beak", "bird head", ["mouth"], ["seed-cracking", "grooming"], "Q102574"),
    ("bill", "bird head", ["beak"], ["seed-cracking"], "Q102574"),
    ("feather", "bird body", None, ["flight", "insulation", "display"], "Q80831"),
    ("wing", "vertebrate", ["feather"], ["flight"], "Q133948"),
    ("bird-wing", "bird body", ["feather"], ["flight"], "Q19595"),
    ("insect-wing", "insect body", None, ["flight"], "Q3568988"),
    ("bat-wing", "bat body", None, ["flight"], "Q1064538"),
    ("tail", "vertebrate", None, ["balance", "communication"], "Q35827"),
    ("tail-feather", "bird body", None, ["steering"], "Q94910"),
    ("fur", "mammal body", None, ["insulation", "camouflage"], "Q80956"),
    ("pelt", "mammal body", ["fur"], ["insulation"], "Q834028"),
    ("mane", "horse body", None, ["display", "insulation"], "Q1077605"),
    ("hoof", "ungulate foot", None, ["walking", "digging"], "Q102178"),
    ("claw", "vertebrate", None, ["gripping", "digging", "defense"], "Q194180"),
    ("talon", "raptor foot", ["claw"], ["prey-grasping"], "Q7674286"),
    ("horn", "vertebrate", None, ["defense", "display"], "Q188828"),
    ("antler", "deer head", None, ["display", "combat"], "Q173799"),
    ("tusk", "mammal head", ["tooth"], ["display", "combat", "digging"], "Q192929"),
    ("fang", "predator mouth", ["tooth"], ["prey-killing", "venom-delivery"], "Q1156040"),
    ("mandible-insect", "insect head", None, ["chewing"], "Q3568988"),
    ("proboscis", "insect head", None, ["nectar-drinking"], "Q193083"),
    ("stinger", "insect body", None, ["defense", "venom"], "Q209101"),
    ("antenna", "arthropod head", None, ["sensing"], "Q40984"),
    ("compound-eye", "arthropod head", None, ["wide-vision"], "Q1155876"),
    ("exoskeleton", "arthropod body", None, ["protection"], "Q83180"),
    ("carapace", "turtle body", None, ["protection"], "Q3308061"),
    ("shell", "invertebrate", None, ["protection"], "Q211781"),
    ("scale", "fish body", None, ["protection"], "Q76285"),
    ("fin", "fish body", ["dorsal-fin", "pectoral-fin", "caudal-fin"], ["swimming"], "Q133376"),
    ("dorsal-fin", "fish body", None, ["stability"], "Q3245517"),
    ("pectoral-fin", "fish body", None, ["steering"], "Q3245524"),
    ("caudal-fin", "fish body", None, ["propulsion"], "Q3245495"),
    ("gill", "fish body", None, ["breathing-underwater"], "Q131396"),
    ("blowhole", "cetacean body", None, ["breathing"], "Q825658"),
    ("flipper", "marine mammal body", None, ["swimming"], "Q80833"),
    ("flukes", "cetacean body", None, ["propulsion"], "Q1128092"),
    ("baleen", "whale mouth", None, ["filter-feeding"], "Q191712"),
    ("gizzard", "bird digestive", None, ["grit-grinding"], "Q1073987"),
    ("crop", "bird digestive", None, ["food-storage"], "Q1155857"),
    ("cocoon", "insect body", None, ["metamorphosis"], "Q189533"),
    ("chrysalis", "butterfly body", None, ["metamorphosis"], "Q193261"),
    ("web", "spider product", None, ["prey-catching"], "Q211781"),
    ("silk-gland", "spider body", None, ["web-production"], "Q1163715"),
    ("venom-gland", "predator body", None, ["prey-subduing"], "Q1163715"),
    ("scent-gland", "mammal body", None, ["marking"], "Q1163715"),
    ("mammary-gland", "mammal body", None, ["nursing"], "Q191067"),
    ("udder", "mammal body", ["mammary-gland"], ["nursing"], "Q173094"),
    ("hump", "camel body", None, ["fat-storage"], "Q179692"),
    ("trunk-elephant", "elephant head", None, ["grasping", "drinking"], "Q189960"),
    ("mane-lion", "lion body", None, ["display"], "Q1077605"),
    ("whiskers", "mammal face", None, ["sensing"], "Q193214"),
    ("tongue-frog", "frog mouth", ["tongue"], ["prey-catching"], "Q9614"),
]

for canon, part_of_hint, sub, used, qid in ANIMAL:
    NODES.append(node(canon, "body-part",
                       synonyms=[canon.replace("-", " "), canon.replace("-", "")],
                       part_of=None,
                       has_part=sub,
                       used_for=used,
                       kid_friendly=True,
                       provenance=[wikidata(qid)] if qid else [authored()]))


# ---------------------------------------------------------------------------
# PLANT + TREE + FUNGUS BODY PARTS (structural)
# ---------------------------------------------------------------------------

PLANT_PARTS = [
    ("leaf", "plant", ["vein-leaf", "blade-leaf", "petiole"], ["photosynthesis"], "Q33971"),
    ("vein-leaf", "leaf", None, ["nutrient-transport"], "Q9609"),
    ("blade-leaf", "leaf", None, ["photosynthesis-surface"], "Q193083"),
    ("petiole", "leaf", None, ["leaf-attachment"], "Q754336"),
    ("stem", "plant", None, ["support", "transport"], "Q193760"),
    ("stalk", "plant", ["stem"], ["support"], "Q193760"),
    ("trunk-tree", "tree", ["bark", "cambium", "heartwood", "sapwood"],
        ["support", "timber"], "Q656720"),
    ("bark", "tree", None, ["protection"], "Q193516"),
    ("cambium", "tree", None, ["growth-layer"], "Q844843"),
    ("heartwood", "tree", None, ["structure"], "Q1148571"),
    ("sapwood", "tree", None, ["water-transport"], "Q7423114"),
    ("branch", "tree", ["twig", "bough"], ["light-capture"], "Q656720"),
    ("bough", "tree", None, ["large-branch"], "Q656720"),
    ("twig", "tree", None, None, "Q102046"),
    ("root", "plant", ["taproot", "root-hair"], ["anchor", "water-uptake"], "Q41500"),
    ("taproot", "plant", None, ["deep-water-uptake"], "Q1140328"),
    ("root-hair", "plant", None, ["water-absorption"], "Q1140312"),
    ("flower", "plant", ["petal", "stamen", "pistil", "sepal", "receptacle"],
        ["reproduction", "beauty"], "Q506"),
    ("petal", "flower", None, ["pollinator-attraction"], "Q193082"),
    ("stamen", "flower", ["anther", "filament-stamen"], ["pollen-production"], "Q152087"),
    ("anther", "stamen", None, ["pollen-release"], "Q1092506"),
    ("filament-stamen", "stamen", None, ["anther-support"], "Q1073987"),
    ("pistil", "flower", ["stigma", "style", "ovary-plant"], ["pollen-receiving"], "Q192974"),
    ("stigma", "pistil", None, ["pollen-receiving"], "Q193254"),
    ("style-plant", "pistil", None, None, "Q193261"),
    ("ovary-plant", "pistil", None, ["seed-formation"], "Q9631"),
    ("sepal", "flower", None, ["bud-protection"], "Q186290"),
    ("receptacle", "flower", None, ["floral-base"], "Q1156040"),
    ("bud", "plant", None, ["future-growth"], "Q47041"),
    ("fruit", "plant", ["seed", "pericarp", "pulp"], ["seed-dispersal"], "Q3314483"),
    ("seed", "fruit", None, ["reproduction"], "Q39833"),
    ("pericarp", "fruit", None, ["seed-protection"], "Q1148571"),
    ("pulp", "fruit", None, ["nutrition"], "Q193462"),
    ("husk", "fruit", None, ["seed-protection"], "Q1148571"),
    ("shell-nut", "fruit", None, ["seed-protection"], "Q211781"),
    ("kernel", "fruit", None, ["nutrition"], "Q106415"),
    ("pit", "fruit", None, ["seed-protection"], "Q1148571"),
    ("stone-fruit", "fruit", None, ["seed-protection"], "Q1148571"),
    ("cone-conifer", "conifer", None, ["reproduction"], "Q193261"),
    ("needle-conifer", "conifer", ["leaf"], ["photosynthesis"], "Q33971"),
    ("catkin", "tree", None, ["pollen-carrying"], "Q734028"),
    ("thorn", "plant", None, ["defense"], "Q844843"),
    ("spine-cactus", "cactus", None, ["defense"], "Q844843"),
    ("tendril", "vine", None, ["climbing"], "Q754336"),
    ("bulb", "plant", None, ["storage", "reproduction"], "Q189370"),
    ("tuber", "plant", None, ["storage"], "Q193302"),
    ("rhizome", "plant", None, ["horizontal-growth"], "Q193760"),
    ("mycelium", "fungus", ["hypha"], ["nutrient-absorption"], "Q191193"),
    ("hypha", "fungus", None, None, "Q188673"),
    ("mushroom-cap", "mushroom", ["gill-mushroom", "stipe"], ["spore-release"], "Q83483"),
    ("gill-mushroom", "mushroom", None, ["spore-release"], "Q131396"),
    ("stipe", "mushroom", None, ["cap-support"], "Q193760"),
    ("spore", "fungus", None, ["reproduction"], "Q192823"),
    ("frond", "fern", ["leaf"], ["photosynthesis"], "Q33971"),
    ("thallus", "algae", None, None, "Q193519"),
    ("holdfast", "algae", None, ["anchor"], "Q1140328"),
]

for canon, part_of_hint, sub, used, qid in PLANT_PARTS:
    NODES.append(node(canon, "body-part",
                       synonyms=[canon.replace("-", " "), canon.replace("-", "")],
                       part_of=None,
                       has_part=sub,
                       used_for=used,
                       kid_friendly=True,
                       provenance=[wikidata(qid)] if qid else [authored()]))
