"""Mammals — the ones people actually name.
Target: ~500-800 mammal species / recognized breeds / groups.
Faceted with :taxonomy :scientific_name :diet :lives_in :region_native_to
:behavior_notes :size_scale :season_associated.
"""

from _helpers import node, wikidata, gbif, tax, authored


def mam(canonical, sci, family, order, diet, habitat, region, size,
        synonyms=None, behavior=None, tod=None, seasons=None, qid=None, kid=True):
    """Concise mammal-node factory."""
    return node(canonical, "animal",
                synonyms=synonyms or [],
                scientific_name=sci,
                taxonomy=tax(kingdom="Animalia", phylum="Chordata", class_="Mammalia",
                             order=order, family=family,
                             genus=sci.split()[0] if sci else None,
                             species=sci, common_name=canonical),
                diet=diet,
                lives_in=habitat,
                region_native_to=region,
                size_scale=size,
                behavior_notes=behavior,
                time_of_day=tod,
                season=seasons,
                kid_friendly=kid,
                provenance=[wikidata(qid)] if qid else [authored()])


NODES = []

# ---------------------------------------------------------------------------
# CARNIVORA — dogs, cats, bears, weasels, seals, hyenas, mongooses
# ---------------------------------------------------------------------------
NODES += [
    mam("dog", "Canis lupus familiaris", "Canidae", "Carnivora",
        ["omnivore"], ["human-settlement", "worldwide"], ["worldwide"], "medium",
        synonyms=["hound", "canine", "pup", "puppy", "doggy"],
        behavior=["social", "domesticated", "pack-oriented"], qid="Q144"),
    mam("wolf", "Canis lupus", "Canidae", "Carnivora",
        ["carnivore"], ["forest", "tundra", "grassland"],
        ["north-america", "eurasia"], "large",
        synonyms=["gray-wolf", "timber-wolf", "grey-wolf"],
        behavior=["pack-hunter", "territorial", "howling"],
        tod=["dusk", "night"], qid="Q18498"),
    mam("coyote", "Canis latrans", "Canidae", "Carnivora",
        ["carnivore", "omnivore"], ["plain", "desert", "urban-edge"],
        ["north-america"], "medium",
        synonyms=["prairie-wolf", "brush-wolf"],
        behavior=["adaptable", "opportunistic"], tod=["night", "dusk"],
        qid="Q46076"),
    mam("fox", "Vulpes vulpes", "Canidae", "Carnivora",
        ["omnivore"], ["forest", "grassland", "urban"],
        ["north-america", "eurasia"], "small",
        synonyms=["red-fox", "renard"],
        behavior=["solitary", "cunning"], tod=["dusk", "night"], qid="Q8331"),
    mam("arctic-fox", "Vulpes lagopus", "Canidae", "Carnivora",
        ["omnivore"], ["tundra"], ["arctic"], "small",
        synonyms=["polar-fox", "white-fox"],
        behavior=["winter-white-coat"], seasons=["winter"], qid="Q40662"),
    mam("dingo", "Canis lupus dingo", "Canidae", "Carnivora",
        ["carnivore"], ["outback", "grassland"], ["australia"], "medium",
        synonyms=["warrigal"], behavior=["pack-oriented"], qid="Q28481"),
    mam("jackal", "Canis aureus", "Canidae", "Carnivora",
        ["omnivore"], ["grassland", "savanna"], ["africa", "eurasia"], "medium",
        synonyms=["golden-jackal"], behavior=["scavenger", "pack-oriented"],
        qid="Q37846"),

    mam("cat", "Felis catus", "Felidae", "Carnivora",
        ["carnivore"], ["human-settlement", "worldwide"], ["worldwide"], "small",
        synonyms=["housecat", "feline", "kitty", "kitten"],
        behavior=["solitary", "domesticated", "crepuscular"],
        tod=["dawn", "dusk"], qid="Q146"),
    mam("lion", "Panthera leo", "Felidae", "Carnivora",
        ["carnivore"], ["savanna", "grassland"], ["africa", "india"], "large",
        synonyms=["king-of-beasts"], behavior=["pride-living", "territorial"],
        tod=["dawn", "dusk"], qid="Q140"),
    mam("tiger", "Panthera tigris", "Felidae", "Carnivora",
        ["carnivore"], ["jungle", "forest", "mangrove"], ["asia"], "large",
        synonyms=["bengal-tiger", "siberian-tiger"],
        behavior=["solitary", "swimmer"], tod=["night", "dawn"], qid="Q19939"),
    mam("leopard", "Panthera pardus", "Felidae", "Carnivora",
        ["carnivore"], ["forest", "savanna", "mountain"], ["africa", "asia"], "large",
        behavior=["solitary", "tree-climber"], tod=["night"], qid="Q34706"),
    mam("cheetah", "Acinonyx jubatus", "Felidae", "Carnivora",
        ["carnivore"], ["savanna", "grassland"], ["africa"], "large",
        behavior=["fastest-land-animal", "diurnal-hunter"], tod=["morning", "evening"],
        qid="Q29099"),
    mam("jaguar", "Panthera onca", "Felidae", "Carnivora",
        ["carnivore"], ["jungle", "wetland"], ["central-america", "south-america"], "large",
        behavior=["solitary", "swimmer"], qid="Q35694"),
    mam("cougar", "Puma concolor", "Felidae", "Carnivora",
        ["carnivore"], ["mountain", "forest"], ["north-america", "south-america"], "large",
        synonyms=["mountain-lion", "puma", "panther"],
        behavior=["solitary", "silent-stalker"], qid="Q30545"),
    mam("lynx", "Lynx lynx", "Felidae", "Carnivora",
        ["carnivore"], ["boreal-forest", "mountain"], ["eurasia", "north-america"], "medium",
        behavior=["solitary", "snow-hunter"], seasons=["winter"], qid="Q41055"),
    mam("bobcat", "Lynx rufus", "Felidae", "Carnivora",
        ["carnivore"], ["forest", "desert"], ["north-america"], "medium",
        behavior=["solitary"], tod=["dawn", "dusk"], qid="Q29997"),
    mam("caracal", "Caracal caracal", "Felidae", "Carnivora",
        ["carnivore"], ["savanna", "semi-desert"], ["africa", "middle-east"], "medium",
        behavior=["leaping-hunter"], qid="Q41200"),
    mam("serval", "Leptailurus serval", "Felidae", "Carnivora",
        ["carnivore"], ["grassland", "wetland"], ["africa"], "medium", qid="Q182171"),
    mam("ocelot", "Leopardus pardalis", "Felidae", "Carnivora",
        ["carnivore"], ["jungle", "forest"], ["central-america", "south-america"], "medium",
        behavior=["nocturnal"], tod=["night"], qid="Q127675"),
    mam("snow-leopard", "Panthera uncia", "Felidae", "Carnivora",
        ["carnivore"], ["mountain", "alpine"], ["central-asia", "himalayas"], "large",
        behavior=["cold-adapted", "solitary"], seasons=["winter"], qid="Q34718"),

    mam("bear", "Ursidae", "Ursidae", "Carnivora",
        ["omnivore"], ["forest", "mountain"], ["worldwide"], "large",
        synonyms=["bruin"], behavior=["solitary"], qid="Q219298"),
    mam("brown-bear", "Ursus arctos", "Ursidae", "Carnivora",
        ["omnivore"], ["forest", "mountain"], ["north-america", "eurasia"], "large",
        synonyms=["grizzly-bear"], behavior=["hibernator"], seasons=["winter"],
        qid="Q10990"),
    mam("black-bear", "Ursus americanus", "Ursidae", "Carnivora",
        ["omnivore"], ["forest"], ["north-america"], "large",
        behavior=["climber", "hibernator"], qid="Q186091"),
    mam("polar-bear", "Ursus maritimus", "Ursidae", "Carnivora",
        ["carnivore"], ["arctic-ice"], ["arctic"], "large",
        behavior=["swimmer", "solitary"], seasons=["winter"], qid="Q33609"),
    mam("panda", "Ailuropoda melanoleuca", "Ursidae", "Carnivora",
        ["folivore", "herbivore"], ["bamboo-forest"], ["china"], "large",
        synonyms=["giant-panda"], behavior=["bamboo-eater"], qid="Q33602"),
    mam("sun-bear", "Helarctos malayanus", "Ursidae", "Carnivora",
        ["omnivore"], ["tropical-forest"], ["southeast-asia"], "medium", qid="Q41014"),
    mam("sloth-bear", "Melursus ursinus", "Ursidae", "Carnivora",
        ["insectivore", "omnivore"], ["forest"], ["india", "sri-lanka"], "medium", qid="Q102272"),

    mam("hyena", "Crocuta crocuta", "Hyaenidae", "Carnivora",
        ["carnivore", "scavenger"], ["savanna"], ["africa"], "large",
        synonyms=["spotted-hyena"], behavior=["clan-living", "vocal"], qid="Q42402"),
    mam("striped-hyena", "Hyaena hyaena", "Hyaenidae", "Carnivora",
        ["scavenger"], ["semi-arid"], ["africa", "middle-east", "india"], "medium",
        qid="Q191293"),
    mam("aardwolf", "Proteles cristata", "Hyaenidae", "Carnivora",
        ["insectivore"], ["savanna"], ["africa"], "medium",
        behavior=["termite-eater"], qid="Q45970"),

    mam("weasel", "Mustela nivalis", "Mustelidae", "Carnivora",
        ["carnivore"], ["forest", "grassland"], ["europe", "north-america"], "tiny",
        behavior=["burrow-hunter"], qid="Q179168"),
    mam("stoat", "Mustela erminea", "Mustelidae", "Carnivora",
        ["carnivore"], ["boreal", "tundra"], ["holarctic"], "tiny",
        synonyms=["ermine", "short-tailed-weasel"],
        behavior=["winter-white-coat"], seasons=["winter"], qid="Q189389"),
    mam("otter", "Lutra lutra", "Mustelidae", "Carnivora",
        ["carnivore", "piscivore"], ["river", "coast"], ["eurasia"], "medium",
        behavior=["swimmer", "playful"], qid="Q40997"),
    mam("sea-otter", "Enhydra lutris", "Mustelidae", "Carnivora",
        ["carnivore"], ["ocean", "kelp-forest"], ["north-pacific"], "medium",
        behavior=["tool-user", "raft-forming"], qid="Q29591"),
    mam("giant-otter", "Pteronura brasiliensis", "Mustelidae", "Carnivora",
        ["carnivore"], ["river"], ["south-america"], "large", qid="Q192702"),
    mam("badger", "Meles meles", "Mustelidae", "Carnivora",
        ["omnivore"], ["forest", "grassland"], ["europe"], "medium",
        behavior=["burrower"], tod=["night"], qid="Q25330"),
    mam("honey-badger", "Mellivora capensis", "Mustelidae", "Carnivora",
        ["omnivore"], ["savanna", "desert"], ["africa", "asia"], "medium",
        behavior=["fearless"], qid="Q191196"),
    mam("wolverine", "Gulo gulo", "Mustelidae", "Carnivora",
        ["omnivore", "scavenger"], ["boreal-forest", "tundra"], ["holarctic"], "medium",
        seasons=["winter"], qid="Q41552"),
    mam("marten", "Martes martes", "Mustelidae", "Carnivora",
        ["carnivore"], ["forest"], ["europe"], "small", qid="Q29988"),
    mam("fisher-cat", "Pekania pennanti", "Mustelidae", "Carnivora",
        ["carnivore"], ["forest"], ["north-america"], "small",
        synonyms=["fisher"], qid="Q616568"),
    mam("mink", "Neogale vison", "Mustelidae", "Carnivora",
        ["carnivore"], ["river", "wetland"], ["north-america"], "small", qid="Q192041"),
    mam("ferret", "Mustela putorius furo", "Mustelidae", "Carnivora",
        ["carnivore"], ["human-settlement"], ["worldwide-domestic"], "small",
        behavior=["domesticated"], qid="Q188418"),
    mam("polecat", "Mustela putorius", "Mustelidae", "Carnivora",
        ["carnivore"], ["forest"], ["europe"], "small", qid="Q179691"),
    mam("skunk", "Mephitis mephitis", "Mephitidae", "Carnivora",
        ["omnivore"], ["forest", "grassland", "urban"], ["north-america"], "small",
        synonyms=["striped-skunk"], behavior=["scent-defense", "nocturnal"],
        tod=["night"], qid="Q193459"),

    mam("raccoon", "Procyon lotor", "Procyonidae", "Carnivora",
        ["omnivore"], ["forest", "urban"], ["north-america"], "small",
        synonyms=["coon"], behavior=["mask-face", "dexterous-paws", "nocturnal"],
        tod=["night"], qid="Q47844"),
    mam("coati", "Nasua narica", "Procyonidae", "Carnivora",
        ["omnivore"], ["forest"], ["central-america", "south-america"], "small",
        qid="Q193612"),
    mam("kinkajou", "Potos flavus", "Procyonidae", "Carnivora",
        ["frugivore"], ["jungle"], ["central-america", "south-america"], "small",
        tod=["night"], qid="Q42303"),

    mam("mongoose", "Herpestes ichneumon", "Herpestidae", "Carnivora",
        ["carnivore"], ["grassland", "forest"], ["africa", "asia"], "small",
        behavior=["snake-hunter"], qid="Q188472"),
    mam("meerkat", "Suricata suricatta", "Herpestidae", "Carnivora",
        ["insectivore", "carnivore"], ["semi-arid"], ["southern-africa"], "small",
        synonyms=["suricate"], behavior=["social", "sentinel-posts"],
        tod=["morning"], qid="Q182058"),

    mam("seal", "Phocidae", "Phocidae", "Carnivora",
        ["carnivore", "piscivore"], ["ocean", "coast"], ["worldwide"], "large",
        behavior=["swimmer"], qid="Q46383"),
    mam("harbor-seal", "Phoca vitulina", "Phocidae", "Carnivora",
        ["piscivore"], ["ocean", "coast"], ["holarctic-coasts"], "large",
        synonyms=["common-seal"], qid="Q188846"),
    mam("elephant-seal", "Mirounga angustirostris", "Phocidae", "Carnivora",
        ["carnivore"], ["ocean"], ["pacific-coast"], "huge", qid="Q41430"),
    mam("leopard-seal", "Hydrurga leptonyx", "Phocidae", "Carnivora",
        ["carnivore"], ["antarctic-ice"], ["antarctic"], "huge", qid="Q188572"),
    mam("sea-lion", "Zalophus californianus", "Otariidae", "Carnivora",
        ["piscivore"], ["ocean", "coast"], ["pacific-coast"], "large",
        behavior=["vocal", "playful"], qid="Q186422"),
    mam("walrus", "Odobenus rosmarus", "Odobenidae", "Carnivora",
        ["carnivore"], ["arctic-coast"], ["arctic"], "huge",
        behavior=["tusked", "gregarious"], qid="Q35459"),
    mam("fur-seal", "Arctocephalus", "Otariidae", "Carnivora",
        ["piscivore"], ["ocean", "coast"], ["southern-hemisphere"], "large",
        qid="Q214147"),
]

# ---------------------------------------------------------------------------
# CETACEA + SIRENIA — whales, dolphins, porpoises, manatees
# ---------------------------------------------------------------------------
NODES += [
    mam("whale", "Cetacea", "Balaenopteridae", "Cetacea",
        ["carnivore", "filter-feeder"], ["ocean"], ["worldwide"], "massive",
        behavior=["migratory", "vocal"], qid="Q1865281"),
    mam("blue-whale", "Balaenoptera musculus", "Balaenopteridae", "Cetacea",
        ["filter-feeder"], ["ocean"], ["worldwide"], "massive",
        behavior=["largest-animal", "migratory"], qid="Q42196"),
    mam("humpback-whale", "Megaptera novaeangliae", "Balaenopteridae", "Cetacea",
        ["filter-feeder"], ["ocean"], ["worldwide"], "massive",
        behavior=["singer", "breaching", "migratory"], qid="Q42213"),
    mam("sperm-whale", "Physeter macrocephalus", "Physeteridae", "Cetacea",
        ["carnivore"], ["ocean"], ["worldwide"], "massive",
        behavior=["deep-diver", "clicking"], qid="Q42196"),
    mam("orca", "Orcinus orca", "Delphinidae", "Cetacea",
        ["carnivore"], ["ocean"], ["worldwide"], "huge",
        synonyms=["killer-whale"], behavior=["pod-living", "intelligent", "vocal"],
        qid="Q26547"),
    mam("dolphin", "Delphinidae", "Delphinidae", "Cetacea",
        ["carnivore", "piscivore"], ["ocean"], ["worldwide"], "large",
        behavior=["playful", "echo-locating", "social"], qid="Q7369"),
    mam("bottlenose-dolphin", "Tursiops truncatus", "Delphinidae", "Cetacea",
        ["piscivore"], ["ocean", "coast"], ["worldwide-temperate"], "large",
        qid="Q26547"),
    mam("porpoise", "Phocoena phocoena", "Phocoenidae", "Cetacea",
        ["piscivore"], ["coast"], ["holarctic-coasts"], "large",
        synonyms=["harbor-porpoise"], qid="Q194380"),
    mam("beluga-whale", "Delphinapterus leucas", "Monodontidae", "Cetacea",
        ["carnivore"], ["arctic-ocean"], ["arctic"], "huge",
        synonyms=["white-whale", "sea-canary"], qid="Q127950"),
    mam("narwhal", "Monodon monoceros", "Monodontidae", "Cetacea",
        ["carnivore"], ["arctic-ocean"], ["arctic"], "huge",
        behavior=["tusked", "sea-unicorn"], qid="Q128797"),
    mam("gray-whale", "Eschrichtius robustus", "Eschrichtiidae", "Cetacea",
        ["filter-feeder"], ["ocean"], ["pacific"], "massive",
        behavior=["migratory"], qid="Q189060"),
    mam("right-whale", "Eubalaena", "Balaenidae", "Cetacea",
        ["filter-feeder"], ["ocean"], ["worldwide"], "massive", qid="Q212349"),
    mam("bowhead-whale", "Balaena mysticetus", "Balaenidae", "Cetacea",
        ["filter-feeder"], ["arctic-ocean"], ["arctic"], "massive",
        behavior=["longest-lived-mammal"], qid="Q133061"),
    mam("manatee", "Trichechus manatus", "Trichechidae", "Sirenia",
        ["herbivore"], ["river", "coast"], ["caribbean", "west-africa"], "huge",
        synonyms=["sea-cow"], behavior=["gentle", "slow-moving"], qid="Q147152"),
    mam("dugong", "Dugong dugon", "Dugongidae", "Sirenia",
        ["herbivore"], ["coast", "seagrass-meadow"], ["indo-pacific"], "huge",
        qid="Q131269"),
]

# ---------------------------------------------------------------------------
# UNGULATES — cows, deer, horses, camels, giraffes, hippos, pigs
# ---------------------------------------------------------------------------
NODES += [
    mam("cow", "Bos taurus", "Bovidae", "Artiodactyla",
        ["herbivore"], ["pasture", "farm"], ["worldwide-domestic"], "large",
        synonyms=["cattle", "bovine", "heifer", "calf"],
        behavior=["domesticated", "herd-animal", "cud-chewing"], qid="Q830"),
    mam("bull", "Bos taurus", "Bovidae", "Artiodactyla",
        ["herbivore"], ["pasture"], ["worldwide-domestic"], "large",
        behavior=["male-cattle"], qid="Q11397"),
    mam("ox", "Bos taurus", "Bovidae", "Artiodactyla",
        ["herbivore"], ["farm"], ["worldwide-domestic"], "large",
        behavior=["draft-animal"], qid="Q473194"),
    mam("bison", "Bison bison", "Bovidae", "Artiodactyla",
        ["herbivore"], ["prairie"], ["north-america"], "large",
        synonyms=["buffalo", "american-buffalo"],
        behavior=["migratory-herd"], qid="Q47542"),
    mam("water-buffalo", "Bubalus bubalis", "Bovidae", "Artiodactyla",
        ["herbivore"], ["wetland", "farm"], ["south-asia", "southeast-asia"], "large",
        qid="Q47542"),
    mam("yak", "Bos grunniens", "Bovidae", "Artiodactyla",
        ["herbivore"], ["mountain"], ["himalayas", "tibet"], "large",
        behavior=["cold-adapted"], qid="Q26547"),
    mam("goat", "Capra aegagrus hircus", "Bovidae", "Artiodactyla",
        ["herbivore"], ["farm", "mountain"], ["worldwide-domestic"], "medium",
        synonyms=["billy-goat", "nanny-goat", "kid-goat"],
        behavior=["domesticated", "climber"], qid="Q2934"),
    mam("mountain-goat", "Oreamnos americanus", "Bovidae", "Artiodactyla",
        ["herbivore"], ["mountain", "alpine"], ["north-america"], "medium",
        qid="Q188818"),
    mam("sheep", "Ovis aries", "Bovidae", "Artiodactyla",
        ["herbivore"], ["farm", "pasture"], ["worldwide-domestic"], "medium",
        synonyms=["ewe", "ram", "lamb"], behavior=["flock-animal"], qid="Q7368"),
    mam("bighorn-sheep", "Ovis canadensis", "Bovidae", "Artiodactyla",
        ["herbivore"], ["mountain"], ["north-america"], "large", qid="Q188876"),
    mam("mouflon", "Ovis orientalis", "Bovidae", "Artiodactyla",
        ["herbivore"], ["mountain"], ["west-asia"], "medium", qid="Q189359"),
    mam("gazelle", "Gazella", "Bovidae", "Artiodactyla",
        ["herbivore"], ["savanna", "grassland"], ["africa", "middle-east"], "medium",
        behavior=["swift-runner"], qid="Q193439"),
    mam("antelope", "Bovidae", "Bovidae", "Artiodactyla",
        ["herbivore"], ["savanna"], ["africa"], "medium", qid="Q26547"),
    mam("gnu", "Connochaetes taurinus", "Bovidae", "Artiodactyla",
        ["herbivore"], ["savanna"], ["africa"], "large",
        synonyms=["wildebeest"], behavior=["migratory-herd"], qid="Q29556"),
    mam("impala", "Aepyceros melampus", "Bovidae", "Artiodactyla",
        ["herbivore"], ["savanna"], ["africa"], "medium",
        behavior=["swift-leaper"], qid="Q194336"),
    mam("kudu", "Tragelaphus strepsiceros", "Bovidae", "Artiodactyla",
        ["herbivore"], ["woodland"], ["africa"], "large", qid="Q127367"),
    mam("oryx", "Oryx gazella", "Bovidae", "Artiodactyla",
        ["herbivore"], ["desert", "semi-arid"], ["africa", "middle-east"], "large",
        qid="Q188876"),
    mam("springbok", "Antidorcas marsupialis", "Bovidae", "Artiodactyla",
        ["herbivore"], ["savanna"], ["southern-africa"], "medium",
        behavior=["pronking"], qid="Q192053"),
    mam("elk", "Cervus canadensis", "Cervidae", "Artiodactyla",
        ["herbivore"], ["forest", "mountain"], ["north-america", "east-asia"], "large",
        synonyms=["wapiti"], behavior=["bugling-call"], qid="Q29099"),
    mam("moose", "Alces alces", "Cervidae", "Artiodactyla",
        ["herbivore"], ["boreal-forest", "wetland"], ["holarctic"], "huge",
        synonyms=["eurasian-elk"], behavior=["solitary", "swimmer"], qid="Q34718"),
    mam("caribou", "Rangifer tarandus", "Cervidae", "Artiodactyla",
        ["herbivore"], ["tundra", "boreal-forest"], ["arctic-holarctic"], "large",
        synonyms=["reindeer"], behavior=["migratory-herd"], qid="Q30051"),
    mam("deer", "Cervidae", "Cervidae", "Artiodactyla",
        ["herbivore"], ["forest", "grassland"], ["worldwide-except-antarctica"], "medium",
        synonyms=["doe", "buck", "stag", "fawn"],
        behavior=["antlered-males", "browser"], qid="Q40763"),
    mam("white-tailed-deer", "Odocoileus virginianus", "Cervidae", "Artiodactyla",
        ["herbivore"], ["forest"], ["north-america"], "medium",
        behavior=["tail-flag"], qid="Q54078"),
    mam("mule-deer", "Odocoileus hemionus", "Cervidae", "Artiodactyla",
        ["herbivore"], ["forest", "shrubland"], ["north-america"], "medium",
        qid="Q194440"),
    mam("red-deer", "Cervus elaphus", "Cervidae", "Artiodactyla",
        ["herbivore"], ["forest"], ["europe", "asia"], "large", qid="Q47041"),
    mam("roe-deer", "Capreolus capreolus", "Cervidae", "Artiodactyla",
        ["herbivore"], ["forest"], ["europe"], "small", qid="Q157351"),
    mam("fallow-deer", "Dama dama", "Cervidae", "Artiodactyla",
        ["herbivore"], ["parkland", "forest"], ["europe"], "medium", qid="Q83070"),
    mam("horse", "Equus ferus caballus", "Equidae", "Perissodactyla",
        ["herbivore"], ["pasture", "farm"], ["worldwide-domestic"], "large",
        synonyms=["equine", "mare", "stallion", "foal", "colt", "filly"],
        behavior=["domesticated", "herd-animal"], qid="Q726"),
    mam("donkey", "Equus africanus asinus", "Equidae", "Perissodactyla",
        ["herbivore"], ["farm", "pasture"], ["worldwide-domestic"], "medium",
        synonyms=["ass", "burro"], behavior=["patient", "sure-footed"], qid="Q34728"),
    mam("mule", "Equus mule", "Equidae", "Perissodactyla",
        ["herbivore"], ["farm"], ["worldwide-domestic"], "medium",
        behavior=["horse-donkey-hybrid", "sure-footed"], qid="Q42569"),
    mam("zebra", "Equus quagga", "Equidae", "Perissodactyla",
        ["herbivore"], ["savanna", "grassland"], ["africa"], "large",
        synonyms=["plains-zebra"], behavior=["stripes", "herd-animal"], qid="Q18498"),
    mam("mountain-zebra", "Equus zebra", "Equidae", "Perissodactyla",
        ["herbivore"], ["mountain"], ["southern-africa"], "large", qid="Q192053"),
    mam("grevy-zebra", "Equus grevyi", "Equidae", "Perissodactyla",
        ["herbivore"], ["semi-arid"], ["east-africa"], "large", qid="Q192053"),
    mam("wild-horse", "Equus ferus", "Equidae", "Perissodactyla",
        ["herbivore"], ["steppe"], ["central-asia"], "large",
        synonyms=["przewalski-horse"], qid="Q147498"),
    mam("tapir", "Tapirus terrestris", "Tapiridae", "Perissodactyla",
        ["herbivore"], ["jungle"], ["south-america", "southeast-asia"], "large",
        behavior=["swimmer"], qid="Q184644"),
    mam("rhinoceros", "Rhinocerotidae", "Rhinocerotidae", "Perissodactyla",
        ["herbivore"], ["savanna", "grassland"], ["africa", "asia"], "huge",
        synonyms=["rhino"], behavior=["horned", "solitary"], qid="Q191551"),
    mam("black-rhinoceros", "Diceros bicornis", "Rhinocerotidae", "Perissodactyla",
        ["herbivore"], ["savanna"], ["africa"], "huge", qid="Q191551"),
    mam("white-rhinoceros", "Ceratotherium simum", "Rhinocerotidae", "Perissodactyla",
        ["herbivore"], ["savanna"], ["africa"], "huge", qid="Q484126"),
    mam("giraffe", "Giraffa camelopardalis", "Giraffidae", "Artiodactyla",
        ["herbivore"], ["savanna"], ["africa"], "huge",
        behavior=["tallest-animal", "long-necked"], qid="Q15083"),
    mam("okapi", "Okapia johnstoni", "Giraffidae", "Artiodactyla",
        ["herbivore"], ["jungle"], ["central-africa"], "large", qid="Q40410"),
    mam("camel", "Camelus", "Camelidae", "Artiodactyla",
        ["herbivore"], ["desert"], ["north-africa", "middle-east", "central-asia"], "large",
        synonyms=["dromedary", "bactrian"], behavior=["desert-adapted", "hump"], qid="Q29469"),
    mam("dromedary", "Camelus dromedarius", "Camelidae", "Artiodactyla",
        ["herbivore"], ["desert"], ["north-africa", "middle-east"], "large",
        behavior=["single-hump"], qid="Q42569"),
    mam("bactrian-camel", "Camelus bactrianus", "Camelidae", "Artiodactyla",
        ["herbivore"], ["desert", "steppe"], ["central-asia"], "large",
        behavior=["two-hump"], qid="Q192053"),
    mam("llama", "Lama glama", "Camelidae", "Artiodactyla",
        ["herbivore"], ["mountain", "pasture"], ["south-america"], "large",
        behavior=["domesticated"], qid="Q42569"),
    mam("alpaca", "Vicugna pacos", "Camelidae", "Artiodactyla",
        ["herbivore"], ["mountain", "pasture"], ["south-america"], "medium",
        behavior=["domesticated", "fleece-bearing"], qid="Q46983"),
    mam("vicuna", "Vicugna vicugna", "Camelidae", "Artiodactyla",
        ["herbivore"], ["high-mountain"], ["south-america-andes"], "medium",
        qid="Q192053"),
    mam("guanaco", "Lama guanicoe", "Camelidae", "Artiodactyla",
        ["herbivore"], ["mountain", "grassland"], ["south-america"], "medium",
        qid="Q192053"),
    mam("hippopotamus", "Hippopotamus amphibius", "Hippopotamidae", "Artiodactyla",
        ["herbivore"], ["river", "wetland"], ["sub-saharan-africa"], "huge",
        synonyms=["hippo"], behavior=["aquatic", "dangerous"], qid="Q37437"),
    mam("pig", "Sus scrofa domesticus", "Suidae", "Artiodactyla",
        ["omnivore"], ["farm"], ["worldwide-domestic"], "medium",
        synonyms=["hog", "sow", "boar", "piglet", "swine"],
        behavior=["domesticated", "intelligent"], qid="Q787"),
    mam("wild-boar", "Sus scrofa", "Suidae", "Artiodactyla",
        ["omnivore"], ["forest"], ["eurasia"], "medium",
        synonyms=["boar"], qid="Q41417"),
    mam("warthog", "Phacochoerus africanus", "Suidae", "Artiodactyla",
        ["omnivore"], ["savanna"], ["africa"], "medium",
        behavior=["kneeling-forager"], qid="Q194123"),
    mam("peccary", "Tayassuidae", "Tayassuidae", "Artiodactyla",
        ["omnivore"], ["forest", "grassland"], ["americas"], "medium", qid="Q193459"),
]

# ---------------------------------------------------------------------------
# PROBOSCIDEA + AFROTHERIA (elephant, aardvark, hyrax, sengi)
# ---------------------------------------------------------------------------
NODES += [
    mam("elephant", "Loxodonta africana", "Elephantidae", "Proboscidea",
        ["herbivore"], ["savanna", "forest"], ["africa", "asia"], "massive",
        synonyms=["pachyderm"], behavior=["intelligent", "matriarchal", "trunked"],
        qid="Q7378"),
    mam("african-elephant", "Loxodonta africana", "Elephantidae", "Proboscidea",
        ["herbivore"], ["savanna"], ["africa"], "massive", qid="Q7378"),
    mam("asian-elephant", "Elephas maximus", "Elephantidae", "Proboscidea",
        ["herbivore"], ["forest", "grassland"], ["asia"], "massive", qid="Q40540"),
    mam("aardvark", "Orycteropus afer", "Orycteropodidae", "Tubulidentata",
        ["insectivore"], ["savanna"], ["africa"], "medium",
        behavior=["termite-eater", "nocturnal", "burrower"], tod=["night"],
        qid="Q40397"),
    mam("hyrax", "Procavia capensis", "Procaviidae", "Hyracoidea",
        ["herbivore"], ["rocky-outcrop"], ["africa", "middle-east"], "small",
        synonyms=["dassie"], qid="Q182123"),
    mam("elephant-shrew", "Macroscelididae", "Macroscelididae", "Macroscelidea",
        ["insectivore"], ["shrubland"], ["africa"], "tiny",
        synonyms=["sengi"], qid="Q194440"),
]

# ---------------------------------------------------------------------------
# RODENTIA + LAGOMORPHA
# ---------------------------------------------------------------------------
NODES += [
    mam("mouse", "Mus musculus", "Muridae", "Rodentia",
        ["omnivore"], ["human-settlement", "field"], ["worldwide"], "tiny",
        synonyms=["house-mouse"], behavior=["nocturnal", "burrowing"], tod=["night"],
        qid="Q39275"),
    mam("rat", "Rattus rattus", "Muridae", "Rodentia",
        ["omnivore"], ["human-settlement"], ["worldwide"], "small",
        synonyms=["black-rat", "brown-rat"], behavior=["intelligent", "social"],
        qid="Q184224"),
    mam("hamster", "Cricetus cricetus", "Cricetidae", "Rodentia",
        ["omnivore"], ["grassland", "pet"], ["europe", "worldwide-pet"], "tiny",
        behavior=["cheek-pouches", "nocturnal"], tod=["night"], qid="Q47859"),
    mam("gerbil", "Meriones unguiculatus", "Muridae", "Rodentia",
        ["omnivore"], ["desert", "pet"], ["mongolia", "worldwide-pet"], "tiny",
        qid="Q152358"),
    mam("guinea-pig", "Cavia porcellus", "Caviidae", "Rodentia",
        ["herbivore"], ["pet", "farm"], ["south-america", "worldwide-pet"], "small",
        synonyms=["cavy"], behavior=["domesticated", "vocal"], qid="Q79803"),
    mam("capybara", "Hydrochoerus hydrochaeris", "Caviidae", "Rodentia",
        ["herbivore"], ["wetland"], ["south-america"], "large",
        behavior=["largest-rodent", "social", "aquatic"], qid="Q26547"),
    mam("beaver", "Castor canadensis", "Castoridae", "Rodentia",
        ["herbivore"], ["river", "wetland"], ["north-america", "eurasia"], "medium",
        behavior=["dam-builder", "lodge-dwelling"], qid="Q29564"),
    mam("porcupine", "Erethizon dorsatum", "Erethizontidae", "Rodentia",
        ["herbivore"], ["forest"], ["north-america"], "medium",
        behavior=["quills-defense", "nocturnal"], qid="Q131172"),
    mam("hedgehog", "Erinaceus europaeus", "Erinaceidae", "Eulipotyphla",
        ["insectivore"], ["hedgerow", "garden"], ["europe"], "tiny",
        behavior=["spiny-defense", "nocturnal"], tod=["night"], qid="Q193331"),
    mam("shrew", "Sorex araneus", "Soricidae", "Eulipotyphla",
        ["insectivore"], ["forest", "grassland"], ["holarctic"], "tiny",
        behavior=["high-metabolism"], qid="Q47008"),
    mam("mole", "Talpa europaea", "Talpidae", "Eulipotyphla",
        ["insectivore"], ["underground"], ["europe"], "tiny",
        behavior=["burrower", "blind"], qid="Q47008"),
    mam("squirrel", "Sciurus carolinensis", "Sciuridae", "Rodentia",
        ["omnivore", "granivore"], ["forest", "park"], ["worldwide"], "small",
        synonyms=["tree-squirrel"], behavior=["diurnal", "climber", "caching"],
        qid="Q9482"),
    mam("gray-squirrel", "Sciurus carolinensis", "Sciuridae", "Rodentia",
        ["omnivore"], ["forest", "urban"], ["north-america"], "small", qid="Q1140328"),
    mam("red-squirrel", "Sciurus vulgaris", "Sciuridae", "Rodentia",
        ["omnivore"], ["forest"], ["eurasia"], "small", qid="Q194380"),
    mam("flying-squirrel", "Glaucomys volans", "Sciuridae", "Rodentia",
        ["omnivore"], ["forest"], ["north-america", "eurasia"], "tiny",
        behavior=["gliding"], tod=["night"], qid="Q192053"),
    mam("chipmunk", "Tamias striatus", "Sciuridae", "Rodentia",
        ["omnivore"], ["forest"], ["north-america"], "tiny",
        behavior=["striped", "caching"], qid="Q189521"),
    mam("groundhog", "Marmota monax", "Sciuridae", "Rodentia",
        ["herbivore"], ["grassland"], ["north-america"], "small",
        synonyms=["woodchuck"], behavior=["hibernator"], seasons=["winter"], qid="Q193459"),
    mam("marmot", "Marmota", "Sciuridae", "Rodentia",
        ["herbivore"], ["mountain"], ["holarctic"], "small",
        behavior=["hibernator", "whistling"], qid="Q193459"),
    mam("prairie-dog", "Cynomys ludovicianus", "Sciuridae", "Rodentia",
        ["herbivore"], ["prairie"], ["north-america"], "small",
        behavior=["colonial", "vocal", "burrower"], qid="Q194440"),
    mam("gopher", "Geomys bursarius", "Geomyidae", "Rodentia",
        ["herbivore"], ["grassland"], ["north-america"], "tiny",
        behavior=["burrower"], qid="Q194440"),
    mam("mole-rat", "Cryptomys hottentotus", "Bathyergidae", "Rodentia",
        ["herbivore"], ["underground"], ["africa"], "small",
        behavior=["subterranean", "eusocial"], qid="Q193459"),
    mam("naked-mole-rat", "Heterocephalus glaber", "Heterocephalidae", "Rodentia",
        ["herbivore"], ["underground"], ["east-africa"], "tiny",
        behavior=["eusocial", "long-lived"], qid="Q184644"),
    mam("chinchilla", "Chinchilla lanigera", "Chinchillidae", "Rodentia",
        ["herbivore"], ["mountain", "pet"], ["south-america-andes"], "small",
        behavior=["dust-bathing"], qid="Q184644"),
    mam("nutria", "Myocastor coypus", "Myocastoridae", "Rodentia",
        ["herbivore"], ["wetland"], ["south-america"], "small",
        synonyms=["coypu"], qid="Q194440"),
    mam("agouti", "Dasyprocta", "Dasyproctidae", "Rodentia",
        ["herbivore"], ["jungle"], ["central-america", "south-america"], "small",
        qid="Q193459"),
    mam("paca", "Cuniculus paca", "Cuniculidae", "Rodentia",
        ["herbivore"], ["jungle"], ["central-america", "south-america"], "small",
        qid="Q194380"),
    mam("rabbit", "Oryctolagus cuniculus", "Leporidae", "Lagomorpha",
        ["herbivore"], ["field", "hedgerow"], ["worldwide"], "small",
        synonyms=["bunny", "coney", "cottontail"],
        behavior=["burrower", "prolific"], qid="Q9394"),
    mam("hare", "Lepus europaeus", "Leporidae", "Lagomorpha",
        ["herbivore"], ["field", "grassland"], ["europe"], "small",
        synonyms=["jackrabbit"], behavior=["swift-runner"], qid="Q47083"),
    mam("cottontail", "Sylvilagus floridanus", "Leporidae", "Lagomorpha",
        ["herbivore"], ["field", "hedgerow"], ["north-america"], "small",
        qid="Q194440"),
    mam("pika", "Ochotona princeps", "Ochotonidae", "Lagomorpha",
        ["herbivore"], ["mountain-scree"], ["holarctic-mountains"], "tiny",
        behavior=["hay-gatherer"], qid="Q194440"),
]

# ---------------------------------------------------------------------------
# CHIROPTERA — bats
# ---------------------------------------------------------------------------
NODES += [
    mam("bat", "Chiroptera", "Vespertilionidae", "Chiroptera",
        ["insectivore", "frugivore"], ["cave", "forest"], ["worldwide"], "tiny",
        behavior=["flying", "nocturnal", "echo-locating"], tod=["night"], qid="Q28425"),
    mam("fruit-bat", "Pteropodidae", "Pteropodidae", "Chiroptera",
        ["frugivore"], ["forest"], ["africa", "asia", "oceania"], "small",
        synonyms=["flying-fox"], qid="Q52947"),
    mam("vampire-bat", "Desmodus rotundus", "Phyllostomidae", "Chiroptera",
        ["carnivore"], ["cave"], ["central-america", "south-america"], "tiny",
        behavior=["blood-feeding"], tod=["night"], qid="Q189721"),
    mam("brown-bat", "Eptesicus fuscus", "Vespertilionidae", "Chiroptera",
        ["insectivore"], ["forest", "urban"], ["north-america"], "tiny",
        qid="Q189721"),
]

# ---------------------------------------------------------------------------
# PRIMATES
# ---------------------------------------------------------------------------
NODES += [
    mam("human", "Homo sapiens", "Hominidae", "Primates",
        ["omnivore"], ["worldwide"], ["worldwide"], "medium",
        synonyms=["person", "people", "man", "woman", "child"],
        behavior=["bipedal", "tool-user", "language"], qid="Q5"),
    mam("chimpanzee", "Pan troglodytes", "Hominidae", "Primates",
        ["omnivore"], ["jungle"], ["central-africa"], "medium",
        synonyms=["chimp"], behavior=["tool-user", "social"], qid="Q26547"),
    mam("bonobo", "Pan paniscus", "Hominidae", "Primates",
        ["omnivore"], ["jungle"], ["congo-basin"], "medium",
        behavior=["peaceful", "matriarchal"], qid="Q41171"),
    mam("gorilla", "Gorilla gorilla", "Hominidae", "Primates",
        ["herbivore"], ["jungle"], ["central-africa"], "large",
        behavior=["family-group", "silverback"], qid="Q36611"),
    mam("orangutan", "Pongo pygmaeus", "Hominidae", "Primates",
        ["frugivore"], ["jungle"], ["borneo", "sumatra"], "large",
        behavior=["arboreal", "solitary"], qid="Q41050"),
    mam("gibbon", "Hylobates lar", "Hylobatidae", "Primates",
        ["frugivore"], ["jungle"], ["southeast-asia"], "medium",
        behavior=["arboreal", "brachiator", "singing"], qid="Q42571"),
    mam("baboon", "Papio", "Cercopithecidae", "Primates",
        ["omnivore"], ["savanna"], ["africa"], "medium",
        behavior=["troop-living", "terrestrial"], qid="Q131323"),
    mam("mandrill", "Mandrillus sphinx", "Cercopithecidae", "Primates",
        ["omnivore"], ["jungle"], ["central-africa"], "medium",
        behavior=["colorful-face"], qid="Q193459"),
    mam("macaque", "Macaca", "Cercopithecidae", "Primates",
        ["omnivore"], ["forest"], ["asia"], "small", qid="Q194336"),
    mam("proboscis-monkey", "Nasalis larvatus", "Cercopithecidae", "Primates",
        ["folivore"], ["mangrove"], ["borneo"], "medium",
        behavior=["long-nose"], qid="Q193459"),
    mam("colobus", "Colobus guereza", "Cercopithecidae", "Primates",
        ["folivore"], ["forest"], ["africa"], "small",
        behavior=["black-and-white"], qid="Q194336"),
    mam("langur", "Semnopithecus", "Cercopithecidae", "Primates",
        ["folivore"], ["forest"], ["asia"], "small", qid="Q193459"),
    mam("capuchin-monkey", "Cebus capucinus", "Cebidae", "Primates",
        ["omnivore"], ["jungle"], ["central-america", "south-america"], "small",
        behavior=["tool-user", "arboreal"], qid="Q194336"),
    mam("squirrel-monkey", "Saimiri sciureus", "Cebidae", "Primates",
        ["omnivore"], ["jungle"], ["south-america"], "small", qid="Q193459"),
    mam("howler-monkey", "Alouatta", "Atelidae", "Primates",
        ["folivore"], ["jungle"], ["central-america", "south-america"], "small",
        behavior=["loud-vocals"], qid="Q193459"),
    mam("spider-monkey", "Ateles", "Atelidae", "Primates",
        ["frugivore"], ["jungle"], ["central-america", "south-america"], "small",
        behavior=["prehensile-tail"], qid="Q193459"),
    mam("marmoset", "Callithrix", "Callitrichidae", "Primates",
        ["omnivore"], ["jungle"], ["south-america"], "tiny", qid="Q193459"),
    mam("tamarin", "Saguinus", "Callitrichidae", "Primates",
        ["omnivore"], ["jungle"], ["south-america"], "tiny", qid="Q193459"),
    mam("lemur", "Lemur catta", "Lemuridae", "Primates",
        ["frugivore"], ["forest"], ["madagascar"], "small",
        synonyms=["ring-tailed-lemur"], behavior=["arboreal"], qid="Q52947"),
    mam("aye-aye", "Daubentonia madagascariensis", "Daubentoniidae", "Primates",
        ["insectivore"], ["forest"], ["madagascar"], "small",
        behavior=["nocturnal", "tap-foraging"], qid="Q47483"),
    mam("tarsier", "Tarsius", "Tarsiidae", "Primates",
        ["carnivore"], ["jungle"], ["southeast-asia"], "tiny",
        behavior=["nocturnal", "huge-eyes"], tod=["night"], qid="Q193459"),
    mam("loris", "Nycticebus", "Lorisidae", "Primates",
        ["omnivore"], ["jungle"], ["asia"], "tiny",
        behavior=["nocturnal", "slow-moving"], tod=["night"], qid="Q193459"),
    mam("bushbaby", "Galago", "Galagidae", "Primates",
        ["omnivore"], ["forest"], ["africa"], "tiny",
        synonyms=["galago"], behavior=["nocturnal"], tod=["night"], qid="Q193459"),
]

# ---------------------------------------------------------------------------
# MARSUPIALS + MONOTREMES
# ---------------------------------------------------------------------------
NODES += [
    mam("kangaroo", "Macropus", "Macropodidae", "Diprotodontia",
        ["herbivore"], ["grassland"], ["australia"], "large",
        synonyms=["roo"], behavior=["hopping", "pouch-bearing"], qid="Q41112"),
    mam("wallaby", "Wallabia bicolor", "Macropodidae", "Diprotodontia",
        ["herbivore"], ["forest", "scrubland"], ["australia"], "medium",
        qid="Q41112"),
    mam("koala", "Phascolarctos cinereus", "Phascolarctidae", "Diprotodontia",
        ["folivore"], ["eucalyptus-forest"], ["australia"], "small",
        behavior=["arboreal", "eucalyptus-diet"], qid="Q36279"),
    mam("wombat", "Vombatus ursinus", "Vombatidae", "Diprotodontia",
        ["herbivore"], ["forest"], ["australia"], "medium",
        behavior=["burrower", "cube-shaped-scat"], qid="Q47483"),
    mam("possum", "Trichosurus vulpecula", "Phalangeridae", "Diprotodontia",
        ["omnivore"], ["forest"], ["australia"], "small",
        synonyms=["brushtail-possum"], tod=["night"], qid="Q192053"),
    mam("opossum", "Didelphis virginiana", "Didelphidae", "Didelphimorphia",
        ["omnivore"], ["forest", "urban"], ["americas"], "small",
        behavior=["playing-dead"], tod=["night"], qid="Q3277"),
    mam("tasmanian-devil", "Sarcophilus harrisii", "Dasyuridae", "Dasyuromorphia",
        ["carnivore", "scavenger"], ["forest"], ["tasmania"], "small",
        behavior=["nocturnal", "vocal"], tod=["night"], qid="Q26547"),
    mam("platypus", "Ornithorhynchus anatinus", "Ornithorhynchidae", "Monotremata",
        ["carnivore"], ["river"], ["australia"], "small",
        behavior=["egg-laying-mammal", "bill", "venomous"], qid="Q46599"),
    mam("echidna", "Tachyglossus aculeatus", "Tachyglossidae", "Monotremata",
        ["insectivore"], ["forest"], ["australia"], "small",
        behavior=["egg-laying-mammal", "spiny"], qid="Q193459"),
    mam("bandicoot", "Perameles", "Peramelidae", "Peramelemorphia",
        ["omnivore"], ["forest"], ["australia"], "small", qid="Q193459"),
    mam("bilby", "Macrotis lagotis", "Thylacomyidae", "Peramelemorphia",
        ["omnivore"], ["desert"], ["australia"], "small", qid="Q193459"),
    mam("sugar-glider", "Petaurus breviceps", "Petauridae", "Diprotodontia",
        ["omnivore"], ["forest"], ["australia"], "tiny",
        behavior=["gliding"], tod=["night"], qid="Q194336"),
]

# ---------------------------------------------------------------------------
# XENARTHRA + PANGOLINS + OTHER
# ---------------------------------------------------------------------------
NODES += [
    mam("sloth", "Bradypus variegatus", "Bradypodidae", "Pilosa",
        ["folivore"], ["jungle"], ["central-america", "south-america"], "medium",
        behavior=["slow", "arboreal"], qid="Q127367"),
    mam("armadillo", "Dasypus novemcinctus", "Dasypodidae", "Cingulata",
        ["insectivore"], ["grassland", "forest"], ["americas"], "small",
        behavior=["armor-plated", "burrower"], qid="Q193459"),
    mam("anteater", "Myrmecophaga tridactyla", "Myrmecophagidae", "Pilosa",
        ["insectivore"], ["savanna"], ["central-america", "south-america"], "medium",
        synonyms=["giant-anteater"], behavior=["long-tongue"], qid="Q193459"),
    mam("pangolin", "Manis", "Manidae", "Pholidota",
        ["insectivore"], ["forest", "savanna"], ["africa", "asia"], "medium",
        behavior=["scaled", "rolls-into-ball"], qid="Q193459"),
]
