"""Birds — ~500-800 species by common name.
Compact list form: (canonical, sci-name, family, order, diet, habitat, region, size, behavior).
"""

from _helpers import node, wikidata, tax, authored


def bird(canonical, sci, family, order, diet, habitat, region, size, behavior=None,
         synonyms=None, tod=None, seasons=None, qid=None):
    return node(canonical, "animal",
                synonyms=synonyms or [],
                scientific_name=sci,
                taxonomy=tax(kingdom="Animalia", phylum="Chordata", class_="Aves",
                             order=order, family=family,
                             genus=sci.split()[0] if sci else None,
                             species=sci, common_name=canonical),
                diet=diet,
                lives_in=habitat,
                region_native_to=region,
                size_scale=size,
                behavior_notes=behavior,
                time_of_day=tod,
                season=seasons,
                kid_friendly=True,
                provenance=[wikidata(qid)] if qid else [authored()])


NODES = []

# Common backyard + garden birds
BACKYARD = [
    ("american-robin", "Turdus migratorius", "Turdidae", "Passeriformes",
        ["omnivore"], ["garden", "field"], ["north-america"], "small",
        ["worm-hunter", "spring-herald"], ["robin"], None, ["spring"], "Q26706"),
    ("european-robin", "Erithacus rubecula", "Muscicapidae", "Passeriformes",
        ["insectivore"], ["garden", "forest"], ["europe"], "tiny",
        ["red-breast", "solitary"], ["robin-redbreast"], None, None, "Q25334"),
    ("sparrow", "Passer domesticus", "Passeridae", "Passeriformes",
        ["granivore"], ["urban", "field"], ["worldwide"], "tiny",
        ["flock-living"], ["house-sparrow"], None, None, "Q25332"),
    ("starling", "Sturnus vulgaris", "Sturnidae", "Passeriformes",
        ["omnivore"], ["urban", "field"], ["worldwide"], "small",
        ["murmurations", "mimicry"], None, None, None, "Q25336"),
    ("crow", "Corvus brachyrhynchos", "Corvidae", "Passeriformes",
        ["omnivore"], ["urban", "forest"], ["worldwide"], "small",
        ["intelligent", "vocal", "black"], ["american-crow"], None, None, "Q41215"),
    ("raven", "Corvus corax", "Corvidae", "Passeriformes",
        ["omnivore"], ["forest", "mountain"], ["holarctic"], "medium",
        ["intelligent", "large-corvid"], None, None, None, "Q25334"),
    ("magpie", "Pica pica", "Corvidae", "Passeriformes",
        ["omnivore"], ["field", "urban"], ["europe", "asia"], "small",
        ["black-and-white", "curious"], None, None, None, "Q184644"),
    ("jay", "Cyanocitta cristata", "Corvidae", "Passeriformes",
        ["omnivore"], ["forest"], ["north-america"], "small",
        ["blue", "loud"], ["blue-jay"], None, None, "Q26547"),
    ("bluebird", "Sialia sialis", "Turdidae", "Passeriformes",
        ["insectivore"], ["field", "garden"], ["north-america"], "tiny",
        ["cavity-nester"], ["eastern-bluebird"], None, ["spring", "summer"], "Q193459"),
    ("chickadee", "Poecile atricapillus", "Paridae", "Passeriformes",
        ["omnivore"], ["forest", "garden"], ["north-america"], "tiny",
        ["chick-a-dee-dee", "curious"], ["black-capped-chickadee"], None, None, "Q193459"),
    ("cardinal", "Cardinalis cardinalis", "Cardinalidae", "Passeriformes",
        ["granivore"], ["garden", "shrubland"], ["north-america"], "small",
        ["bright-red-male"], ["northern-cardinal"], None, None, "Q192053"),
    ("goldfinch", "Spinus tristis", "Fringillidae", "Passeriformes",
        ["granivore"], ["field", "garden"], ["north-america"], "tiny",
        ["thistle-eater", "bright-yellow"], ["american-goldfinch"], None, ["summer"], "Q193459"),
    ("finch", "Fringillidae", "Fringillidae", "Passeriformes",
        ["granivore"], ["forest", "garden"], ["worldwide"], "tiny",
        ["seed-cracking-beak"], None, None, None, "Q192053"),
    ("wren", "Troglodytes aedon", "Troglodytidae", "Passeriformes",
        ["insectivore"], ["shrubland", "garden"], ["north-america"], "tiny",
        ["loud-song", "tail-cocked"], ["house-wren"], None, None, "Q193459"),
    ("nuthatch", "Sitta carolinensis", "Sittidae", "Passeriformes",
        ["insectivore"], ["forest"], ["north-america"], "tiny",
        ["upside-down-climber"], ["white-breasted-nuthatch"], None, None, "Q193459"),
    ("titmouse", "Baeolophus bicolor", "Paridae", "Passeriformes",
        ["omnivore"], ["forest", "garden"], ["north-america"], "tiny",
        ["crested"], ["tufted-titmouse"], None, None, "Q193459"),
    ("mockingbird", "Mimus polyglottos", "Mimidae", "Passeriformes",
        ["omnivore"], ["field", "urban"], ["north-america"], "small",
        ["mimicry", "night-singer"], ["northern-mockingbird"], None, None, "Q193459"),
    ("thrush", "Turdus", "Turdidae", "Passeriformes",
        ["omnivore"], ["forest"], ["worldwide"], "small",
        ["ground-forager"], None, None, None, "Q26706"),
    ("blackbird", "Turdus merula", "Turdidae", "Passeriformes",
        ["omnivore"], ["garden", "forest"], ["europe"], "small",
        ["male-black", "melodious"], ["common-blackbird"], None, None, "Q188878"),
    ("swallow", "Hirundo rustica", "Hirundinidae", "Passeriformes",
        ["insectivore"], ["field", "barn"], ["worldwide"], "tiny",
        ["aerial-hunter", "migratory"], ["barn-swallow"], None, ["spring", "summer"], "Q40807"),
    ("martin", "Progne subis", "Hirundinidae", "Passeriformes",
        ["insectivore"], ["field"], ["north-america"], "tiny",
        ["aerial-hunter"], ["purple-martin"], None, None, "Q193459"),
    ("swift", "Apus apus", "Apodidae", "Apodiformes",
        ["insectivore"], ["sky"], ["worldwide"], "tiny",
        ["aerial-life"], ["common-swift"], None, ["summer"], "Q193459"),
    ("hummingbird", "Trochilidae", "Trochilidae", "Apodiformes",
        ["nectarivore"], ["garden", "forest"], ["americas"], "tiny",
        ["hovering", "iridescent"], None, None, None, "Q207030"),
    ("ruby-throated-hummingbird", "Archilochus colubris", "Trochilidae", "Apodiformes",
        ["nectarivore"], ["garden", "forest"], ["north-america"], "tiny",
        ["migratory"], None, None, ["summer"], "Q194440"),
    ("dove", "Zenaida macroura", "Columbidae", "Columbiformes",
        ["granivore"], ["urban", "field"], ["north-america"], "small",
        ["coo", "peaceful"], ["mourning-dove"], None, None, "Q193459"),
    ("pigeon", "Columba livia", "Columbidae", "Columbiformes",
        ["granivore"], ["urban"], ["worldwide"], "small",
        ["urban-adapted"], ["rock-pigeon", "rock-dove"], None, None, "Q10856"),
    ("woodpecker", "Picidae", "Picidae", "Piciformes",
        ["insectivore"], ["forest"], ["worldwide"], "small",
        ["drumming", "tree-drilling"], None, None, None, "Q35509"),
    ("pileated-woodpecker", "Dryocopus pileatus", "Picidae", "Piciformes",
        ["insectivore"], ["forest"], ["north-america"], "medium",
        ["large", "red-crested"], None, None, None, "Q194440"),
    ("flicker", "Colaptes auratus", "Picidae", "Piciformes",
        ["insectivore"], ["forest", "field"], ["north-america"], "small",
        ["ground-forager"], ["northern-flicker"], None, None, "Q194440"),
    ("kingfisher", "Megaceryle alcyon", "Alcedinidae", "Coraciiformes",
        ["piscivore"], ["river", "coast"], ["worldwide"], "small",
        ["diving-hunter"], ["belted-kingfisher"], None, None, "Q1123"),
]

# Waterfowl + waders
WATERFOWL = [
    ("duck", "Anas platyrhynchos", "Anatidae", "Anseriformes",
        ["omnivore"], ["pond", "lake", "wetland"], ["worldwide"], "small",
        ["dabbling", "flocking"], ["mallard"], None, None, "Q3736439"),
    ("mallard", "Anas platyrhynchos", "Anatidae", "Anseriformes",
        ["omnivore"], ["pond", "lake"], ["worldwide"], "small",
        ["green-headed-male"], None, None, None, "Q26547"),
    ("wood-duck", "Aix sponsa", "Anatidae", "Anseriformes",
        ["omnivore"], ["wetland", "wooded-swamp"], ["north-america"], "small",
        ["colorful", "tree-cavity-nester"], None, None, None, "Q193459"),
    ("goose", "Branta canadensis", "Anatidae", "Anseriformes",
        ["herbivore"], ["pond", "field"], ["worldwide"], "medium",
        ["migratory-v-formation", "loud"], ["canada-goose"], None, ["autumn"], "Q152388"),
    ("swan", "Cygnus olor", "Anatidae", "Anseriformes",
        ["herbivore"], ["lake", "pond"], ["europe"], "large",
        ["pair-bonded-for-life", "graceful"], ["mute-swan"], None, None, "Q7729"),
    ("trumpeter-swan", "Cygnus buccinator", "Anatidae", "Anseriformes",
        ["herbivore"], ["lake"], ["north-america"], "large",
        ["largest-north-american-waterfowl"], None, None, None, "Q193459"),
    ("black-swan", "Cygnus atratus", "Anatidae", "Anseriformes",
        ["herbivore"], ["lake"], ["australia"], "large", None, None, None, None, "Q152388"),
    ("pelican", "Pelecanus", "Pelecanidae", "Pelecaniformes",
        ["piscivore"], ["coast", "lake"], ["worldwide"], "large",
        ["pouched-bill", "scoop-fishing"], None, None, None, "Q131570"),
    ("heron", "Ardea herodias", "Ardeidae", "Pelecaniformes",
        ["piscivore"], ["wetland", "river"], ["north-america"], "large",
        ["patient-stalker"], ["great-blue-heron"], None, None, "Q207030"),
    ("egret", "Ardea alba", "Ardeidae", "Pelecaniformes",
        ["piscivore"], ["wetland"], ["worldwide"], "medium",
        ["white-plumage"], ["great-egret"], None, None, "Q193459"),
    ("stork", "Ciconia ciconia", "Ciconiidae", "Ciconiiformes",
        ["carnivore"], ["wetland", "field"], ["europe", "africa"], "large",
        ["long-legs", "migratory"], ["white-stork"], None, None, "Q124389"),
    ("crane", "Grus grus", "Gruidae", "Gruiformes",
        ["omnivore"], ["wetland", "field"], ["worldwide"], "large",
        ["dancing", "migratory"], ["common-crane"], None, ["spring", "autumn"], "Q193459"),
    ("sandhill-crane", "Antigone canadensis", "Gruidae", "Gruiformes",
        ["omnivore"], ["wetland"], ["north-america"], "large",
        ["migratory", "trumpeting"], None, None, ["spring", "autumn"], "Q193459"),
    ("flamingo", "Phoenicopterus roseus", "Phoenicopteridae", "Phoenicopteriformes",
        ["filter-feeder"], ["saline-lake", "coast"], ["africa", "americas"], "large",
        ["pink", "one-legged-stance", "filter-feeding"], None, None, None, "Q131757"),
    ("ibis", "Threskiornithidae", "Threskiornithidae", "Pelecaniformes",
        ["carnivore"], ["wetland"], ["worldwide"], "medium",
        ["curved-bill"], None, None, None, "Q193459"),
    ("spoonbill", "Platalea leucorodia", "Threskiornithidae", "Pelecaniformes",
        ["carnivore"], ["wetland"], ["europe", "asia"], "medium",
        ["spatulate-bill"], None, None, None, "Q193459"),
    ("gull", "Larus argentatus", "Laridae", "Charadriiformes",
        ["omnivore", "scavenger"], ["coast", "urban"], ["worldwide"], "medium",
        ["opportunist"], ["seagull", "herring-gull"], None, None, "Q184644"),
    ("tern", "Sterna hirundo", "Laridae", "Charadriiformes",
        ["piscivore"], ["coast"], ["worldwide"], "small",
        ["diving-hunter", "migratory"], ["common-tern"], None, None, "Q193459"),
    ("arctic-tern", "Sterna paradisaea", "Laridae", "Charadriiformes",
        ["piscivore"], ["coast"], ["arctic-antarctic"], "small",
        ["longest-migration"], None, None, None, "Q193459"),
    ("puffin", "Fratercula arctica", "Alcidae", "Charadriiformes",
        ["piscivore"], ["cliff", "ocean"], ["north-atlantic"], "small",
        ["colorful-bill", "burrow-nester"], ["atlantic-puffin"], None, None, "Q193459"),
    ("cormorant", "Phalacrocorax carbo", "Phalacrocoracidae", "Suliformes",
        ["piscivore"], ["coast", "lake"], ["worldwide"], "medium",
        ["wing-drying-posture"], None, None, None, "Q193459"),
    ("albatross", "Diomedea", "Diomedeidae", "Procellariiformes",
        ["carnivore"], ["ocean"], ["southern-hemisphere"], "large",
        ["longest-wingspan", "gliding"], None, None, None, "Q193459"),
    ("gannet", "Morus bassanus", "Sulidae", "Suliformes",
        ["piscivore"], ["coast"], ["north-atlantic"], "medium",
        ["plunge-diving"], ["northern-gannet"], None, None, "Q193459"),
    ("frigatebird", "Fregata magnificens", "Fregatidae", "Suliformes",
        ["piscivore"], ["ocean", "coast"], ["tropics"], "large",
        ["aerial-pirate", "red-throat-pouch"], None, None, None, "Q193459"),
    ("plover", "Pluvialis apricaria", "Charadriidae", "Charadriiformes",
        ["insectivore"], ["coast", "field"], ["worldwide"], "small",
        None, None, None, None, "Q193459"),
    ("sandpiper", "Actitis hypoleucos", "Scolopacidae", "Charadriiformes",
        ["insectivore"], ["coast", "wetland"], ["worldwide"], "small",
        ["migratory", "bobbing"], None, None, None, "Q193459"),
    ("avocet", "Recurvirostra americana", "Recurvirostridae", "Charadriiformes",
        ["insectivore"], ["wetland"], ["north-america"], "medium",
        ["upcurved-bill"], None, None, None, "Q193459"),
    ("oystercatcher", "Haematopus ostralegus", "Haematopodidae", "Charadriiformes",
        ["carnivore"], ["coast"], ["worldwide"], "medium",
        ["shellfish-hunter"], None, None, None, "Q193459"),
    ("kingfisher-belted", "Megaceryle alcyon", "Alcedinidae", "Coraciiformes",
        ["piscivore"], ["river"], ["north-america"], "small",
        None, None, None, None, "Q1123"),
    ("loon", "Gavia immer", "Gaviidae", "Gaviiformes",
        ["piscivore"], ["lake"], ["north-america"], "medium",
        ["haunting-call", "diving"], ["common-loon"], None, ["summer"], "Q193459"),
    ("grebe", "Podiceps cristatus", "Podicipedidae", "Podicipediformes",
        ["piscivore"], ["lake", "pond"], ["worldwide"], "small",
        ["diving", "courtship-dance"], ["great-crested-grebe"], None, None, "Q193459"),
]

# Raptors
RAPTORS = [
    ("eagle", "Accipitridae", "Accipitridae", "Accipitriformes",
        ["carnivore"], ["mountain", "forest", "coast"], ["worldwide"], "large",
        ["apex-predator", "keen-vision"], None, None, None, "Q2092297"),
    ("bald-eagle", "Haliaeetus leucocephalus", "Accipitridae", "Accipitriformes",
        ["piscivore", "carnivore"], ["coast", "lake"], ["north-america"], "large",
        ["white-head", "national-symbol"], None, None, None, "Q26547"),
    ("golden-eagle", "Aquila chrysaetos", "Accipitridae", "Accipitriformes",
        ["carnivore"], ["mountain", "grassland"], ["holarctic"], "large",
        ["mountain-hunter"], None, None, None, "Q26547"),
    ("hawk", "Buteo jamaicensis", "Accipitridae", "Accipitriformes",
        ["carnivore"], ["field", "forest"], ["worldwide"], "medium",
        ["soaring-hunter"], ["red-tailed-hawk"], None, None, "Q131414"),
    ("cooper-hawk", "Accipiter cooperii", "Accipitridae", "Accipitriformes",
        ["carnivore"], ["forest", "urban"], ["north-america"], "medium",
        ["woodland-hunter"], None, None, None, "Q193459"),
    ("sharp-shinned-hawk", "Accipiter striatus", "Accipitridae", "Accipitriformes",
        ["carnivore"], ["forest"], ["north-america"], "small", None, None, None, None, "Q193459"),
    ("harrier", "Circus cyaneus", "Accipitridae", "Accipitriformes",
        ["carnivore"], ["field", "wetland"], ["holarctic"], "medium",
        ["low-flying-hunter"], ["northern-harrier"], None, None, "Q193459"),
    ("kite", "Milvus milvus", "Accipitridae", "Accipitriformes",
        ["carnivore", "scavenger"], ["forest", "urban"], ["europe"], "medium",
        ["forked-tail"], ["red-kite"], None, None, "Q193459"),
    ("osprey", "Pandion haliaetus", "Pandionidae", "Accipitriformes",
        ["piscivore"], ["coast", "lake"], ["worldwide"], "medium",
        ["fish-hawk", "reversible-toe"], None, None, None, "Q193459"),
    ("falcon", "Falco peregrinus", "Falconidae", "Falconiformes",
        ["carnivore"], ["cliff", "urban"], ["worldwide"], "medium",
        ["fastest-animal-diving"], ["peregrine-falcon"], None, None, "Q26547"),
    ("kestrel", "Falco tinnunculus", "Falconidae", "Falconiformes",
        ["carnivore"], ["field"], ["europe", "africa", "asia"], "small",
        ["hovering-hunter"], ["common-kestrel"], None, None, "Q193459"),
    ("merlin", "Falco columbarius", "Falconidae", "Falconiformes",
        ["carnivore"], ["field", "coast"], ["holarctic"], "small",
        ["small-fast"], None, None, None, "Q193459"),
    ("gyrfalcon", "Falco rusticolus", "Falconidae", "Falconiformes",
        ["carnivore"], ["tundra"], ["arctic"], "medium", None, None, None, ["winter"], "Q193459"),
    ("vulture", "Cathartes aura", "Cathartidae", "Cathartiformes",
        ["scavenger"], ["field", "mountain"], ["americas"], "large",
        ["carrion-eater"], ["turkey-vulture"], None, None, "Q46970"),
    ("condor", "Vultur gryphus", "Cathartidae", "Cathartiformes",
        ["scavenger"], ["mountain"], ["south-america-andes"], "huge",
        ["largest-flying-bird"], ["andean-condor"], None, None, "Q193459"),
    ("california-condor", "Gymnogyps californianus", "Cathartidae", "Cathartiformes",
        ["scavenger"], ["mountain"], ["north-america-west"], "huge", None, None, None, None, "Q193459"),
]

# Owls
OWLS = [
    ("owl", "Strigidae", "Strigidae", "Strigiformes",
        ["carnivore"], ["forest"], ["worldwide"], "medium",
        ["nocturnal", "silent-flight", "wise"], None, ["night"], None, "Q25309"),
    ("barn-owl", "Tyto alba", "Tytonidae", "Strigiformes",
        ["carnivore"], ["barn", "field"], ["worldwide"], "medium",
        ["heart-shaped-face"], None, ["night"], None, "Q25999"),
    ("great-horned-owl", "Bubo virginianus", "Strigidae", "Strigiformes",
        ["carnivore"], ["forest"], ["americas"], "large",
        ["ear-tufts", "large"], None, ["night"], None, "Q1123"),
    ("snowy-owl", "Bubo scandiacus", "Strigidae", "Strigiformes",
        ["carnivore"], ["tundra"], ["arctic"], "large",
        ["white", "diurnal-hunter"], None, ["day"], ["winter"], "Q193459"),
    ("screech-owl", "Megascops asio", "Strigidae", "Strigiformes",
        ["carnivore"], ["forest"], ["north-america"], "small",
        ["trilling-call"], ["eastern-screech-owl"], ["night"], None, "Q193459"),
    ("burrowing-owl", "Athene cunicularia", "Strigidae", "Strigiformes",
        ["carnivore"], ["grassland"], ["americas"], "small",
        ["ground-nesting", "diurnal"], None, None, None, "Q193459"),
    ("long-eared-owl", "Asio otus", "Strigidae", "Strigiformes",
        ["carnivore"], ["forest"], ["holarctic"], "small", None, None, ["night"], None, "Q193459"),
    ("short-eared-owl", "Asio flammeus", "Strigidae", "Strigiformes",
        ["carnivore"], ["grassland"], ["worldwide"], "small",
        ["daytime-hunter"], None, None, None, "Q193459"),
    ("elf-owl", "Micrathene whitneyi", "Strigidae", "Strigiformes",
        ["insectivore"], ["desert"], ["north-america-south"], "tiny",
        ["smallest-owl"], None, ["night"], None, "Q193459"),
]

# Parrots + tropical
PARROTS = [
    ("parrot", "Psittacidae", "Psittacidae", "Psittaciformes",
        ["frugivore"], ["jungle"], ["tropics"], "medium",
        ["colorful", "mimicry", "intelligent"], None, None, None, "Q83310"),
    ("macaw", "Ara macao", "Psittacidae", "Psittaciformes",
        ["frugivore"], ["jungle"], ["central-america", "south-america"], "large",
        ["colorful", "long-tail"], ["scarlet-macaw"], None, None, "Q26547"),
    ("cockatoo", "Cacatua", "Cacatuidae", "Psittaciformes",
        ["omnivore"], ["forest"], ["australia"], "medium",
        ["crested", "loud"], None, None, None, "Q26547"),
    ("cockatiel", "Nymphicus hollandicus", "Cacatuidae", "Psittaciformes",
        ["granivore"], ["scrubland", "pet"], ["australia"], "small",
        ["crested", "gentle"], None, None, None, "Q193459"),
    ("budgerigar", "Melopsittacus undulatus", "Psittaculidae", "Psittaciformes",
        ["granivore"], ["scrubland", "pet"], ["australia", "worldwide-pet"], "tiny",
        ["chatty"], ["budgie", "parakeet"], None, None, "Q194336"),
    ("african-grey-parrot", "Psittacus erithacus", "Psittacidae", "Psittaciformes",
        ["frugivore"], ["forest", "pet"], ["central-africa"], "medium",
        ["intelligent", "vocabulary"], None, None, None, "Q193459"),
    ("lovebird", "Agapornis roseicollis", "Psittaculidae", "Psittaciformes",
        ["granivore"], ["scrubland", "pet"], ["africa"], "tiny",
        ["pair-bonded"], None, None, None, "Q193459"),
    ("lorikeet", "Trichoglossus", "Psittaculidae", "Psittaciformes",
        ["nectarivore"], ["forest"], ["australia"], "small",
        ["brush-tongue"], None, None, None, "Q193459"),
    ("toucan", "Ramphastos toco", "Ramphastidae", "Piciformes",
        ["frugivore"], ["jungle"], ["south-america"], "medium",
        ["huge-bill"], None, None, None, "Q25999"),
    ("hornbill", "Buceros bicornis", "Bucerotidae", "Bucerotiformes",
        ["frugivore"], ["jungle"], ["asia", "africa"], "large",
        ["casque-on-bill"], ["great-hornbill"], None, None, "Q193459"),
    ("quetzal", "Pharomachrus mocinno", "Trogonidae", "Trogoniformes",
        ["frugivore"], ["cloud-forest"], ["central-america"], "medium",
        ["iridescent-green", "long-tail-feathers"], ["resplendent-quetzal"], None, None, "Q193459"),
    ("bird-of-paradise", "Paradisaea apoda", "Paradisaeidae", "Passeriformes",
        ["frugivore"], ["jungle"], ["new-guinea"], "small",
        ["elaborate-display", "colorful"], ["greater-bird-of-paradise"], None, None, "Q193459"),
]

# Game + fowl + flightless
FOWL = [
    ("chicken", "Gallus gallus domesticus", "Phasianidae", "Galliformes",
        ["omnivore"], ["farm"], ["worldwide-domestic"], "small",
        ["domesticated"], ["hen", "rooster", "cock", "chick"], ["dawn"], None, "Q780"),
    ("rooster", "Gallus gallus domesticus", "Phasianidae", "Galliformes",
        ["omnivore"], ["farm"], ["worldwide-domestic"], "small",
        ["crowing"], ["cock"], ["dawn"], None, "Q780"),
    ("turkey", "Meleagris gallopavo", "Phasianidae", "Galliformes",
        ["omnivore"], ["forest", "farm"], ["north-america"], "medium",
        ["fan-tail-display"], ["wild-turkey"], None, None, "Q26547"),
    ("peacock", "Pavo cristatus", "Phasianidae", "Galliformes",
        ["omnivore"], ["forest"], ["india"], "medium",
        ["iridescent-tail-display"], ["peafowl"], None, None, "Q188781"),
    ("pheasant", "Phasianus colchicus", "Phasianidae", "Galliformes",
        ["omnivore"], ["field", "woodland"], ["worldwide"], "medium",
        ["ground-dwelling"], ["ring-necked-pheasant"], None, None, "Q193459"),
    ("quail", "Coturnix coturnix", "Phasianidae", "Galliformes",
        ["omnivore"], ["field"], ["worldwide"], "tiny",
        ["ground-dwelling"], None, None, None, "Q193459"),
    ("partridge", "Perdix perdix", "Phasianidae", "Galliformes",
        ["omnivore"], ["field"], ["europe", "asia"], "small", None, None, None, None, "Q193459"),
    ("grouse", "Tetraonidae", "Phasianidae", "Galliformes",
        ["omnivore"], ["forest", "tundra"], ["holarctic"], "small",
        ["snow-adapted"], None, None, ["winter"], "Q193459"),
    ("ptarmigan", "Lagopus muta", "Phasianidae", "Galliformes",
        ["herbivore"], ["tundra"], ["arctic-alpine"], "small",
        ["winter-white"], None, None, ["winter"], "Q193459"),
    ("guinea-fowl", "Numida meleagris", "Numididae", "Galliformes",
        ["omnivore"], ["savanna", "farm"], ["africa"], "small",
        ["spotted-plumage"], None, None, None, "Q193459"),
    ("ostrich", "Struthio camelus", "Struthionidae", "Struthioniformes",
        ["omnivore"], ["savanna"], ["africa"], "huge",
        ["largest-bird", "flightless", "fast-runner"], None, None, None, "Q26547"),
    ("emu", "Dromaius novaehollandiae", "Casuariidae", "Casuariiformes",
        ["omnivore"], ["outback"], ["australia"], "large",
        ["flightless"], None, None, None, "Q34739"),
    ("cassowary", "Casuarius casuarius", "Casuariidae", "Casuariiformes",
        ["frugivore"], ["jungle"], ["new-guinea", "australia"], "large",
        ["dangerous", "casque"], None, None, None, "Q193459"),
    ("rhea", "Rhea americana", "Rheidae", "Rheiformes",
        ["omnivore"], ["grassland"], ["south-america"], "large",
        ["flightless"], None, None, None, "Q193459"),
    ("kiwi", "Apteryx", "Apterygidae", "Apterygiformes",
        ["omnivore"], ["forest"], ["new-zealand"], "small",
        ["flightless", "long-bill", "nocturnal"], None, ["night"], None, "Q26547"),
    ("penguin", "Aptenodytes forsteri", "Spheniscidae", "Sphenisciformes",
        ["piscivore"], ["antarctic-ice", "coast"], ["southern-hemisphere"], "medium",
        ["flightless", "swimmer", "tuxedoed"], ["emperor-penguin"], None, ["winter"], "Q39918"),
    ("king-penguin", "Aptenodytes patagonicus", "Spheniscidae", "Sphenisciformes",
        ["piscivore"], ["antarctic-island"], ["sub-antarctic"], "medium",
        ["orange-throat"], None, None, None, "Q193459"),
    ("gentoo-penguin", "Pygoscelis papua", "Spheniscidae", "Sphenisciformes",
        ["piscivore"], ["antarctic-coast"], ["sub-antarctic"], "medium",
        ["fastest-swimming-penguin"], None, None, None, "Q193459"),
    ("adelie-penguin", "Pygoscelis adeliae", "Spheniscidae", "Sphenisciformes",
        ["piscivore"], ["antarctic-ice"], ["antarctic"], "small", None, None, None, None, "Q193459"),
]

for spec in BACKYARD + WATERFOWL + RAPTORS + OWLS + PARROTS + FOWL:
    canonical, sci, family, order, diet, habitat, region, size, behavior, syns, tod, seasons, qid = spec
    NODES.append(bird(canonical, sci, family, order, diet, habitat, region, size,
                       behavior=behavior, synonyms=syns, tod=tod, seasons=seasons, qid=qid))
