"""Fish — freshwater + saltwater + cartilaginous. Compact list form.
Target: ~300-500 species most commonly named.
"""

from _helpers import node, wikidata, tax, authored


def fish(canonical, sci, family, order, class_, diet, habitat, region, size,
         behavior=None, synonyms=None, qid=None):
    return node(canonical, "animal",
                synonyms=synonyms or [],
                scientific_name=sci,
                taxonomy=tax(kingdom="Animalia", phylum="Chordata", class_=class_,
                             order=order, family=family,
                             genus=sci.split()[0] if sci else None,
                             species=sci, common_name=canonical),
                diet=diet, lives_in=habitat, region_native_to=region,
                size_scale=size, behavior_notes=behavior,
                kid_friendly=True,
                provenance=[wikidata(qid)] if qid else [authored()])


NODES = []


def _emit(entry):
    n = len(entry)
    if n == 10:
        canonical, sci, family, order, class_, diet, habitat, region, size, qid = entry
        behavior = None; syns = None
    elif n == 11:
        canonical, sci, family, order, class_, diet, habitat, region, size, behavior, qid = entry
        syns = None
    elif n == 12:
        canonical, sci, family, order, class_, diet, habitat, region, size, behavior, syns, qid = entry
    else:
        raise ValueError(f"Bad fish tuple len {n}: {entry!r}")
    NODES.append(fish(canonical, sci, family, order, class_, diet,
                      [habitat] if isinstance(habitat, str) else habitat,
                      [region] if isinstance(region, str) else region,
                      size, behavior=behavior, synonyms=syns, qid=qid))


# ---------------------------------------------------------------------------
# CARTILAGINOUS — sharks, rays, chimaeras
# ---------------------------------------------------------------------------
CARTILAGE = [
    ("shark", "Selachimorpha", "Carcharhinidae", "Carcharhiniformes", "Chondrichthyes",
        ["carnivore"], "ocean", "worldwide", "large",
        ["apex-predator", "cartilaginous"], None, "Q483521"),
    ("great-white-shark", "Carcharodon carcharias", "Lamnidae", "Lamniformes", "Chondrichthyes",
        ["carnivore"], "ocean", "worldwide-temperate", "huge",
        ["apex-predator", "warm-blooded"], ["white-shark"], "Q129026"),
    ("tiger-shark", "Galeocerdo cuvier", "Carcharhinidae", "Carcharhiniformes", "Chondrichthyes",
        ["carnivore"], "ocean", "worldwide-tropical", "huge", None, None, "Q129471"),
    ("bull-shark", "Carcharhinus leucas", "Carcharhinidae", "Carcharhiniformes", "Chondrichthyes",
        ["carnivore"], ["ocean", "river"], "worldwide-warm", "large",
        ["freshwater-tolerant"], None, "Q193459"),
    ("hammerhead-shark", "Sphyrna", "Sphyrnidae", "Carcharhiniformes", "Chondrichthyes",
        ["carnivore"], "ocean", "worldwide-warm", "large",
        ["cephalofoil-head", "schooling"], ["hammerhead"], "Q193459"),
    ("whale-shark", "Rhincodon typus", "Rhincodontidae", "Orectolobiformes", "Chondrichthyes",
        ["filter-feeder"], "ocean", "worldwide-tropical", "massive",
        ["largest-fish", "gentle"], None, "Q191773"),
    ("basking-shark", "Cetorhinus maximus", "Cetorhinidae", "Lamniformes", "Chondrichthyes",
        ["filter-feeder"], "ocean", "worldwide-temperate", "massive",
        ["second-largest-fish"], None, "Q193459"),
    ("nurse-shark", "Ginglymostoma cirratum", "Ginglymostomatidae", "Orectolobiformes", "Chondrichthyes",
        ["carnivore"], "ocean-reef", "atlantic-caribbean", "large",
        ["docile", "bottom-dweller"], None, "Q193459"),
    ("mako-shark", "Isurus oxyrinchus", "Lamnidae", "Lamniformes", "Chondrichthyes",
        ["carnivore"], "ocean", "worldwide", "large",
        ["fastest-shark"], ["shortfin-mako"], "Q193459"),
    ("thresher-shark", "Alopias vulpinus", "Alopiidae", "Lamniformes", "Chondrichthyes",
        ["carnivore"], "ocean", "worldwide", "large",
        ["long-tail-hunter"], None, "Q193459"),
    ("blue-shark", "Prionace glauca", "Carcharhinidae", "Carcharhiniformes", "Chondrichthyes",
        ["carnivore"], "ocean", "worldwide", "large",
        ["migratory"], None, "Q193459"),
    ("lemon-shark", "Negaprion brevirostris", "Carcharhinidae", "Carcharhiniformes", "Chondrichthyes",
        ["carnivore"], "ocean-coast", "atlantic-tropical", "large", None, None, "Q193459"),
    ("reef-shark", "Carcharhinus", "Carcharhinidae", "Carcharhiniformes", "Chondrichthyes",
        ["carnivore"], "reef", "worldwide-tropical", "large", None, None, "Q193459"),
    ("goblin-shark", "Mitsukurina owstoni", "Mitsukurinidae", "Lamniformes", "Chondrichthyes",
        ["carnivore"], "deep-sea", "worldwide", "large",
        ["living-fossil", "protrusible-jaw"], None, "Q193459"),
    ("cookie-cutter-shark", "Isistius brasiliensis", "Dalatiidae", "Squaliformes", "Chondrichthyes",
        ["carnivore"], "deep-sea", "worldwide-tropical", "small",
        ["parasitic-bite"], None, "Q193459"),
    ("dogfish", "Squalus acanthias", "Squalidae", "Squaliformes", "Chondrichthyes",
        ["carnivore"], "ocean", "worldwide", "small",
        ["schooling"], ["spiny-dogfish"], "Q193459"),
    ("ray", "Batoidea", "Rajidae", "Rajiformes", "Chondrichthyes",
        ["carnivore"], ["ocean", "sea-floor"], "worldwide", "medium",
        ["flat-body"], None, "Q193459"),
    ("stingray", "Dasyatidae", "Dasyatidae", "Myliobatiformes", "Chondrichthyes",
        ["carnivore"], ["ocean", "sea-floor"], "worldwide-warm", "medium",
        ["venomous-tail"], None, "Q193459"),
    ("manta-ray", "Mobula birostris", "Mobulidae", "Myliobatiformes", "Chondrichthyes",
        ["filter-feeder"], "ocean", "worldwide-tropical", "huge",
        ["gentle-giant"], ["giant-manta"], "Q131389"),
    ("electric-ray", "Torpedo torpedo", "Torpedinidae", "Torpediniformes", "Chondrichthyes",
        ["carnivore"], "ocean", "worldwide", "medium",
        ["electric-shock"], ["torpedo-fish"], "Q193459"),
    ("sawfish", "Pristis", "Pristidae", "Rhinopristiformes", "Chondrichthyes",
        ["carnivore"], ["ocean", "estuary"], "worldwide-tropical", "large",
        ["saw-rostrum"], None, "Q193459"),
    ("skate", "Rajidae", "Rajidae", "Rajiformes", "Chondrichthyes",
        ["carnivore"], "ocean-floor", "worldwide", "medium", None, None, "Q193459"),
    ("chimaera", "Chimaera monstrosa", "Chimaeridae", "Chimaeriformes", "Chondrichthyes",
        ["carnivore"], "deep-sea", "worldwide", "medium",
        ["ghost-shark"], ["rat-fish"], "Q193459"),
]

for e in CARTILAGE: _emit(e)


# ---------------------------------------------------------------------------
# FRESHWATER BONY FISH
# ---------------------------------------------------------------------------
FRESH = [
    ("bass", "Micropterus salmoides", "Centrarchidae", "Perciformes", "Actinopterygii",
        ["carnivore"], ["lake", "river"], "north-america", "medium",
        ["ambush-predator"], ["largemouth-bass"], "Q193459"),
    ("smallmouth-bass", "Micropterus dolomieu", "Centrarchidae", "Perciformes", "Actinopterygii",
        ["carnivore"], ["lake", "river"], "north-america", "medium", None, None, "Q193459"),
    ("striped-bass", "Morone saxatilis", "Moronidae", "Perciformes", "Actinopterygii",
        ["carnivore"], ["river", "estuary"], "north-america-east", "medium",
        ["anadromous"], ["striper"], "Q193459"),
    ("trout", "Salmo trutta", "Salmonidae", "Salmoniformes", "Actinopterygii",
        ["carnivore"], ["stream", "lake"], "worldwide-temperate", "medium",
        ["cold-water"], ["brown-trout"], "Q131400"),
    ("rainbow-trout", "Oncorhynchus mykiss", "Salmonidae", "Salmoniformes", "Actinopterygii",
        ["carnivore"], ["stream", "lake"], "north-america", "medium", None, None, "Q193459"),
    ("brook-trout", "Salvelinus fontinalis", "Salmonidae", "Salmoniformes", "Actinopterygii",
        ["carnivore"], "stream", "north-america-east", "small",
        ["cold-clear-water"], None, "Q193459"),
    ("lake-trout", "Salvelinus namaycush", "Salmonidae", "Salmoniformes", "Actinopterygii",
        ["carnivore"], "lake", "north-america", "large", None, None, "Q193459"),
    ("salmon", "Salmo salar", "Salmonidae", "Salmoniformes", "Actinopterygii",
        ["carnivore"], ["ocean", "river"], "north-atlantic", "medium",
        ["anadromous", "spawning-migration"], ["atlantic-salmon"], "Q42395"),
    ("chinook-salmon", "Oncorhynchus tshawytscha", "Salmonidae", "Salmoniformes", "Actinopterygii",
        ["carnivore"], ["ocean", "river"], "north-pacific", "large",
        ["anadromous"], ["king-salmon"], "Q193459"),
    ("sockeye-salmon", "Oncorhynchus nerka", "Salmonidae", "Salmoniformes", "Actinopterygii",
        ["carnivore"], ["ocean", "river"], "north-pacific", "medium",
        ["red-spawning"], ["red-salmon"], "Q193459"),
    ("coho-salmon", "Oncorhynchus kisutch", "Salmonidae", "Salmoniformes", "Actinopterygii",
        ["carnivore"], ["ocean", "river"], "north-pacific", "medium",
        None, ["silver-salmon"], "Q193459"),
    ("pink-salmon", "Oncorhynchus gorbuscha", "Salmonidae", "Salmoniformes", "Actinopterygii",
        ["carnivore"], ["ocean", "river"], "north-pacific", "medium",
        None, ["humpy"], "Q193459"),
    ("chum-salmon", "Oncorhynchus keta", "Salmonidae", "Salmoniformes", "Actinopterygii",
        ["carnivore"], ["ocean", "river"], "north-pacific", "medium",
        None, ["dog-salmon"], "Q193459"),
    ("char", "Salvelinus alpinus", "Salmonidae", "Salmoniformes", "Actinopterygii",
        ["carnivore"], ["lake", "river"], "arctic", "medium",
        None, ["arctic-char"], "Q193459"),
    ("grayling", "Thymallus thymallus", "Salmonidae", "Salmoniformes", "Actinopterygii",
        ["insectivore"], "stream", "eurasia", "small",
        ["sail-fin"], None, "Q193459"),
    ("carp", "Cyprinus carpio", "Cyprinidae", "Cypriniformes", "Actinopterygii",
        ["omnivore"], ["lake", "pond", "river"], "worldwide", "medium",
        ["bottom-feeder"], ["common-carp"], "Q26214"),
    ("koi", "Cyprinus rubrofuscus", "Cyprinidae", "Cypriniformes", "Actinopterygii",
        ["omnivore"], ["pond", "garden"], "east-asia", "medium",
        ["ornamental"], ["nishikigoi"], "Q101097"),
    ("goldfish", "Carassius auratus", "Cyprinidae", "Cypriniformes", "Actinopterygii",
        ["omnivore"], ["pond", "aquarium"], "east-asia", "small",
        ["ornamental", "domesticated"], ["carassius"], "Q40607"),
    ("catfish", "Ictalurus punctatus", "Ictaluridae", "Siluriformes", "Actinopterygii",
        ["omnivore"], ["river", "lake"], "worldwide", "medium",
        ["bottom-feeder", "whiskers"], ["channel-catfish"], "Q193459"),
    ("bullhead", "Ameiurus", "Ictaluridae", "Siluriformes", "Actinopterygii",
        ["omnivore"], ["pond", "river"], "north-america", "small",
        ["bottom-dweller"], None, "Q193459"),
    ("perch", "Perca fluviatilis", "Percidae", "Perciformes", "Actinopterygii",
        ["carnivore"], ["lake", "river"], "eurasia", "small",
        ["schooling"], ["european-perch"], "Q193459"),
    ("walleye", "Sander vitreus", "Percidae", "Perciformes", "Actinopterygii",
        ["carnivore"], ["lake", "river"], "north-america", "medium",
        ["night-hunter"], None, "Q193459"),
    ("pike", "Esox lucius", "Esocidae", "Esociformes", "Actinopterygii",
        ["carnivore"], ["lake", "river"], "north-temperate", "medium",
        ["ambush-predator"], ["northern-pike"], "Q193459"),
    ("muskellunge", "Esox masquinongy", "Esocidae", "Esociformes", "Actinopterygii",
        ["carnivore"], ["lake"], "north-america", "large",
        None, ["musky"], "Q193459"),
    ("pickerel", "Esox niger", "Esocidae", "Esociformes", "Actinopterygii",
        ["carnivore"], "river", "north-america-east", "small",
        None, ["chain-pickerel"], "Q193459"),
    ("sunfish", "Lepomis macrochirus", "Centrarchidae", "Perciformes", "Actinopterygii",
        ["omnivore"], ["pond", "lake"], "north-america", "small",
        None, ["bluegill"], "Q193459"),
    ("crappie", "Pomoxis nigromaculatus", "Centrarchidae", "Perciformes", "Actinopterygii",
        ["carnivore"], ["lake", "pond"], "north-america", "small",
        ["schooling"], ["black-crappie"], "Q193459"),
    ("minnow", "Cyprinidae", "Cyprinidae", "Cypriniformes", "Actinopterygii",
        ["omnivore"], ["stream", "pond"], "worldwide", "tiny",
        ["schooling"], None, "Q193459"),
    ("guppy", "Poecilia reticulata", "Poeciliidae", "Cyprinodontiformes", "Actinopterygii",
        ["omnivore"], ["aquarium", "stream"], "south-america", "tiny",
        ["livebearing", "colorful"], None, "Q193459"),
    ("betta", "Betta splendens", "Osphronemidae", "Anabantiformes", "Actinopterygii",
        ["carnivore"], "aquarium", "southeast-asia", "tiny",
        ["labyrinth-breather", "territorial"], ["siamese-fighting-fish"], "Q193459"),
    ("angelfish", "Pterophyllum scalare", "Cichlidae", "Cichliformes", "Actinopterygii",
        ["omnivore"], ["aquarium", "river"], "south-america", "small",
        ["elegant"], ["freshwater-angel"], "Q193459"),
    ("discus", "Symphysodon", "Cichlidae", "Cichliformes", "Actinopterygii",
        ["omnivore"], ["aquarium", "river"], "amazon-basin", "small",
        ["disc-shaped"], None, "Q193459"),
    ("tetra", "Paracheirodon innesi", "Characidae", "Characiformes", "Actinopterygii",
        ["omnivore"], "aquarium", "south-america", "tiny",
        ["schooling"], ["neon-tetra"], "Q193459"),
    ("piranha", "Pygocentrus nattereri", "Serrasalmidae", "Characiformes", "Actinopterygii",
        ["carnivore"], "river", "amazon-basin", "small",
        ["schooling", "sharp-teeth"], ["red-piranha"], "Q193459"),
    ("arapaima", "Arapaima gigas", "Osteoglossidae", "Osteoglossiformes", "Actinopterygii",
        ["carnivore"], "river", "amazon-basin", "huge",
        ["air-breathing", "largest-freshwater"], ["pirarucu"], "Q193459"),
    ("arowana", "Osteoglossum bicirrhosum", "Osteoglossidae", "Osteoglossiformes", "Actinopterygii",
        ["carnivore"], "river", "south-america", "large",
        ["surface-hunter"], ["silver-arowana"], "Q193459"),
    ("sturgeon", "Acipenser", "Acipenseridae", "Acipenseriformes", "Actinopterygii",
        ["omnivore"], ["river", "estuary"], "north-hemisphere", "huge",
        ["living-fossil", "caviar-source"], None, "Q193459"),
    ("paddlefish", "Polyodon spathula", "Polyodontidae", "Acipenseriformes", "Actinopterygii",
        ["filter-feeder"], "river", "north-america", "large",
        ["paddle-snout"], None, "Q193459"),
    ("gar", "Lepisosteus", "Lepisosteidae", "Lepisosteiformes", "Actinopterygii",
        ["carnivore"], ["river", "lake"], "north-america", "large",
        ["armored-scales", "ancient"], None, "Q193459"),
    ("alligator-gar", "Atractosteus spatula", "Lepisosteidae", "Lepisosteiformes", "Actinopterygii",
        ["carnivore"], "river", "north-america-south", "huge", None, None, "Q193459"),
    ("bowfin", "Amia calva", "Amiidae", "Amiiformes", "Actinopterygii",
        ["carnivore"], ["river", "swamp"], "north-america", "medium",
        ["air-breathing", "living-fossil"], ["dogfish"], "Q193459"),
    ("eel", "Anguilla anguilla", "Anguillidae", "Anguilliformes", "Actinopterygii",
        ["carnivore"], ["river", "ocean"], "worldwide", "medium",
        ["catadromous", "elongate"], ["european-eel"], "Q193459"),
    ("moray-eel", "Muraenidae", "Muraenidae", "Anguilliformes", "Actinopterygii",
        ["carnivore"], "reef", "worldwide-warm", "medium",
        ["reef-dweller"], None, "Q193459"),
    ("electric-eel", "Electrophorus electricus", "Gymnotidae", "Gymnotiformes", "Actinopterygii",
        ["carnivore"], "river", "amazon-basin", "medium",
        ["electric-shock"], None, "Q193459"),
    ("tilapia", "Oreochromis niloticus", "Cichlidae", "Cichliformes", "Actinopterygii",
        ["omnivore"], ["lake", "farm"], "africa-worldwide", "medium",
        ["farmed"], None, "Q193459"),
    ("cichlid", "Cichlidae", "Cichlidae", "Cichliformes", "Actinopterygii",
        ["omnivore"], ["lake", "aquarium"], "africa-south-america", "small",
        ["territorial", "diverse"], None, "Q193459"),
    ("lungfish", "Protopterus annectens", "Protopteridae", "Ceratodontiformes", "Sarcopterygii",
        ["omnivore"], ["swamp", "river"], "africa", "medium",
        ["air-breathing", "aestivation"], None, "Q193459"),
]

for e in FRESH: _emit(e)


# ---------------------------------------------------------------------------
# SALTWATER BONY FISH
# ---------------------------------------------------------------------------
SALT = [
    ("tuna", "Thunnus albacares", "Scombridae", "Perciformes", "Actinopterygii",
        ["carnivore"], "ocean", "worldwide", "large",
        ["warm-blooded", "fast-swimmer"], ["yellowfin-tuna"], "Q131772"),
    ("bluefin-tuna", "Thunnus thynnus", "Scombridae", "Perciformes", "Actinopterygii",
        ["carnivore"], "ocean", "atlantic", "huge",
        ["fastest-ocean-fish"], None, "Q193459"),
    ("albacore", "Thunnus alalunga", "Scombridae", "Perciformes", "Actinopterygii",
        ["carnivore"], "ocean", "worldwide", "large", None, None, "Q193459"),
    ("skipjack-tuna", "Katsuwonus pelamis", "Scombridae", "Perciformes", "Actinopterygii",
        ["carnivore"], "ocean", "worldwide-tropical", "medium", None, None, "Q193459"),
    ("mackerel", "Scomber scombrus", "Scombridae", "Perciformes", "Actinopterygii",
        ["carnivore"], "ocean", "north-atlantic", "small",
        ["schooling"], ["atlantic-mackerel"], "Q193459"),
    ("marlin", "Makaira nigricans", "Istiophoridae", "Istiophoriformes", "Actinopterygii",
        ["carnivore"], "ocean", "worldwide-tropical", "huge",
        ["billfish", "sport-fish"], ["blue-marlin"], "Q193459"),
    ("swordfish", "Xiphias gladius", "Xiphiidae", "Istiophoriformes", "Actinopterygii",
        ["carnivore"], "ocean", "worldwide", "huge",
        ["billfish"], None, "Q193459"),
    ("sailfish", "Istiophorus platypterus", "Istiophoridae", "Istiophoriformes", "Actinopterygii",
        ["carnivore"], "ocean", "worldwide-tropical", "huge",
        ["fastest-fish", "sail-dorsal"], None, "Q193459"),
    ("wahoo", "Acanthocybium solandri", "Scombridae", "Perciformes", "Actinopterygii",
        ["carnivore"], "ocean", "worldwide-tropical", "large",
        ["fast-swimmer"], None, "Q193459"),
    ("mahi-mahi", "Coryphaena hippurus", "Coryphaenidae", "Perciformes", "Actinopterygii",
        ["carnivore"], "ocean", "worldwide-tropical", "large",
        ["colorful", "surface-dweller"], ["dorado", "dolphin-fish"], "Q193459"),
    ("cod", "Gadus morhua", "Gadidae", "Gadiformes", "Actinopterygii",
        ["carnivore"], "ocean", "north-atlantic", "large",
        ["schooling", "commercial"], ["atlantic-cod"], "Q193459"),
    ("haddock", "Melanogrammus aeglefinus", "Gadidae", "Gadiformes", "Actinopterygii",
        ["carnivore"], "ocean", "north-atlantic", "medium", None, None, "Q193459"),
    ("pollock", "Pollachius pollachius", "Gadidae", "Gadiformes", "Actinopterygii",
        ["carnivore"], "ocean", "north-atlantic", "medium", None, None, "Q193459"),
    ("hake", "Merluccius merluccius", "Merlucciidae", "Gadiformes", "Actinopterygii",
        ["carnivore"], "ocean", "north-atlantic", "medium", None, None, "Q193459"),
    ("herring", "Clupea harengus", "Clupeidae", "Clupeiformes", "Actinopterygii",
        ["filter-feeder"], "ocean", "north-atlantic", "small",
        ["massive-schools"], ["atlantic-herring"], "Q193459"),
    ("sardine", "Sardina pilchardus", "Clupeidae", "Clupeiformes", "Actinopterygii",
        ["filter-feeder"], "ocean", "worldwide", "small",
        ["schooling"], ["pilchard"], "Q193459"),
    ("anchovy", "Engraulis encrasicolus", "Engraulidae", "Clupeiformes", "Actinopterygii",
        ["filter-feeder"], "ocean", "worldwide", "tiny",
        ["schooling"], None, "Q193459"),
    ("menhaden", "Brevoortia tyrannus", "Clupeidae", "Clupeiformes", "Actinopterygii",
        ["filter-feeder"], "ocean-coastal", "north-atlantic", "small",
        ["baitfish"], ["bunker"], "Q193459"),
    ("flounder", "Paralichthys dentatus", "Paralichthyidae", "Pleuronectiformes", "Actinopterygii",
        ["carnivore"], "ocean-floor", "north-atlantic", "medium",
        ["flat-bottom-dweller"], ["summer-flounder"], "Q193459"),
    ("halibut", "Hippoglossus hippoglossus", "Pleuronectidae", "Pleuronectiformes", "Actinopterygii",
        ["carnivore"], "ocean-floor", "north-atlantic", "huge",
        ["flat", "largest-flatfish"], ["atlantic-halibut"], "Q193459"),
    ("sole", "Solea solea", "Soleidae", "Pleuronectiformes", "Actinopterygii",
        ["carnivore"], "ocean-floor", "european-waters", "small",
        ["flat"], None, "Q193459"),
    ("turbot", "Scophthalmus maximus", "Scophthalmidae", "Pleuronectiformes", "Actinopterygii",
        ["carnivore"], "ocean-floor", "european-waters", "medium",
        ["flat"], None, "Q193459"),
    ("plaice", "Pleuronectes platessa", "Pleuronectidae", "Pleuronectiformes", "Actinopterygii",
        ["carnivore"], "ocean-floor", "european-waters", "medium", None, None, "Q193459"),
    ("snapper", "Lutjanus", "Lutjanidae", "Perciformes", "Actinopterygii",
        ["carnivore"], "reef", "worldwide-tropical", "medium",
        None, ["red-snapper"], "Q193459"),
    ("grouper", "Epinephelus", "Serranidae", "Perciformes", "Actinopterygii",
        ["carnivore"], "reef", "worldwide-warm", "large",
        ["ambush-predator"], None, "Q193459"),
    ("sea-bass", "Dicentrarchus labrax", "Moronidae", "Perciformes", "Actinopterygii",
        ["carnivore"], "ocean-coastal", "european-waters", "medium",
        None, ["european-seabass"], "Q193459"),
    ("bluefish", "Pomatomus saltatrix", "Pomatomidae", "Perciformes", "Actinopterygii",
        ["carnivore"], "ocean-coastal", "worldwide-warm", "medium",
        ["voracious"], None, "Q193459"),
    ("pompano", "Trachinotus carolinus", "Carangidae", "Carangiformes", "Actinopterygii",
        ["carnivore"], "ocean-coastal", "atlantic", "small", None, None, "Q193459"),
    ("jack", "Caranx", "Carangidae", "Carangiformes", "Actinopterygii",
        ["carnivore"], "ocean", "worldwide", "medium",
        None, ["crevalle-jack"], "Q193459"),
    ("amberjack", "Seriola dumerili", "Carangidae", "Carangiformes", "Actinopterygii",
        ["carnivore"], "ocean-reef", "worldwide-warm", "large", None, None, "Q193459"),
    ("yellowtail", "Seriola lalandi", "Carangidae", "Carangiformes", "Actinopterygii",
        ["carnivore"], "ocean", "worldwide-warm", "medium",
        None, ["kingfish"], "Q193459"),
    ("barracuda", "Sphyraena barracuda", "Sphyraenidae", "Sphyraeniformes", "Actinopterygii",
        ["carnivore"], "ocean", "worldwide-tropical", "large",
        ["ambush-predator", "toothy"], ["great-barracuda"], "Q193459"),
    ("bonito", "Sarda sarda", "Scombridae", "Perciformes", "Actinopterygii",
        ["carnivore"], "ocean", "worldwide", "medium",
        None, ["atlantic-bonito"], "Q193459"),
    ("kingfish", "Scomberomorus cavalla", "Scombridae", "Perciformes", "Actinopterygii",
        ["carnivore"], "ocean", "atlantic", "large",
        None, ["king-mackerel"], "Q193459"),
    ("clownfish", "Amphiprion ocellaris", "Pomacentridae", "Perciformes", "Actinopterygii",
        ["omnivore"], "reef", "indo-pacific", "tiny",
        ["anemone-symbiosis"], ["anemonefish"], "Q189928"),
    ("damselfish", "Pomacentridae", "Pomacentridae", "Perciformes", "Actinopterygii",
        ["omnivore"], "reef", "worldwide-tropical", "tiny",
        ["territorial"], None, "Q193459"),
    ("parrotfish", "Scaridae", "Scaridae", "Perciformes", "Actinopterygii",
        ["herbivore"], "reef", "worldwide-tropical", "medium",
        ["coral-grazer"], None, "Q193459"),
    ("wrasse", "Labridae", "Labridae", "Perciformes", "Actinopterygii",
        ["carnivore"], "reef", "worldwide", "small",
        ["cleaner-fish"], None, "Q193459"),
    ("triggerfish", "Balistes", "Balistidae", "Tetraodontiformes", "Actinopterygii",
        ["omnivore"], "reef", "worldwide-warm", "small",
        ["angular-body"], None, "Q193459"),
    ("pufferfish", "Tetraodontidae", "Tetraodontidae", "Tetraodontiformes", "Actinopterygii",
        ["omnivore"], "reef", "worldwide-warm", "small",
        ["inflation-defense", "toxic"], ["blowfish", "fugu"], "Q193459"),
    ("boxfish", "Ostraciidae", "Ostraciidae", "Tetraodontiformes", "Actinopterygii",
        ["omnivore"], "reef", "worldwide-tropical", "small",
        ["boxy-body"], None, "Q193459"),
    ("porcupinefish", "Diodon", "Diodontidae", "Tetraodontiformes", "Actinopterygii",
        ["carnivore"], "reef", "worldwide-warm", "small",
        ["spines", "inflation-defense"], None, "Q193459"),
    ("ocean-sunfish", "Mola mola", "Molidae", "Tetraodontiformes", "Actinopterygii",
        ["omnivore"], "ocean", "worldwide", "massive",
        ["heaviest-bony-fish"], ["mola"], "Q193459"),
    ("lionfish", "Pterois volitans", "Scorpaenidae", "Scorpaeniformes", "Actinopterygii",
        ["carnivore"], "reef", "indo-pacific", "small",
        ["venomous-spines", "invasive"], None, "Q193459"),
    ("scorpionfish", "Scorpaenidae", "Scorpaenidae", "Scorpaeniformes", "Actinopterygii",
        ["carnivore"], "reef", "worldwide-warm", "small",
        ["venomous", "camouflage"], None, "Q193459"),
    ("stonefish", "Synanceia verrucosa", "Synanceiidae", "Scorpaeniformes", "Actinopterygii",
        ["carnivore"], "reef", "indo-pacific", "small",
        ["most-venomous-fish"], None, "Q193459"),
    ("seahorse", "Hippocampus", "Syngnathidae", "Syngnathiformes", "Actinopterygii",
        ["carnivore"], ["seagrass", "reef"], "worldwide-warm", "tiny",
        ["male-pregnancy", "prehensile-tail"], None, "Q193459"),
    ("seadragon", "Phyllopteryx taeniolatus", "Syngnathidae", "Syngnathiformes", "Actinopterygii",
        ["carnivore"], "kelp-forest", "australia", "small",
        ["leafy-appendages"], ["leafy-seadragon"], "Q193459"),
    ("pipefish", "Syngnathidae", "Syngnathidae", "Syngnathiformes", "Actinopterygii",
        ["carnivore"], ["seagrass", "reef"], "worldwide", "small",
        ["elongate"], None, "Q193459"),
    ("goby", "Gobiidae", "Gobiidae", "Gobiiformes", "Actinopterygii",
        ["omnivore"], ["reef", "estuary"], "worldwide", "tiny",
        ["bottom-dweller"], None, "Q193459"),
    ("blenny", "Blenniidae", "Blenniidae", "Blenniiformes", "Actinopterygii",
        ["omnivore"], "reef", "worldwide", "tiny", None, None, "Q193459"),
    ("mudskipper", "Periophthalmus", "Gobiidae", "Gobiiformes", "Actinopterygii",
        ["carnivore"], "mangrove", "indo-pacific", "small",
        ["amphibious", "air-breathing"], None, "Q193459"),
    ("anglerfish", "Lophius piscatorius", "Lophiidae", "Lophiiformes", "Actinopterygii",
        ["carnivore"], "deep-sea", "worldwide", "medium",
        ["bioluminescent-lure"], ["deep-sea-anglerfish"], "Q193459"),
    ("lanternfish", "Myctophidae", "Myctophidae", "Myctophiformes", "Actinopterygii",
        ["carnivore"], "deep-sea", "worldwide", "small",
        ["bioluminescent", "vertical-migration"], None, "Q193459"),
    ("viperfish", "Chauliodus sloani", "Stomiidae", "Stomiiformes", "Actinopterygii",
        ["carnivore"], "deep-sea", "worldwide", "small",
        ["long-teeth", "bioluminescent"], None, "Q193459"),
    ("dragonfish", "Stomiidae", "Stomiidae", "Stomiiformes", "Actinopterygii",
        ["carnivore"], "deep-sea", "worldwide", "small",
        ["bioluminescent"], None, "Q193459"),
    ("coelacanth", "Latimeria chalumnae", "Latimeriidae", "Coelacanthiformes", "Sarcopterygii",
        ["carnivore"], "deep-sea", "africa", "medium",
        ["living-fossil"], None, "Q193459"),
    ("flying-fish", "Exocoetidae", "Exocoetidae", "Beloniformes", "Actinopterygii",
        ["carnivore"], "ocean-surface", "worldwide-warm", "small",
        ["glides-above-water"], None, "Q193459"),
    ("needlefish", "Belonidae", "Belonidae", "Beloniformes", "Actinopterygii",
        ["carnivore"], "ocean-surface", "worldwide-warm", "small",
        ["long-jaws"], None, "Q193459"),
    ("herring-smelt", "Osmerus eperlanus", "Osmeridae", "Osmeriformes", "Actinopterygii",
        ["carnivore"], ["river", "ocean"], "north-atlantic", "small",
        None, ["smelt"], "Q193459"),
    ("capelin", "Mallotus villosus", "Osmeridae", "Osmeriformes", "Actinopterygii",
        ["filter-feeder"], "ocean", "arctic-atlantic", "small",
        ["forage-fish"], None, "Q193459"),
]

for e in SALT: _emit(e)
