"""Insects + arachnids + myriapods — ~300-500 nodes.
Compact tuple form. Most are kid-recognizable common insects.
"""

from _helpers import node, wikidata, tax, authored


def bug(canonical, sci, family, order, class_, diet, habitat, region, size,
        behavior=None, synonyms=None, seasons=None, tod=None, qid=None):
    return node(canonical, "animal",
                synonyms=synonyms or [],
                scientific_name=sci,
                taxonomy=tax(kingdom="Animalia", phylum="Arthropoda", class_=class_,
                             order=order, family=family,
                             genus=sci.split()[0] if sci else None,
                             species=sci, common_name=canonical),
                diet=diet, lives_in=habitat, region_native_to=region,
                size_scale=size, behavior_notes=behavior,
                season=seasons, time_of_day=tod,
                kid_friendly=True,
                provenance=[wikidata(qid)] if qid else [authored()])


NODES = []


def _emit(entry):
    n = len(entry)
    if n == 10:
        canonical, sci, family, order, class_, diet, habitat, region, size, qid = entry
        behavior = None; syns = None
    elif n == 11:
        canonical, sci, family, order, class_, diet, habitat, region, size, behavior, qid = entry
        syns = None
    elif n == 12:
        canonical, sci, family, order, class_, diet, habitat, region, size, behavior, syns, qid = entry
    else:
        raise ValueError(f"Bad insect tuple len {n}: {entry!r}")
    NODES.append(bug(canonical, sci, family, order, class_, diet,
                     [habitat] if isinstance(habitat, str) else habitat,
                     [region] if isinstance(region, str) else region,
                     size, behavior=behavior, synonyms=syns, qid=qid))


# ---------------------------------------------------------------------------
# BEETLES — Coleoptera
# ---------------------------------------------------------------------------
BEETLES = [
    ("beetle", "Coleoptera", "Coleoptera", "Coleoptera", "Insecta",
        ["omnivore"], "worldwide", "worldwide", "tiny",
        ["hardened-wing-covers"], None, "Q25334"),
    ("ladybug", "Coccinella septempunctata", "Coccinellidae", "Coleoptera", "Insecta",
        ["carnivore"], ["garden", "field"], "worldwide", "tiny",
        ["aphid-predator", "bright-red"], ["ladybird", "lady-beetle"], "Q11202"),
    ("stag-beetle", "Lucanus cervus", "Lucanidae", "Coleoptera", "Insecta",
        ["omnivore"], "forest", "europe", "small",
        ["large-mandibles"], None, "Q193459"),
    ("rhinoceros-beetle", "Dynastes hercules", "Scarabaeidae", "Coleoptera", "Insecta",
        ["herbivore"], "jungle", "central-america", "small",
        ["horn", "strongest-animal"], ["hercules-beetle"], "Q193459"),
    ("scarab-beetle", "Scarabaeus sacer", "Scarabaeidae", "Coleoptera", "Insecta",
        ["detritivore"], ["desert", "grassland"], ["africa", "mediterranean"], "tiny",
        ["dung-rolling"], ["dung-beetle"], "Q193459"),
    ("dung-beetle", "Scarabaeidae", "Scarabaeidae", "Coleoptera", "Insecta",
        ["detritivore"], "grassland", "worldwide", "tiny",
        ["dung-rolling"], None, "Q193459"),
    ("firefly", "Photinus pyralis", "Lampyridae", "Coleoptera", "Insecta",
        ["carnivore"], ["meadow", "forest-edge"], "worldwide", "tiny",
        ["bioluminescent", "mating-flash"], ["lightning-bug", "glow-worm"], "Q25381"),
    ("weevil", "Curculionidae", "Curculionidae", "Coleoptera", "Insecta",
        ["herbivore"], "worldwide", "worldwide", "tiny",
        ["snout-nose"], None, "Q193459"),
    ("boll-weevil", "Anthonomus grandis", "Curculionidae", "Coleoptera", "Insecta",
        ["herbivore"], "farm", "north-america", "tiny",
        ["cotton-pest"], None, "Q193459"),
    ("ground-beetle", "Carabidae", "Carabidae", "Coleoptera", "Insecta",
        ["carnivore"], "worldwide", "worldwide", "tiny",
        ["predator", "nocturnal"], None, "Q193459"),
    ("tiger-beetle", "Cicindelinae", "Carabidae", "Coleoptera", "Insecta",
        ["carnivore"], "sandy-ground", "worldwide", "tiny",
        ["fastest-insect"], None, "Q193459"),
    ("longhorn-beetle", "Cerambycidae", "Cerambycidae", "Coleoptera", "Insecta",
        ["herbivore"], "forest", "worldwide", "small",
        ["long-antennae"], None, "Q193459"),
    ("bark-beetle", "Scolytinae", "Curculionidae", "Coleoptera", "Insecta",
        ["herbivore"], "forest", "worldwide", "tiny",
        ["tree-tunneling"], None, "Q193459"),
    ("click-beetle", "Elateridae", "Elateridae", "Coleoptera", "Insecta",
        ["herbivore"], "field", "worldwide", "tiny",
        ["snap-flip-mechanism"], None, "Q193459"),
    ("water-beetle", "Dytiscidae", "Dytiscidae", "Coleoptera", "Insecta",
        ["carnivore"], "pond", "worldwide", "tiny",
        ["aquatic", "diving"], ["diving-beetle"], "Q193459"),
    ("whirligig-beetle", "Gyrinidae", "Gyrinidae", "Coleoptera", "Insecta",
        ["carnivore"], "pond", "worldwide", "tiny",
        ["surface-swimmer", "spinning"], None, "Q193459"),
    ("colorado-potato-beetle", "Leptinotarsa decemlineata", "Chrysomelidae", "Coleoptera", "Insecta",
        ["herbivore"], "farm", "north-america", "tiny",
        ["potato-pest"], None, "Q193459"),
    ("japanese-beetle", "Popillia japonica", "Scarabaeidae", "Coleoptera", "Insecta",
        ["herbivore"], "garden", "japan-invasive-worldwide", "tiny",
        ["invasive-pest"], None, "Q193459"),
    ("june-bug", "Phyllophaga", "Scarabaeidae", "Coleoptera", "Insecta",
        ["herbivore"], "field", "north-america", "tiny",
        ["nocturnal"], ["may-beetle", "june-beetle"], "Q193459"),
    ("bombardier-beetle", "Brachinus", "Carabidae", "Coleoptera", "Insecta",
        ["carnivore"], "field", "worldwide", "tiny",
        ["chemical-spray-defense"], None, "Q193459"),
    ("blister-beetle", "Meloidae", "Meloidae", "Coleoptera", "Insecta",
        ["omnivore"], "field", "worldwide", "tiny",
        ["cantharidin-toxin"], None, "Q193459"),
    ("mealworm", "Tenebrio molitor", "Tenebrionidae", "Coleoptera", "Insecta",
        ["omnivore"], ["grain-storage", "farm"], "worldwide", "tiny",
        ["larva-form-of-darkling"], ["darkling-beetle-larva"], "Q193459"),
]

for e in BEETLES: _emit(e)


# ---------------------------------------------------------------------------
# BUTTERFLIES + MOTHS — Lepidoptera
# ---------------------------------------------------------------------------
LEPS = [
    ("butterfly", "Lepidoptera", "Nymphalidae", "Lepidoptera", "Insecta",
        ["nectarivore"], ["meadow", "garden"], "worldwide", "tiny",
        ["scaled-wings", "day-flying"], None, "Q11946202"),
    ("moth", "Lepidoptera", "Noctuidae", "Lepidoptera", "Insecta",
        ["nectarivore"], "worldwide", "worldwide", "tiny",
        ["nocturnal", "attracted-to-light"], None, "Q192505"),
    ("monarch-butterfly", "Danaus plexippus", "Nymphalidae", "Lepidoptera", "Insecta",
        ["nectarivore"], ["meadow", "milkweed-patch"], "north-america", "tiny",
        ["long-distance-migration", "orange-black"], ["monarch"], "Q131817"),
    ("swallowtail", "Papilio machaon", "Papilionidae", "Lepidoptera", "Insecta",
        ["nectarivore"], "meadow", "north-hemisphere", "tiny",
        ["tail-extended-wings"], None, "Q193459"),
    ("cabbage-white", "Pieris rapae", "Pieridae", "Lepidoptera", "Insecta",
        ["nectarivore"], ["garden", "farm"], "worldwide", "tiny",
        ["cabbage-pest-as-caterpillar"], None, "Q193459"),
    ("painted-lady", "Vanessa cardui", "Nymphalidae", "Lepidoptera", "Insecta",
        ["nectarivore"], "worldwide", "worldwide", "tiny",
        ["migratory"], None, "Q193459"),
    ("mourning-cloak", "Nymphalis antiopa", "Nymphalidae", "Lepidoptera", "Insecta",
        ["nectarivore"], "forest", "north-hemisphere", "tiny",
        ["overwinters-as-adult"], None, "Q193459"),
    ("red-admiral", "Vanessa atalanta", "Nymphalidae", "Lepidoptera", "Insecta",
        ["nectarivore"], "garden", "worldwide", "tiny",
        ["migratory"], None, "Q193459"),
    ("blue-morpho", "Morpho peleides", "Nymphalidae", "Lepidoptera", "Insecta",
        ["nectarivore"], "jungle", "central-america", "tiny",
        ["iridescent-blue"], None, "Q193459"),
    ("queen-alexandra-birdwing", "Ornithoptera alexandrae", "Papilionidae", "Lepidoptera", "Insecta",
        ["nectarivore"], "jungle", "papua-new-guinea", "small",
        ["largest-butterfly"], None, "Q193459"),
    ("skipper", "Hesperiidae", "Hesperiidae", "Lepidoptera", "Insecta",
        ["nectarivore"], "meadow", "worldwide", "tiny",
        ["darting-flight"], None, "Q193459"),
    ("hairstreak", "Lycaenidae", "Lycaenidae", "Lepidoptera", "Insecta",
        ["nectarivore"], "meadow", "worldwide", "tiny", None, None, "Q193459"),
    ("fritillary", "Speyeria", "Nymphalidae", "Lepidoptera", "Insecta",
        ["nectarivore"], "meadow", "north-hemisphere", "tiny",
        ["orange-black-checked"], None, "Q193459"),
    ("silkworm", "Bombyx mori", "Bombycidae", "Lepidoptera", "Insecta",
        ["herbivore"], "farm", "east-asia-domesticated", "tiny",
        ["domesticated", "silk-producer"], ["silk-moth"], "Q193459"),
    ("luna-moth", "Actias luna", "Saturniidae", "Lepidoptera", "Insecta",
        ["nectarivore"], "forest", "north-america", "small",
        ["pale-green", "long-tailed"], None, "Q193459"),
    ("atlas-moth", "Attacus atlas", "Saturniidae", "Lepidoptera", "Insecta",
        ["nectarivore"], "jungle", "southeast-asia", "small",
        ["largest-moth"], None, "Q193459"),
    ("hawk-moth", "Sphingidae", "Sphingidae", "Lepidoptera", "Insecta",
        ["nectarivore"], "garden", "worldwide", "small",
        ["hovering-flight", "long-tongue"], ["sphinx-moth", "hummingbird-moth"], "Q193459"),
    ("gypsy-moth", "Lymantria dispar", "Erebidae", "Lepidoptera", "Insecta",
        ["herbivore"], "forest", "eurasia-invasive-north-america", "tiny",
        ["tree-defoliator"], None, "Q193459"),
    ("codling-moth", "Cydia pomonella", "Tortricidae", "Lepidoptera", "Insecta",
        ["herbivore"], "orchard", "worldwide", "tiny",
        ["apple-pest"], None, "Q193459"),
    ("caterpillar", "Lepidoptera", "Nymphalidae", "Lepidoptera", "Insecta",
        ["herbivore"], "worldwide", "worldwide", "tiny",
        ["larva-form-of-butterfly-moth"], None, "Q3417225"),
    ("wooly-bear", "Pyrrharctia isabella", "Erebidae", "Lepidoptera", "Insecta",
        ["herbivore"], "field", "north-america", "tiny",
        ["fuzzy-caterpillar", "winter-hardy"], ["woolly-bear-caterpillar"], "Q193459"),
]

for e in LEPS: _emit(e)


# ---------------------------------------------------------------------------
# BEES + WASPS + ANTS — Hymenoptera
# ---------------------------------------------------------------------------
HYMEN = [
    ("bee", "Apis", "Apidae", "Hymenoptera", "Insecta",
        ["nectarivore"], ["meadow", "garden"], "worldwide", "tiny",
        ["pollinator", "social"], None, "Q7391"),
    ("honey-bee", "Apis mellifera", "Apidae", "Hymenoptera", "Insecta",
        ["nectarivore"], ["hive", "meadow"], "worldwide", "tiny",
        ["colony", "waggle-dance", "honey-producer"], ["honeybee"], "Q133600"),
    ("bumblebee", "Bombus terrestris", "Apidae", "Hymenoptera", "Insecta",
        ["nectarivore"], ["meadow", "garden"], "north-hemisphere", "tiny",
        ["fuzzy", "cold-tolerant"], ["bumble-bee"], "Q7418"),
    ("carpenter-bee", "Xylocopa", "Apidae", "Hymenoptera", "Insecta",
        ["nectarivore"], ["garden", "wooden-structures"], "worldwide", "tiny",
        ["wood-nesting"], None, "Q193459"),
    ("mason-bee", "Osmia", "Megachilidae", "Hymenoptera", "Insecta",
        ["nectarivore"], "meadow", "north-hemisphere", "tiny",
        ["solitary", "mud-nests"], None, "Q193459"),
    ("leafcutter-bee", "Megachile", "Megachilidae", "Hymenoptera", "Insecta",
        ["nectarivore"], "meadow", "worldwide", "tiny",
        ["cuts-leaf-circles"], None, "Q193459"),
    ("stingless-bee", "Meliponini", "Apidae", "Hymenoptera", "Insecta",
        ["nectarivore"], "jungle", "tropics-worldwide", "tiny",
        ["stingless", "honey-producer"], None, "Q193459"),
    ("wasp", "Vespidae", "Vespidae", "Hymenoptera", "Insecta",
        ["omnivore"], "worldwide", "worldwide", "tiny",
        ["stinger"], None, "Q193459"),
    ("paper-wasp", "Polistes", "Vespidae", "Hymenoptera", "Insecta",
        ["carnivore"], "garden", "worldwide", "tiny",
        ["paper-nests"], None, "Q193459"),
    ("yellowjacket", "Vespula", "Vespidae", "Hymenoptera", "Insecta",
        ["omnivore"], "worldwide", "north-hemisphere", "tiny",
        ["aggressive", "scavenger"], ["yellow-jacket"], "Q193459"),
    ("hornet", "Vespa crabro", "Vespidae", "Hymenoptera", "Insecta",
        ["carnivore"], "forest", "north-hemisphere", "tiny",
        ["large-wasp", "aggressive"], ["european-hornet"], "Q193459"),
    ("japanese-giant-hornet", "Vespa mandarinia", "Vespidae", "Hymenoptera", "Insecta",
        ["carnivore"], "forest", "east-asia", "small",
        ["largest-hornet"], ["murder-hornet"], "Q193459"),
    ("mud-dauber", "Sphecidae", "Sphecidae", "Hymenoptera", "Insecta",
        ["carnivore"], "garden", "worldwide", "tiny",
        ["mud-tube-nest"], None, "Q193459"),
    ("cicada-killer", "Sphecius speciosus", "Crabronidae", "Hymenoptera", "Insecta",
        ["carnivore"], "field", "north-america", "tiny",
        ["cicada-hunter"], None, "Q193459"),
    ("tarantula-hawk", "Pepsis grossa", "Pompilidae", "Hymenoptera", "Insecta",
        ["carnivore"], "desert", "americas", "tiny",
        ["most-painful-sting"], None, "Q193459"),
    ("ant", "Formicidae", "Formicidae", "Hymenoptera", "Insecta",
        ["omnivore"], "worldwide", "worldwide", "tiny",
        ["social", "colony", "queen-workers-soldiers"], None, "Q7386"),
    ("carpenter-ant", "Camponotus", "Formicidae", "Hymenoptera", "Insecta",
        ["omnivore"], ["forest", "structures"], "worldwide", "tiny",
        ["wood-nesting"], None, "Q193459"),
    ("fire-ant", "Solenopsis invicta", "Formicidae", "Hymenoptera", "Insecta",
        ["omnivore"], "farm", "south-america-invasive", "tiny",
        ["painful-sting", "aggressive"], ["red-imported-fire-ant"], "Q193459"),
    ("army-ant", "Eciton", "Formicidae", "Hymenoptera", "Insecta",
        ["carnivore"], "jungle", "tropics-worldwide", "tiny",
        ["nomadic", "raiding-swarms"], None, "Q193459"),
    ("leafcutter-ant", "Atta", "Formicidae", "Hymenoptera", "Insecta",
        ["herbivore"], "jungle", "americas", "tiny",
        ["leaf-carrying", "fungus-farming"], None, "Q193459"),
    ("bullet-ant", "Paraponera clavata", "Formicidae", "Hymenoptera", "Insecta",
        ["carnivore"], "jungle", "central-america", "tiny",
        ["most-painful-sting"], None, "Q193459"),
    ("harvester-ant", "Pogonomyrmex", "Formicidae", "Hymenoptera", "Insecta",
        ["omnivore"], "desert", "north-america", "tiny",
        ["seed-collector"], None, "Q193459"),
    ("weaver-ant", "Oecophylla", "Formicidae", "Hymenoptera", "Insecta",
        ["carnivore"], "jungle", "tropics-worldwide", "tiny",
        ["silk-nest-weaving"], None, "Q193459"),
    ("velvet-ant", "Mutillidae", "Mutillidae", "Hymenoptera", "Insecta",
        ["carnivore"], "field", "worldwide", "tiny",
        ["fuzzy-red", "cow-killer"], None, "Q193459"),
    ("termite", "Isoptera", "Termitidae", "Blattodea", "Insecta",
        ["detritivore"], ["forest", "structures"], "worldwide-warm", "tiny",
        ["wood-eater", "colony"], ["white-ant"], "Q129857"),
    ("sawfly", "Symphyta", "Tenthredinidae", "Hymenoptera", "Insecta",
        ["herbivore"], "forest", "worldwide", "tiny",
        ["wasp-relative"], None, "Q193459"),
]

for e in HYMEN: _emit(e)


# ---------------------------------------------------------------------------
# FLIES + MOSQUITOES — Diptera
# ---------------------------------------------------------------------------
DIP = [
    ("fly", "Musca domestica", "Muscidae", "Diptera", "Insecta",
        ["omnivore"], "worldwide", "worldwide", "tiny",
        ["two-wings"], ["housefly"], "Q193459"),
    ("housefly", "Musca domestica", "Muscidae", "Diptera", "Insecta",
        ["omnivore"], ["structures", "worldwide"], "worldwide", "tiny",
        ["disease-vector"], ["common-fly"], "Q191184"),
    ("horsefly", "Tabanus", "Tabanidae", "Diptera", "Insecta",
        ["carnivore"], "farm", "worldwide", "tiny",
        ["biting", "blood-feeder"], ["gadfly"], "Q193459"),
    ("deerfly", "Chrysops", "Tabanidae", "Diptera", "Insecta",
        ["carnivore"], "forest", "worldwide", "tiny",
        ["biting"], None, "Q193459"),
    ("blowfly", "Calliphora vomitoria", "Calliphoridae", "Diptera", "Insecta",
        ["detritivore"], "worldwide", "worldwide", "tiny",
        ["carcass-feeder", "metallic-blue"], ["bluebottle"], "Q193459"),
    ("fruit-fly", "Drosophila melanogaster", "Drosophilidae", "Diptera", "Insecta",
        ["omnivore"], ["kitchen", "orchard"], "worldwide", "tiny",
        ["genetic-model-organism"], None, "Q130888"),
    ("mosquito", "Culicidae", "Culicidae", "Diptera", "Insecta",
        ["carnivore"], "worldwide", "worldwide", "tiny",
        ["blood-feeder", "disease-vector"], ["skeeter"], "Q7367"),
    ("aedes-mosquito", "Aedes aegypti", "Culicidae", "Diptera", "Insecta",
        ["carnivore"], "urban", "tropics-worldwide", "tiny",
        ["yellow-fever-vector"], ["yellow-fever-mosquito"], "Q193459"),
    ("gnat", "Nematocera", "Chironomidae", "Diptera", "Insecta",
        ["omnivore"], "worldwide", "worldwide", "tiny",
        ["swarming"], None, "Q193459"),
    ("midge", "Chironomidae", "Chironomidae", "Diptera", "Insecta",
        ["omnivore"], ["wetland", "worldwide"], "worldwide", "tiny",
        ["swarming"], None, "Q193459"),
    ("black-fly", "Simuliidae", "Simuliidae", "Diptera", "Insecta",
        ["carnivore"], "stream", "worldwide", "tiny",
        ["biting"], None, "Q193459"),
    ("crane-fly", "Tipulidae", "Tipulidae", "Diptera", "Insecta",
        ["nectarivore"], "meadow", "worldwide", "tiny",
        ["long-legged", "harmless"], ["daddy-longlegs"], "Q193459"),
    ("dragonfly", "Anisoptera", "Libellulidae", "Odonata", "Insecta",
        ["carnivore"], "pond", "worldwide", "tiny",
        ["fast-fliers", "aerial-predator"], ["dragon-fly"], "Q26948"),
    ("damselfly", "Zygoptera", "Coenagrionidae", "Odonata", "Insecta",
        ["carnivore"], "pond", "worldwide", "tiny",
        ["slender-wings-held-together"], None, "Q193459"),
    ("mayfly", "Ephemeroptera", "Ephemeridae", "Ephemeroptera", "Insecta",
        ["herbivore"], "stream", "worldwide", "tiny",
        ["ephemeral-adult", "mass-emergence"], None, "Q193459"),
]

for e in DIP: _emit(e)


# ---------------------------------------------------------------------------
# GRASSHOPPERS + CRICKETS + MANTIDS + ROACHES
# ---------------------------------------------------------------------------
ORTHO = [
    ("grasshopper", "Caelifera", "Acrididae", "Orthoptera", "Insecta",
        ["herbivore"], ["meadow", "field"], "worldwide", "tiny",
        ["jumping", "chirping"], None, "Q37363"),
    ("locust", "Schistocerca gregaria", "Acrididae", "Orthoptera", "Insecta",
        ["herbivore"], "farm", "africa-asia", "tiny",
        ["swarming-crop-devastation"], ["desert-locust"], "Q193459"),
    ("cricket", "Gryllus", "Gryllidae", "Orthoptera", "Insecta",
        ["omnivore"], ["field", "garden"], "worldwide", "tiny",
        ["chirping", "nocturnal"], None, "Q193459"),
    ("katydid", "Tettigoniidae", "Tettigoniidae", "Orthoptera", "Insecta",
        ["herbivore"], "forest", "worldwide", "tiny",
        ["leaf-mimic"], ["bush-cricket"], "Q193459"),
    ("cicada", "Cicadidae", "Cicadidae", "Hemiptera", "Insecta",
        ["herbivore"], "forest", "worldwide", "tiny",
        ["loud-chorus", "periodic-emergence"], None, "Q193459"),
    ("praying-mantis", "Mantis religiosa", "Mantidae", "Mantodea", "Insecta",
        ["carnivore"], ["garden", "meadow"], "worldwide", "tiny",
        ["ambush-predator", "cannibalistic-mating"], ["mantis"], "Q28347"),
    ("walking-stick", "Phasmatodea", "Phasmatidae", "Phasmatodea", "Insecta",
        ["herbivore"], "forest", "worldwide", "small",
        ["twig-mimic"], ["stick-insect"], "Q193459"),
    ("leaf-insect", "Phyllium", "Phylliidae", "Phasmatodea", "Insecta",
        ["herbivore"], "forest", "asia", "small",
        ["leaf-mimic"], None, "Q193459"),
    ("cockroach", "Blattodea", "Blattidae", "Blattodea", "Insecta",
        ["omnivore"], ["structures", "worldwide"], "worldwide", "tiny",
        ["nocturnal", "hardy"], ["roach"], "Q188748"),
    ("madagascar-hissing-cockroach", "Gromphadorhina portentosa", "Blaberidae", "Blattodea", "Insecta",
        ["detritivore"], "forest", "madagascar", "small",
        ["audible-hiss"], None, "Q193459"),
    ("earwig", "Forficula auricularia", "Forficulidae", "Dermaptera", "Insecta",
        ["omnivore"], ["garden", "structures"], "worldwide", "tiny",
        ["pincer-tail"], None, "Q193459"),
    ("silverfish", "Lepisma saccharinum", "Lepismatidae", "Zygentoma", "Insecta",
        ["omnivore"], "structures", "worldwide", "tiny",
        ["wingless", "nocturnal", "silvery"], None, "Q193459"),
    ("stonefly", "Plecoptera", "Perlidae", "Plecoptera", "Insecta",
        ["herbivore"], "stream", "worldwide", "tiny",
        ["indicator-species"], None, "Q193459"),
]

for e in ORTHO: _emit(e)


# ---------------------------------------------------------------------------
# TRUE BUGS — Hemiptera
# ---------------------------------------------------------------------------
HEMI = [
    ("bug", "Hemiptera", "Pentatomidae", "Hemiptera", "Insecta",
        ["omnivore"], "worldwide", "worldwide", "tiny",
        ["piercing-mouthparts"], None, "Q193459"),
    ("aphid", "Aphidoidea", "Aphididae", "Hemiptera", "Insecta",
        ["herbivore"], "garden", "worldwide", "tiny",
        ["sap-feeder", "asexual-reproduction"], ["plant-lice", "greenfly"], "Q193459"),
    ("cicada-nymph", "Cicadidae", "Cicadidae", "Hemiptera", "Insecta",
        ["herbivore"], "soil", "worldwide", "tiny",
        ["long-underground-life"], None, "Q193459"),
    ("stink-bug", "Pentatomidae", "Pentatomidae", "Hemiptera", "Insecta",
        ["herbivore"], ["garden", "farm"], "worldwide", "tiny",
        ["chemical-defense"], ["shield-bug"], "Q193459"),
    ("assassin-bug", "Reduviidae", "Reduviidae", "Hemiptera", "Insecta",
        ["carnivore"], "field", "worldwide", "tiny",
        ["predator", "ambush"], None, "Q193459"),
    ("bed-bug", "Cimex lectularius", "Cimicidae", "Hemiptera", "Insecta",
        ["carnivore"], "structures", "worldwide", "tiny",
        ["blood-feeder", "nocturnal"], ["bedbug"], "Q193459"),
    ("water-strider", "Gerridae", "Gerridae", "Hemiptera", "Insecta",
        ["carnivore"], "pond-surface", "worldwide", "tiny",
        ["surface-walker"], ["pond-skater"], "Q193459"),
    ("water-boatman", "Corixidae", "Corixidae", "Hemiptera", "Insecta",
        ["omnivore"], "pond", "worldwide", "tiny",
        ["aquatic", "oar-legs"], None, "Q193459"),
    ("scale-insect", "Coccoidea", "Coccidae", "Hemiptera", "Insecta",
        ["herbivore"], "garden", "worldwide", "tiny",
        ["sap-feeder", "stationary"], None, "Q193459"),
    ("leafhopper", "Cicadellidae", "Cicadellidae", "Hemiptera", "Insecta",
        ["herbivore"], "field", "worldwide", "tiny",
        ["jumping"], None, "Q193459"),
    ("whitefly", "Aleyrodidae", "Aleyrodidae", "Hemiptera", "Insecta",
        ["herbivore"], "garden", "worldwide", "tiny",
        ["greenhouse-pest"], None, "Q193459"),
    ("mealybug", "Pseudococcidae", "Pseudococcidae", "Hemiptera", "Insecta",
        ["herbivore"], "garden", "worldwide", "tiny",
        ["waxy-covering"], None, "Q193459"),
]

for e in HEMI: _emit(e)


# ---------------------------------------------------------------------------
# ARACHNIDS — spiders + scorpions + ticks + mites
# ---------------------------------------------------------------------------
ARACH = [
    ("spider", "Araneae", "Araneidae", "Araneae", "Arachnida",
        ["carnivore"], "worldwide", "worldwide", "tiny",
        ["eight-legs", "silk-producer"], None, "Q1357"),
    ("tarantula", "Theraphosidae", "Theraphosidae", "Araneae", "Arachnida",
        ["carnivore"], ["desert", "jungle"], "worldwide-warm", "small",
        ["large", "burrowing", "hairy"], None, "Q152234"),
    ("orb-weaver", "Araneidae", "Araneidae", "Araneae", "Arachnida",
        ["carnivore"], "garden", "worldwide", "tiny",
        ["circular-web"], None, "Q193459"),
    ("garden-spider", "Argiope aurantia", "Araneidae", "Araneae", "Arachnida",
        ["carnivore"], "garden", "worldwide", "tiny",
        ["zigzag-web-decoration"], ["writing-spider"], "Q193459"),
    ("black-widow", "Latrodectus mactans", "Theridiidae", "Araneae", "Arachnida",
        ["carnivore"], "structures", "americas", "tiny",
        ["venomous", "red-hourglass"], None, "Q193459"),
    ("brown-recluse", "Loxosceles reclusa", "Sicariidae", "Araneae", "Arachnida",
        ["carnivore"], "structures", "north-america-central", "tiny",
        ["venomous", "necrotic-bite"], ["fiddleback-spider"], "Q193459"),
    ("wolf-spider", "Lycosidae", "Lycosidae", "Araneae", "Arachnida",
        ["carnivore"], ["field", "forest"], "worldwide", "tiny",
        ["ground-hunter", "carries-eggs"], None, "Q193459"),
    ("jumping-spider", "Salticidae", "Salticidae", "Araneae", "Arachnida",
        ["carnivore"], "worldwide", "worldwide", "tiny",
        ["stalking", "large-eyes"], None, "Q193459"),
    ("crab-spider", "Thomisidae", "Thomisidae", "Araneae", "Arachnida",
        ["carnivore"], "flower", "worldwide", "tiny",
        ["ambush-predator"], None, "Q193459"),
    ("funnel-web-spider", "Atracidae", "Atracidae", "Araneae", "Arachnida",
        ["carnivore"], "forest", "australia", "tiny",
        ["highly-venomous"], ["sydney-funnel-web"], "Q193459"),
    ("goliath-birdeater", "Theraphosa blondi", "Theraphosidae", "Araneae", "Arachnida",
        ["carnivore"], "jungle", "south-america", "small",
        ["largest-spider"], None, "Q193459"),
    ("daddy-long-legs", "Pholcus phalangioides", "Pholcidae", "Araneae", "Arachnida",
        ["carnivore"], "structures", "worldwide", "tiny",
        ["long-thin-legs"], ["cellar-spider"], "Q193459"),
    ("harvestman", "Opiliones", "Phalangiidae", "Opiliones", "Arachnida",
        ["omnivore"], ["forest", "structures"], "worldwide", "tiny",
        ["not-a-spider"], ["daddy-longlegs"], "Q193459"),
    ("scorpion", "Scorpiones", "Buthidae", "Scorpiones", "Arachnida",
        ["carnivore"], ["desert", "forest"], "worldwide-warm", "tiny",
        ["stinger-tail", "pincers", "uv-glow"], None, "Q193459"),
    ("emperor-scorpion", "Pandinus imperator", "Scorpionidae", "Scorpiones", "Arachnida",
        ["carnivore"], "jungle", "africa", "small",
        ["largest-scorpion"], None, "Q193459"),
    ("bark-scorpion", "Centruroides sculpturatus", "Buthidae", "Scorpiones", "Arachnida",
        ["carnivore"], "desert", "north-america-southwest", "tiny",
        ["venomous"], None, "Q193459"),
    ("tick", "Ixodida", "Ixodidae", "Ixodida", "Arachnida",
        ["carnivore"], ["forest", "meadow"], "worldwide", "tiny",
        ["blood-feeder", "disease-vector"], None, "Q193459"),
    ("mite", "Acari", "Acaridae", "Acari", "Arachnida",
        ["omnivore"], "worldwide", "worldwide", "tiny",
        ["microscopic"], None, "Q193459"),
    ("dust-mite", "Dermatophagoides", "Pyroglyphidae", "Sarcoptiformes", "Arachnida",
        ["detritivore"], "structures", "worldwide", "tiny",
        ["allergen-source"], None, "Q193459"),
    ("chigger", "Trombiculidae", "Trombiculidae", "Trombidiformes", "Arachnida",
        ["carnivore"], "field", "worldwide", "tiny",
        ["itchy-bite", "larval-stage"], None, "Q193459"),
]

for e in ARACH: _emit(e)


# ---------------------------------------------------------------------------
# CENTIPEDES + MILLIPEDES + CRUSTACEANS + WORMS (arthropods & annelids)
# ---------------------------------------------------------------------------
OTHER = [
    ("centipede", "Chilopoda", "Scolopendridae", "Scolopendromorpha", "Chilopoda",
        ["carnivore"], ["forest", "structures"], "worldwide", "tiny",
        ["many-legs-one-per-segment", "venomous"], None, "Q193459"),
    ("millipede", "Diplopoda", "Julidae", "Julida", "Diplopoda",
        ["detritivore"], "forest-floor", "worldwide", "tiny",
        ["many-legs-two-per-segment", "coiling-defense"], None, "Q193459"),
    ("pill-bug", "Armadillidium vulgare", "Armadillidiidae", "Isopoda", "Malacostraca",
        ["detritivore"], "garden", "worldwide", "tiny",
        ["curls-into-ball"], ["roly-poly", "sow-bug", "wood-louse"], "Q193459"),
    ("crab", "Brachyura", "Portunidae", "Decapoda", "Malacostraca",
        ["omnivore"], ["ocean", "beach"], "worldwide", "small",
        ["sideways-walking", "pincers"], None, "Q1357"),
    ("blue-crab", "Callinectes sapidus", "Portunidae", "Decapoda", "Malacostraca",
        ["omnivore"], "estuary", "atlantic", "small",
        ["swimming-legs"], None, "Q193459"),
    ("king-crab", "Paralithodes camtschaticus", "Lithodidae", "Decapoda", "Malacostraca",
        ["omnivore"], "deep-ocean", "north-pacific", "medium",
        ["prized-food"], ["alaska-king-crab"], "Q193459"),
    ("dungeness-crab", "Metacarcinus magister", "Cancridae", "Decapoda", "Malacostraca",
        ["omnivore"], "ocean-coast", "north-pacific", "small", None, None, "Q193459"),
    ("hermit-crab", "Paguroidea", "Paguridae", "Decapoda", "Malacostraca",
        ["omnivore"], ["ocean-coast", "beach"], "worldwide", "tiny",
        ["shell-borrower"], None, "Q193459"),
    ("horseshoe-crab", "Limulus polyphemus", "Limulidae", "Xiphosurida", "Merostomata",
        ["omnivore"], "ocean-coast", "atlantic", "medium",
        ["living-fossil", "blue-blood"], None, "Q193459"),
    ("lobster", "Homarus americanus", "Nephropidae", "Decapoda", "Malacostraca",
        ["omnivore"], "ocean-floor", "north-atlantic", "medium",
        ["large-claws"], ["american-lobster"], "Q193459"),
    ("spiny-lobster", "Palinurus elephas", "Palinuridae", "Decapoda", "Malacostraca",
        ["omnivore"], "ocean-reef", "worldwide-warm", "small",
        ["no-large-claws"], None, "Q193459"),
    ("crayfish", "Astacoidea", "Cambaridae", "Decapoda", "Malacostraca",
        ["omnivore"], ["river", "creek"], "worldwide", "tiny",
        ["freshwater"], ["crawfish", "crawdad", "mudbug"], "Q193459"),
    ("shrimp", "Caridea", "Palaemonidae", "Decapoda", "Malacostraca",
        ["omnivore"], "ocean", "worldwide", "tiny",
        ["swimming"], ["prawn"], "Q193459"),
    ("krill", "Euphausia superba", "Euphausiidae", "Euphausiacea", "Malacostraca",
        ["filter-feeder"], "ocean", "worldwide", "tiny",
        ["swarming", "whale-food"], ["antarctic-krill"], "Q193459"),
    ("barnacle", "Cirripedia", "Balanidae", "Sessilia", "Thecostraca",
        ["filter-feeder"], "ocean-rocks", "worldwide", "tiny",
        ["sessile", "shelled"], None, "Q193459"),
    ("earthworm", "Lumbricus terrestris", "Lumbricidae", "Opisthopora", "Clitellata",
        ["detritivore"], "soil", "worldwide", "tiny",
        ["soil-aerator"], ["nightcrawler"], "Q193459"),
    ("leech", "Hirudinea", "Hirudinidae", "Arhynchobdellida", "Clitellata",
        ["carnivore"], ["pond", "wetland"], "worldwide", "tiny",
        ["blood-feeder"], None, "Q193459"),
    ("nematode", "Nematoda", "Rhabditidae", "Rhabditida", "Chromadorea",
        ["omnivore"], "soil", "worldwide", "tiny",
        ["microscopic-worm"], ["roundworm"], "Q193459"),
    ("tardigrade", "Hypsibius dujardini", "Hypsibiidae", "Parachela", "Eutardigrada",
        ["omnivore"], "moss", "worldwide", "tiny",
        ["extremophile", "cryptobiosis"], ["water-bear", "moss-piglet"], "Q193459"),
]

for e in OTHER: _emit(e)
