"""Trees — the ~300 most-named tree species + genera.
Compact tuple form.
"""

from _helpers import node, wikidata, tax, authored


def tree(canonical, sci, family, order, diet, habitat, region, size,
         used_for=None, synonyms=None, seasons=None, qid=None):
    return node(canonical, "plant",
                synonyms=synonyms or [],
                scientific_name=sci,
                taxonomy=tax(kingdom="Plantae",
                             order=order, family=family,
                             genus=sci.split()[0] if sci else None,
                             species=sci, common_name=canonical),
                lives_in=habitat, region_native_to=region,
                size_scale=size, used_for=used_for,
                season=seasons,
                kid_friendly=True,
                provenance=[wikidata(qid)] if qid else [authored()])


NODES = []


def _emit(entry):
    n = len(entry)
    if n == 9:
        canonical, sci, family, order, habitat, region, size, used, qid = entry
        syns = None; seasons = None
    elif n == 10:
        canonical, sci, family, order, habitat, region, size, used, syns, qid = entry
        seasons = None
    elif n == 11:
        canonical, sci, family, order, habitat, region, size, used, syns, seasons, qid = entry
    else:
        raise ValueError(f"Bad tree tuple len {n}: {entry!r}")
    NODES.append(tree(canonical, sci, family, order,
                      diet=["photosynthesis"],
                      habitat=[habitat] if isinstance(habitat, str) else habitat,
                      region=[region] if isinstance(region, str) else region,
                      size=size, used_for=used, synonyms=syns, seasons=seasons, qid=qid))


# ---------------------------------------------------------------------------
# CONIFERS
# ---------------------------------------------------------------------------
CONIFERS = [
    ("pine", "Pinus", "Pinaceae", "Pinales",
        "forest", "north-hemisphere", "large",
        ["lumber", "resin", "paper-pulp"], ["pine-tree"], "Q12024"),
    ("scots-pine", "Pinus sylvestris", "Pinaceae", "Pinales",
        "forest", "eurasia", "large",
        ["lumber", "furniture"], None, "Q129091"),
    ("white-pine", "Pinus strobus", "Pinaceae", "Pinales",
        "forest", "north-america-east", "large",
        ["lumber", "masts"], ["eastern-white-pine"], "Q193459"),
    ("ponderosa-pine", "Pinus ponderosa", "Pinaceae", "Pinales",
        "forest", "north-america-west", "large",
        ["lumber", "windbreak"], None, "Q193459"),
    ("longleaf-pine", "Pinus palustris", "Pinaceae", "Pinales",
        "forest", "north-america-southeast", "large",
        ["lumber", "pine-straw"], None, "Q193459"),
    ("lodgepole-pine", "Pinus contorta", "Pinaceae", "Pinales",
        "forest", "north-america-west", "large",
        ["lumber"], None, "Q193459"),
    ("bristlecone-pine", "Pinus longaeva", "Pinaceae", "Pinales",
        "mountain", "north-america-west", "medium",
        ["oldest-living-trees"], None, "Q193459"),
    ("stone-pine", "Pinus pinea", "Pinaceae", "Pinales",
        "coastal-forest", "mediterranean", "large",
        ["pine-nuts", "ornamental"], ["italian-stone-pine", "umbrella-pine"], "Q193459"),
    ("loblolly-pine", "Pinus taeda", "Pinaceae", "Pinales",
        "forest", "north-america-southeast", "large",
        ["lumber", "paper"], None, "Q193459"),
    ("fir", "Abies", "Pinaceae", "Pinales",
        "forest", "north-hemisphere", "large",
        ["lumber", "christmas-tree"], ["fir-tree"], "Q107586"),
    ("douglas-fir", "Pseudotsuga menziesii", "Pinaceae", "Pinales",
        "forest", "north-america-west", "huge",
        ["lumber", "christmas-tree"], None, "Q158248"),
    ("balsam-fir", "Abies balsamea", "Pinaceae", "Pinales",
        "boreal-forest", "north-america-east", "medium",
        ["christmas-tree", "resin"], None, "Q193459"),
    ("fraser-fir", "Abies fraseri", "Pinaceae", "Pinales",
        "mountain", "north-america-southeast", "medium",
        ["christmas-tree"], None, "Q193459"),
    ("spruce", "Picea", "Pinaceae", "Pinales",
        "forest", "north-hemisphere", "large",
        ["lumber", "paper", "instrument-tops"], None, "Q118809"),
    ("norway-spruce", "Picea abies", "Pinaceae", "Pinales",
        "forest", "europe", "huge",
        ["lumber", "christmas-tree"], None, "Q193459"),
    ("blue-spruce", "Picea pungens", "Pinaceae", "Pinales",
        "mountain", "north-america-west", "large",
        ["ornamental"], ["colorado-blue-spruce"], "Q193459"),
    ("sitka-spruce", "Picea sitchensis", "Pinaceae", "Pinales",
        "coastal-forest", "north-america-northwest", "huge",
        ["lumber", "aircraft"], None, "Q193459"),
    ("hemlock", "Tsuga canadensis", "Pinaceae", "Pinales",
        "forest", "north-america-east", "large",
        ["lumber", "tannin"], ["eastern-hemlock"], "Q193459"),
    ("larch", "Larix", "Pinaceae", "Pinales",
        "boreal-forest", "north-hemisphere", "large",
        ["lumber", "deciduous-conifer"], ["tamarack"], "Q193459"),
    ("cedar", "Cedrus", "Pinaceae", "Pinales",
        "mountain", "mediterranean", "large",
        ["fragrant-wood", "shingles"], ["cedar-tree"], "Q125896"),
    ("cedar-of-lebanon", "Cedrus libani", "Pinaceae", "Pinales",
        "mountain", "lebanon", "large",
        ["timber", "biblical-tree"], None, "Q193459"),
    ("western-red-cedar", "Thuja plicata", "Cupressaceae", "Cupressales",
        "coastal-forest", "north-america-northwest", "huge",
        ["shingles", "canoes"], None, "Q193459"),
    ("juniper", "Juniperus", "Cupressaceae", "Cupressales",
        ["forest", "scrubland"], "north-hemisphere", "small",
        ["berries-for-gin", "wood"], None, "Q193459"),
    ("cypress", "Cupressus", "Cupressaceae", "Cupressales",
        "coastal", "mediterranean", "medium",
        ["ornamental", "graveyards"], None, "Q193459"),
    ("bald-cypress", "Taxodium distichum", "Cupressaceae", "Cupressales",
        ["swamp", "wetland"], "north-america-southeast", "large",
        ["water-tolerant", "lumber"], None, "Q193459"),
    ("dawn-redwood", "Metasequoia glyptostroboides", "Cupressaceae", "Cupressales",
        "forest", "china", "large",
        ["deciduous-conifer", "living-fossil"], None, "Q193459"),
    ("giant-sequoia", "Sequoiadendron giganteum", "Cupressaceae", "Cupressales",
        "mountain-forest", "north-america-west", "massive",
        ["largest-trees-by-volume"], ["sierra-redwood"], "Q193459"),
    ("coast-redwood", "Sequoia sempervirens", "Cupressaceae", "Cupressales",
        "coastal-forest", "north-america-west", "massive",
        ["tallest-trees", "lumber"], ["redwood", "california-redwood"], "Q193459"),
    ("yew", "Taxus baccata", "Taxaceae", "Pinales",
        "forest", "europe", "medium",
        ["long-lived", "toxic-berries", "bow-wood"], ["english-yew"], "Q193459"),
    ("araucaria", "Araucaria araucana", "Araucariaceae", "Araucariales",
        "mountain", "chile-argentina", "large",
        ["ornamental", "edible-seeds"], ["monkey-puzzle"], "Q193459"),
    ("norfolk-island-pine", "Araucaria heterophylla", "Araucariaceae", "Araucariales",
        "coastal", "norfolk-island", "medium",
        ["ornamental"], None, "Q193459"),
    ("kauri", "Agathis australis", "Araucariaceae", "Araucariales",
        "forest", "new-zealand", "huge",
        ["large-timber"], None, "Q193459"),
    ("ginkgo", "Ginkgo biloba", "Ginkgoaceae", "Ginkgoales",
        "urban", "china-ancient", "large",
        ["ornamental", "medicinal-leaves", "living-fossil"], ["maidenhair-tree"], "Q43284"),
]

for e in CONIFERS: _emit(e)


# ---------------------------------------------------------------------------
# DECIDUOUS BROADLEAVES — oaks, maples, elms, birches, beeches
# ---------------------------------------------------------------------------
DECID = [
    ("oak", "Quercus", "Fagaceae", "Fagales",
        "forest", "worldwide-temperate", "large",
        ["lumber", "furniture", "acorns", "cooperage"], ["oak-tree"], "Q12004"),
    ("white-oak", "Quercus alba", "Fagaceae", "Fagales",
        "forest", "north-america-east", "large",
        ["barrels", "lumber"], None, "Q193459"),
    ("red-oak", "Quercus rubra", "Fagaceae", "Fagales",
        "forest", "north-america-east", "large",
        ["lumber", "flooring"], ["northern-red-oak"], "Q193459"),
    ("pin-oak", "Quercus palustris", "Fagaceae", "Fagales",
        "forest", "north-america-east", "large",
        ["ornamental"], None, "Q193459"),
    ("live-oak", "Quercus virginiana", "Fagaceae", "Fagales",
        "forest", "north-america-southeast", "large",
        ["evergreen", "shipbuilding"], ["southern-live-oak"], "Q193459"),
    ("english-oak", "Quercus robur", "Fagaceae", "Fagales",
        "forest", "europe", "large",
        ["lumber", "shipbuilding"], None, "Q193459"),
    ("cork-oak", "Quercus suber", "Fagaceae", "Fagales",
        "mediterranean-forest", "iberia", "medium",
        ["cork-bark"], None, "Q193459"),
    ("bur-oak", "Quercus macrocarpa", "Fagaceae", "Fagales",
        "prairie", "north-america", "large",
        ["fire-resistant"], None, "Q193459"),
    ("maple", "Acer", "Sapindaceae", "Sapindales",
        "forest", "north-hemisphere", "large",
        ["lumber", "syrup", "ornamental"], ["maple-tree"], "Q31742"),
    ("sugar-maple", "Acer saccharum", "Sapindaceae", "Sapindales",
        "forest", "north-america-east", "large",
        ["maple-syrup", "lumber", "flooring"], None, "Q193459"),
    ("red-maple", "Acer rubrum", "Sapindaceae", "Sapindales",
        "forest", "north-america-east", "medium",
        ["ornamental", "fall-color"], None, "Q193459"),
    ("silver-maple", "Acer saccharinum", "Sapindaceae", "Sapindales",
        "riparian", "north-america-east", "large",
        ["fast-growing"], None, "Q193459"),
    ("japanese-maple", "Acer palmatum", "Sapindaceae", "Sapindales",
        "garden", "japan", "small",
        ["ornamental", "bonsai"], None, "Q193459"),
    ("norway-maple", "Acer platanoides", "Sapindaceae", "Sapindales",
        "urban", "europe", "medium",
        ["street-tree"], None, "Q193459"),
    ("boxelder", "Acer negundo", "Sapindaceae", "Sapindales",
        "riparian", "north-america", "medium",
        ["fast-growing"], ["ash-leaved-maple"], "Q193459"),
    ("elm", "Ulmus", "Ulmaceae", "Rosales",
        "urban", "worldwide-temperate", "large",
        ["lumber", "shade-tree"], ["elm-tree"], "Q193459"),
    ("american-elm", "Ulmus americana", "Ulmaceae", "Rosales",
        "urban", "north-america-east", "large",
        ["vase-shape", "dutch-elm-disease-susceptible"], None, "Q193459"),
    ("english-elm", "Ulmus procera", "Ulmaceae", "Rosales",
        "hedgerow", "europe", "large",
        ["shade-tree"], None, "Q193459"),
    ("beech", "Fagus", "Fagaceae", "Fagales",
        "forest", "north-hemisphere", "large",
        ["lumber", "smooth-bark", "beechnuts"], ["beech-tree"], "Q124515"),
    ("american-beech", "Fagus grandifolia", "Fagaceae", "Fagales",
        "forest", "north-america-east", "large",
        ["shade-tree"], None, "Q193459"),
    ("european-beech", "Fagus sylvatica", "Fagaceae", "Fagales",
        "forest", "europe", "large",
        ["lumber", "hedging"], None, "Q193459"),
    ("birch", "Betula", "Betulaceae", "Fagales",
        "forest", "north-hemisphere", "medium",
        ["paper-bark", "canoes", "syrup"], ["birch-tree"], "Q125051"),
    ("paper-birch", "Betula papyrifera", "Betulaceae", "Fagales",
        ["boreal-forest", "forest"], "north-america", "medium",
        ["canoes", "white-bark"], ["white-birch", "canoe-birch"], "Q193459"),
    ("river-birch", "Betula nigra", "Betulaceae", "Fagales",
        "riparian", "north-america-east", "medium",
        ["ornamental", "peeling-bark"], None, "Q193459"),
    ("yellow-birch", "Betula alleghaniensis", "Betulaceae", "Fagales",
        "forest", "north-america-east", "large",
        ["lumber", "flooring"], None, "Q193459"),
    ("silver-birch", "Betula pendula", "Betulaceae", "Fagales",
        "forest", "eurasia", "medium",
        ["ornamental"], None, "Q193459"),
    ("alder", "Alnus", "Betulaceae", "Fagales",
        "riparian", "north-hemisphere", "medium",
        ["nitrogen-fixing", "lumber"], None, "Q193459"),
    ("hazel", "Corylus avellana", "Betulaceae", "Fagales",
        "hedgerow", "europe", "small",
        ["hazelnuts", "coppice-wood"], ["common-hazel"], "Q193459"),
    ("hornbeam", "Carpinus betulus", "Betulaceae", "Fagales",
        "forest", "europe", "medium",
        ["dense-wood", "hedging"], None, "Q193459"),
    ("hickory", "Carya", "Juglandaceae", "Fagales",
        "forest", "north-america-east", "large",
        ["nuts", "tool-handles", "smoking-wood"], None, "Q193459"),
    ("shagbark-hickory", "Carya ovata", "Juglandaceae", "Fagales",
        "forest", "north-america-east", "large",
        ["shaggy-bark", "nuts"], None, "Q193459"),
    ("pecan", "Carya illinoinensis", "Juglandaceae", "Fagales",
        "orchard", "north-america-south", "large",
        ["pecans", "orchard"], None, "Q193459"),
    ("walnut", "Juglans regia", "Juglandaceae", "Fagales",
        "orchard", "eurasia", "large",
        ["walnuts", "furniture-wood"], ["english-walnut"], "Q193459"),
    ("black-walnut", "Juglans nigra", "Juglandaceae", "Fagales",
        "forest", "north-america-east", "large",
        ["nuts", "prized-wood"], None, "Q193459"),
    ("butternut", "Juglans cinerea", "Juglandaceae", "Fagales",
        "forest", "north-america-east", "medium",
        ["nuts"], ["white-walnut"], "Q193459"),
    ("chestnut", "Castanea sativa", "Fagaceae", "Fagales",
        "forest", "europe", "large",
        ["nuts", "coppice-wood"], ["sweet-chestnut"], "Q193459"),
    ("american-chestnut", "Castanea dentata", "Fagaceae", "Fagales",
        "forest", "north-america-east", "large",
        ["nuts", "chestnut-blight-decimated"], None, "Q193459"),
    ("poplar", "Populus", "Salicaceae", "Malpighiales",
        "riparian", "worldwide-temperate", "large",
        ["fast-growing", "pulp"], None, "Q193459"),
    ("cottonwood", "Populus deltoides", "Salicaceae", "Malpighiales",
        "riparian", "north-america", "large",
        ["fluffy-seeds"], ["eastern-cottonwood"], "Q193459"),
    ("aspen", "Populus tremuloides", "Salicaceae", "Malpighiales",
        ["mountain-forest", "forest"], "north-america", "medium",
        ["clonal-groves", "quaking-leaves"], ["quaking-aspen"], "Q193459"),
    ("willow", "Salix", "Salicaceae", "Malpighiales",
        "riparian", "worldwide-temperate", "medium",
        ["basketry", "salicylate-medicine"], ["willow-tree"], "Q157658"),
    ("weeping-willow", "Salix babylonica", "Salicaceae", "Malpighiales",
        ["riparian", "garden"], "east-asia", "medium",
        ["ornamental", "graceful-form"], None, "Q193459"),
    ("pussy-willow", "Salix discolor", "Salicaceae", "Malpighiales",
        "wetland", "north-america", "small",
        ["fuzzy-catkins"], None, "Q193459"),
    ("ash", "Fraxinus", "Oleaceae", "Lamiales",
        "forest", "north-hemisphere", "large",
        ["lumber", "tool-handles", "baseball-bats"], ["ash-tree"], "Q193459"),
    ("white-ash", "Fraxinus americana", "Oleaceae", "Lamiales",
        "forest", "north-america-east", "large",
        ["baseball-bats", "lumber"], None, "Q193459"),
    ("green-ash", "Fraxinus pennsylvanica", "Oleaceae", "Lamiales",
        "urban", "north-america", "medium",
        ["street-tree", "emerald-ash-borer-vulnerable"], None, "Q193459"),
    ("mountain-ash", "Sorbus aucuparia", "Rosaceae", "Rosales",
        "mountain", "europe", "small",
        ["rowanberries", "ornamental"], ["rowan"], "Q193459"),
    ("linden", "Tilia", "Malvaceae", "Malvales",
        "urban", "north-hemisphere", "large",
        ["shade-tree", "fragrant-flowers", "bee-forage"], ["basswood", "lime-tree"], "Q193459"),
    ("sycamore", "Platanus occidentalis", "Platanaceae", "Proteales",
        "riparian", "north-america-east", "huge",
        ["peeling-bark", "shade-tree"], ["american-planetree"], "Q193459"),
    ("london-plane", "Platanus × acerifolia", "Platanaceae", "Proteales",
        "urban", "hybrid-worldwide", "large",
        ["street-tree", "pollution-tolerant"], None, "Q193459"),
    ("horse-chestnut", "Aesculus hippocastanum", "Sapindaceae", "Sapindales",
        "urban", "balkans", "large",
        ["conkers", "ornamental"], None, "Q193459"),
    ("buckeye", "Aesculus glabra", "Sapindaceae", "Sapindales",
        "forest", "north-america-central", "medium",
        ["ornamental", "state-tree-of-ohio"], ["ohio-buckeye"], "Q193459"),
    ("catalpa", "Catalpa bignonioides", "Bignoniaceae", "Lamiales",
        "urban", "north-america-south", "medium",
        ["large-leaves", "long-seed-pods"], None, "Q193459"),
    ("tupelo", "Nyssa sylvatica", "Nyssaceae", "Cornales",
        "swamp", "north-america-east", "medium",
        ["fall-color", "honey-source"], ["black-gum"], "Q193459"),
    ("sassafras", "Sassafras albidum", "Lauraceae", "Laurales",
        "forest", "north-america-east", "medium",
        ["aromatic", "root-beer-flavor"], None, "Q193459"),
    ("sweetgum", "Liquidambar styraciflua", "Altingiaceae", "Saxifragales",
        "forest", "north-america-east", "large",
        ["fall-color", "spiky-fruits"], None, "Q193459"),
    ("tulip-tree", "Liriodendron tulipifera", "Magnoliaceae", "Magnoliales",
        "forest", "north-america-east", "huge",
        ["lumber", "tulip-shaped-flowers"], ["yellow-poplar"], "Q193459"),
    ("magnolia", "Magnolia grandiflora", "Magnoliaceae", "Magnoliales",
        ["garden", "forest"], "north-america-southeast", "large",
        ["ornamental", "fragrant-flowers"], ["southern-magnolia"], "Q193459"),
    ("dogwood", "Cornus florida", "Cornaceae", "Cornales",
        ["forest", "garden"], "north-america-east", "small",
        ["ornamental", "spring-flowers"], ["flowering-dogwood"], "Q193459"),
    ("redbud", "Cercis canadensis", "Fabaceae", "Fabales",
        ["forest", "garden"], "north-america-east", "small",
        ["pink-flowers"], ["eastern-redbud"], "Q193459"),
    ("locust", "Robinia pseudoacacia", "Fabaceae", "Fabales",
        "forest", "north-america-east", "large",
        ["rot-resistant-wood", "nitrogen-fixing"], ["black-locust"], "Q193459"),
    ("honey-locust", "Gleditsia triacanthos", "Fabaceae", "Fabales",
        "urban", "north-america", "large",
        ["street-tree", "thorny-native"], None, "Q193459"),
    ("mulberry", "Morus alba", "Moraceae", "Rosales",
        ["urban", "orchard"], "east-asia", "medium",
        ["silkworm-food", "berries"], ["white-mulberry"], "Q193459"),
    ("fig", "Ficus carica", "Moraceae", "Rosales",
        "orchard", "mediterranean", "small",
        ["figs", "shade"], ["common-fig"], "Q193459"),
    ("banyan", "Ficus benghalensis", "Moraceae", "Rosales",
        "jungle", "india", "huge",
        ["aerial-roots", "shade"], None, "Q193459"),
    ("bodhi-tree", "Ficus religiosa", "Moraceae", "Rosales",
        "temple-garden", "india", "large",
        ["sacred-tree"], ["sacred-fig", "peepal"], "Q193459"),
    ("baobab", "Adansonia digitata", "Malvaceae", "Malvales",
        "savanna", "africa", "huge",
        ["water-storage", "long-lived"], ["tree-of-life"], "Q193459"),
    ("mahogany", "Swietenia macrophylla", "Meliaceae", "Sapindales",
        "jungle", "central-america", "large",
        ["prized-furniture-wood"], None, "Q193459"),
    ("teak", "Tectona grandis", "Lamiaceae", "Lamiales",
        "monsoon-forest", "south-asia", "large",
        ["boat-building", "furniture"], None, "Q193459"),
    ("ebony", "Diospyros ebenum", "Ebenaceae", "Ericales",
        "forest", "sri-lanka", "medium",
        ["black-wood", "carving"], None, "Q193459"),
    ("rosewood", "Dalbergia nigra", "Fabaceae", "Fabales",
        "jungle", "brazil", "medium",
        ["furniture", "musical-instruments"], None, "Q193459"),
    ("bamboo", "Bambusa vulgaris", "Poaceae", "Poales",
        ["forest", "garden"], "asia", "large",
        ["construction", "furniture", "food-shoots"], None, "Q193459"),
    ("palm", "Arecaceae", "Arecaceae", "Arecales",
        ["coastal", "tropical"], "tropics-worldwide", "large",
        ["fronds", "coconuts-or-dates"], ["palm-tree"], "Q14001"),
    ("coconut-palm", "Cocos nucifera", "Arecaceae", "Arecales",
        "coastal", "tropics-worldwide", "large",
        ["coconuts", "coir"], ["coco-palm"], "Q193459"),
    ("date-palm", "Phoenix dactylifera", "Arecaceae", "Arecales",
        "oasis", "middle-east", "large",
        ["dates"], None, "Q193459"),
    ("acai-palm", "Euterpe oleracea", "Arecaceae", "Arecales",
        "jungle", "amazon-basin", "medium",
        ["acai-berries", "palm-hearts"], None, "Q193459"),
    ("oil-palm", "Elaeis guineensis", "Arecaceae", "Arecales",
        "farm", "africa", "large",
        ["palm-oil"], None, "Q193459"),
    ("sago-palm", "Metroxylon sagu", "Arecaceae", "Arecales",
        "swamp", "southeast-asia", "medium",
        ["sago-starch"], None, "Q193459"),
    ("saw-palmetto", "Serenoa repens", "Arecaceae", "Arecales",
        "scrubland", "north-america-southeast", "small",
        ["berries-medicinal"], None, "Q193459"),
    ("royal-palm", "Roystonea regia", "Arecaceae", "Arecales",
        "urban", "caribbean", "large",
        ["ornamental", "avenue-tree"], None, "Q193459"),
    ("acacia", "Vachellia", "Fabaceae", "Fabales",
        "savanna", "africa", "medium",
        ["thorns", "gum-arabic"], ["thorn-tree"], "Q193459"),
    ("mimosa", "Albizia julibrissin", "Fabaceae", "Fabales",
        "garden", "asia", "medium",
        ["pink-flowers"], ["silk-tree"], "Q193459"),
    ("jacaranda", "Jacaranda mimosifolia", "Bignoniaceae", "Lamiales",
        "urban", "south-america", "medium",
        ["purple-flowers"], None, "Q193459"),
    ("frangipani", "Plumeria", "Apocynaceae", "Gentianales",
        "garden", "central-america", "small",
        ["fragrant-flowers"], ["plumeria"], "Q193459"),
    ("bougainvillea", "Bougainvillea", "Nyctaginaceae", "Caryophyllales",
        "garden", "south-america", "medium",
        ["colorful-bracts"], None, "Q193459"),
    ("eucalyptus", "Eucalyptus globulus", "Myrtaceae", "Myrtales",
        "forest", "australia", "huge",
        ["essential-oil", "koala-food", "pulp"], ["blue-gum"], "Q193459"),
    ("gum-tree", "Eucalyptus", "Myrtaceae", "Myrtales",
        "forest", "australia", "large",
        ["fast-growing"], None, "Q193459"),
    ("olive-tree", "Olea europaea", "Oleaceae", "Lamiales",
        "orchard", "mediterranean", "medium",
        ["olives", "olive-oil", "long-lived"], ["olive"], "Q193459"),
    ("cork-tree", "Quercus suber", "Fagaceae", "Fagales",
        "mediterranean-forest", "iberia", "medium",
        ["cork"], None, "Q193459"),
    ("carob-tree", "Ceratonia siliqua", "Fabaceae", "Fabales",
        "mediterranean-scrubland", "mediterranean", "medium",
        ["carob-pods"], None, "Q193459"),
    ("almond-tree", "Prunus dulcis", "Rosaceae", "Rosales",
        "orchard", "mediterranean", "medium",
        ["almonds"], None, "Q193459"),
    ("cherry-tree", "Prunus serrulata", "Rosaceae", "Rosales",
        ["garden", "orchard"], "japan", "medium",
        ["cherry-blossoms", "cherries"], ["sakura"], "Q193459"),
    ("apple-tree", "Malus domestica", "Rosaceae", "Rosales",
        "orchard", "worldwide-temperate", "medium",
        ["apples"], None, "Q193459"),
    ("pear-tree", "Pyrus communis", "Rosaceae", "Rosales",
        "orchard", "europe", "medium",
        ["pears"], None, "Q193459"),
    ("plum-tree", "Prunus domestica", "Rosaceae", "Rosales",
        "orchard", "worldwide-temperate", "small",
        ["plums"], None, "Q193459"),
    ("peach-tree", "Prunus persica", "Rosaceae", "Rosales",
        "orchard", "east-asia", "small",
        ["peaches"], None, "Q193459"),
    ("apricot-tree", "Prunus armeniaca", "Rosaceae", "Rosales",
        "orchard", "central-asia", "small",
        ["apricots"], None, "Q193459"),
    ("orange-tree", "Citrus sinensis", "Rutaceae", "Sapindales",
        "orchard", "asia", "small",
        ["oranges"], None, "Q193459"),
    ("lemon-tree", "Citrus limon", "Rutaceae", "Sapindales",
        "orchard", "asia", "small",
        ["lemons"], None, "Q193459"),
    ("lime-tree-citrus", "Citrus aurantiifolia", "Rutaceae", "Sapindales",
        "orchard", "southeast-asia", "small",
        ["limes"], None, "Q193459"),
    ("grapefruit-tree", "Citrus × paradisi", "Rutaceae", "Sapindales",
        "orchard", "caribbean", "small",
        ["grapefruits"], None, "Q193459"),
    ("mango-tree", "Mangifera indica", "Anacardiaceae", "Sapindales",
        "orchard", "south-asia", "large",
        ["mangoes"], None, "Q193459"),
    ("avocado-tree", "Persea americana", "Lauraceae", "Laurales",
        "orchard", "central-america", "medium",
        ["avocados"], None, "Q193459"),
    ("papaya-tree", "Carica papaya", "Caricaceae", "Brassicales",
        "orchard", "central-america", "small",
        ["papayas"], None, "Q193459"),
    ("guava-tree", "Psidium guajava", "Myrtaceae", "Myrtales",
        "orchard", "central-america", "small",
        ["guavas"], None, "Q193459"),
    ("pomegranate-tree", "Punica granatum", "Lythraceae", "Myrtales",
        "orchard", "middle-east", "small",
        ["pomegranates"], None, "Q193459"),
    ("coffee-tree", "Coffea arabica", "Rubiaceae", "Gentianales",
        "highland-farm", "africa", "small",
        ["coffee-beans"], None, "Q193459"),
    ("cacao-tree", "Theobroma cacao", "Malvaceae", "Malvales",
        "jungle", "central-america", "small",
        ["cocoa-beans"], ["cocoa-tree"], "Q193459"),
    ("rubber-tree", "Hevea brasiliensis", "Euphorbiaceae", "Malpighiales",
        "jungle", "amazon-basin", "large",
        ["latex-rubber"], None, "Q193459"),
    ("tea-tree", "Camellia sinensis", "Theaceae", "Ericales",
        "highland-farm", "east-asia", "small",
        ["tea-leaves"], None, "Q193459"),
    ("mangrove", "Rhizophora mangle", "Rhizophoraceae", "Malpighiales",
        ["coastal", "estuary"], "tropics-worldwide", "medium",
        ["salt-tolerant", "prop-roots"], ["red-mangrove"], "Q193459"),
    ("dragon-tree", "Dracaena draco", "Asparagaceae", "Asparagales",
        "arid-mountain", "canary-islands", "medium",
        ["red-resin", "long-lived"], None, "Q193459"),
    ("joshua-tree", "Yucca brevifolia", "Asparagaceae", "Asparagales",
        "desert", "north-america-southwest", "medium",
        ["iconic-mojave", "yucca"], None, "Q193459"),
    ("saguaro", "Carnegiea gigantea", "Cactaceae", "Caryophyllales",
        "desert", "north-america-southwest", "large",
        ["iconic-sonoran", "arm-forming"], ["saguaro-cactus"], "Q193459"),
    ("larchpole", "Larix laricina", "Pinaceae", "Pinales",
        "boreal", "north-america-north", "medium",
        ["tamarack-swamp-tree"], ["tamarack"], "Q193459"),
    ("holly", "Ilex aquifolium", "Aquifoliaceae", "Aquifoliales",
        ["forest", "garden"], "europe", "small",
        ["evergreen", "red-berries", "prickly-leaves"], ["european-holly"], "Q193459"),
    ("laurel", "Laurus nobilis", "Lauraceae", "Laurales",
        ["mediterranean-forest", "garden"], "mediterranean", "medium",
        ["bay-leaves", "hedging"], ["bay-laurel"], "Q193459"),
    ("myrtle", "Myrtus communis", "Myrtaceae", "Myrtales",
        "mediterranean-scrubland", "mediterranean", "small",
        ["fragrant-leaves", "ceremonial"], ["common-myrtle"], "Q193459"),
    ("rhododendron-tree", "Rhododendron", "Ericaceae", "Ericales",
        ["mountain", "forest"], "himalaya", "medium",
        ["flowering-shrub-tree"], None, "Q193459"),
    ("kapok", "Ceiba pentandra", "Malvaceae", "Malvales",
        "jungle", "central-america", "huge",
        ["silky-fibers", "sacred-tree"], ["silk-cotton-tree"], "Q193459"),
    ("brazil-nut-tree", "Bertholletia excelsa", "Lecythidaceae", "Ericales",
        "jungle", "amazon-basin", "huge",
        ["brazil-nuts"], None, "Q193459"),
    ("cinnamon-tree", "Cinnamomum verum", "Lauraceae", "Laurales",
        "orchard", "sri-lanka", "small",
        ["cinnamon-bark"], None, "Q193459"),
    ("clove-tree", "Syzygium aromaticum", "Myrtaceae", "Myrtales",
        "orchard", "indonesia", "medium",
        ["cloves"], None, "Q193459"),
    ("nutmeg-tree", "Myristica fragrans", "Myristicaceae", "Magnoliales",
        "orchard", "indonesia", "medium",
        ["nutmeg", "mace"], None, "Q193459"),
    ("allspice-tree", "Pimenta dioica", "Myrtaceae", "Myrtales",
        "orchard", "caribbean", "medium",
        ["allspice-berries"], None, "Q193459"),
    ("bay-tree", "Laurus nobilis", "Lauraceae", "Laurales",
        "garden", "mediterranean", "small",
        ["bay-leaves"], None, "Q193459"),
    ("wisteria", "Wisteria sinensis", "Fabaceae", "Fabales",
        "garden", "east-asia", "medium",
        ["cascading-flowers", "vine-tree"], None, "Q193459"),
    ("silver-fir", "Abies alba", "Pinaceae", "Pinales",
        "mountain-forest", "europe", "huge",
        ["lumber"], None, "Q193459"),
    ("hackberry", "Celtis occidentalis", "Cannabaceae", "Rosales",
        "urban", "north-america", "medium",
        ["urban-tolerance"], None, "Q193459"),
    ("persimmon", "Diospyros virginiana", "Ebenaceae", "Ericales",
        ["forest", "orchard"], "north-america-east", "medium",
        ["persimmons"], ["american-persimmon"], "Q193459"),
    ("pawpaw", "Asimina triloba", "Annonaceae", "Magnoliales",
        "forest", "north-america-east", "small",
        ["pawpaw-fruit"], None, "Q193459"),
    ("juneberry", "Amelanchier canadensis", "Rosaceae", "Rosales",
        "forest", "north-america-east", "small",
        ["berries", "spring-blossom"], ["serviceberry", "shadbush"], "Q193459"),
    ("chinaberry", "Melia azedarach", "Meliaceae", "Sapindales",
        "urban", "asia", "medium",
        ["ornamental"], None, "Q193459"),
    ("neem", "Azadirachta indica", "Meliaceae", "Sapindales",
        "urban", "south-asia", "large",
        ["medicinal", "insecticide"], None, "Q193459"),
    ("sandalwood", "Santalum album", "Santalaceae", "Santalales",
        "forest", "south-asia", "small",
        ["fragrant-wood", "incense"], None, "Q193459"),
]

for e in DECID: _emit(e)
