"""Flowering plants — ~200-300 flower species people name.
Compact tuple form.
"""

from _helpers import node, wikidata, tax, authored


def flower(canonical, sci, family, order, habitat, region, size, seasons=None,
           used_for=None, synonyms=None, qid=None):
    return node(canonical, "plant",
                synonyms=synonyms or [],
                scientific_name=sci,
                taxonomy=tax(kingdom="Plantae",
                             order=order, family=family,
                             genus=sci.split()[0] if sci else None,
                             species=sci, common_name=canonical),
                lives_in=[habitat] if isinstance(habitat, str) else habitat,
                region_native_to=[region] if isinstance(region, str) else region,
                size_scale=size, used_for=used_for, season=seasons,
                kid_friendly=True,
                provenance=[wikidata(qid)] if qid else [authored()])


NODES = []


def _emit(entry):
    n = len(entry)
    if n == 9:
        canonical, sci, family, order, habitat, region, size, seasons, qid = entry
        used = None; syns = None
    elif n == 10:
        canonical, sci, family, order, habitat, region, size, seasons, used, qid = entry
        syns = None
    elif n == 11:
        canonical, sci, family, order, habitat, region, size, seasons, used, syns, qid = entry
    else:
        raise ValueError(f"Bad flower tuple len {n}: {entry!r}")
    NODES.append(flower(canonical, sci, family, order, habitat, region, size,
                        seasons=seasons, used_for=used, synonyms=syns, qid=qid))


# ---------------------------------------------------------------------------
# GARDEN + WILD FLOWERS
# ---------------------------------------------------------------------------
FLOWERS = [
    ("rose", "Rosa", "Rosaceae", "Rosales",
        "garden", "worldwide-temperate", "small", ["spring", "summer"],
        ["ornamental", "perfume", "symbol-of-love"], ["rose-flower"], "Q102231"),
    ("tulip", "Tulipa gesneriana", "Liliaceae", "Liliales",
        "garden", "central-asia", "small", ["spring"],
        ["ornamental"], None, "Q41601"),
    ("daffodil", "Narcissus pseudonarcissus", "Amaryllidaceae", "Asparagales",
        "garden", "europe", "small", ["spring"],
        ["ornamental", "spring-symbol"], ["narcissus", "jonquil"], "Q41500"),
    ("crocus", "Crocus sativus", "Iridaceae", "Asparagales",
        "garden", "eurasia", "tiny", ["spring", "autumn"],
        ["saffron", "ornamental"], None, "Q158657"),
    ("hyacinth", "Hyacinthus orientalis", "Asparagaceae", "Asparagales",
        "garden", "middle-east", "small", ["spring"],
        ["ornamental", "fragrant"], None, "Q193459"),
    ("iris", "Iris germanica", "Iridaceae", "Asparagales",
        "garden", "europe", "small", ["spring"],
        ["ornamental"], None, "Q156191"),
    ("lily", "Lilium candidum", "Liliaceae", "Liliales",
        "garden", "eurasia", "small", ["summer"],
        ["ornamental", "symbolism-of-purity"], ["madonna-lily"], "Q193459"),
    ("tiger-lily", "Lilium lancifolium", "Liliaceae", "Liliales",
        "garden", "east-asia", "small", ["summer"],
        ["ornamental"], None, "Q193459"),
    ("day-lily", "Hemerocallis fulva", "Asphodelaceae", "Asparagales",
        "garden", "east-asia", "small", ["summer"],
        ["ornamental"], ["daylily"], "Q193459"),
    ("calla-lily", "Zantedeschia aethiopica", "Araceae", "Alismatales",
        "garden", "africa", "small", ["summer"],
        ["cut-flower"], None, "Q193459"),
    ("water-lily", "Nymphaea alba", "Nymphaeaceae", "Nymphaeales",
        "pond", "worldwide", "small", ["summer"],
        ["ornamental", "floating"], ["waterlily"], "Q193459"),
    ("lotus", "Nelumbo nucifera", "Nelumbonaceae", "Proteales",
        "pond", "asia", "small", ["summer"],
        ["sacred-flower", "edible-roots"], ["sacred-lotus"], "Q193459"),
    ("sunflower", "Helianthus annuus", "Asteraceae", "Asterales",
        ["garden", "farm"], "north-america", "medium", ["summer", "autumn"],
        ["ornamental", "sunflower-seeds", "oil"], None, "Q40287"),
    ("daisy", "Bellis perennis", "Asteraceae", "Asterales",
        ["meadow", "garden"], "europe", "tiny", ["spring", "summer"],
        ["ornamental"], ["common-daisy", "english-daisy"], "Q159232"),
    ("shasta-daisy", "Leucanthemum × superbum", "Asteraceae", "Asterales",
        "garden", "europe", "small", ["summer"],
        ["ornamental"], None, "Q193459"),
    ("gerbera", "Gerbera jamesonii", "Asteraceae", "Asterales",
        "garden", "south-africa", "small", ["spring", "summer"],
        ["cut-flower"], None, "Q193459"),
    ("chrysanthemum", "Chrysanthemum × morifolium", "Asteraceae", "Asterales",
        "garden", "east-asia", "small", ["autumn"],
        ["ornamental", "symbolism-of-longevity"], ["mum"], "Q193459"),
    ("aster", "Symphyotrichum novi-belgii", "Asteraceae", "Asterales",
        ["garden", "meadow"], "north-america", "small", ["autumn"],
        ["ornamental"], ["new-york-aster"], "Q193459"),
    ("dahlia", "Dahlia pinnata", "Asteraceae", "Asterales",
        "garden", "central-america", "small", ["summer", "autumn"],
        ["ornamental"], None, "Q193459"),
    ("zinnia", "Zinnia elegans", "Asteraceae", "Asterales",
        "garden", "central-america", "small", ["summer"],
        ["ornamental", "cut-flower"], None, "Q193459"),
    ("marigold", "Tagetes patula", "Asteraceae", "Asterales",
        ["garden", "farm"], "central-america", "small", ["summer", "autumn"],
        ["ornamental", "pest-repellent"], ["french-marigold"], "Q193459"),
    ("cosmos", "Cosmos bipinnatus", "Asteraceae", "Asterales",
        "garden", "central-america", "small", ["summer", "autumn"],
        ["ornamental"], None, "Q193459"),
    ("black-eyed-susan", "Rudbeckia hirta", "Asteraceae", "Asterales",
        ["meadow", "garden"], "north-america", "small", ["summer"],
        ["ornamental", "wildflower"], None, "Q193459"),
    ("coneflower", "Echinacea purpurea", "Asteraceae", "Asterales",
        ["prairie", "garden"], "north-america", "small", ["summer"],
        ["medicinal", "ornamental"], ["purple-coneflower"], "Q193459"),
    ("sneezeweed", "Helenium autumnale", "Asteraceae", "Asterales",
        "wetland", "north-america", "small", ["autumn"],
        None, None, "Q193459"),
    ("dandelion", "Taraxacum officinale", "Asteraceae", "Asterales",
        ["lawn", "meadow"], "worldwide", "tiny", ["spring", "summer"],
        ["edible-greens", "wine-flower"], None, "Q193459"),
    ("thistle", "Cirsium vulgare", "Asteraceae", "Asterales",
        ["meadow", "roadside"], "eurasia", "small", ["summer"],
        ["scotland-symbol"], ["bull-thistle"], "Q193459"),
    ("goldenrod", "Solidago canadensis", "Asteraceae", "Asterales",
        ["meadow", "prairie"], "north-america", "small", ["autumn"],
        ["wildflower"], None, "Q193459"),
    ("yarrow", "Achillea millefolium", "Asteraceae", "Asterales",
        ["meadow", "roadside"], "north-hemisphere", "small", ["summer"],
        ["medicinal"], None, "Q193459"),
    ("chamomile", "Matricaria chamomilla", "Asteraceae", "Asterales",
        ["meadow", "garden"], "europe", "tiny", ["summer"],
        ["tea", "medicinal"], ["german-chamomile"], "Q193459"),
    ("peony", "Paeonia lactiflora", "Paeoniaceae", "Saxifragales",
        "garden", "east-asia", "small", ["spring"],
        ["ornamental", "fragrant"], ["chinese-peony"], "Q193459"),
    ("poppy", "Papaver rhoeas", "Papaveraceae", "Ranunculales",
        ["meadow", "garden"], "europe", "small", ["summer"],
        ["ornamental", "symbol-of-remembrance"], ["corn-poppy", "field-poppy"], "Q193459"),
    ("california-poppy", "Eschscholzia californica", "Papaveraceae", "Ranunculales",
        ["meadow", "desert"], "north-america-west", "small", ["spring"],
        ["state-flower-california"], None, "Q193459"),
    ("iceland-poppy", "Papaver nudicaule", "Papaveraceae", "Ranunculales",
        "garden", "arctic", "small", ["summer"],
        ["cold-hardy"], None, "Q193459"),
    ("carnation", "Dianthus caryophyllus", "Caryophyllaceae", "Caryophyllales",
        "garden", "mediterranean", "small", ["summer"],
        ["cut-flower", "boutonniere"], None, "Q193459"),
    ("sweet-william", "Dianthus barbatus", "Caryophyllaceae", "Caryophyllales",
        "garden", "europe", "small", ["summer"],
        ["ornamental"], None, "Q193459"),
    ("baby-s-breath", "Gypsophila paniculata", "Caryophyllaceae", "Caryophyllales",
        "garden", "eurasia", "small", ["summer"],
        ["filler-flower"], ["gypsophila"], "Q193459"),
    ("primrose", "Primula vulgaris", "Primulaceae", "Ericales",
        ["woodland", "garden"], "europe", "tiny", ["spring"],
        ["ornamental"], ["common-primrose"], "Q193459"),
    ("cyclamen", "Cyclamen persicum", "Primulaceae", "Ericales",
        "garden", "mediterranean", "small", ["winter"],
        ["ornamental"], None, "Q193459"),
    ("azalea", "Rhododendron", "Ericaceae", "Ericales",
        "garden", ["east-asia", "north-america"], "small", ["spring"],
        ["ornamental"], None, "Q193459"),
    ("rhododendron", "Rhododendron ponticum", "Ericaceae", "Ericales",
        ["garden", "forest"], "worldwide-temperate", "medium", ["spring"],
        ["ornamental"], None, "Q193459"),
    ("hydrangea", "Hydrangea macrophylla", "Hydrangeaceae", "Cornales",
        "garden", "east-asia", "small", ["summer"],
        ["ornamental", "ph-color-change"], ["bigleaf-hydrangea"], "Q193459"),
    ("lilac", "Syringa vulgaris", "Oleaceae", "Lamiales",
        "garden", "balkans", "medium", ["spring"],
        ["fragrant", "ornamental"], None, "Q193459"),
    ("jasmine", "Jasminum officinale", "Oleaceae", "Lamiales",
        "garden", "asia", "small", ["summer"],
        ["fragrant", "perfume"], ["common-jasmine"], "Q193459"),
    ("gardenia", "Gardenia jasminoides", "Rubiaceae", "Gentianales",
        "garden", "east-asia", "small", ["summer"],
        ["fragrant"], None, "Q193459"),
    ("hibiscus", "Hibiscus rosa-sinensis", "Malvaceae", "Malvales",
        "garden", "east-asia", "small", ["summer"],
        ["tropical-ornamental"], ["chinese-hibiscus"], "Q193459"),
    ("hollyhock", "Alcea rosea", "Malvaceae", "Malvales",
        "garden", "asia", "medium", ["summer"],
        ["cottage-garden"], None, "Q193459"),
    ("mallow", "Malva sylvestris", "Malvaceae", "Malvales",
        ["meadow", "garden"], "eurasia", "small", ["summer"],
        ["ornamental", "medicinal"], ["common-mallow"], "Q193459"),
    ("nasturtium", "Tropaeolum majus", "Tropaeolaceae", "Brassicales",
        "garden", "south-america", "small", ["summer"],
        ["edible-flower"], None, "Q193459"),
    ("morning-glory", "Ipomoea purpurea", "Convolvulaceae", "Solanales",
        "garden", "central-america", "small", ["summer"],
        ["climbing-vine"], None, "Q193459"),
    ("sweet-pea", "Lathyrus odoratus", "Fabaceae", "Fabales",
        "garden", "mediterranean", "small", ["spring", "summer"],
        ["fragrant", "climbing"], None, "Q193459"),
    ("wisteria-flower", "Wisteria sinensis", "Fabaceae", "Fabales",
        "garden", "east-asia", "medium", ["spring"],
        ["cascading-flowers", "climbing-vine"], None, "Q193459"),
    ("clover", "Trifolium repens", "Fabaceae", "Fabales",
        ["lawn", "meadow"], "eurasia", "tiny", ["spring", "summer"],
        ["forage", "nitrogen-fixing"], ["white-clover"], "Q193459"),
    ("red-clover", "Trifolium pratense", "Fabaceae", "Fabales",
        ["meadow", "farm"], "eurasia", "tiny", ["summer"],
        ["forage", "medicinal"], None, "Q193459"),
    ("bluebell", "Hyacinthoides non-scripta", "Asparagaceae", "Asparagales",
        "woodland", "europe-west", "tiny", ["spring"],
        ["carpet-of-blue"], ["english-bluebell"], "Q193459"),
    ("snowdrop", "Galanthus nivalis", "Amaryllidaceae", "Asparagales",
        ["woodland", "garden"], "europe", "tiny", ["winter", "spring"],
        ["earliest-spring-flower"], None, "Q193459"),
    ("crocus-autumn", "Colchicum autumnale", "Colchicaceae", "Liliales",
        "meadow", "europe", "tiny", ["autumn"],
        ["autumn-blooming"], ["meadow-saffron"], "Q193459"),
    ("violet", "Viola odorata", "Violaceae", "Malpighiales",
        ["woodland", "garden"], "europe", "tiny", ["spring"],
        ["fragrant", "candied"], ["sweet-violet"], "Q193459"),
    ("pansy", "Viola × wittrockiana", "Violaceae", "Malpighiales",
        "garden", "hybrid", "tiny", ["spring", "autumn"],
        ["ornamental"], None, "Q193459"),
    ("johnny-jump-up", "Viola tricolor", "Violaceae", "Malpighiales",
        ["meadow", "garden"], "europe", "tiny", ["spring", "summer"],
        ["ornamental"], ["heartsease"], "Q193459"),
    ("bleeding-heart", "Dicentra spectabilis", "Papaveraceae", "Ranunculales",
        "garden", "east-asia", "small", ["spring"],
        ["heart-shaped-flowers"], None, "Q193459"),
    ("columbine", "Aquilegia canadensis", "Ranunculaceae", "Ranunculales",
        ["woodland", "garden"], "north-america", "small", ["spring"],
        ["ornamental"], ["wild-columbine"], "Q193459"),
    ("buttercup", "Ranunculus acris", "Ranunculaceae", "Ranunculales",
        ["meadow", "field"], "eurasia", "tiny", ["spring", "summer"],
        ["wildflower"], ["meadow-buttercup"], "Q193459"),
    ("anemone-flower", "Anemone coronaria", "Ranunculaceae", "Ranunculales",
        "garden", "mediterranean", "small", ["spring"],
        ["cut-flower"], ["windflower"], "Q193459"),
    ("hellebore", "Helleborus niger", "Ranunculaceae", "Ranunculales",
        "garden", "europe", "small", ["winter"],
        ["winter-blooming"], ["christmas-rose"], "Q193459"),
    ("clematis", "Clematis vitalba", "Ranunculaceae", "Ranunculales",
        "garden", "europe", "medium", ["summer"],
        ["climbing-vine"], None, "Q193459"),
    ("delphinium", "Delphinium elatum", "Ranunculaceae", "Ranunculales",
        "garden", "europe", "medium", ["summer"],
        ["cottage-garden-spires"], ["larkspur"], "Q193459"),
    ("monkshood", "Aconitum napellus", "Ranunculaceae", "Ranunculales",
        "garden", "europe", "small", ["summer"],
        ["highly-toxic"], ["aconite", "wolfsbane"], "Q193459"),
    ("foxglove", "Digitalis purpurea", "Plantaginaceae", "Lamiales",
        ["woodland", "garden"], "europe", "small", ["summer"],
        ["digitalis-medicine", "toxic"], None, "Q193459"),
    ("snapdragon", "Antirrhinum majus", "Plantaginaceae", "Lamiales",
        "garden", "europe", "small", ["spring", "summer"],
        ["cottage-garden"], None, "Q193459"),
    ("penstemon", "Penstemon digitalis", "Plantaginaceae", "Lamiales",
        ["prairie", "garden"], "north-america", "small", ["summer"],
        ["beardtongue"], ["beard-tongue"], "Q193459"),
    ("veronica", "Veronica spicata", "Plantaginaceae", "Lamiales",
        "garden", "europe", "small", ["summer"],
        ["ornamental"], ["speedwell"], "Q193459"),
    ("forget-me-not", "Myosotis sylvatica", "Boraginaceae", "Boraginales",
        "garden", "europe", "tiny", ["spring"],
        ["ornamental"], None, "Q193459"),
    ("borage", "Borago officinalis", "Boraginaceae", "Boraginales",
        "garden", "mediterranean", "small", ["summer"],
        ["edible-flowers", "bee-forage"], None, "Q193459"),
    ("phlox", "Phlox paniculata", "Polemoniaceae", "Ericales",
        "garden", "north-america", "small", ["summer"],
        ["fragrant"], None, "Q193459"),
    ("impatiens", "Impatiens walleriana", "Balsaminaceae", "Ericales",
        "garden", "africa", "tiny", ["summer"],
        ["shade-flower"], ["busy-lizzie"], "Q193459"),
    ("begonia", "Begonia semperflorens", "Begoniaceae", "Cucurbitales",
        "garden", "central-america", "small", ["summer"],
        ["ornamental"], None, "Q193459"),
    ("geranium", "Pelargonium × hortorum", "Geraniaceae", "Geraniales",
        "garden", "south-africa", "small", ["summer"],
        ["ornamental", "container-plant"], None, "Q193459"),
    ("orchid", "Orchidaceae", "Orchidaceae", "Asparagales",
        ["jungle", "greenhouse"], "worldwide", "tiny", ["any-season"],
        ["ornamental", "diverse-family"], None, "Q193459"),
    ("moth-orchid", "Phalaenopsis", "Orchidaceae", "Asparagales",
        "greenhouse", "southeast-asia", "small", ["any-season"],
        ["popular-houseplant"], ["phalaenopsis"], "Q193459"),
    ("vanilla-orchid", "Vanilla planifolia", "Orchidaceae", "Asparagales",
        "jungle", "central-america", "small", ["any-season"],
        ["vanilla-flavoring"], None, "Q193459"),
    ("lady-slipper", "Cypripedium acaule", "Orchidaceae", "Asparagales",
        "woodland", "north-america", "small", ["spring"],
        ["orchid-native"], ["pink-lady-slipper"], "Q193459"),
    ("bird-of-paradise", "Strelitzia reginae", "Strelitziaceae", "Zingiberales",
        ["garden", "greenhouse"], "south-africa", "small", ["any-season"],
        ["tropical-ornamental"], None, "Q193459"),
    ("heliconia", "Heliconia rostrata", "Heliconiaceae", "Zingiberales",
        "jungle", "central-america", "medium", ["any-season"],
        ["parrot-flowers"], ["lobster-claw"], "Q193459"),
    ("passion-flower", "Passiflora incarnata", "Passifloraceae", "Malpighiales",
        ["forest", "garden"], "north-america-south", "small", ["summer"],
        ["climbing-vine"], ["maypop"], "Q193459"),
    ("magnolia-flower", "Magnolia grandiflora", "Magnoliaceae", "Magnoliales",
        "garden", "north-america-southeast", "medium", ["summer"],
        ["fragrant-flower"], None, "Q193459"),
    ("cherry-blossom", "Prunus serrulata", "Rosaceae", "Rosales",
        "garden", "japan", "small", ["spring"],
        ["hanami-viewing", "symbol-of-transience"], ["sakura-blossom"], "Q193459"),
    ("plum-blossom", "Prunus mume", "Rosaceae", "Rosales",
        "garden", "east-asia", "small", ["winter", "spring"],
        ["early-blooming"], ["ume"], "Q193459"),
    ("apple-blossom", "Malus domestica", "Rosaceae", "Rosales",
        "orchard", "worldwide", "small", ["spring"],
        ["orchard-flower"], None, "Q193459"),
    ("crabapple-blossom", "Malus", "Rosaceae", "Rosales",
        ["garden", "orchard"], "worldwide-temperate", "small", ["spring"],
        ["ornamental"], None, "Q193459"),
    ("bougainvillea-flower", "Bougainvillea glabra", "Nyctaginaceae", "Caryophyllales",
        "garden", "south-america", "medium", ["any-season"],
        ["colorful-bracts"], None, "Q193459"),
    ("plumeria-flower", "Plumeria rubra", "Apocynaceae", "Gentianales",
        "garden", "central-america", "small", ["summer"],
        ["fragrant", "leis"], ["frangipani"], "Q193459"),
    ("edelweiss", "Leontopodium alpinum", "Asteraceae", "Asterales",
        "alpine", "europe", "tiny", ["summer"],
        ["alpine-symbol"], None, "Q193459"),
    ("gentian", "Gentiana lutea", "Gentianaceae", "Gentianales",
        "alpine", "europe", "small", ["summer"],
        ["blue-alpine-flower"], ["great-yellow-gentian"], "Q193459"),
    ("saxifrage", "Saxifraga oppositifolia", "Saxifragaceae", "Saxifragales",
        "alpine", "arctic", "tiny", ["spring"],
        ["rock-crevice-flower"], None, "Q193459"),
    ("arctic-poppy", "Papaver radicatum", "Papaveraceae", "Ranunculales",
        "arctic-tundra", "arctic", "tiny", ["summer"],
        None, None, "Q193459"),
    ("cactus-flower", "Cactaceae", "Cactaceae", "Caryophyllales",
        "desert", "americas", "tiny", ["spring"],
        None, None, "Q193459"),
    ("prickly-pear-flower", "Opuntia ficus-indica", "Cactaceae", "Caryophyllales",
        "desert", "americas", "small", ["spring"],
        ["edible-cactus-fruit"], None, "Q193459"),
    ("agave-flower", "Agave americana", "Asparagaceae", "Asparagales",
        "desert", "central-america", "large", ["once-per-life"],
        ["century-plant"], None, "Q193459"),
    ("yucca-flower", "Yucca filamentosa", "Asparagaceae", "Asparagales",
        "arid-scrubland", "north-america-southeast", "medium", ["summer"],
        ["night-fragrance", "moth-pollinated"], None, "Q193459"),
    ("lavender", "Lavandula angustifolia", "Lamiaceae", "Lamiales",
        ["garden", "mediterranean-scrubland"], "mediterranean", "small", ["summer"],
        ["fragrant", "essential-oil"], ["english-lavender"], "Q193459"),
    ("sage-flower", "Salvia officinalis", "Lamiaceae", "Lamiales",
        "garden", "mediterranean", "small", ["summer"],
        ["culinary-herb"], None, "Q193459"),
    ("rosemary-flower", "Salvia rosmarinus", "Lamiaceae", "Lamiales",
        "garden", "mediterranean", "small", ["spring"],
        ["culinary-herb"], None, "Q193459"),
    ("thyme-flower", "Thymus vulgaris", "Lamiaceae", "Lamiales",
        "garden", "mediterranean", "tiny", ["summer"],
        ["culinary-herb"], None, "Q193459"),
    ("basil-flower", "Ocimum basilicum", "Lamiaceae", "Lamiales",
        "garden", "asia", "small", ["summer"],
        ["culinary-herb"], None, "Q193459"),
    ("mint-flower", "Mentha", "Lamiaceae", "Lamiales",
        ["garden", "wetland"], "worldwide", "small", ["summer"],
        ["culinary-herb"], None, "Q193459"),
    ("bee-balm", "Monarda didyma", "Lamiaceae", "Lamiales",
        "garden", "north-america", "small", ["summer"],
        ["bee-hummingbird-magnet"], ["oswego-tea"], "Q193459"),
    ("salvia", "Salvia splendens", "Lamiaceae", "Lamiales",
        "garden", "south-america", "small", ["summer"],
        ["scarlet-sage"], None, "Q193459"),
    ("catnip", "Nepeta cataria", "Lamiaceae", "Lamiales",
        "garden", "europe", "small", ["summer"],
        ["cat-attractant"], None, "Q193459"),
    ("wolfsbane", "Aconitum lycoctonum", "Ranunculaceae", "Ranunculales",
        "meadow", "europe", "small", ["summer"],
        ["toxic"], None, "Q193459"),
    ("belladonna", "Atropa belladonna", "Solanaceae", "Solanales",
        "woodland", "europe", "small", ["summer"],
        ["highly-toxic"], ["deadly-nightshade"], "Q193459"),
    ("morning-glory-cypress", "Ipomoea alba", "Convolvulaceae", "Solanales",
        "garden", "americas", "medium", ["summer"],
        ["night-blooming"], ["moonflower"], "Q193459"),
    ("gladiolus", "Gladiolus × hortulanus", "Iridaceae", "Asparagales",
        "garden", "africa", "medium", ["summer"],
        ["cut-flower"], ["sword-lily"], "Q193459"),
    ("freesia", "Freesia × hybrida", "Iridaceae", "Asparagales",
        "garden", "south-africa", "small", ["spring"],
        ["fragrant-cut-flower"], None, "Q193459"),
    ("amaryllis", "Hippeastrum", "Amaryllidaceae", "Asparagales",
        ["garden", "houseplant"], "south-america", "small", ["winter"],
        ["large-trumpet"], None, "Q193459"),
    ("alstroemeria", "Alstroemeria", "Alstroemeriaceae", "Liliales",
        "garden", "south-america", "small", ["summer"],
        ["peruvian-lily"], None, "Q193459"),
    ("bluet", "Houstonia caerulea", "Rubiaceae", "Gentianales",
        "meadow", "north-america", "tiny", ["spring"],
        ["tiny-blue-flower"], ["quaker-ladies"], "Q193459"),
    ("trillium", "Trillium grandiflorum", "Melanthiaceae", "Liliales",
        "woodland", "north-america-east", "small", ["spring"],
        ["three-leaves-three-petals"], ["wake-robin"], "Q193459"),
    ("mayapple", "Podophyllum peltatum", "Berberidaceae", "Ranunculales",
        "woodland", "north-america-east", "small", ["spring"],
        None, None, "Q193459"),
    ("jack-in-the-pulpit", "Arisaema triphyllum", "Araceae", "Alismatales",
        "woodland", "north-america-east", "small", ["spring"],
        ["arum-family"], None, "Q193459"),
    ("skunk-cabbage", "Symplocarpus foetidus", "Araceae", "Alismatales",
        "wetland", "north-america-east", "small", ["late-winter"],
        ["thermogenic", "early-blooming"], None, "Q193459"),
    ("marsh-marigold", "Caltha palustris", "Ranunculaceae", "Ranunculales",
        "wetland", "north-hemisphere", "small", ["spring"],
        ["kingcup"], ["kingcup"], "Q193459"),
    ("water-hyacinth", "Eichhornia crassipes", "Pontederiaceae", "Commelinales",
        "pond", "south-america", "small", ["summer"],
        ["invasive-aquatic"], None, "Q193459"),
    ("cattail", "Typha latifolia", "Typhaceae", "Poales",
        "wetland", "worldwide", "medium", ["summer"],
        ["edible-parts"], ["bulrush"], "Q193459"),
    ("iris-flag", "Iris pseudacorus", "Iridaceae", "Asparagales",
        "wetland", "europe", "small", ["spring"],
        ["yellow-flag"], None, "Q193459"),
    ("indian-paintbrush", "Castilleja coccinea", "Orobanchaceae", "Lamiales",
        "meadow", "north-america", "small", ["spring", "summer"],
        ["red-bracts"], None, "Q193459"),
    ("fireweed", "Chamaenerion angustifolium", "Onagraceae", "Myrtales",
        "burned-area", "north-hemisphere", "small", ["summer"],
        ["colonizer-after-fire"], ["rosebay-willowherb"], "Q193459"),
    ("evening-primrose", "Oenothera biennis", "Onagraceae", "Myrtales",
        "meadow", "north-america", "small", ["summer"],
        ["evening-blooming"], None, "Q193459"),
    ("moonflower", "Ipomoea alba", "Convolvulaceae", "Solanales",
        "garden", "americas", "medium", ["summer"],
        ["night-blooming"], None, "Q193459"),
    ("night-blooming-cereus", "Selenicereus grandiflorus", "Cactaceae", "Caryophyllales",
        "garden", "central-america", "medium", ["summer"],
        ["one-night-bloom"], None, "Q193459"),
    ("queen-of-the-night", "Epiphyllum oxypetalum", "Cactaceae", "Caryophyllales",
        "garden", "central-america", "medium", ["summer"],
        ["one-night-bloom", "fragrant"], None, "Q193459"),
    ("bird-of-paradise-orange", "Strelitzia reginae", "Strelitziaceae", "Zingiberales",
        "greenhouse", "south-africa", "small", ["any-season"],
        None, None, "Q193459"),
    ("rafflesia", "Rafflesia arnoldii", "Rafflesiaceae", "Malpighiales",
        "jungle", "southeast-asia", "medium", ["any-season"],
        ["largest-single-flower", "carrion-scent"], None, "Q193459"),
    ("titan-arum", "Amorphophallus titanum", "Araceae", "Alismatales",
        "jungle", "sumatra", "large", ["rare"],
        ["largest-unbranched-inflorescence", "corpse-flower"], ["corpse-flower"], "Q193459"),
    ("venus-flytrap", "Dionaea muscipula", "Droseraceae", "Caryophyllales",
        "wetland", "north-america-southeast", "tiny", ["spring"],
        ["carnivorous"], None, "Q193459"),
    ("pitcher-plant", "Sarracenia purpurea", "Sarraceniaceae", "Ericales",
        "wetland", "north-america", "small", ["spring"],
        ["carnivorous"], None, "Q193459"),
    ("sundew", "Drosera rotundifolia", "Droseraceae", "Caryophyllales",
        "bog", "worldwide", "tiny", ["summer"],
        ["carnivorous", "sticky-hairs"], None, "Q193459"),
]

for e in FLOWERS: _emit(e)
