"""Edible plants — vegetables, fruits, grains, legumes, herbs, spices.
The kinds Sakura sees on a plate or in a market. ~250 nodes.
"""

from _helpers import node, wikidata, tax, authored


def crop(canonical, sci, family, order, kind, region, size, used_for=None,
         synonyms=None, seasons=None, qid=None):
    return node(canonical, "plant",
                synonyms=synonyms or [],
                scientific_name=sci,
                taxonomy=tax(kingdom="Plantae",
                             order=order, family=family,
                             genus=sci.split()[0] if sci else None,
                             species=sci, common_name=canonical),
                lives_in=[kind] if isinstance(kind, str) else kind,
                region_native_to=[region] if isinstance(region, str) else region,
                size_scale=size, used_for=used_for, season=seasons,
                kid_friendly=True,
                provenance=[wikidata(qid)] if qid else [authored()])


NODES = []


def _emit(entry):
    n = len(entry)
    if n == 9:
        canonical, sci, family, order, kind, region, size, used, qid = entry
        syns = None; seasons = None
    elif n == 10:
        canonical, sci, family, order, kind, region, size, used, syns, qid = entry
        seasons = None
    elif n == 11:
        canonical, sci, family, order, kind, region, size, used, syns, seasons, qid = entry
    else:
        raise ValueError(f"Bad crop tuple len {n}: {entry!r}")
    NODES.append(crop(canonical, sci, family, order, kind, region, size,
                      used_for=used, synonyms=syns, seasons=seasons, qid=qid))


# ---------------------------------------------------------------------------
# VEGETABLES — roots, leaves, brassicas, cucurbits, alliums, solanums
# ---------------------------------------------------------------------------
VEG = [
    ("carrot", "Daucus carota", "Apiaceae", "Apiales",
        "farm", "worldwide", "tiny", ["food", "root-vegetable"],
        None, None, "Q81"),
    ("parsnip", "Pastinaca sativa", "Apiaceae", "Apiales",
        "farm", "eurasia", "tiny", ["food", "root-vegetable"],
        None, None, "Q193459"),
    ("celery", "Apium graveolens", "Apiaceae", "Apiales",
        "farm", "mediterranean", "small", ["food", "stalks"],
        None, None, "Q193459"),
    ("celeriac", "Apium graveolens rapaceum", "Apiaceae", "Apiales",
        "farm", "europe", "small", ["food", "root-vegetable"],
        ["celery-root"], None, "Q193459"),
    ("fennel", "Foeniculum vulgare", "Apiaceae", "Apiales",
        "farm", "mediterranean", "small", ["food", "bulb", "seeds"],
        None, None, "Q193459"),
    ("dill-plant", "Anethum graveolens", "Apiaceae", "Apiales",
        "farm", "eurasia", "small", ["food", "herb"],
        None, None, "Q193459"),
    ("parsley", "Petroselinum crispum", "Apiaceae", "Apiales",
        "garden", "mediterranean", "small", ["food", "herb"],
        None, None, "Q193459"),
    ("cilantro", "Coriandrum sativum", "Apiaceae", "Apiales",
        "garden", "mediterranean", "small", ["food", "herb"],
        ["coriander"], None, "Q193459"),
    ("carrot-wild", "Daucus carota carota", "Apiaceae", "Apiales",
        "meadow", "eurasia", "small", ["wildflower"],
        ["queen-anne-s-lace"], None, "Q193459"),
    ("potato", "Solanum tuberosum", "Solanaceae", "Solanales",
        "farm", "south-america", "tiny", ["food", "tuber", "staple"],
        ["spud", "tater"], None, "Q10998"),
    ("sweet-potato", "Ipomoea batatas", "Convolvulaceae", "Solanales",
        "farm", "central-america", "tiny", ["food", "tuber"],
        None, None, "Q193459"),
    ("yam", "Dioscorea alata", "Dioscoreaceae", "Dioscoreales",
        "farm", "asia", "small", ["food", "tuber"],
        None, None, "Q193459"),
    ("cassava", "Manihot esculenta", "Euphorbiaceae", "Malpighiales",
        "farm", "south-america", "medium", ["food", "tuber", "tapioca"],
        ["manioc", "yuca"], None, "Q193459"),
    ("taro", "Colocasia esculenta", "Araceae", "Alismatales",
        "farm", "southeast-asia", "small", ["food", "tuber"],
        None, None, "Q193459"),
    ("turnip", "Brassica rapa", "Brassicaceae", "Brassicales",
        "farm", "eurasia", "tiny", ["food", "root-vegetable"],
        None, None, "Q193459"),
    ("rutabaga", "Brassica napus napobrassica", "Brassicaceae", "Brassicales",
        "farm", "europe", "tiny", ["food", "root-vegetable"],
        ["swede"], None, "Q193459"),
    ("radish", "Raphanus sativus", "Brassicaceae", "Brassicales",
        "garden", "eurasia", "tiny", ["food", "root-vegetable"],
        None, None, "Q193459"),
    ("daikon", "Raphanus sativus longipinnatus", "Brassicaceae", "Brassicales",
        "farm", "east-asia", "small", ["food"],
        ["white-radish"], None, "Q193459"),
    ("horseradish", "Armoracia rusticana", "Brassicaceae", "Brassicales",
        "garden", "europe", "small", ["food", "condiment"],
        None, None, "Q193459"),
    ("wasabi-plant", "Eutrema japonicum", "Brassicaceae", "Brassicales",
        "stream-bank", "japan", "small", ["food", "condiment"],
        None, None, "Q193459"),
    ("beetroot", "Beta vulgaris", "Amaranthaceae", "Caryophyllales",
        "farm", "mediterranean", "tiny", ["food", "root-vegetable"],
        ["beet"], None, "Q193459"),
    ("chard", "Beta vulgaris cicla", "Amaranthaceae", "Caryophyllales",
        "farm", "mediterranean", "small", ["food", "leafy-green"],
        ["swiss-chard"], None, "Q193459"),
    ("spinach", "Spinacia oleracea", "Amaranthaceae", "Caryophyllales",
        "farm", "central-asia", "small", ["food", "leafy-green"],
        None, None, "Q193459"),
    ("quinoa", "Chenopodium quinoa", "Amaranthaceae", "Caryophyllales",
        "highland-farm", "south-america", "medium", ["food", "pseudograin"],
        None, None, "Q193459"),
    ("amaranth", "Amaranthus caudatus", "Amaranthaceae", "Caryophyllales",
        "farm", "central-america", "medium", ["food", "pseudograin"],
        None, None, "Q193459"),
    ("cabbage", "Brassica oleracea capitata", "Brassicaceae", "Brassicales",
        "farm", "europe", "small", ["food", "leafy-green"],
        None, None, "Q193459"),
    ("broccoli", "Brassica oleracea italica", "Brassicaceae", "Brassicales",
        "farm", "mediterranean", "small", ["food", "flower-head"],
        None, None, "Q193459"),
    ("cauliflower", "Brassica oleracea botrytis", "Brassicaceae", "Brassicales",
        "farm", "mediterranean", "small", ["food", "flower-head"],
        None, None, "Q193459"),
    ("brussels-sprout", "Brassica oleracea gemmifera", "Brassicaceae", "Brassicales",
        "farm", "europe", "small", ["food"],
        ["brussels-sprouts"], None, "Q193459"),
    ("kale", "Brassica oleracea acephala", "Brassicaceae", "Brassicales",
        "garden", "europe", "small", ["food", "leafy-green"],
        None, None, "Q193459"),
    ("collard-greens", "Brassica oleracea viridis", "Brassicaceae", "Brassicales",
        "farm", "europe", "small", ["food", "leafy-green"],
        None, None, "Q193459"),
    ("kohlrabi", "Brassica oleracea gongylodes", "Brassicaceae", "Brassicales",
        "farm", "europe", "small", ["food", "stem"],
        None, None, "Q193459"),
    ("bok-choy", "Brassica rapa chinensis", "Brassicaceae", "Brassicales",
        "farm", "east-asia", "small", ["food", "leafy-green"],
        ["pak-choi"], None, "Q193459"),
    ("napa-cabbage", "Brassica rapa pekinensis", "Brassicaceae", "Brassicales",
        "farm", "east-asia", "small", ["food"],
        ["chinese-cabbage"], None, "Q193459"),
    ("mustard-greens", "Brassica juncea", "Brassicaceae", "Brassicales",
        "farm", "asia", "small", ["food", "leafy-green"],
        None, None, "Q193459"),
    ("watercress", "Nasturtium officinale", "Brassicaceae", "Brassicales",
        "stream", "eurasia", "tiny", ["food", "leafy-green"],
        None, None, "Q193459"),
    ("arugula", "Eruca vesicaria", "Brassicaceae", "Brassicales",
        "garden", "mediterranean", "tiny", ["food", "leafy-green"],
        ["rocket"], None, "Q193459"),
    ("lettuce", "Lactuca sativa", "Asteraceae", "Asterales",
        "garden", "worldwide", "small", ["food", "leafy-green"],
        None, None, "Q193459"),
    ("romaine-lettuce", "Lactuca sativa longifolia", "Asteraceae", "Asterales",
        "garden", "mediterranean", "small", ["food"],
        ["cos-lettuce"], None, "Q193459"),
    ("iceberg-lettuce", "Lactuca sativa capitata", "Asteraceae", "Asterales",
        "farm", "worldwide", "small", ["food"],
        None, None, "Q193459"),
    ("butter-lettuce", "Lactuca sativa capitata", "Asteraceae", "Asterales",
        "garden", "worldwide", "small", ["food"],
        ["boston-lettuce"], None, "Q193459"),
    ("endive", "Cichorium endivia", "Asteraceae", "Asterales",
        "garden", "mediterranean", "small", ["food", "leafy-green"],
        None, None, "Q193459"),
    ("radicchio", "Cichorium intybus foliosum", "Asteraceae", "Asterales",
        "garden", "italy", "small", ["food", "leafy-green"],
        None, None, "Q193459"),
    ("chicory", "Cichorium intybus", "Asteraceae", "Asterales",
        "meadow", "europe", "small", ["food", "coffee-substitute"],
        None, None, "Q193459"),
    ("artichoke", "Cynara cardunculus scolymus", "Asteraceae", "Asterales",
        "farm", "mediterranean", "small", ["food", "flower-bud"],
        None, None, "Q193459"),
    ("cardoon", "Cynara cardunculus", "Asteraceae", "Asterales",
        "farm", "mediterranean", "medium", ["food"],
        None, None, "Q193459"),
    ("sunchoke", "Helianthus tuberosus", "Asteraceae", "Asterales",
        "farm", "north-america", "small", ["food", "tuber"],
        ["jerusalem-artichoke"], None, "Q193459"),
    ("onion", "Allium cepa", "Amaryllidaceae", "Asparagales",
        "farm", "central-asia", "tiny", ["food", "bulb"],
        None, None, "Q193459"),
    ("shallot", "Allium ascalonicum", "Amaryllidaceae", "Asparagales",
        "farm", "asia", "tiny", ["food", "bulb"],
        None, None, "Q193459"),
    ("scallion", "Allium fistulosum", "Amaryllidaceae", "Asparagales",
        "garden", "asia", "tiny", ["food"],
        ["green-onion", "spring-onion"], None, "Q193459"),
    ("leek", "Allium ampeloprasum", "Amaryllidaceae", "Asparagales",
        "farm", "mediterranean", "small", ["food"],
        None, None, "Q193459"),
    ("chive", "Allium schoenoprasum", "Amaryllidaceae", "Asparagales",
        "garden", "eurasia", "tiny", ["food", "herb"],
        ["chives"], None, "Q193459"),
    ("garlic", "Allium sativum", "Amaryllidaceae", "Asparagales",
        "garden", "central-asia", "tiny", ["food", "bulb", "seasoning"],
        None, None, "Q193459"),
    ("ramp", "Allium tricoccum", "Amaryllidaceae", "Asparagales",
        "woodland", "north-america-east", "tiny", ["food", "wild-leek"],
        ["wild-leek", "wild-garlic"], None, "Q193459"),
    ("asparagus", "Asparagus officinalis", "Asparagaceae", "Asparagales",
        "farm", "europe", "small", ["food", "shoot"],
        None, None, "Q193459"),
    ("tomato", "Solanum lycopersicum", "Solanaceae", "Solanales",
        "garden", "south-america", "small", ["food", "fruit-vegetable"],
        None, None, "Q193459"),
    ("cherry-tomato", "Solanum lycopersicum cerasiforme", "Solanaceae", "Solanales",
        "garden", "south-america", "tiny", ["food"],
        None, None, "Q193459"),
    ("eggplant", "Solanum melongena", "Solanaceae", "Solanales",
        "farm", "south-asia", "small", ["food"],
        ["aubergine", "brinjal"], None, "Q193459"),
    ("bell-pepper", "Capsicum annuum", "Solanaceae", "Solanales",
        "garden", "central-america", "small", ["food"],
        ["capsicum", "sweet-pepper"], None, "Q193459"),
    ("chili-pepper", "Capsicum annuum", "Solanaceae", "Solanales",
        "garden", "central-america", "tiny", ["food", "spice"],
        None, None, "Q193459"),
    ("jalapeno", "Capsicum annuum", "Solanaceae", "Solanales",
        "farm", "mexico", "tiny", ["food", "spice"],
        None, None, "Q193459"),
    ("habanero", "Capsicum chinense", "Solanaceae", "Solanales",
        "farm", "yucatan", "tiny", ["food", "spice"],
        None, None, "Q193459"),
    ("cayenne-pepper", "Capsicum annuum", "Solanaceae", "Solanales",
        "farm", "central-america", "tiny", ["food", "spice"],
        None, None, "Q193459"),
    ("tomatillo", "Physalis philadelphica", "Solanaceae", "Solanales",
        "farm", "mexico", "tiny", ["food"],
        None, None, "Q193459"),
    ("ground-cherry", "Physalis pruinosa", "Solanaceae", "Solanales",
        "garden", "americas", "tiny", ["food"],
        ["husk-cherry"], None, "Q193459"),
    ("okra", "Abelmoschus esculentus", "Malvaceae", "Malvales",
        "farm", "africa", "small", ["food", "pod"],
        ["ladies-fingers"], None, "Q193459"),
    ("cucumber", "Cucumis sativus", "Cucurbitaceae", "Cucurbitales",
        "garden", "south-asia", "small", ["food"],
        None, None, "Q193459"),
    ("pickling-cucumber", "Cucumis sativus", "Cucurbitaceae", "Cucurbitales",
        "garden", "south-asia", "tiny", ["food"],
        ["gherkin"], None, "Q193459"),
    ("zucchini", "Cucurbita pepo", "Cucurbitaceae", "Cucurbitales",
        "garden", "central-america", "small", ["food"],
        ["courgette"], None, "Q193459"),
    ("squash", "Cucurbita", "Cucurbitaceae", "Cucurbitales",
        "farm", "americas", "small", ["food"],
        None, None, "Q193459"),
    ("pumpkin", "Cucurbita pepo", "Cucurbitaceae", "Cucurbitales",
        "farm", "north-america", "medium", ["food", "carving"],
        None, None, "Q193459"),
    ("butternut-squash", "Cucurbita moschata", "Cucurbitaceae", "Cucurbitales",
        "farm", "americas", "small", ["food"],
        None, None, "Q193459"),
    ("acorn-squash", "Cucurbita pepo", "Cucurbitaceae", "Cucurbitales",
        "farm", "americas", "small", ["food"],
        None, None, "Q193459"),
    ("spaghetti-squash", "Cucurbita pepo", "Cucurbitaceae", "Cucurbitales",
        "farm", "americas", "small", ["food"],
        None, None, "Q193459"),
    ("delicata-squash", "Cucurbita pepo", "Cucurbitaceae", "Cucurbitales",
        "farm", "americas", "small", ["food"],
        None, None, "Q193459"),
    ("kabocha", "Cucurbita maxima", "Cucurbitaceae", "Cucurbitales",
        "farm", "japan", "small", ["food"],
        ["japanese-pumpkin"], None, "Q193459"),
    ("melon", "Cucumis melo", "Cucurbitaceae", "Cucurbitales",
        "farm", "africa", "small", ["food"],
        None, None, "Q193459"),
    ("cantaloupe", "Cucumis melo cantalupensis", "Cucurbitaceae", "Cucurbitales",
        "farm", "eurasia", "small", ["food"],
        ["muskmelon"], None, "Q193459"),
    ("honeydew", "Cucumis melo inodorus", "Cucurbitaceae", "Cucurbitales",
        "farm", "eurasia", "small", ["food"],
        None, None, "Q193459"),
    ("watermelon", "Citrullus lanatus", "Cucurbitaceae", "Cucurbitales",
        "farm", "africa", "small", ["food"],
        None, None, "Q193459"),
    ("bitter-melon", "Momordica charantia", "Cucurbitaceae", "Cucurbitales",
        "farm", "asia", "small", ["food"],
        ["bitter-gourd"], None, "Q193459"),
    ("chayote", "Sechium edule", "Cucurbitaceae", "Cucurbitales",
        "farm", "central-america", "small", ["food"],
        ["mirliton"], None, "Q193459"),
    ("mushroom-vegetable", "Agaricus bisporus", "Agaricaceae", "Agaricales",
        "farm", "worldwide", "tiny", ["food"],
        ["button-mushroom"], None, "Q193459"),
]

for e in VEG: _emit(e)


# ---------------------------------------------------------------------------
# FRUITS
# ---------------------------------------------------------------------------
FRUIT = [
    ("apple", "Malus domestica", "Rosaceae", "Rosales",
        "orchard", "central-asia", "tiny", ["food"],
        None, None, "Q89"),
    ("pear", "Pyrus communis", "Rosaceae", "Rosales",
        "orchard", "europe", "tiny", ["food"],
        None, None, "Q193459"),
    ("peach", "Prunus persica", "Rosaceae", "Rosales",
        "orchard", "east-asia", "tiny", ["food"],
        None, None, "Q193459"),
    ("nectarine", "Prunus persica nucipersica", "Rosaceae", "Rosales",
        "orchard", "east-asia", "tiny", ["food"],
        None, None, "Q193459"),
    ("plum", "Prunus domestica", "Rosaceae", "Rosales",
        "orchard", "eurasia", "tiny", ["food"],
        None, None, "Q193459"),
    ("apricot", "Prunus armeniaca", "Rosaceae", "Rosales",
        "orchard", "central-asia", "tiny", ["food"],
        None, None, "Q193459"),
    ("cherry", "Prunus avium", "Rosaceae", "Rosales",
        "orchard", "eurasia", "tiny", ["food"],
        ["sweet-cherry"], None, "Q193459"),
    ("sour-cherry", "Prunus cerasus", "Rosaceae", "Rosales",
        "orchard", "eurasia", "tiny", ["food"],
        ["tart-cherry"], None, "Q193459"),
    ("quince", "Cydonia oblonga", "Rosaceae", "Rosales",
        "orchard", "central-asia", "tiny", ["food"],
        None, None, "Q193459"),
    ("crabapple", "Malus sylvestris", "Rosaceae", "Rosales",
        "orchard", "europe", "tiny", ["food-preserves"],
        None, None, "Q193459"),
    ("loquat", "Eriobotrya japonica", "Rosaceae", "Rosales",
        "orchard", "east-asia", "tiny", ["food"],
        None, None, "Q193459"),
    ("medlar", "Mespilus germanica", "Rosaceae", "Rosales",
        "orchard", "europe", "tiny", ["food"],
        None, None, "Q193459"),
    ("strawberry", "Fragaria × ananassa", "Rosaceae", "Rosales",
        "garden", "worldwide-temperate", "tiny", ["food"],
        None, None, "Q193459"),
    ("raspberry", "Rubus idaeus", "Rosaceae", "Rosales",
        "garden", "europe", "tiny", ["food"],
        None, None, "Q193459"),
    ("blackberry", "Rubus fruticosus", "Rosaceae", "Rosales",
        ["hedgerow", "garden"], "eurasia", "tiny", ["food"],
        None, None, "Q193459"),
    ("blueberry", "Vaccinium corymbosum", "Ericaceae", "Ericales",
        ["garden", "bog"], "north-america", "tiny", ["food"],
        None, None, "Q193459"),
    ("cranberry", "Vaccinium macrocarpon", "Ericaceae", "Ericales",
        "bog", "north-america", "tiny", ["food"],
        None, None, "Q193459"),
    ("gooseberry", "Ribes uva-crispa", "Grossulariaceae", "Saxifragales",
        "garden", "eurasia", "tiny", ["food"],
        None, None, "Q193459"),
    ("currant", "Ribes rubrum", "Grossulariaceae", "Saxifragales",
        "garden", "europe", "tiny", ["food"],
        None, None, "Q193459"),
    ("elderberry", "Sambucus nigra", "Adoxaceae", "Dipsacales",
        ["hedgerow", "garden"], "europe", "tiny", ["food", "medicinal"],
        None, None, "Q193459"),
    ("mulberry-fruit", "Morus alba", "Moraceae", "Rosales",
        "orchard", "east-asia", "tiny", ["food"],
        None, None, "Q193459"),
    ("grape", "Vitis vinifera", "Vitaceae", "Vitales",
        "vineyard", "eurasia", "tiny", ["food", "wine"],
        None, None, "Q193459"),
    ("kiwi", "Actinidia deliciosa", "Actinidiaceae", "Ericales",
        "orchard", "east-asia", "tiny", ["food"],
        ["kiwifruit"], None, "Q193459"),
    ("pomegranate", "Punica granatum", "Lythraceae", "Myrtales",
        "orchard", "middle-east", "tiny", ["food"],
        None, None, "Q193459"),
    ("fig-fruit", "Ficus carica", "Moraceae", "Rosales",
        "orchard", "mediterranean", "tiny", ["food"],
        None, None, "Q193459"),
    ("date", "Phoenix dactylifera", "Arecaceae", "Arecales",
        "orchard", "middle-east", "tiny", ["food"],
        None, None, "Q193459"),
    ("olive", "Olea europaea", "Oleaceae", "Lamiales",
        "orchard", "mediterranean", "tiny", ["food", "oil"],
        None, None, "Q193459"),
    ("orange", "Citrus sinensis", "Rutaceae", "Sapindales",
        "orchard", "asia", "tiny", ["food"],
        None, None, "Q193459"),
    ("mandarin", "Citrus reticulata", "Rutaceae", "Sapindales",
        "orchard", "asia", "tiny", ["food"],
        ["tangerine"], None, "Q193459"),
    ("clementine", "Citrus clementina", "Rutaceae", "Sapindales",
        "orchard", "mediterranean", "tiny", ["food"],
        None, None, "Q193459"),
    ("lemon", "Citrus limon", "Rutaceae", "Sapindales",
        "orchard", "asia", "tiny", ["food"],
        None, None, "Q193459"),
    ("lime", "Citrus aurantiifolia", "Rutaceae", "Sapindales",
        "orchard", "southeast-asia", "tiny", ["food"],
        None, None, "Q193459"),
    ("grapefruit", "Citrus × paradisi", "Rutaceae", "Sapindales",
        "orchard", "caribbean", "tiny", ["food"],
        None, None, "Q193459"),
    ("pomelo", "Citrus maxima", "Rutaceae", "Sapindales",
        "orchard", "southeast-asia", "tiny", ["food"],
        None, None, "Q193459"),
    ("kumquat", "Citrus japonica", "Rutaceae", "Sapindales",
        "orchard", "east-asia", "tiny", ["food"],
        None, None, "Q193459"),
    ("yuzu", "Citrus × junos", "Rutaceae", "Sapindales",
        "orchard", "east-asia", "tiny", ["food"],
        None, None, "Q193459"),
    ("bergamot", "Citrus × bergamia", "Rutaceae", "Sapindales",
        "orchard", "italy", "tiny", ["oil"],
        None, None, "Q193459"),
    ("banana", "Musa acuminata", "Musaceae", "Zingiberales",
        "orchard", "southeast-asia", "tiny", ["food"],
        None, None, "Q193459"),
    ("plantain", "Musa × paradisiaca", "Musaceae", "Zingiberales",
        "orchard", "southeast-asia", "tiny", ["food"],
        None, None, "Q193459"),
    ("pineapple", "Ananas comosus", "Bromeliaceae", "Poales",
        "farm", "south-america", "small", ["food"],
        None, None, "Q193459"),
    ("mango", "Mangifera indica", "Anacardiaceae", "Sapindales",
        "orchard", "south-asia", "tiny", ["food"],
        None, None, "Q193459"),
    ("papaya", "Carica papaya", "Caricaceae", "Brassicales",
        "orchard", "central-america", "tiny", ["food"],
        None, None, "Q193459"),
    ("guava", "Psidium guajava", "Myrtaceae", "Myrtales",
        "orchard", "central-america", "tiny", ["food"],
        None, None, "Q193459"),
    ("passion-fruit", "Passiflora edulis", "Passifloraceae", "Malpighiales",
        "orchard", "south-america", "tiny", ["food"],
        None, None, "Q193459"),
    ("dragon-fruit", "Hylocereus undatus", "Cactaceae", "Caryophyllales",
        "orchard", "central-america", "tiny", ["food"],
        ["pitaya"], None, "Q193459"),
    ("lychee", "Litchi chinensis", "Sapindaceae", "Sapindales",
        "orchard", "china", "tiny", ["food"],
        ["litchi"], None, "Q193459"),
    ("longan", "Dimocarpus longan", "Sapindaceae", "Sapindales",
        "orchard", "china", "tiny", ["food"],
        None, None, "Q193459"),
    ("rambutan", "Nephelium lappaceum", "Sapindaceae", "Sapindales",
        "orchard", "southeast-asia", "tiny", ["food"],
        None, None, "Q193459"),
    ("mangosteen", "Garcinia mangostana", "Clusiaceae", "Malpighiales",
        "orchard", "southeast-asia", "tiny", ["food"],
        None, None, "Q193459"),
    ("durian", "Durio zibethinus", "Malvaceae", "Malvales",
        "orchard", "southeast-asia", "small", ["food", "pungent"],
        None, None, "Q193459"),
    ("jackfruit", "Artocarpus heterophyllus", "Moraceae", "Rosales",
        "orchard", "south-asia", "large", ["food"],
        None, None, "Q193459"),
    ("breadfruit", "Artocarpus altilis", "Moraceae", "Rosales",
        "orchard", "pacific-islands", "medium", ["food"],
        None, None, "Q193459"),
    ("starfruit", "Averrhoa carambola", "Oxalidaceae", "Oxalidales",
        "orchard", "southeast-asia", "tiny", ["food"],
        ["carambola"], None, "Q193459"),
    ("avocado", "Persea americana", "Lauraceae", "Laurales",
        "orchard", "central-america", "tiny", ["food"],
        ["alligator-pear"], None, "Q193459"),
    ("persimmon-fruit", "Diospyros kaki", "Ebenaceae", "Ericales",
        "orchard", "east-asia", "tiny", ["food"],
        None, None, "Q193459"),
    ("cherimoya", "Annona cherimola", "Annonaceae", "Magnoliales",
        "orchard", "south-america", "tiny", ["food"],
        None, None, "Q193459"),
    ("soursop", "Annona muricata", "Annonaceae", "Magnoliales",
        "orchard", "central-america", "small", ["food"],
        ["guanabana"], None, "Q193459"),
    ("acai", "Euterpe oleracea", "Arecaceae", "Arecales",
        "jungle-farm", "amazon-basin", "tiny", ["food"],
        ["acai-berry"], None, "Q193459"),
    ("goji-berry", "Lycium barbarum", "Solanaceae", "Solanales",
        "farm", "china", "tiny", ["food"],
        ["wolfberry"], None, "Q193459"),
    ("sea-buckthorn", "Hippophae rhamnoides", "Elaeagnaceae", "Rosales",
        ["coastal-scrub", "farm"], "eurasia", "tiny", ["food"],
        None, None, "Q193459"),
    ("chokecherry", "Prunus virginiana", "Rosaceae", "Rosales",
        "forest-edge", "north-america", "tiny", ["food", "preserves"],
        None, None, "Q193459"),
    ("saskatoon-berry", "Amelanchier alnifolia", "Rosaceae", "Rosales",
        "prairie", "north-america", "tiny", ["food"],
        ["service-berry"], None, "Q193459"),
    ("cloudberry", "Rubus chamaemorus", "Rosaceae", "Rosales",
        "bog", "arctic-boreal", "tiny", ["food"],
        None, None, "Q193459"),
    ("lingonberry", "Vaccinium vitis-idaea", "Ericaceae", "Ericales",
        "boreal-forest", "north-hemisphere", "tiny", ["food"],
        None, None, "Q193459"),
    ("huckleberry", "Vaccinium ovatum", "Ericaceae", "Ericales",
        "forest", "north-america-west", "tiny", ["food"],
        None, None, "Q193459"),
]

for e in FRUIT: _emit(e)


# ---------------------------------------------------------------------------
# GRAINS + LEGUMES + SEEDS
# ---------------------------------------------------------------------------
GRAIN = [
    ("wheat", "Triticum aestivum", "Poaceae", "Poales",
        "farm", "middle-east", "small", ["food", "grain", "staple"],
        None, None, "Q193459"),
    ("durum-wheat", "Triticum durum", "Poaceae", "Poales",
        "farm", "mediterranean", "small", ["food", "pasta"],
        None, None, "Q193459"),
    ("spelt", "Triticum spelta", "Poaceae", "Poales",
        "farm", "europe", "small", ["food"],
        None, None, "Q193459"),
    ("barley", "Hordeum vulgare", "Poaceae", "Poales",
        "farm", "middle-east", "small", ["food", "beer"],
        None, None, "Q193459"),
    ("oats", "Avena sativa", "Poaceae", "Poales",
        "farm", "europe", "small", ["food"],
        None, None, "Q193459"),
    ("rye", "Secale cereale", "Poaceae", "Poales",
        "farm", "turkey", "small", ["food"],
        None, None, "Q193459"),
    ("triticale", "× Triticosecale", "Poaceae", "Poales",
        "farm", "hybrid", "small", ["food"],
        None, None, "Q193459"),
    ("rice", "Oryza sativa", "Poaceae", "Poales",
        "paddy", "asia", "small", ["food", "grain", "staple"],
        None, None, "Q193459"),
    ("wild-rice", "Zizania palustris", "Poaceae", "Poales",
        "wetland", "north-america", "small", ["food"],
        None, None, "Q193459"),
    ("corn", "Zea mays", "Poaceae", "Poales",
        "farm", "central-america", "medium", ["food", "grain", "staple"],
        ["maize"], None, "Q193459"),
    ("popcorn", "Zea mays everta", "Poaceae", "Poales",
        "farm", "central-america", "medium", ["food"],
        None, None, "Q193459"),
    ("sorghum", "Sorghum bicolor", "Poaceae", "Poales",
        "farm", "africa", "medium", ["food"],
        None, None, "Q193459"),
    ("millet", "Pennisetum glaucum", "Poaceae", "Poales",
        "farm", "africa", "medium", ["food"],
        ["pearl-millet"], None, "Q193459"),
    ("teff", "Eragrostis tef", "Poaceae", "Poales",
        "farm", "ethiopia", "small", ["food"],
        None, None, "Q193459"),
    ("fonio", "Digitaria exilis", "Poaceae", "Poales",
        "farm", "west-africa", "small", ["food"],
        None, None, "Q193459"),
    ("buckwheat", "Fagopyrum esculentum", "Polygonaceae", "Caryophyllales",
        "farm", "east-asia", "small", ["food"],
        None, None, "Q193459"),
    ("lentil", "Lens culinaris", "Fabaceae", "Fabales",
        "farm", "middle-east", "tiny", ["food", "legume"],
        None, None, "Q193459"),
    ("chickpea", "Cicer arietinum", "Fabaceae", "Fabales",
        "farm", "middle-east", "tiny", ["food", "legume"],
        ["garbanzo"], None, "Q193459"),
    ("black-bean", "Phaseolus vulgaris", "Fabaceae", "Fabales",
        "farm", "americas", "tiny", ["food"],
        None, None, "Q193459"),
    ("kidney-bean", "Phaseolus vulgaris", "Fabaceae", "Fabales",
        "farm", "americas", "tiny", ["food"],
        None, None, "Q193459"),
    ("pinto-bean", "Phaseolus vulgaris", "Fabaceae", "Fabales",
        "farm", "americas", "tiny", ["food"],
        None, None, "Q193459"),
    ("navy-bean", "Phaseolus vulgaris", "Fabaceae", "Fabales",
        "farm", "americas", "tiny", ["food"],
        None, None, "Q193459"),
    ("green-bean", "Phaseolus vulgaris", "Fabaceae", "Fabales",
        "garden", "americas", "tiny", ["food"],
        ["string-bean"], None, "Q193459"),
    ("lima-bean", "Phaseolus lunatus", "Fabaceae", "Fabales",
        "farm", "south-america", "tiny", ["food"],
        ["butter-bean"], None, "Q193459"),
    ("fava-bean", "Vicia faba", "Fabaceae", "Fabales",
        "farm", "middle-east", "tiny", ["food"],
        ["broad-bean"], None, "Q193459"),
    ("soybean", "Glycine max", "Fabaceae", "Fabales",
        "farm", "east-asia", "tiny", ["food", "oil", "tofu"],
        None, None, "Q193459"),
    ("mung-bean", "Vigna radiata", "Fabaceae", "Fabales",
        "farm", "asia", "tiny", ["food"],
        None, None, "Q193459"),
    ("adzuki-bean", "Vigna angularis", "Fabaceae", "Fabales",
        "farm", "east-asia", "tiny", ["food"],
        None, None, "Q193459"),
    ("peanut", "Arachis hypogaea", "Fabaceae", "Fabales",
        "farm", "south-america", "tiny", ["food"],
        ["groundnut"], None, "Q193459"),
    ("pea", "Pisum sativum", "Fabaceae", "Fabales",
        "garden", "middle-east", "tiny", ["food"],
        None, None, "Q193459"),
    ("snap-pea", "Pisum sativum saccharatum", "Fabaceae", "Fabales",
        "garden", "worldwide", "tiny", ["food"],
        None, None, "Q193459"),
    ("snow-pea", "Pisum sativum saccharatum", "Fabaceae", "Fabales",
        "garden", "worldwide", "tiny", ["food"],
        None, None, "Q193459"),
    ("black-eyed-pea", "Vigna unguiculata", "Fabaceae", "Fabales",
        "farm", "africa", "tiny", ["food"],
        ["cowpea"], None, "Q193459"),
    ("pigeon-pea", "Cajanus cajan", "Fabaceae", "Fabales",
        "farm", "south-asia", "tiny", ["food"],
        None, None, "Q193459"),
    ("sesame", "Sesamum indicum", "Pedaliaceae", "Lamiales",
        "farm", "africa", "tiny", ["food", "oil"],
        None, None, "Q193459"),
    ("flaxseed", "Linum usitatissimum", "Linaceae", "Malpighiales",
        "farm", "middle-east", "tiny", ["food", "oil", "linen"],
        ["linseed"], None, "Q193459"),
    ("chia", "Salvia hispanica", "Lamiaceae", "Lamiales",
        "farm", "central-america", "tiny", ["food"],
        None, None, "Q193459"),
    ("sunflower-seed", "Helianthus annuus", "Asteraceae", "Asterales",
        "farm", "north-america", "tiny", ["food", "oil"],
        None, None, "Q193459"),
    ("pumpkin-seed", "Cucurbita pepo", "Cucurbitaceae", "Cucurbitales",
        "farm", "americas", "tiny", ["food"],
        ["pepita"], None, "Q193459"),
    ("poppy-seed", "Papaver somniferum", "Papaveraceae", "Ranunculales",
        "farm", "eurasia", "tiny", ["food"],
        None, None, "Q193459"),
    ("hemp-seed", "Cannabis sativa", "Cannabaceae", "Rosales",
        "farm", "central-asia", "tiny", ["food", "oil", "fiber"],
        None, None, "Q193459"),
    ("almond", "Prunus dulcis", "Rosaceae", "Rosales",
        "orchard", "mediterranean", "tiny", ["food"],
        None, None, "Q193459"),
    ("walnut-nut", "Juglans regia", "Juglandaceae", "Fagales",
        "orchard", "eurasia", "tiny", ["food"],
        None, None, "Q193459"),
    ("pecan-nut", "Carya illinoinensis", "Juglandaceae", "Fagales",
        "orchard", "north-america-south", "tiny", ["food"],
        None, None, "Q193459"),
    ("hazelnut", "Corylus avellana", "Betulaceae", "Fagales",
        "orchard", "europe", "tiny", ["food"],
        ["filbert"], None, "Q193459"),
    ("chestnut-nut", "Castanea sativa", "Fagaceae", "Fagales",
        "orchard", "europe", "tiny", ["food"],
        None, None, "Q193459"),
    ("pistachio", "Pistacia vera", "Anacardiaceae", "Sapindales",
        "orchard", "central-asia", "tiny", ["food"],
        None, None, "Q193459"),
    ("cashew", "Anacardium occidentale", "Anacardiaceae", "Sapindales",
        "orchard", "brazil", "tiny", ["food"],
        None, None, "Q193459"),
    ("macadamia", "Macadamia integrifolia", "Proteaceae", "Proteales",
        "orchard", "australia", "tiny", ["food"],
        None, None, "Q193459"),
    ("brazil-nut", "Bertholletia excelsa", "Lecythidaceae", "Ericales",
        "jungle", "amazon-basin", "tiny", ["food"],
        None, None, "Q193459"),
    ("pine-nut", "Pinus pinea", "Pinaceae", "Pinales",
        "mediterranean", "mediterranean", "tiny", ["food"],
        ["pignoli"], None, "Q193459"),
]

for e in GRAIN: _emit(e)


# ---------------------------------------------------------------------------
# HERBS + SPICES
# ---------------------------------------------------------------------------
HERB = [
    ("basil", "Ocimum basilicum", "Lamiaceae", "Lamiales",
        "garden", "asia", "tiny", ["food", "herb"], None, None, "Q193459"),
    ("thyme", "Thymus vulgaris", "Lamiaceae", "Lamiales",
        "garden", "mediterranean", "tiny", ["food", "herb"], None, None, "Q193459"),
    ("rosemary", "Salvia rosmarinus", "Lamiaceae", "Lamiales",
        "garden", "mediterranean", "small", ["food", "herb"], None, None, "Q193459"),
    ("sage", "Salvia officinalis", "Lamiaceae", "Lamiales",
        "garden", "mediterranean", "small", ["food", "herb"], None, None, "Q193459"),
    ("oregano", "Origanum vulgare", "Lamiaceae", "Lamiales",
        "garden", "mediterranean", "small", ["food", "herb"], None, None, "Q193459"),
    ("marjoram", "Origanum majorana", "Lamiaceae", "Lamiales",
        "garden", "mediterranean", "small", ["food", "herb"], None, None, "Q193459"),
    ("mint", "Mentha", "Lamiaceae", "Lamiales",
        "garden", "worldwide", "tiny", ["food", "herb"], None, None, "Q193459"),
    ("spearmint", "Mentha spicata", "Lamiaceae", "Lamiales",
        "garden", "europe", "tiny", ["food", "herb"], None, None, "Q193459"),
    ("peppermint", "Mentha × piperita", "Lamiaceae", "Lamiales",
        "garden", "europe", "tiny", ["food", "herb"], None, None, "Q193459"),
    ("tarragon", "Artemisia dracunculus", "Asteraceae", "Asterales",
        "garden", "eurasia", "small", ["food", "herb"], None, None, "Q193459"),
    ("chervil", "Anthriscus cerefolium", "Apiaceae", "Apiales",
        "garden", "europe", "tiny", ["food", "herb"], None, None, "Q193459"),
    ("lemon-balm", "Melissa officinalis", "Lamiaceae", "Lamiales",
        "garden", "europe", "small", ["food", "herb"], None, None, "Q193459"),
    ("lemongrass", "Cymbopogon citratus", "Poaceae", "Poales",
        "garden", "south-asia", "small", ["food", "herb"], None, None, "Q193459"),
    ("bay-leaf", "Laurus nobilis", "Lauraceae", "Laurales",
        "garden", "mediterranean", "small", ["food", "herb"], None, None, "Q193459"),
    ("black-pepper", "Piper nigrum", "Piperaceae", "Piperales",
        "farm", "south-asia", "small", ["food", "spice"], None, None, "Q193459"),
    ("cinnamon", "Cinnamomum verum", "Lauraceae", "Laurales",
        "orchard", "sri-lanka", "small", ["food", "spice"], None, None, "Q193459"),
    ("clove", "Syzygium aromaticum", "Myrtaceae", "Myrtales",
        "orchard", "indonesia", "small", ["food", "spice"], None, None, "Q193459"),
    ("nutmeg", "Myristica fragrans", "Myristicaceae", "Magnoliales",
        "orchard", "indonesia", "small", ["food", "spice"], None, None, "Q193459"),
    ("mace-spice", "Myristica fragrans", "Myristicaceae", "Magnoliales",
        "orchard", "indonesia", "small", ["food", "spice"], None, None, "Q193459"),
    ("allspice", "Pimenta dioica", "Myrtaceae", "Myrtales",
        "orchard", "caribbean", "small", ["food", "spice"], None, None, "Q193459"),
    ("cardamom", "Elettaria cardamomum", "Zingiberaceae", "Zingiberales",
        "farm", "south-asia", "small", ["food", "spice"], None, None, "Q193459"),
    ("ginger", "Zingiber officinale", "Zingiberaceae", "Zingiberales",
        "farm", "southeast-asia", "small", ["food", "spice"], None, None, "Q193459"),
    ("turmeric", "Curcuma longa", "Zingiberaceae", "Zingiberales",
        "farm", "south-asia", "small", ["food", "spice", "dye"], None, None, "Q193459"),
    ("galangal", "Alpinia galanga", "Zingiberaceae", "Zingiberales",
        "farm", "southeast-asia", "small", ["food", "spice"], None, None, "Q193459"),
    ("cumin", "Cuminum cyminum", "Apiaceae", "Apiales",
        "farm", "middle-east", "tiny", ["food", "spice"], None, None, "Q193459"),
    ("coriander-seed", "Coriandrum sativum", "Apiaceae", "Apiales",
        "farm", "mediterranean", "tiny", ["food", "spice"], None, None, "Q193459"),
    ("fennel-seed", "Foeniculum vulgare", "Apiaceae", "Apiales",
        "farm", "mediterranean", "tiny", ["food", "spice"], None, None, "Q193459"),
    ("anise", "Pimpinella anisum", "Apiaceae", "Apiales",
        "farm", "mediterranean", "small", ["food", "spice"], None, None, "Q193459"),
    ("star-anise", "Illicium verum", "Schisandraceae", "Austrobaileyales",
        "orchard", "east-asia", "small", ["food", "spice"], None, None, "Q193459"),
    ("caraway", "Carum carvi", "Apiaceae", "Apiales",
        "farm", "eurasia", "tiny", ["food", "spice"], None, None, "Q193459"),
    ("dill-seed", "Anethum graveolens", "Apiaceae", "Apiales",
        "garden", "eurasia", "tiny", ["food", "spice"], None, None, "Q193459"),
    ("mustard-seed", "Sinapis alba", "Brassicaceae", "Brassicales",
        "farm", "eurasia", "tiny", ["food", "spice"], None, None, "Q193459"),
    ("fenugreek", "Trigonella foenum-graecum", "Fabaceae", "Fabales",
        "farm", "south-asia", "tiny", ["food", "spice"], None, None, "Q193459"),
    ("saffron", "Crocus sativus", "Iridaceae", "Asparagales",
        "farm", "middle-east", "tiny", ["food", "spice"], None, None, "Q193459"),
    ("vanilla", "Vanilla planifolia", "Orchidaceae", "Asparagales",
        "farm", "central-america", "small", ["food", "spice"], None, None, "Q193459"),
    ("paprika", "Capsicum annuum", "Solanaceae", "Solanales",
        "farm", "central-europe", "tiny", ["food", "spice"], None, None, "Q193459"),
    ("sumac", "Rhus coriaria", "Anacardiaceae", "Sapindales",
        "scrubland", "middle-east", "small", ["food", "spice"], None, None, "Q193459"),
    ("sichuan-pepper", "Zanthoxylum piperitum", "Rutaceae", "Sapindales",
        "orchard", "east-asia", "small", ["food", "spice"],
        ["szechuan-peppercorn"], None, "Q193459"),
    ("juniper-berry", "Juniperus communis", "Cupressaceae", "Cupressales",
        "scrubland", "north-hemisphere", "tiny", ["food", "spice", "gin"], None, None, "Q193459"),
    ("stevia", "Stevia rebaudiana", "Asteraceae", "Asterales",
        "farm", "south-america", "tiny", ["food", "sweetener"], None, None, "Q193459"),
    ("licorice", "Glycyrrhiza glabra", "Fabaceae", "Fabales",
        "farm", "middle-east", "small", ["food", "flavoring"],
        ["liquorice"], None, "Q193459"),
    ("hops", "Humulus lupulus", "Cannabaceae", "Rosales",
        "farm", "north-hemisphere", "medium", ["beer"], None, None, "Q193459"),
    ("cocoa", "Theobroma cacao", "Malvaceae", "Malvales",
        "orchard", "central-america", "tiny", ["food"], ["cacao"], None, "Q193459"),
    ("coffee-bean", "Coffea arabica", "Rubiaceae", "Gentianales",
        "highland-farm", "africa", "tiny", ["drink"], None, None, "Q193459"),
    ("tea-leaf", "Camellia sinensis", "Theaceae", "Ericales",
        "highland-farm", "east-asia", "tiny", ["drink"], None, None, "Q193459"),
    ("sugarcane", "Saccharum officinarum", "Poaceae", "Poales",
        "farm", "southeast-asia", "medium", ["food", "sugar"], None, None, "Q193459"),
    ("sugar-beet", "Beta vulgaris altissima", "Amaranthaceae", "Caryophyllales",
        "farm", "europe", "tiny", ["food", "sugar"], None, None, "Q193459"),
    ("maple-sugar", "Acer saccharum", "Sapindaceae", "Sapindales",
        "forest", "north-america-east", "large", ["food", "syrup"], None, None, "Q193459"),
]

for e in HERB: _emit(e)
