"""Ferns, mosses, grasses, aquatic + wetland, houseplants, cacti+succulents,
vines, ornamentals. ~120-180 nodes."""

from _helpers import node, wikidata, tax, authored


def pl(canonical, sci, family, kind, region, size, syns=None, used=None,
       seasons=None, qid=None):
    return node(canonical, "plant",
                synonyms=syns or [],
                scientific_name=sci,
                taxonomy=tax(kingdom="Plantae", family=family,
                             genus=sci.split()[0] if sci else None,
                             species=sci, common_name=canonical),
                lives_in=[kind] if isinstance(kind, str) else kind,
                region_native_to=[region] if isinstance(region, str) else region,
                size_scale=size, used_for=used, season=seasons,
                kid_friendly=True,
                provenance=[wikidata(qid)] if qid else [authored()])


NODES = []

# Ferns
FERN = [
    ("fern", "Polypodiopsida", "Polypodiaceae", ["forest", "shade"], "worldwide", "small",
        None, ["ornamental"], None, "Q193459"),
    ("boston-fern", "Nephrolepis exaltata", "Lomariopsidaceae", ["houseplant"], "americas", "small",
        None, ["houseplant"], None, "Q193459"),
    ("bracken", "Pteridium aquilinum", "Dennstaedtiaceae", ["forest", "meadow"], "worldwide", "medium",
        None, None, None, "Q193459"),
    ("maidenhair-fern", "Adiantum capillus-veneris", "Pteridaceae", ["shade", "cliff"], "worldwide", "tiny",
        None, ["ornamental"], None, "Q193459"),
    ("ostrich-fern", "Matteuccia struthiopteris", "Onocleaceae", ["forest", "wetland"], "north-hemisphere", "medium",
        None, ["fiddleheads-edible"], None, "Q193459"),
    ("cinnamon-fern", "Osmundastrum cinnamomeum", "Osmundaceae", ["wetland"], "americas", "medium",
        None, None, None, "Q193459"),
    ("staghorn-fern", "Platycerium bifurcatum", "Polypodiaceae", ["epiphyte", "tree"], "australia", "small",
        None, ["ornamental"], None, "Q193459"),
    ("horsetail", "Equisetum arvense", "Equisetaceae", ["wetland", "roadside"], "north-hemisphere", "small",
        ["scouring-rush"], None, None, "Q193459"),
    ("club-moss", "Lycopodium clavatum", "Lycopodiaceae", ["forest"], "north-hemisphere", "tiny",
        ["ground-pine"], None, None, "Q193459"),
    ("tree-fern", "Cyathea", "Cyatheaceae", ["cloud-forest"], "tropics-worldwide", "medium",
        None, None, None, "Q193459"),
]
for e in FERN: NODES.append(pl(e[0], e[1], e[2], e[3], e[4], e[5], syns=e[6], used=e[7], seasons=e[8], qid=e[9]))

# Mosses + lichens
MOSS = [
    ("moss", "Bryophyta", "Bryaceae", ["forest-floor", "rock"], "worldwide", "tiny",
        None, ["ground-cover"], None, "Q193459"),
    ("sphagnum-moss", "Sphagnum", "Sphagnaceae", ["bog"], "north-hemisphere", "tiny",
        ["peat-moss"], ["peat", "gardening"], None, "Q193459"),
    ("haircap-moss", "Polytrichum commune", "Polytrichaceae", ["forest", "heath"], "worldwide", "tiny",
        None, None, None, "Q193459"),
    ("spanish-moss", "Tillandsia usneoides", "Bromeliaceae", ["tree", "epiphyte"], "americas-south", "tiny",
        None, ["ornamental"], None, "Q193459"),
    ("liverwort", "Marchantiophyta", "Marchantiaceae", ["shade", "wetland"], "worldwide", "tiny",
        None, None, None, "Q193459"),
    ("reindeer-lichen", "Cladonia rangiferina", "Cladoniaceae", ["arctic-tundra"], "arctic", "tiny",
        None, ["reindeer-food"], None, "Q193459"),
    ("crustose-lichen", "Rhizocarpon geographicum", "Rhizocarpaceae", ["rock"], "worldwide", "tiny",
        ["map-lichen"], None, None, "Q193459"),
    ("beard-lichen", "Usnea", "Parmeliaceae", ["tree"], "worldwide", "tiny",
        ["old-mans-beard"], None, None, "Q193459"),
]
for e in MOSS: NODES.append(pl(e[0], e[1], e[2], e[3], e[4], e[5], syns=e[6], used=e[7], seasons=e[8], qid=e[9]))

# Grasses + sedges + rushes
GRASS = [
    ("grass", "Poaceae", "Poaceae", ["lawn", "meadow"], "worldwide", "tiny",
        None, ["forage", "lawn"], None, "Q193459"),
    ("kentucky-bluegrass", "Poa pratensis", "Poaceae", ["lawn"], "eurasia", "tiny",
        None, ["lawn"], None, "Q193459"),
    ("bermuda-grass", "Cynodon dactylon", "Poaceae", ["lawn"], "africa", "tiny",
        None, ["lawn"], None, "Q193459"),
    ("st-augustine-grass", "Stenotaphrum secundatum", "Poaceae", ["lawn"], "africa", "tiny",
        None, ["warm-season-lawn"], None, "Q193459"),
    ("fescue", "Festuca", "Poaceae", ["lawn", "meadow"], "worldwide-temperate", "tiny",
        None, ["forage"], None, "Q193459"),
    ("ryegrass", "Lolium perenne", "Poaceae", ["lawn", "pasture"], "eurasia", "tiny",
        None, ["forage"], None, "Q193459"),
    ("timothy-grass", "Phleum pratense", "Poaceae", ["hayfield"], "eurasia", "small",
        None, ["hay"], None, "Q193459"),
    ("crabgrass", "Digitaria sanguinalis", "Poaceae", ["lawn"], "worldwide", "tiny",
        None, ["weed"], None, "Q193459"),
    ("switchgrass", "Panicum virgatum", "Poaceae", ["prairie"], "north-america", "medium",
        None, ["forage", "biofuel"], None, "Q193459"),
    ("big-bluestem", "Andropogon gerardii", "Poaceae", ["prairie"], "north-america", "medium",
        None, ["prairie-icon"], None, "Q193459"),
    ("little-bluestem", "Schizachyrium scoparium", "Poaceae", ["prairie"], "north-america", "small",
        None, ["prairie-icon"], None, "Q193459"),
    ("pampas-grass", "Cortaderia selloana", "Poaceae", ["garden", "grassland"], "south-america", "large",
        None, ["ornamental"], None, "Q193459"),
    ("miscanthus", "Miscanthus sinensis", "Poaceae", ["garden"], "east-asia", "medium",
        None, ["ornamental", "biofuel"], None, "Q193459"),
    ("fountain-grass", "Pennisetum alopecuroides", "Poaceae", ["garden"], "east-asia", "small",
        None, ["ornamental"], None, "Q193459"),
    ("sea-oats", "Uniola paniculata", "Poaceae", ["beach"], "north-america", "small",
        None, ["dune-stabilizer"], None, "Q193459"),
    ("marram-grass", "Ammophila arenaria", "Poaceae", ["dune"], "europe", "small",
        None, ["dune-stabilizer"], ["beach-grass"], "Q193459"),
    ("papyrus", "Cyperus papyrus", "Cyperaceae", ["wetland"], "africa", "medium",
        None, ["ancient-paper"], None, "Q193459"),
    ("sedge", "Cyperaceae", "Cyperaceae", ["wetland"], "worldwide", "small",
        None, None, None, "Q193459"),
    ("rush", "Juncus effusus", "Juncaceae", ["wetland"], "worldwide", "small",
        None, ["basketry"], ["common-rush"], "Q193459"),
    ("horsetail-rush", "Equisetum hyemale", "Equisetaceae", ["wetland"], "north-hemisphere", "small",
        None, None, ["scouring-rush"], "Q193459"),
    ("reed", "Phragmites australis", "Poaceae", ["wetland"], "worldwide", "medium",
        None, ["thatching"], ["common-reed"], "Q193459"),
    ("bulrush", "Schoenoplectus", "Cyperaceae", ["wetland"], "worldwide", "small",
        None, ["basketry"], None, "Q193459"),
    ("cattail-broadleaf", "Typha latifolia", "Typhaceae", ["wetland"], "worldwide", "medium",
        None, ["food-stalks"], None, "Q193459"),
]
for e in GRASS: NODES.append(pl(e[0], e[1], e[2], e[3], e[4], e[5], syns=e[6], used=e[7], seasons=e[8], qid=e[9]))

# Aquatic plants
AQUA = [
    ("seaweed", "Macroalgae", None, ["ocean"], "worldwide", "medium",
        None, ["food", "agar"], None, "Q193459"),
    ("kelp", "Laminariales", "Laminariaceae", ["kelp-forest"], "worldwide-temperate", "large",
        None, ["food", "alginate"], None, "Q193459"),
    ("bull-kelp", "Nereocystis luetkeana", "Laminariaceae", ["kelp-forest"], "north-pacific", "large",
        None, None, None, "Q193459"),
    ("giant-kelp", "Macrocystis pyrifera", "Laminariaceae", ["kelp-forest"], "north-pacific", "huge",
        None, None, None, "Q193459"),
    ("nori", "Pyropia yezoensis", "Bangiaceae", ["ocean-coast"], "east-asia", "small",
        None, ["food"], ["laver"], "Q193459"),
    ("wakame", "Undaria pinnatifida", "Alariaceae", ["ocean"], "east-asia", "medium",
        None, ["food"], None, "Q193459"),
    ("dulse", "Palmaria palmata", "Palmariaceae", ["rocky-shore"], "north-atlantic", "small",
        None, ["food"], None, "Q193459"),
    ("sea-lettuce", "Ulva lactuca", "Ulvaceae", ["rocky-shore"], "worldwide", "small",
        None, ["food"], None, "Q193459"),
    ("agar-red-alga", "Gelidium", "Gelidiaceae", ["ocean"], "worldwide", "small",
        None, ["agar-source"], None, "Q193459"),
    ("carrageen-moss", "Chondrus crispus", "Gigartinaceae", ["rocky-shore"], "north-atlantic", "tiny",
        ["irish-moss"], ["carrageenan"], None, "Q193459"),
    ("eelgrass", "Zostera marina", "Zosteraceae", ["seagrass-meadow"], "worldwide", "small",
        None, None, None, "Q193459"),
    ("seagrass", "Zostera", "Zosteraceae", ["seagrass-meadow"], "worldwide", "small",
        None, None, None, "Q193459"),
    ("duckweed", "Lemna minor", "Araceae", ["pond"], "worldwide", "tiny",
        None, None, None, "Q193459"),
    ("water-lettuce", "Pistia stratiotes", "Araceae", ["pond"], "tropics-worldwide", "small",
        None, None, None, "Q193459"),
    ("hornwort-aquatic", "Ceratophyllum demersum", "Ceratophyllaceae", ["pond"], "worldwide", "small",
        None, None, None, "Q193459"),
    ("elodea", "Elodea canadensis", "Hydrocharitaceae", ["pond"], "north-america", "small",
        ["waterweed"], None, None, "Q193459"),
    ("water-milfoil", "Myriophyllum spicatum", "Haloragaceae", ["pond"], "eurasia", "small",
        None, None, None, "Q193459"),
    ("watermeal", "Wolffia globosa", "Araceae", ["pond"], "worldwide", "microscopic",
        None, ["smallest-flowering-plant"], None, "Q193459"),
]
for e in AQUA: NODES.append(pl(e[0], e[1], e[2], e[3], e[4], e[5], syns=e[6], used=e[7], seasons=e[8], qid=e[9]))

# Cacti + succulents
SUCC = [
    ("cactus", "Cactaceae", "Cactaceae", ["desert"], "americas", "small",
        None, ["ornamental"], None, "Q193459"),
    ("barrel-cactus", "Ferocactus", "Cactaceae", ["desert"], "north-america-southwest", "medium",
        None, None, None, "Q193459"),
    ("prickly-pear", "Opuntia ficus-indica", "Cactaceae", ["desert", "scrub"], "americas", "medium",
        None, ["food-pads-fruit"], None, "Q193459"),
    ("cholla", "Cylindropuntia bigelovii", "Cactaceae", ["desert"], "north-america-southwest", "small",
        ["jumping-cholla"], None, None, "Q193459"),
    ("christmas-cactus", "Schlumbergera", "Cactaceae", ["houseplant"], "brazil", "small",
        None, ["ornamental"], ["winter"], "Q193459"),
    ("prayer-plant", "Maranta leuconeura", "Marantaceae", ["houseplant"], "brazil", "tiny",
        None, ["ornamental"], None, "Q193459"),
    ("aloe-vera", "Aloe vera", "Asphodelaceae", ["desert", "houseplant"], "arabian-peninsula", "small",
        None, ["medicinal-gel"], None, "Q193459"),
    ("agave", "Agave americana", "Asparagaceae", ["desert"], "central-america", "medium",
        ["century-plant"], ["tequila-source"], None, "Q193459"),
    ("jade-plant", "Crassula ovata", "Crassulaceae", ["houseplant"], "south-africa", "small",
        None, ["ornamental"], None, "Q193459"),
    ("echeveria", "Echeveria", "Crassulaceae", ["houseplant", "garden"], "mexico", "tiny",
        None, ["ornamental"], None, "Q193459"),
    ("sedum", "Sedum acre", "Crassulaceae", ["rock-garden"], "eurasia", "tiny",
        ["stonecrop"], ["ground-cover"], None, "Q193459"),
    ("houseleek", "Sempervivum tectorum", "Crassulaceae", ["rock-garden"], "europe", "tiny",
        ["hen-and-chicks"], None, None, "Q193459"),
    ("hen-and-chicks", "Sempervivum", "Crassulaceae", ["rock-garden"], "europe", "tiny",
        None, ["ornamental"], None, "Q193459"),
    ("snake-plant", "Dracaena trifasciata", "Asparagaceae", ["houseplant"], "africa", "small",
        ["mother-in-law-tongue"], ["ornamental", "air-purifier"], None, "Q193459"),
    ("zz-plant", "Zamioculcas zamiifolia", "Araceae", ["houseplant"], "east-africa", "small",
        None, ["ornamental"], None, "Q193459"),
    ("pothos", "Epipremnum aureum", "Araceae", ["houseplant"], "southeast-asia", "small",
        ["devils-ivy"], ["ornamental", "climbing-vine"], None, "Q193459"),
    ("philodendron", "Philodendron", "Araceae", ["houseplant", "jungle"], "americas", "small",
        None, ["ornamental"], None, "Q193459"),
    ("monstera", "Monstera deliciosa", "Araceae", ["houseplant", "jungle"], "central-america", "medium",
        ["swiss-cheese-plant"], ["ornamental"], None, "Q193459"),
    ("fiddle-leaf-fig", "Ficus lyrata", "Moraceae", ["houseplant"], "west-africa", "medium",
        None, ["ornamental"], None, "Q193459"),
    ("rubber-plant", "Ficus elastica", "Moraceae", ["houseplant"], "south-asia", "medium",
        None, ["ornamental"], None, "Q193459"),
    ("peace-lily", "Spathiphyllum wallisii", "Araceae", ["houseplant"], "central-america", "small",
        None, ["ornamental"], None, "Q193459"),
    ("spider-plant", "Chlorophytum comosum", "Asparagaceae", ["houseplant"], "africa", "tiny",
        None, ["ornamental"], None, "Q193459"),
    ("english-ivy", "Hedera helix", "Araliaceae", ["garden", "wall"], "europe", "small",
        None, ["climbing-vine"], None, "Q193459"),
    ("boston-ivy", "Parthenocissus tricuspidata", "Vitaceae", ["wall"], "east-asia", "medium",
        None, ["fall-color"], None, "Q193459"),
    ("virginia-creeper", "Parthenocissus quinquefolia", "Vitaceae", ["forest", "wall"], "north-america", "medium",
        None, None, None, "Q193459"),
    ("kudzu", "Pueraria montana", "Fabaceae", ["forest-edge"], "east-asia", "medium",
        None, ["invasive"], None, "Q193459"),
    ("bamboo-clumping", "Fargesia", "Poaceae", ["garden"], "asia", "medium",
        None, ["ornamental"], None, "Q193459"),
    ("hosta", "Hosta", "Asparagaceae", ["shade-garden"], "east-asia", "small",
        ["plantain-lily"], ["ornamental"], None, "Q193459"),
    ("fern-tree", "Dicksonia antarctica", "Dicksoniaceae", ["cloud-forest"], "australia", "medium",
        None, None, None, "Q193459"),
]
for e in SUCC: NODES.append(pl(e[0], e[1], e[2], e[3], e[4], e[5], syns=e[6], used=e[7], seasons=e[8], qid=e[9]))
