"""Fungi — mushrooms, molds, yeasts, lichens. ~80-120 nodes."""

from _helpers import node, wikidata, tax, authored


def fun(canonical, sci, family, kind, region, size, syns=None, used=None, qid=None):
    return node(canonical, "fungus",
                synonyms=syns or [],
                scientific_name=sci,
                taxonomy=tax(kingdom="Fungi", family=family,
                             genus=sci.split()[0] if sci else None,
                             species=sci, common_name=canonical),
                lives_in=[kind] if isinstance(kind, str) else kind,
                region_native_to=[region] if isinstance(region, str) else region,
                size_scale=size, used_for=used,
                kid_friendly=True,
                provenance=[wikidata(qid)] if qid else [authored()])


NODES = []

FUNGI = [
    ("mushroom", "Agaricus", "Agaricaceae", ["forest", "field"], "worldwide", "tiny",
        ["toadstool"], None, "Q83093"),
    ("button-mushroom", "Agaricus bisporus", "Agaricaceae", ["farm"], "worldwide", "tiny",
        ["white-mushroom"], ["food"], "Q193459"),
    ("cremini", "Agaricus bisporus", "Agaricaceae", ["farm"], "worldwide", "tiny",
        ["brown-mushroom"], ["food"], "Q193459"),
    ("portobello", "Agaricus bisporus", "Agaricaceae", ["farm"], "worldwide", "small",
        None, ["food"], "Q193459"),
    ("shiitake", "Lentinula edodes", "Marasmiaceae", ["farm", "forest"], "east-asia", "tiny",
        None, ["food"], "Q193459"),
    ("oyster-mushroom", "Pleurotus ostreatus", "Pleurotaceae", ["farm", "forest"], "worldwide", "tiny",
        None, ["food"], "Q193459"),
    ("king-oyster", "Pleurotus eryngii", "Pleurotaceae", ["farm"], "mediterranean", "small",
        None, ["food"], "Q193459"),
    ("enoki", "Flammulina velutipes", "Physalacriaceae", ["farm"], "east-asia", "tiny",
        None, ["food"], "Q193459"),
    ("maitake", "Grifola frondosa", "Meripilaceae", ["forest"], "north-hemisphere", "small",
        ["hen-of-the-woods"], ["food"], "Q193459"),
    ("chanterelle", "Cantharellus cibarius", "Cantharellaceae", ["forest"], "north-hemisphere", "tiny",
        None, ["food"], "Q193459"),
    ("porcini", "Boletus edulis", "Boletaceae", ["forest"], "north-hemisphere", "tiny",
        ["cep", "king-bolete"], ["food"], "Q193459"),
    ("morel", "Morchella esculenta", "Morchellaceae", ["forest"], "north-hemisphere", "tiny",
        None, ["food"], "Q193459"),
    ("truffle", "Tuber melanosporum", "Tuberaceae", ["forest-soil"], "europe", "tiny",
        None, ["food"], "Q193459"),
    ("white-truffle", "Tuber magnatum", "Tuberaceae", ["forest-soil"], "italy", "tiny",
        None, ["food"], "Q193459"),
    ("black-truffle", "Tuber melanosporum", "Tuberaceae", ["forest-soil"], "europe", "tiny",
        ["perigord-truffle"], ["food"], "Q193459"),
    ("puffball", "Calvatia gigantea", "Agaricaceae", ["field"], "worldwide", "small",
        None, None, "Q193459"),
    ("giant-puffball", "Calvatia gigantea", "Agaricaceae", ["field"], "worldwide", "medium",
        None, ["food"], "Q193459"),
    ("chicken-of-the-woods", "Laetiporus sulphureus", "Fomitopsidaceae", ["forest"], "worldwide", "small",
        None, ["food"], "Q193459"),
    ("beefsteak-fungus", "Fistulina hepatica", "Fistulinaceae", ["forest"], "worldwide", "small",
        None, ["food"], "Q193459"),
    ("lions-mane", "Hericium erinaceus", "Hericiaceae", ["forest"], "north-hemisphere", "small",
        None, ["food", "medicinal"], "Q193459"),
    ("reishi", "Ganoderma lingzhi", "Ganodermataceae", ["forest"], "east-asia", "small",
        ["ling-zhi"], ["medicinal"], "Q193459"),
    ("turkey-tail", "Trametes versicolor", "Polyporaceae", ["forest"], "worldwide", "tiny",
        None, ["medicinal"], "Q193459"),
    ("bracket-fungus", "Polyporales", "Polyporaceae", ["forest", "log"], "worldwide", "small",
        ["shelf-fungus"], None, "Q193459"),
    ("artist-conk", "Ganoderma applanatum", "Ganodermataceae", ["forest"], "worldwide", "small",
        None, None, "Q193459"),
    ("tinder-fungus", "Fomes fomentarius", "Polyporaceae", ["forest"], "north-hemisphere", "small",
        ["hoof-fungus"], ["tinder"], "Q193459"),
    ("stinkhorn", "Phallus impudicus", "Phallaceae", ["forest", "garden"], "worldwide", "small",
        None, None, "Q193459"),
    ("earthstar", "Geastrum", "Geastraceae", ["forest"], "worldwide", "tiny",
        None, None, "Q193459"),
    ("cup-fungus", "Peziza", "Pezizaceae", ["forest-floor"], "worldwide", "tiny",
        None, None, "Q193459"),
    ("jelly-fungus", "Tremella", "Tremellaceae", ["forest"], "worldwide", "tiny",
        None, None, "Q193459"),
    ("witches-butter", "Tremella mesenterica", "Tremellaceae", ["forest"], "worldwide", "tiny",
        None, None, "Q193459"),
    ("wood-ear", "Auricularia auricula-judae", "Auriculariaceae", ["forest"], "worldwide", "tiny",
        None, ["food"], "Q193459"),
    ("bird-s-nest-fungus", "Nidulariaceae", "Nidulariaceae", ["mulch"], "worldwide", "tiny",
        ["birds-nest-fungus"], None, "Q193459"),
    ("dead-mans-fingers", "Xylaria polymorpha", "Xylariaceae", ["forest-log"], "worldwide", "tiny",
        None, None, "Q193459"),
    ("amanita", "Amanita muscaria", "Amanitaceae", ["forest"], "north-hemisphere", "tiny",
        ["fly-agaric"], None, "Q193459"),
    ("death-cap", "Amanita phalloides", "Amanitaceae", ["forest"], "europe", "tiny",
        None, ["highly-toxic"], "Q193459"),
    ("destroying-angel", "Amanita bisporigera", "Amanitaceae", ["forest"], "north-america", "tiny",
        None, ["highly-toxic"], "Q193459"),
    ("false-morel", "Gyromitra esculenta", "Discinaceae", ["forest"], "north-hemisphere", "tiny",
        None, ["toxic"], "Q193459"),
    ("jack-o-lantern-mushroom", "Omphalotus olearius", "Omphalotaceae", ["forest"], "worldwide", "small",
        None, ["bioluminescent"], "Q193459"),
    ("bleeding-tooth", "Hydnellum peckii", "Bankeraceae", ["forest"], "north-america", "tiny",
        ["strawberries-and-cream"], None, "Q193459"),
    ("mycena", "Mycena", "Mycenaceae", ["forest-floor"], "worldwide", "tiny",
        None, ["some-bioluminescent"], "Q193459"),
    ("shaggy-mane", "Coprinus comatus", "Agaricaceae", ["lawn", "field"], "worldwide", "tiny",
        ["inky-cap"], ["food"], "Q193459"),
    ("field-mushroom", "Agaricus campestris", "Agaricaceae", ["field"], "worldwide", "tiny",
        None, ["food"], "Q193459"),
    ("meadow-mushroom", "Agaricus campestris", "Agaricaceae", ["meadow"], "worldwide", "tiny",
        None, ["food"], "Q193459"),
    ("horse-mushroom", "Agaricus arvensis", "Agaricaceae", ["pasture"], "worldwide", "small",
        None, ["food"], "Q193459"),
    ("parasol-mushroom", "Macrolepiota procera", "Agaricaceae", ["meadow"], "europe", "small",
        None, ["food"], "Q193459"),
    ("fairy-ring-mushroom", "Marasmius oreades", "Marasmiaceae", ["lawn"], "worldwide", "tiny",
        None, ["food"], "Q193459"),
    ("mold", "Rhizopus stolonifer", None, ["decaying-matter"], "worldwide", "microscopic",
        None, None, "Q193459"),
    ("bread-mold", "Rhizopus stolonifer", "Mucoraceae", ["bread"], "worldwide", "microscopic",
        None, None, "Q193459"),
    ("penicillium", "Penicillium chrysogenum", "Trichocomaceae", ["cheese", "medicinal"], "worldwide", "microscopic",
        None, ["antibiotic"], "Q193459"),
    ("aspergillus", "Aspergillus niger", "Trichocomaceae", ["decaying-matter"], "worldwide", "microscopic",
        None, ["fermentation"], "Q193459"),
    ("black-mold", "Stachybotrys chartarum", "Stachybotryaceae", ["damp-structures"], "worldwide", "microscopic",
        None, ["toxic-indoor-contaminant"], "Q193459"),
    ("mildew", "Erysiphales", "Erysiphaceae", ["plant-leaves"], "worldwide", "microscopic",
        ["powdery-mildew"], None, "Q193459"),
    ("rust-fungus", "Pucciniales", "Pucciniaceae", ["plant-leaves"], "worldwide", "microscopic",
        None, None, "Q193459"),
    ("smut-fungus", "Ustilaginales", "Ustilaginaceae", ["grain"], "worldwide", "microscopic",
        None, None, "Q193459"),
    ("cordyceps", "Ophiocordyceps sinensis", "Ophiocordycipitaceae", ["insect-host"], "himalaya", "tiny",
        None, ["medicinal"], "Q193459"),
    ("yeast", "Saccharomyces cerevisiae", "Saccharomycetaceae", ["fermentation"], "worldwide", "microscopic",
        ["brewers-yeast", "bakers-yeast"], ["bread", "beer", "wine"], "Q193459"),
    ("baker-s-yeast", "Saccharomyces cerevisiae", "Saccharomycetaceae", ["kitchen"], "worldwide", "microscopic",
        None, ["bread"], "Q193459"),
    ("brewer-s-yeast", "Saccharomyces cerevisiae", "Saccharomycetaceae", ["brewery"], "worldwide", "microscopic",
        None, ["beer"], "Q193459"),
    ("candida", "Candida albicans", "Saccharomycetaceae", ["mammal"], "worldwide", "microscopic",
        None, None, "Q193459"),
    ("slime-mold", "Physarum polycephalum", None, ["forest-floor", "log"], "worldwide", "small",
        None, ["distributed-intelligence"], "Q193459"),
]

for e in FUNGI:
    NODES.append(fun(e[0], e[1], e[2], e[3], e[4], e[5], syns=e[6], used=e[7], qid=e[8]))
