"""Weather + atmospheric phenomena. ~120-180 nodes."""

from _helpers import node, wikidata, authored


def wx(canonical, phen_scale=None, seasons=None, tod=None, syns=None,
       used=None, sensory=None, qid=None):
    return node(canonical, "weather",
                synonyms=syns or [],
                phenomenon_scale=phen_scale or [],
                season=seasons,
                time_of_day=tod,
                used_for=used,
                sensory_signatures=sensory,
                kid_friendly=True,
                provenance=[wikidata(qid)] if qid else [authored()])


def ph(canonical, phen_scale=None, seasons=None, tod=None, syns=None,
       sensory=None, qid=None):
    return node(canonical, "phenomenon",
                synonyms=syns or [],
                phenomenon_scale=phen_scale or [],
                season=seasons, time_of_day=tod,
                sensory_signatures=sensory,
                kid_friendly=True,
                provenance=[wikidata(qid)] if qid else [authored()])


NODES = []

# Precipitation
NODES += [
    wx("rain", ["local", "regional"], syns=["rainfall", "shower"],
       sensory=["petrichor", "patter", "cool"], qid="Q7925"),
    wx("drizzle", ["local"], syns=["mist-rain", "sprinkle"],
       sensory=["fine-mist"], qid="Q193459"),
    wx("shower", ["local", "momentary"], syns=["rain-shower"],
       sensory=["brief-rain"], qid="Q193459"),
    wx("downpour", ["local", "momentary"], syns=["deluge", "cloudburst"],
       sensory=["torrent", "loud"], qid="Q193459"),
    wx("thunderstorm", ["local", "regional", "momentary"],
       seasons=["summer"], syns=["storm"],
       sensory=["thunder", "lightning", "rain"], qid="Q31708"),
    wx("hail", ["local", "momentary"], syns=["hailstorm"],
       sensory=["clatter-on-roof", "ice-pellets"], qid="Q37602"),
    wx("sleet", ["local"], seasons=["winter"], syns=["ice-pellets", "graupel"],
       sensory=["stinging"], qid="Q193459"),
    wx("snow", ["local", "regional"], seasons=["winter"], syns=["snowfall"],
       sensory=["quiet", "cold", "white"], qid="Q7561"),
    wx("blizzard", ["regional", "momentary"], seasons=["winter"],
       syns=["snowstorm"],
       sensory=["whiteout", "howling-wind"], qid="Q193459"),
    wx("snow-flurry", ["local", "momentary"], seasons=["winter"],
       syns=["flurry"], sensory=["light-snow"], qid="Q193459"),
    wx("freezing-rain", ["local"], seasons=["winter"],
       syns=["glaze", "ice-storm"],
       sensory=["glassy-coating"], qid="Q193459"),
    wx("ice-storm", ["regional"], seasons=["winter"],
       syns=["freezing-rain-event"],
       sensory=["cracking-branches", "shimmer"], qid="Q193459"),
    wx("graupel", ["local", "momentary"], seasons=["winter"],
       syns=["soft-hail", "snow-pellets"], qid="Q193459"),
]

# Clouds + fog
NODES += [
    wx("cloud", ["local", "regional"], syns=["cloudiness"],
       sensory=["overcast"], qid="Q8074"),
    wx("cumulus", ["local"], syns=["fair-weather-cloud", "cotton-cloud"],
       qid="Q193459"),
    wx("cumulonimbus", ["local", "regional"], syns=["thundercloud", "storm-cloud"],
       qid="Q193459"),
    wx("cirrus", ["regional"], syns=["mare-s-tail", "wispy-cloud"],
       qid="Q193459"),
    wx("stratus", ["regional"], syns=["overcast-layer"],
       qid="Q193459"),
    wx("nimbostratus", ["regional"], syns=["rain-cloud"],
       qid="Q193459"),
    wx("altocumulus", ["regional"], syns=["mackerel-sky"],
       qid="Q193459"),
    wx("altostratus", ["regional"],
       qid="Q193459"),
    wx("lenticular-cloud", ["local"], syns=["ufo-cloud", "mountain-wave-cloud"],
       qid="Q193459"),
    wx("mammatus", ["local"], syns=["pouch-cloud"],
       qid="Q193459"),
    wx("noctilucent-cloud", ["regional"], syns=["night-shining-cloud"],
       tod=["night", "twilight"], qid="Q193459"),
    wx("fog", ["local"], tod=["morning", "night"],
       syns=["mist", "haze"], sensory=["damp", "quiet"], qid="Q184491"),
    wx("mist", ["local"], syns=["light-fog", "haze"],
       sensory=["soft-light"], qid="Q193459"),
    wx("haze", ["regional"], syns=["atmospheric-haze"],
       sensory=["muted-distance"], qid="Q193459"),
    wx("smog", ["regional"], syns=["air-pollution"],
       sensory=["irritating"], qid="Q193459"),
]

# Wind + storms
NODES += [
    wx("wind", ["local", "regional"], syns=["breeze", "gust"],
       sensory=["rustling"], qid="Q8094"),
    wx("breeze", ["local"], syns=["gentle-wind"],
       sensory=["cooling"], qid="Q193459"),
    wx("gust", ["local", "momentary"], syns=["wind-gust"],
       qid="Q193459"),
    wx("gale", ["regional"], syns=["strong-wind"],
       qid="Q193459"),
    wx("hurricane", ["regional", "seasonal"], seasons=["summer", "autumn"],
       syns=["tropical-cyclone"],
       sensory=["destructive", "sustained-wind"], qid="Q193459"),
    wx("typhoon", ["regional", "seasonal"], seasons=["summer", "autumn"],
       syns=["pacific-hurricane"],
       qid="Q193459"),
    wx("cyclone", ["regional", "seasonal"], syns=["tropical-cyclone"],
       qid="Q193459"),
    wx("tornado", ["local", "momentary"], seasons=["spring", "summer"],
       syns=["twister", "funnel-cloud"],
       sensory=["freight-train-roar"], qid="Q193459"),
    wx("waterspout", ["local", "momentary"], syns=["water-tornado"],
       qid="Q193459"),
    wx("dust-devil", ["local", "momentary"], syns=["whirlwind", "dust-whirl"],
       qid="Q193459"),
    wx("dust-storm", ["regional"], syns=["sandstorm"],
       sensory=["gritty", "orange-sky"], qid="Q193459"),
    wx("haboob", ["regional"], seasons=["summer"], syns=["desert-dust-wall"],
       sensory=["wall-of-sand"], qid="Q193459"),
    wx("sandstorm", ["regional"], syns=["sand-storm"],
       qid="Q193459"),
    wx("chinook", ["regional"], syns=["snow-eater", "foehn-wind"],
       qid="Q193459"),
    wx("santa-ana-wind", ["regional"], seasons=["autumn"], syns=["devil-wind"],
       qid="Q193459"),
    wx("sirocco", ["regional"], syns=["sahara-wind"],
       qid="Q193459"),
    wx("mistral", ["regional"], syns=["cold-north-wind"],
       qid="Q193459"),
    wx("trade-wind", ["hemispheric"], syns=["trades"],
       qid="Q193459"),
    wx("westerlies", ["hemispheric"], syns=["westerly-winds"],
       qid="Q193459"),
    wx("jet-stream", ["hemispheric"], syns=["upper-atmosphere-current"],
       qid="Q193459"),
    wx("polar-vortex", ["hemispheric"], seasons=["winter"], syns=["polar-cyclone"],
       qid="Q193459"),
    wx("nor-easter", ["regional"], seasons=["winter"], syns=["nor-easter-storm"],
       qid="Q193459"),
    wx("monsoon", ["regional", "seasonal"], seasons=["monsoon"],
       syns=["rainy-season"],
       sensory=["torrential-rain"], qid="Q193459"),
    wx("derecho", ["regional", "momentary"], syns=["straight-line-wind-storm"],
       qid="Q193459"),
    wx("bomb-cyclone", ["regional"], seasons=["winter"], syns=["explosive-cyclogenesis"],
       qid="Q193459"),
    wx("microburst", ["local", "momentary"], syns=["downburst"],
       qid="Q193459"),
    wx("squall", ["local", "momentary"], syns=["sudden-wind-and-rain"],
       qid="Q193459"),
    wx("squall-line", ["regional"], syns=["storm-line"],
       qid="Q193459"),
]

# Sky + atmospheric optical
NODES += [
    ph("rainbow", ["local", "momentary"], syns=["arc-in-the-sky"],
       sensory=["prismatic"], qid="Q4290"),
    ph("double-rainbow", ["local", "momentary"], syns=["secondary-rainbow"],
       qid="Q193459"),
    ph("moonbow", ["local", "momentary"], tod=["night"], syns=["lunar-rainbow"],
       qid="Q193459"),
    ph("halo", ["local"], syns=["sun-halo", "moon-halo"],
       sensory=["ring-around-sun"], qid="Q193459"),
    ph("sun-dog", ["local"], syns=["parhelion", "mock-sun"],
       qid="Q193459"),
    ph("crepuscular-rays", ["local"], tod=["dawn", "dusk"], syns=["sun-rays", "god-rays"],
       qid="Q193459"),
    ph("green-flash", ["local", "momentary"], tod=["sunset"],
       syns=["green-ray"], qid="Q193459"),
    ph("aurora", ["hemispheric"], tod=["night"],
       syns=["northern-lights", "southern-lights", "aurora-borealis", "aurora-australis"],
       sensory=["shimmering-curtains"], qid="Q193459"),
    ph("mirage", ["local", "momentary"], syns=["heat-shimmer", "fata-morgana"],
       sensory=["distortion"], qid="Q193459"),
    ph("brocken-spectre", ["local"], syns=["mountain-ghost"],
       qid="Q193459"),
    ph("iridescent-cloud", ["local"], syns=["cloud-iridescence"],
       qid="Q193459"),
    ph("nacreous-cloud", ["regional"], syns=["mother-of-pearl-cloud"],
       qid="Q193459"),
    ph("noctilucent-glow", ["regional"], tod=["twilight"],
       syns=["night-shining"], qid="Q193459"),
    ph("lightning", ["local", "momentary"], syns=["thunderbolt"],
       sensory=["blinding-flash", "afterimage"], qid="Q7817"),
    ph("thunder", ["local", "momentary"], syns=["thunderclap", "rumble"],
       sensory=["boom", "reverberation"], qid="Q193459"),
    ph("ball-lightning", ["local", "momentary"], syns=["fireball"],
       qid="Q193459"),
    ph("st-elmo-s-fire", ["local"], syns=["corona-discharge"],
       qid="Q193459"),
    ph("heat-lightning", ["local"], seasons=["summer"], syns=["distant-lightning"],
       qid="Q193459"),
]

# Temperature + humidity
NODES += [
    wx("heat-wave", ["regional"], seasons=["summer"], syns=["extreme-heat"],
       sensory=["oppressive"], qid="Q193459"),
    wx("cold-snap", ["regional"], seasons=["winter"], syns=["cold-wave"],
       sensory=["biting-cold"], qid="Q193459"),
    wx("humidity", ["local", "regional"], syns=["humid-air"],
       sensory=["sticky", "muggy"], qid="Q193459"),
    wx("dew", ["local"], tod=["dawn", "morning"], syns=["morning-dew"],
       sensory=["wet-grass"], qid="Q193459"),
    wx("frost", ["local"], seasons=["autumn", "winter"], tod=["morning"],
       syns=["hoarfrost", "rime"], sensory=["crunch-underfoot"], qid="Q193459"),
    wx("hoarfrost", ["local"], seasons=["winter"], tod=["morning"],
       syns=["frost-crystals"], qid="Q193459"),
    wx("rime-ice", ["local"], seasons=["winter"], syns=["rime"],
       qid="Q193459"),
    wx("black-ice", ["local"], seasons=["winter"], syns=["invisible-ice"],
       sensory=["treacherous"], qid="Q193459"),
    wx("permafrost", ["regional"], syns=["frozen-ground"],
       qid="Q193459"),
    wx("indian-summer", ["regional"], seasons=["autumn"], syns=["late-warm-spell"],
       qid="Q193459"),
]

# Water phenomena
NODES += [
    wx("flood", ["local", "regional"], syns=["flooding", "inundation"],
       qid="Q193459"),
    wx("flash-flood", ["local", "momentary"], syns=["sudden-flood"],
       qid="Q193459"),
    wx("drought", ["regional"], syns=["dry-spell", "water-shortage"],
       qid="Q193459"),
    wx("king-tide", ["local", "cyclical"], syns=["perigean-tide"],
       qid="Q193459"),
    wx("storm-surge", ["regional"], syns=["hurricane-surge"],
       qid="Q193459"),
    wx("tide", ["cyclical"], syns=["ocean-tide"],
       sensory=["rising-falling-water"], qid="Q193459"),
    wx("high-tide", ["cyclical"], syns=["flood-tide"],
       qid="Q193459"),
    wx("low-tide", ["cyclical"], syns=["ebb-tide"],
       qid="Q193459"),
    wx("neap-tide", ["cyclical"], syns=["low-range-tide"],
       qid="Q193459"),
    wx("spring-tide", ["cyclical"], syns=["high-range-tide"],
       qid="Q193459"),
    wx("tsunami", ["regional", "rare"], syns=["tidal-wave", "seismic-sea-wave"],
       qid="Q193459"),
    wx("rogue-wave", ["local", "momentary"], syns=["freak-wave", "monster-wave"],
       qid="Q193459"),
    wx("waterspout-marine", ["local"], syns=["ocean-waterspout"],
       qid="Q193459"),
]

# Fire-related weather
NODES += [
    ph("wildfire", ["regional", "seasonal"], seasons=["fire-season", "dry-season"],
       syns=["forest-fire", "bushfire", "brush-fire"],
       sensory=["smoke", "roar"], qid="Q193459"),
    ph("firestorm", ["regional"], syns=["fire-tornado"],
       qid="Q193459"),
    ph("fire-whirl", ["local"], syns=["fire-devil", "fire-tornado"],
       qid="Q193459"),
    ph("volcanic-ash", ["regional"], syns=["ashfall"],
       sensory=["gritty"], qid="Q193459"),
    ph("smoke-plume", ["regional"], syns=["fire-plume"],
       qid="Q193459"),
]

# Seismic + geo
NODES += [
    ph("earthquake", ["regional", "momentary"], syns=["tremor", "quake", "temblor"],
       sensory=["shaking", "roar"], qid="Q7944"),
    ph("aftershock", ["local", "momentary"], syns=["earthquake-aftershock"],
       qid="Q193459"),
    ph("volcanic-eruption", ["regional", "rare"], syns=["eruption"],
       sensory=["ash", "lava-glow"], qid="Q193459"),
    ph("lava-flow", ["local"], syns=["molten-rock-stream"],
       qid="Q193459"),
    ph("pyroclastic-flow", ["regional", "momentary"], syns=["nuee-ardente"],
       qid="Q193459"),
    ph("landslide", ["local", "momentary"], syns=["landfall", "avalanche"],
       qid="Q193459"),
    ph("mudslide", ["local"], syns=["mudflow", "debris-flow"],
       qid="Q193459"),
    ph("rockslide", ["local", "momentary"], syns=["rockfall"],
       qid="Q193459"),
    ph("avalanche", ["local", "momentary"], seasons=["winter"], syns=["snow-avalanche"],
       qid="Q193459"),
    ph("sinkhole", ["local"], syns=["cenote", "doline"],
       qid="Q193459"),
    ph("geyser", ["local"], syns=["thermal-fountain"],
       sensory=["steam", "sulfur-smell"], qid="Q193459"),
    ph("fumarole", ["local"], syns=["steam-vent"],
       qid="Q193459"),
    ph("hot-spring", ["local"], syns=["thermal-spring"],
       qid="Q193459"),
    ph("mud-pot", ["local"], syns=["mudpot", "boiling-mud"],
       qid="Q193459"),
    ph("solfatara", ["local"], syns=["sulfur-vent"],
       qid="Q193459"),
]

# Atmospheric misc
NODES += [
    ph("pollen-cloud", ["regional", "seasonal"], seasons=["spring"], syns=["pollen-plume"],
       qid="Q193459"),
    ph("smoke", ["local"], syns=["woodsmoke"], sensory=["acrid"], qid="Q193459"),
    ph("dust", ["local"], syns=["airborne-dust"], qid="Q193459"),
    ph("pollen", ["local", "seasonal"], seasons=["spring", "summer"], syns=["plant-pollen"],
       qid="Q193459"),
    ph("mist-marine", ["local"], syns=["sea-mist", "sea-smoke"], qid="Q193459"),
    ph("virga", ["local"], syns=["fallstreak", "phantom-rain"],
       qid="Q193459"),
    ph("cloud-shadow", ["local", "momentary"], syns=["shadow-under-cloud"],
       qid="Q193459"),
    ph("rainshaft", ["local"], syns=["rain-column"],
       qid="Q193459"),
]

# Season transitions / weather patterns
NODES += [
    ph("el-nino", ["hemispheric", "cyclical"], syns=["enso-warm-phase"],
       qid="Q193459"),
    ph("la-nina", ["hemispheric", "cyclical"], syns=["enso-cool-phase"],
       qid="Q193459"),
    ph("madden-julian-oscillation", ["hemispheric", "cyclical"], syns=["mjo"],
       qid="Q193459"),
    ph("arctic-oscillation", ["hemispheric", "cyclical"], syns=["ao"],
       qid="Q193459"),
    ph("north-atlantic-oscillation", ["hemispheric", "cyclical"], syns=["nao"],
       qid="Q193459"),
]
