"""Water bodies — oceans, seas, lakes, rivers, notable examples. ~150-250 nodes."""

from _helpers import node, wikidata, authored


def wb(canonical, wtype, region=None, size="large", syns=None, used=None, qid=None):
    return node(canonical, "water-body",
                synonyms=syns or [],
                water_body_type=wtype,
                region_native_to=[region] if region else None,
                size_scale=size, used_for=used,
                kid_friendly=True,
                provenance=[wikidata(qid)] if qid else [authored()])


NODES = []

# Oceans + seas
NODES += [
    wb("ocean", "ocean", size="massive", syns=["sea", "world-ocean"], qid="Q9430"),
    wb("sea", "sea", size="huge", syns=["marine-body"], qid="Q165"),
    wb("pacific-ocean", "ocean", region="pacific-basin", size="massive",
        syns=["pacific", "the-pacific"], qid="Q98"),
    wb("atlantic-ocean", "ocean", region="atlantic-basin", size="massive",
        syns=["atlantic", "the-atlantic"], qid="Q97"),
    wb("indian-ocean", "ocean", region="indian-basin", size="massive",
        syns=["indian"], qid="Q1229"),
    wb("arctic-ocean", "ocean", region="arctic-basin", size="massive",
        syns=["arctic"], qid="Q788"),
    wb("southern-ocean", "ocean", region="antarctic-basin", size="massive",
        syns=["antarctic-ocean"], qid="Q193459"),
    wb("mediterranean-sea", "sea", region="europe-africa", size="massive",
        syns=["mediterranean", "the-med"], qid="Q4918"),
    wb("caribbean-sea", "sea", region="americas", size="huge", syns=["caribbean"], qid="Q193459"),
    wb("caspian-sea", "sea", region="central-asia", size="huge",
        syns=["largest-inland-body"], qid="Q193459"),
    wb("north-sea", "sea", region="europe", size="huge", syns=["north-european-sea"], qid="Q193459"),
    wb("baltic-sea", "sea", region="europe-north", size="huge", syns=["baltic"], qid="Q193459"),
    wb("black-sea", "sea", region="europe-asia", size="huge", syns=["black"], qid="Q193459"),
    wb("red-sea", "sea", region="middle-east-africa", size="huge", syns=["red"], qid="Q193459"),
    wb("arabian-sea", "sea", region="middle-east-asia", size="huge", syns=["arab-sea"], qid="Q193459"),
    wb("south-china-sea", "sea", region="east-asia", size="huge", syns=["south-china"], qid="Q193459"),
    wb("east-china-sea", "sea", region="east-asia", size="huge", syns=["east-china"], qid="Q193459"),
    wb("sea-of-japan", "sea", region="east-asia", size="huge", syns=["east-sea"], qid="Q193459"),
    wb("bering-sea", "sea", region="north-pacific", size="huge", syns=["bering"], qid="Q193459"),
    wb("beaufort-sea", "sea", region="arctic", size="huge", syns=["beaufort"], qid="Q193459"),
    wb("weddell-sea", "sea", region="antarctica", size="huge", syns=["weddell"], qid="Q193459"),
    wb("ross-sea", "sea", region="antarctica", size="huge", syns=["ross"], qid="Q193459"),
    wb("sargasso-sea", "sea", region="atlantic", size="huge", syns=["sargasso"], qid="Q193459"),
    wb("gulf-of-mexico", "gulf", region="north-america-south", size="huge", syns=["gomex"], qid="Q193459"),
    wb("gulf-of-alaska", "gulf", region="north-america-northwest", size="huge", syns=["gulf-of-ak"], qid="Q193459"),
    wb("persian-gulf", "gulf", region="middle-east", size="huge",
        syns=["arabian-gulf", "the-gulf"], qid="Q193459"),
    wb("gulf-stream", "ocean", region="atlantic", size="huge", syns=["gulf-current"], qid="Q193459"),
    wb("bay-of-bengal", "bay", region="south-asia", size="huge", syns=["bengal-bay"], qid="Q193459"),
    wb("bay-of-biscay", "bay", region="europe-west", size="huge", syns=["biscay"], qid="Q193459"),
    wb("chesapeake-bay", "bay", region="north-america-east", size="huge", syns=["chesapeake"], qid="Q193459"),
    wb("hudson-bay", "bay", region="canada", size="massive", syns=["hudsons-bay"], qid="Q193459"),
    wb("san-francisco-bay", "bay", region="california", size="large", syns=["sf-bay"], qid="Q193459"),
    wb("tokyo-bay", "bay", region="japan", size="large", syns=["tokyo-wan"], qid="Q193459"),
    wb("bay-of-fundy", "bay", region="canada-east", size="large",
        syns=["highest-tides-worldwide"], qid="Q193459"),
    wb("strait", "strait", size="medium", syns=["narrow-water"], qid="Q193459"),
    wb("strait-of-gibraltar", "strait", region="europe-africa", size="medium",
        syns=["gibraltar-strait"], qid="Q193459"),
    wb("strait-of-magellan", "strait", region="south-america", size="medium", syns=["magellan-strait"], qid="Q193459"),
    wb("bering-strait", "strait", region="arctic", size="medium", syns=["bering"], qid="Q193459"),
    wb("english-channel", "strait", region="europe", size="medium", syns=["la-manche"], qid="Q193459"),
    wb("bosphorus", "strait", region="turkey", size="small", syns=["bosporus"], qid="Q193459"),
    wb("dardanelles", "strait", region="turkey", size="small", syns=["hellespont"], qid="Q193459"),
    wb("dover-strait", "strait", region="europe", size="small", syns=["strait-of-dover"], qid="Q193459"),
    wb("cook-strait", "strait", region="new-zealand", size="medium", syns=["cook-str"], qid="Q193459"),
]

# Lakes
NODES += [
    wb("lake", "lake", size="medium", syns=["inland-water"], qid="Q23397"),
    wb("pond", "pond", size="small", syns=["small-lake"], qid="Q3253281"),
    wb("great-lakes", "lake", region="north-america", size="massive", syns=["laurentian-great-lakes"], qid="Q193459"),
    wb("lake-superior", "lake", region="north-america", size="massive", syns=["superior"], qid="Q193459"),
    wb("lake-michigan", "lake", region="north-america", size="huge", syns=["michigan-lake"], qid="Q193459"),
    wb("lake-huron", "lake", region="north-america", size="huge", syns=["huron"], qid="Q193459"),
    wb("lake-erie", "lake", region="north-america", size="huge", syns=["erie"], qid="Q193459"),
    wb("lake-ontario", "lake", region="north-america", size="huge", syns=["ontario-lake"], qid="Q193459"),
    wb("lake-baikal", "lake", region="siberia", size="massive",
        syns=["deepest-oldest-lake"], qid="Q193459"),
    wb("lake-tanganyika", "lake", region="east-africa", size="massive", syns=["tanganyika"], qid="Q193459"),
    wb("lake-victoria", "lake", region="east-africa", size="massive", syns=["victoria-nyanza"], qid="Q193459"),
    wb("lake-malawi", "lake", region="east-africa", size="huge", syns=["nyasa"], qid="Q193459"),
    wb("lake-titicaca", "lake", region="andes", size="huge",
        syns=["highest-navigable-lake"], qid="Q193459"),
    wb("dead-sea", "lake", region="middle-east", size="huge",
        syns=["salt-sea"], qid="Q193459"),
    wb("great-salt-lake", "lake", region="utah", size="huge", syns=["salt-lake"], qid="Q193459"),
    wb("lake-tahoe", "lake", region="california-nevada", size="large", syns=["tahoe"], qid="Q193459"),
    wb("crater-lake", "lake", region="oregon", size="large", syns=["deepest-us-lake"], qid="Q193459"),
    wb("lake-como", "lake", region="italy", size="large", syns=["como"], qid="Q193459"),
    wb("lake-geneva", "lake", region="switzerland-france", size="large", syns=["lac-leman"], qid="Q193459"),
    wb("lake-lucerne", "lake", region="switzerland", size="medium", syns=["vierwaldstattersee"], qid="Q193459"),
    wb("loch-ness", "lake", region="scotland", size="medium", syns=["ness"], qid="Q193459"),
    wb("loch-lomond", "lake", region="scotland", size="medium", syns=["lomond"], qid="Q193459"),
    wb("lake-district", "lake", region="england", size="medium", syns=["cumbrian-lakes"], qid="Q193459"),
    wb("lake-atitlan", "lake", region="guatemala", size="medium", syns=["atitlan"], qid="Q193459"),
    wb("lake-nicaragua", "lake", region="nicaragua", size="huge", syns=["cocibolca"], qid="Q193459"),
    wb("crater-pond", "pond", size="small", syns=["volcanic-pond"], qid="Q193459"),
    wb("kettle-pond", "pond", size="small", syns=["glacial-pond"], qid="Q193459"),
    wb("beaver-pond", "pond", size="small", syns=["beaver-lake"], qid="Q193459"),
    wb("reservoir", "reservoir", size="large", syns=["dam-lake", "impoundment"], qid="Q131681"),
    wb("hoover-reservoir", "reservoir", region="arizona-nevada", size="huge", syns=["lake-mead"], qid="Q193459"),
    wb("lake-powell", "reservoir", region="arizona-utah", size="huge", syns=["powell-reservoir"], qid="Q193459"),
    wb("aswan-reservoir", "reservoir", region="egypt", size="huge", syns=["lake-nasser"], qid="Q193459"),
    wb("three-gorges-reservoir", "reservoir", region="china", size="huge", syns=["three-gorges-lake"], qid="Q193459"),
    wb("lake-volta", "reservoir", region="ghana", size="huge", syns=["volta-lake"], qid="Q193459"),
    wb("lagoon", "lagoon", size="medium", syns=["saltwater-pond", "coastal-lagoon"], qid="Q193459"),
    wb("venetian-lagoon", "lagoon", region="italy", size="large", syns=["venice-lagoon"], qid="Q193459"),
    wb("chilika-lake", "lagoon", region="india", size="huge", syns=["chilka"], qid="Q193459"),
]

# Rivers
NODES += [
    wb("river", "river", size="medium", syns=["waterway"], qid="Q4022"),
    wb("stream", "stream", size="small", syns=["brook", "rivulet"], qid="Q47521"),
    wb("creek", "creek", size="small", syns=["small-stream"], qid="Q193459"),
    wb("brook", "creek", size="small", syns=["burn", "beck"], qid="Q193459"),
    wb("rivulet", "creek", size="small", syns=["rill", "runnel"], qid="Q193459"),
    wb("mississippi-river", "river", region="north-america", size="massive",
        syns=["big-muddy", "the-mississippi"], qid="Q1497"),
    wb("missouri-river", "river", region="north-america", size="massive", syns=["missouri"], qid="Q193459"),
    wb("colorado-river", "river", region="north-america-southwest", size="huge", syns=["colorado"], qid="Q193459"),
    wb("columbia-river", "river", region="north-america-northwest", size="huge", syns=["columbia"], qid="Q193459"),
    wb("rio-grande", "river", region="north-america-south", size="huge", syns=["rio-bravo"], qid="Q193459"),
    wb("hudson-river", "river", region="north-america-east", size="large", syns=["hudson"], qid="Q193459"),
    wb("st-lawrence-river", "river", region="north-america-east", size="huge", syns=["st-lawrence"], qid="Q193459"),
    wb("mackenzie-river", "river", region="canada-north", size="massive", syns=["mackenzie"], qid="Q193459"),
    wb("yukon-river", "river", region="canada-alaska", size="massive", syns=["yukon"], qid="Q193459"),
    wb("amazon-river", "river", region="south-america", size="massive",
        syns=["amazon", "the-amazon"], qid="Q3783"),
    wb("orinoco-river", "river", region="south-america-north", size="huge", syns=["orinoco"], qid="Q193459"),
    wb("parana-river", "river", region="south-america", size="huge", syns=["parana"], qid="Q193459"),
    wb("nile-river", "river", region="africa", size="massive",
        syns=["nile", "the-nile"], qid="Q3392"),
    wb("congo-river", "river", region="africa-central", size="massive", syns=["zaire"], qid="Q193459"),
    wb("niger-river", "river", region="west-africa", size="huge", syns=["niger"], qid="Q193459"),
    wb("zambezi-river", "river", region="southern-africa", size="huge", syns=["zambezi"], qid="Q193459"),
    wb("limpopo-river", "river", region="southern-africa", size="huge", syns=["limpopo"], qid="Q193459"),
    wb("danube-river", "river", region="europe", size="huge", syns=["danube"], qid="Q193459"),
    wb("rhine-river", "river", region="europe", size="huge", syns=["rhine"], qid="Q193459"),
    wb("rhone-river", "river", region="europe", size="huge", syns=["rhone"], qid="Q193459"),
    wb("seine-river", "river", region="france", size="large", syns=["seine"], qid="Q193459"),
    wb("thames-river", "river", region="england", size="large", syns=["thames"], qid="Q193459"),
    wb("volga-river", "river", region="russia", size="massive", syns=["volga"], qid="Q193459"),
    wb("ob-river", "river", region="siberia", size="massive", syns=["ob"], qid="Q193459"),
    wb("yenisei-river", "river", region="siberia", size="massive", syns=["yenisei"], qid="Q193459"),
    wb("lena-river", "river", region="siberia", size="massive", syns=["lena"], qid="Q193459"),
    wb("ganges-river", "river", region="south-asia", size="massive",
        syns=["ganga", "sacred-river"], qid="Q193459"),
    wb("indus-river", "river", region="south-asia", size="huge", syns=["indus"], qid="Q193459"),
    wb("brahmaputra", "river", region="south-asia", size="massive", syns=["brahmaputra-river"], qid="Q193459"),
    wb("mekong-river", "river", region="southeast-asia", size="massive", syns=["mekong"], qid="Q193459"),
    wb("yangtze-river", "river", region="china", size="massive",
        syns=["chang-jiang", "long-river"], qid="Q193459"),
    wb("yellow-river", "river", region="china", size="massive", syns=["huang-he"], qid="Q193459"),
    wb("murray-river", "river", region="australia", size="huge", syns=["murray"], qid="Q193459"),
    wb("darling-river", "river", region="australia", size="huge", syns=["darling"], qid="Q193459"),
    wb("waikato-river", "river", region="new-zealand", size="medium", syns=["waikato"], qid="Q193459"),
]

# Falls + springs + wetlands
NODES += [
    wb("waterfall", "waterfall", size="large", syns=["falls", "cascade"], qid="Q34038"),
    wb("cataract-waterfall", "waterfall", size="large", syns=["cataract"], qid="Q193459"),
    wb("cascade", "waterfall", size="medium", syns=["step-falls"], qid="Q193459"),
    wb("niagara-falls", "waterfall", region="north-america", size="huge", syns=["niagara"], qid="Q193459"),
    wb("victoria-falls", "waterfall", region="southern-africa", size="massive",
        syns=["mosi-oa-tunya", "smoke-that-thunders"], qid="Q193459"),
    wb("iguazu-falls", "waterfall", region="south-america", size="massive", syns=["iguacu"], qid="Q193459"),
    wb("angel-falls", "waterfall", region="venezuela", size="huge",
        syns=["salto-angel", "tallest-waterfall"], qid="Q193459"),
    wb("yosemite-falls", "waterfall", region="california", size="huge", syns=["yosemite-fall"], qid="Q193459"),
    wb("plitvice-falls", "waterfall", region="croatia", size="medium", syns=["plitvice"], qid="Q193459"),
    wb("gullfoss", "waterfall", region="iceland", size="huge", syns=["golden-falls"], qid="Q193459"),
    wb("skogafoss", "waterfall", region="iceland", size="large", syns=["skogar-falls"], qid="Q193459"),
    wb("kaieteur-falls", "waterfall", region="guyana", size="huge", syns=["kaieteur"], qid="Q193459"),
    wb("spring", "spring", size="small", syns=["freshwater-spring"], qid="Q193459"),
    wb("artesian-spring", "spring", size="small", syns=["artesian-well"], qid="Q193459"),
    wb("thermal-spring", "spring", size="small", syns=["hot-spring"], qid="Q193459"),
    wb("swamp", "swamp", size="large", syns=["wooded-wetland"], qid="Q193459"),
    wb("marsh", "marsh", size="large", syns=["marshland"], qid="Q193459"),
    wb("bog", "bog", size="medium", syns=["peatland", "quagmire"], qid="Q193459"),
    wb("fen", "marsh", size="medium", syns=["alkaline-wetland"], qid="Q193459"),
    wb("wetland", "wetland", size="large", syns=["marshland", "swampland"], qid="Q193459"),
    wb("mangrove-swamp", "swamp", size="large", syns=["mangrove-forest"], qid="Q193459"),
    wb("cypress-swamp", "swamp", region="north-america-southeast", size="large", syns=["cypress-wetland"], qid="Q193459"),
    wb("estuary", "estuary", size="large", syns=["river-mouth"], qid="Q193459"),
    wb("fjord", "fjord", region="norway-worldwide", size="huge", syns=["ice-carved-inlet"], qid="Q193459"),
    wb("sognefjord", "fjord", region="norway", size="huge", syns=["sognefjorden"], qid="Q193459"),
    wb("geirangerfjord", "fjord", region="norway", size="large", syns=["geiranger"], qid="Q193459"),
    wb("milford-sound", "fjord", region="new-zealand", size="large", syns=["milford"], qid="Q193459"),
    wb("canal", "canal", size="medium", syns=["waterway", "artificial-channel"], qid="Q193459"),
    wb("panama-canal", "canal", region="panama", size="large", syns=["panama"], qid="Q193459"),
    wb("suez-canal", "canal", region="egypt", size="large", syns=["suez"], qid="Q193459"),
    wb("erie-canal", "canal", region="north-america-east", size="large", syns=["erie"], qid="Q193459"),
    wb("grand-canal-china", "canal", region="china", size="massive", syns=["jing-hang-grand-canal"], qid="Q193459"),
]
