"""Times of day + seasons + cyclic time nodes. ~40-70 nodes."""

from _helpers import node, wikidata, authored


def t(canonical, cat, tod=None, seasons=None, syns=None, sensory=None, qid=None):
    return node(canonical, cat,
                synonyms=syns or [],
                time_of_day_associated=tod or [],
                season=seasons,
                sensory_signatures=sensory,
                kid_friendly=True,
                provenance=[wikidata(qid)] if qid else [authored()])


NODES = []

# Times of day
NODES += [
    t("dawn", "time-of-day", tod=["dawn"],
       syns=["daybreak", "sunup", "first-light", "cockcrow", "aurora"],
       sensory=["cool", "pink-sky", "birdsong-swell"], qid="Q182527"),
    t("sunrise", "time-of-day", tod=["sunrise"],
       syns=["dayspring", "morning-light"],
       sensory=["orange-horizon"], qid="Q193459"),
    t("morning", "time-of-day", tod=["morning"],
       syns=["a-m", "morn", "morningtime"],
       sensory=["fresh", "coffee-smell"], qid="Q193459"),
    t("mid-morning", "time-of-day", tod=["morning"],
       syns=["late-morning"], qid="Q193459"),
    t("noon", "time-of-day", tod=["midday"],
       syns=["midday", "high-noon", "twelve-noon"],
       sensory=["sun-overhead"], qid="Q193459"),
    t("afternoon", "time-of-day", tod=["afternoon"],
       syns=["p-m", "post-meridiem"],
       sensory=["warm", "golden"], qid="Q193459"),
    t("late-afternoon", "time-of-day", tod=["afternoon"],
       syns=["fading-day"], qid="Q193459"),
    t("golden-hour", "time-of-day", tod=["golden-hour"],
       syns=["magic-hour", "golden-light"],
       sensory=["warm-glow"], qid="Q193459"),
    t("evening", "time-of-day", tod=["evening"],
       syns=["eve", "eventide"],
       sensory=["cooling"], qid="Q193459"),
    t("sunset", "time-of-day", tod=["sunset"],
       syns=["sundown", "twilight-hour"],
       sensory=["red-sky", "cricket-song-start"], qid="Q193459"),
    t("dusk", "time-of-day", tod=["dusk"],
       syns=["gloaming", "nightfall", "twilight"],
       sensory=["first-star"], qid="Q193459"),
    t("twilight", "time-of-day", tod=["twilight"],
       syns=["half-light", "afterglow"],
       sensory=["deepening-blue"], qid="Q193459"),
    t("blue-hour", "time-of-day", tod=["blue-hour"],
       syns=["blue-twilight"],
       sensory=["cool-blue-light"], qid="Q193459"),
    t("night", "time-of-day", tod=["night"],
       syns=["nighttime", "nite", "after-dark"],
       sensory=["dark", "quiet"], qid="Q193459"),
    t("midnight", "time-of-day", tod=["midnight"],
       syns=["stroke-of-midnight", "witching-hour"],
       sensory=["still"], qid="Q193459"),
    t("witching-hour", "time-of-day", tod=["midnight", "night"],
       syns=["three-am"], qid="Q193459"),
    t("cockcrow", "time-of-day", tod=["dawn"],
       syns=["cock-crow", "rooster-hour"], qid="Q193459"),
    t("civil-twilight", "time-of-day", tod=["twilight"],
       syns=["civil-dawn", "civil-dusk"], qid="Q193459"),
    t("nautical-twilight", "time-of-day", tod=["twilight"],
       syns=["nautical-dawn"], qid="Q193459"),
    t("astronomical-twilight", "time-of-day", tod=["twilight"],
       syns=["astro-twilight"], qid="Q193459"),
]

# Seasons
NODES += [
    t("spring", "season", seasons=["spring"],
       syns=["springtime", "vernal", "the-spring"],
       sensory=["blossom", "warm-rain", "green"], qid="Q1312"),
    t("summer", "season", seasons=["summer"],
       syns=["summertime", "estival"],
       sensory=["hot", "long-days", "cicada-song"], qid="Q1313"),
    t("autumn", "season", seasons=["autumn"],
       syns=["fall", "the-fall", "autumntime", "harvest-time"],
       sensory=["leaf-fall", "wood-smoke"], qid="Q1314"),
    t("winter", "season", seasons=["winter"],
       syns=["wintertime", "hibernal"],
       sensory=["cold", "quiet-snow"], qid="Q1311"),
    t("dry-season", "season", seasons=["dry-season"],
       syns=["dry"],
       sensory=["parched"], qid="Q193459"),
    t("wet-season", "season", seasons=["wet-season"],
       syns=["rainy-season", "green-season"],
       sensory=["torrential"], qid="Q193459"),
    t("monsoon-season", "season", seasons=["monsoon"],
       syns=["monsoon", "rains"],
       sensory=["heavy-rain"], qid="Q193459"),
    t("cherry-blossom-season", "season", seasons=["cherry-blossom-season", "spring"],
       syns=["hanami", "sakura-season"],
       sensory=["pink-petals-drifting"], qid="Q193459"),
    t("harvest-season", "season", seasons=["harvest-season", "autumn"],
       syns=["harvest-time", "reaping"],
       sensory=["grain-dust", "fruit-smell"], qid="Q193459"),
    t("fire-season", "season", seasons=["fire-season"],
       syns=["wildfire-season"],
       sensory=["smoky-air"], qid="Q193459"),
    t("migration-season", "season", seasons=["migration-season"],
       syns=["bird-migration"],
       sensory=["v-formations-overhead"], qid="Q193459"),
    t("hurricane-season", "season", seasons=["summer", "autumn"],
       syns=["storm-season"], qid="Q193459"),
    t("tornado-season", "season", seasons=["spring", "summer"],
       syns=["twister-season"], qid="Q193459"),
    t("mud-season", "season", seasons=["spring"],
       syns=["thaw-season"], qid="Q193459"),
    t("indian-summer-season", "season", seasons=["autumn"],
       syns=["late-warm-spell", "old-woman-summer"], qid="Q193459"),
    t("shoulder-season", "season",
       syns=["off-peak"], qid="Q193459"),
    t("high-season", "season",
       syns=["peak-season"], qid="Q193459"),
    t("low-season", "season",
       syns=["off-season"], qid="Q193459"),
]

# Solar / astronomical time markers (phenomenon-adjacent but season-related)
NODES += [
    t("solstice", "phenomenon", seasons=["summer", "winter"],
       syns=["longest-shortest-day"], qid="Q193459"),
    t("summer-solstice", "phenomenon", seasons=["summer"],
       syns=["midsummer", "longest-day"], qid="Q193459"),
    t("winter-solstice", "phenomenon", seasons=["winter"],
       syns=["midwinter", "shortest-day", "yule"], qid="Q193459"),
    t("equinox", "phenomenon", seasons=["spring", "autumn"],
       syns=["equal-night"], qid="Q193459"),
    t("spring-equinox", "phenomenon", seasons=["spring"],
       syns=["vernal-equinox"], qid="Q193459"),
    t("autumn-equinox", "phenomenon", seasons=["autumn"],
       syns=["fall-equinox", "harvest-equinox"], qid="Q193459"),
    t("midsummer", "phenomenon", seasons=["summer"],
       syns=["midsummer-day", "st-johns-day"], qid="Q193459"),
    t("midwinter", "phenomenon", seasons=["winter"],
       syns=["midwinter-day"], qid="Q193459"),
]
