"""Materials — natural + processed + minerals + elements + substances.
~300-500 nodes with :made-of and :material-for-ref cross-refs to store-objects.
"""

from _helpers import node, wikidata, authored


def mat(canonical, origin=None, forms=None, syns=None, used=None,
        material_for=None, worn_on=None, qid=None, category="material"):
    return node(canonical, category,
                synonyms=syns or [],
                origin_source=origin or [],
                material_form=forms or [],
                used_for=used,
                material_for=material_for,
                worn_on=worn_on,
                kid_friendly=True,
                provenance=[wikidata(qid)] if qid else [authored()])


NODES = []

# ----- Woods -----
WOODS = [
    ("wood", ["plant"], ["solid", "plank", "beam", "block"],
        ["timber", "lumber"], ["furniture", "construction", "firewood"],
        ["furniture", "spoons", "toys"], "Q287"),
    ("oak-wood", ["plant"], ["solid", "plank", "beam"], ["oak-lumber"],
        ["furniture", "flooring", "barrels", "cabinetry"],
        ["furniture", "flooring"], "Q193459"),
    ("pine-wood", ["plant"], ["solid", "plank", "beam"], ["pine-lumber"],
        ["framing", "furniture", "paper-pulp"],
        ["furniture", "framing"], "Q193459"),
    ("maple-wood", ["plant"], ["solid", "plank"], ["maple-lumber"],
        ["flooring", "furniture", "instrument-necks"],
        ["furniture", "flooring", "instruments"], "Q193459"),
    ("cherry-wood", ["plant"], ["solid", "plank"], ["cherry-lumber"],
        ["furniture", "cabinetry"], ["furniture"], "Q193459"),
    ("walnut-wood", ["plant"], ["solid", "plank"], ["walnut-lumber"],
        ["furniture", "gunstocks"], ["furniture"], "Q193459"),
    ("cedar-wood", ["plant"], ["solid", "plank"], ["cedar-lumber"],
        ["closets", "shingles", "chests"], ["storage", "shingles"], "Q193459"),
    ("redwood-timber", ["plant"], ["solid", "plank"], ["redwood-lumber"],
        ["outdoor-decking", "siding"], ["decking"], "Q193459"),
    ("mahogany-wood", ["plant"], ["solid", "plank"], ["mahogany-lumber"],
        ["fine-furniture", "guitars"], ["furniture", "instruments"], "Q193459"),
    ("teak-wood", ["plant"], ["solid", "plank"], ["teak-lumber"],
        ["boats", "outdoor-furniture"], ["furniture", "decking"], "Q193459"),
    ("ebony-wood", ["plant"], ["solid"], ["ebony"],
        ["carving", "piano-keys"], ["instruments"], "Q193459"),
    ("rosewood-timber", ["plant"], ["solid"], ["rosewood"],
        ["fingerboards", "furniture"], ["instruments", "furniture"], "Q193459"),
    ("bamboo-material", ["plant"], ["solid", "rod", "sheet"], ["bamboo-timber"],
        ["scaffolding", "flooring", "utensils"], ["flooring", "utensils"], "Q193459"),
    ("plywood", ["plant", "composite"], ["sheet"], ["ply"],
        ["construction", "furniture-cabinets"], ["furniture", "construction"], "Q193459"),
    ("particleboard", ["plant", "composite"], ["sheet"], ["chipboard"],
        ["low-cost-furniture"], ["furniture"], "Q193459"),
    ("mdf", ["plant", "composite"], ["sheet"], ["medium-density-fiberboard"],
        ["furniture", "cabinets"], ["furniture"], "Q193459"),
    ("cork-material", ["plant"], ["sheet", "block"], ["cork"],
        ["stoppers", "bulletin-boards", "flooring"], ["flooring"], "Q193459"),
    ("charcoal", ["plant"], ["solid", "block"], ["char"],
        ["cooking", "drawing", "filtration"], ["fuel"], "Q193459"),
    ("firewood", ["plant"], ["block"], ["log-fuel"],
        ["heating", "cooking"], None, "Q193459"),
]
for c in WOODS:
    NODES.append(mat(c[0], c[1], c[2], c[3], c[4], material_for=c[5], qid=c[6]))

# ----- Fibers / textiles / animal materials -----
FIBER = [
    ("cotton", ["plant"], ["fiber", "thread", "fabric"], ["cotton-fiber"],
        ["clothing", "sheets", "towels"], ["shirt", "sheet", "towel"], ["torso", "legs"], "Q193459"),
    ("linen", ["plant"], ["fiber", "thread", "fabric"], ["flax-linen"],
        ["shirts", "sheets", "napkins"], ["shirt", "sheet"], ["torso"], "Q193459"),
    ("hemp-fiber", ["plant"], ["fiber", "thread", "fabric"], ["hemp-cloth"],
        ["rope", "clothing", "canvas"], ["rope"], ["torso"], "Q193459"),
    ("jute", ["plant"], ["fiber", "thread"], ["gunny"],
        ["burlap-sacks", "rope"], ["bags"], None, "Q193459"),
    ("sisal", ["plant"], ["fiber"], ["agave-fiber"],
        ["rope", "rugs"], ["rugs"], None, "Q193459"),
    ("silk", ["animal"], ["fiber", "thread", "fabric"], ["silk-thread"],
        ["scarves", "ties", "gowns"], ["scarf", "tie", "shirt"], ["torso", "neck"], "Q193459"),
    ("wool", ["animal"], ["fiber", "thread", "fabric", "fleece"], ["sheep-wool"],
        ["sweaters", "carpets", "felt"], ["sweater", "carpet", "hat"], ["torso", "head"], "Q193459"),
    ("cashmere", ["animal"], ["fiber", "thread", "fabric"], ["cashmere-wool"],
        ["luxury-sweaters"], ["sweater"], ["torso"], "Q193459"),
    ("mohair", ["animal"], ["fiber", "thread"], ["angora-goat-wool"],
        ["sweaters", "upholstery"], ["sweater"], ["torso"], "Q193459"),
    ("angora", ["animal"], ["fiber"], ["angora-rabbit-wool"],
        ["fluffy-sweaters"], ["sweater"], ["torso"], "Q193459"),
    ("alpaca-fiber", ["animal"], ["fiber", "thread"], ["alpaca-wool"],
        ["sweaters", "scarves"], ["sweater", "scarf"], ["torso"], "Q193459"),
    ("llama-fiber", ["animal"], ["fiber"], ["llama-wool"],
        ["blankets", "rope"], None, None, "Q193459"),
    ("vicuna-fiber", ["animal"], ["fiber"], ["vicuna-wool"],
        ["luxury-textiles"], None, ["torso"], "Q193459"),
    ("leather", ["animal"], ["sheet"], ["hide"],
        ["shoes", "belts", "jackets", "wallets"], ["shoe", "belt", "wallet", "jacket"], ["feet", "torso", "hands"], "Q193459"),
    ("suede", ["animal"], ["sheet"], ["napped-leather"],
        ["jackets", "shoes", "boots"], ["shoe", "jacket"], ["feet", "torso"], "Q193459"),
    ("nubuck", ["animal"], ["sheet"], ["sanded-leather"],
        ["shoes", "jackets"], ["shoe"], ["feet"], "Q193459"),
    ("fur", ["animal"], ["fleece", "sheet"], ["animal-fur"],
        ["coats", "hats"], ["coat", "hat"], ["torso", "head"], "Q193459"),
    ("down-fiber", ["animal"], ["fiber", "fleece"], ["duck-down", "goose-down"],
        ["pillows", "comforters", "jackets"], ["pillow", "jacket"], None, "Q193459"),
    ("feather", ["animal"], ["fiber"], ["quill"],
        ["pillows", "hats", "art"], ["pillow"], ["head"], "Q193459"),
    ("horn", ["animal"], ["block", "solid"], ["animal-horn"],
        ["buttons", "combs", "handles"], None, None, "Q193459"),
    ("bone", ["animal"], ["block", "solid"], ["skeletal-material"],
        ["tools", "buttons", "carving"], None, None, "Q193459"),
    ("ivory", ["animal"], ["block"], ["tusk-material"],
        ["carving", "piano-keys"], None, None, "Q193459"),
    ("mother-of-pearl", ["animal"], ["sheet"], ["nacre"],
        ["buttons", "inlay", "jewelry"], ["jewelry"], None, "Q193459"),
    ("pearl", ["animal"], ["solid"], ["cultured-pearl"],
        ["jewelry"], ["jewelry"], ["neck", "wrist"], "Q193459"),
    ("shell-material", ["animal"], ["sheet", "block"], ["seashell"],
        ["decoration", "jewelry"], ["jewelry"], None, "Q193459"),
    ("beeswax", ["animal"], ["solid", "block"], ["wax"],
        ["candles", "polish", "cosmetics"], ["candle"], None, "Q193459"),
    ("honey-material", ["animal"], ["liquid"], ["natural-honey"],
        ["food", "cosmetics"], None, None, "Q193459"),
    ("shellac", ["animal"], ["liquid", "solid"], ["lac-resin"],
        ["finish", "polish"], None, None, "Q193459"),
    ("catgut", ["animal"], ["thread"], ["gut-string"],
        ["strings", "sutures"], ["instruments"], None, "Q193459"),
]
for c in FIBER:
    NODES.append(mat(c[0], c[1], c[2], c[3], c[4], material_for=c[5], worn_on=c[6], qid=c[7]))

# ----- Synthetic + polymer textiles -----
SYN_TEX = [
    ("polyester", ["synthetic", "petroleum"], ["fiber", "thread", "fabric"],
        ["poly"], ["clothing", "bottles"], ["shirt", "jacket"], ["torso"], "Q193459"),
    ("nylon", ["synthetic", "petroleum"], ["fiber", "thread", "fabric"],
        ["polyamide"], ["stockings", "rope", "toothbrushes"], ["stockings"], ["legs"], "Q193459"),
    ("spandex", ["synthetic", "petroleum"], ["fiber", "fabric"],
        ["lycra", "elastane"], ["stretch-clothing"], ["leggings"], ["legs", "torso"], "Q193459"),
    ("rayon", ["plant", "engineered"], ["fiber", "fabric"], ["viscose"],
        ["clothing", "linings"], ["shirt"], ["torso"], "Q193459"),
    ("acrylic-fiber", ["synthetic"], ["fiber", "fabric"], ["acrylic-yarn"],
        ["sweaters", "blankets"], ["sweater"], ["torso"], "Q193459"),
    ("polar-fleece", ["synthetic", "petroleum"], ["fabric", "fleece"], ["fleece"],
        ["jackets", "blankets"], ["jacket"], ["torso"], "Q193459"),
    ("kevlar", ["synthetic"], ["fiber", "fabric"], ["aramid"],
        ["body-armor", "ropes"], None, None, "Q193459"),
    ("nomex", ["synthetic"], ["fiber", "fabric"], ["aramid-fire-resistant"],
        ["firefighter-gear"], None, None, "Q193459"),
    ("gore-tex-fabric", ["synthetic"], ["fabric"], ["ptfe-membrane-fabric"],
        ["outdoor-jackets", "shoes"], ["jacket"], ["torso"], "Q193459"),
    ("felt", ["animal", "synthetic"], ["fabric", "sheet"], ["felted-material"],
        ["hats", "crafts"], ["hat"], ["head"], "Q193459"),
    ("canvas", ["plant", "synthetic"], ["fabric", "sheet"], ["heavy-cotton"],
        ["bags", "tents", "shoes", "art-canvases"], ["bag", "tent", "shoe"], ["feet"], "Q193459"),
    ("denim", ["plant"], ["fabric"], ["blue-jean-cloth"],
        ["jeans", "jackets"], ["jeans", "jacket"], ["legs", "torso"], "Q193459"),
    ("velvet", ["plant", "synthetic"], ["fabric"], ["luxury-pile-fabric"],
        ["clothing", "upholstery"], ["jacket", "sofa"], None, "Q193459"),
    ("corduroy", ["plant"], ["fabric"], ["ribbed-cotton"],
        ["pants", "jackets"], ["pants"], ["legs"], "Q193459"),
    ("flannel", ["plant", "animal"], ["fabric"], ["flannel-cloth"],
        ["shirts", "pajamas", "sheets"], ["shirt", "sheet"], ["torso"], "Q193459"),
    ("chiffon", ["synthetic"], ["fabric"], ["sheer-fabric"],
        ["dresses", "scarves"], ["dress"], ["torso"], "Q193459"),
    ("satin", ["synthetic", "animal"], ["fabric"], ["glossy-fabric"],
        ["dresses", "linings"], ["dress"], ["torso"], "Q193459"),
    ("tweed", ["animal"], ["fabric"], ["wool-tweed"],
        ["jackets", "hats"], ["jacket", "hat"], ["torso", "head"], "Q193459"),
    ("burlap", ["plant"], ["fabric"], ["hessian"],
        ["sacks", "landscaping"], ["bag"], None, "Q193459"),
]
for c in SYN_TEX:
    NODES.append(mat(c[0], c[1], c[2], c[3], c[4], material_for=c[5], worn_on=c[6], qid=c[7]))

# ----- Metals -----
METAL = [
    ("iron", ["mineral"], ["ingot", "solid", "ore"], ["fe"],
        ["tools", "construction", "cookware"], None, "Q677"),
    ("steel", ["mineral", "synthetic"], ["ingot", "beam", "sheet", "rod"], ["mild-steel", "carbon-steel"],
        ["construction", "tools", "cars"], ["car", "tool", "beam"], "Q11427"),
    ("stainless-steel", ["mineral", "synthetic"], ["sheet", "solid"], ["ss"],
        ["kitchen", "surgical-tools", "sinks"], ["cookware", "sink"], "Q193459"),
    ("cast-iron", ["mineral"], ["solid", "block"], ["cast-iron-material"],
        ["cookware", "stoves", "pans"], ["cookware"], "Q193459"),
    ("wrought-iron", ["mineral"], ["rod", "beam"], ["forged-iron"],
        ["fences", "gates", "railings"], ["fence"], "Q193459"),
    ("aluminum", ["mineral"], ["sheet", "ingot", "rod"], ["aluminium"],
        ["foil", "cans", "aircraft"], ["can", "foil"], "Q193459"),
    ("copper", ["mineral"], ["sheet", "rod", "ingot"], ["cu"],
        ["wiring", "pipes", "cookware"], ["pipe", "wire"], "Q193459"),
    ("brass", ["mineral", "synthetic"], ["sheet", "rod"], ["copper-zinc-alloy"],
        ["instruments", "fittings", "decor"], ["instruments", "fittings"], "Q193459"),
    ("bronze", ["mineral", "synthetic"], ["ingot", "solid"], ["copper-tin-alloy"],
        ["sculpture", "bells", "bearings"], ["sculpture", "bells"], "Q193459"),
    ("tin", ["mineral"], ["sheet", "solid"], ["sn"],
        ["cans", "solder", "pewter"], None, "Q193459"),
    ("zinc", ["mineral"], ["sheet", "ingot"], ["zn"],
        ["galvanizing", "batteries"], None, "Q193459"),
    ("lead", ["mineral"], ["ingot", "sheet"], ["pb"],
        ["batteries", "shielding"], None, "Q193459"),
    ("nickel", ["mineral"], ["sheet"], ["ni"],
        ["coins", "plating"], None, "Q193459"),
    ("chromium", ["mineral"], ["sheet"], ["cr"],
        ["plating", "stainless-steel"], None, "Q193459"),
    ("titanium", ["mineral"], ["sheet", "rod"], ["ti"],
        ["aerospace", "medical-implants"], None, "Q193459"),
    ("magnesium", ["mineral"], ["ingot"], ["mg"],
        ["alloys", "flares"], None, "Q193459"),
    ("gold", ["mineral"], ["ingot", "sheet"], ["au"],
        ["jewelry", "electronics"], ["jewelry"], "Q193459"),
    ("silver", ["mineral"], ["ingot", "sheet"], ["ag"],
        ["jewelry", "silverware", "photography"], ["jewelry", "silverware"], "Q193459"),
    ("platinum", ["mineral"], ["ingot"], ["pt"],
        ["jewelry", "catalysts"], ["jewelry"], "Q193459"),
    ("mercury-metal", ["mineral"], ["liquid"], ["quicksilver"],
        ["thermometers-historic"], None, "Q193459"),
    ("tungsten", ["mineral"], ["rod", "ingot"], ["wolfram"],
        ["light-bulb-filaments", "cutting-tools"], None, "Q193459"),
    ("cobalt", ["mineral"], ["ingot"], ["co"],
        ["batteries", "blue-pigment"], None, "Q193459"),
    ("uranium", ["mineral"], ["ingot"], ["u"],
        ["nuclear-fuel"], None, "Q193459"),
    ("solder", ["mineral", "synthetic"], ["rod", "wire"], ["tin-lead-solder"],
        ["electronics", "plumbing"], None, "Q193459"),
    ("pewter", ["mineral", "synthetic"], ["ingot"], ["tin-alloy"],
        ["mugs", "figurines"], None, "Q193459"),
    ("sterling-silver", ["mineral", "synthetic"], ["sheet", "solid"], ["925-silver"],
        ["jewelry", "flatware"], ["jewelry"], "Q193459"),
]
for c in METAL:
    NODES.append(mat(c[0], c[1], c[2], c[3], c[4], material_for=c[5], qid=c[6]))

# ----- Ceramics, glass, stone, concrete -----
CERAM = [
    ("clay", ["mineral"], ["solid", "powder"], ["potters-clay"],
        ["pottery", "bricks", "sculpture"], ["pottery", "brick"], "Q42302"),
    ("ceramic", ["mineral"], ["solid"], ["fired-clay"],
        ["dishes", "tiles", "vases"], ["dish", "tile"], "Q45621"),
    ("porcelain", ["mineral"], ["solid"], ["china"],
        ["fine-china", "sinks", "toilets"], ["dish"], "Q193459"),
    ("stoneware", ["mineral"], ["solid"], ["stone-clay"],
        ["dinnerware", "crocks"], ["dish"], "Q193459"),
    ("earthenware", ["mineral"], ["solid"], ["terracotta"],
        ["planters", "tiles"], ["planter"], "Q193459"),
    ("terracotta", ["mineral"], ["solid"], ["baked-clay"],
        ["planters", "roof-tiles"], ["planter"], "Q193459"),
    ("bone-china", ["mineral", "animal"], ["solid"], ["fine-china"],
        ["fine-dinnerware"], ["dish"], "Q193459"),
    ("glass", ["mineral"], ["sheet", "solid"], ["silica-glass"],
        ["windows", "bottles", "art"], ["window", "bottle"], "Q11469"),
    ("crystal", ["mineral"], ["solid"], ["lead-crystal"],
        ["glasses", "chandeliers"], ["glassware"], "Q193459"),
    ("stained-glass", ["mineral"], ["sheet"], ["colored-glass"],
        ["windows", "art"], ["window"], "Q193459"),
    ("frosted-glass", ["mineral"], ["sheet"], ["etched-glass"],
        ["privacy-windows"], None, "Q193459"),
    ("tempered-glass", ["mineral"], ["sheet"], ["safety-glass"],
        ["shower-doors", "phone-screens"], None, "Q193459"),
    ("stone", ["mineral"], ["solid", "block"], ["rock"],
        ["masonry", "sculpture", "construction"], ["construction"], "Q193459"),
    ("granite", ["mineral"], ["solid", "block", "sheet"], ["granite-rock"],
        ["countertops", "monuments", "curbs"], ["countertop"], "Q193459"),
    ("marble", ["mineral"], ["solid", "block", "sheet"], ["marble-stone"],
        ["sculpture", "flooring", "countertops"], ["countertop", "sculpture"], "Q193459"),
    ("slate", ["mineral"], ["sheet"], ["slate-rock"],
        ["roofing", "chalkboards", "flooring"], ["roofing", "floor"], "Q193459"),
    ("limestone", ["mineral"], ["block"], ["ls"],
        ["building", "cement-source"], ["construction"], "Q193459"),
    ("sandstone", ["mineral"], ["block"], ["sandstone-rock"],
        ["building"], ["construction"], "Q193459"),
    ("basalt", ["mineral"], ["block"], ["volcanic-rock"],
        ["road-stone"], None, "Q193459"),
    ("obsidian", ["mineral"], ["solid"], ["volcanic-glass"],
        ["blades", "jewelry"], ["jewelry"], "Q193459"),
    ("pumice", ["mineral"], ["block"], ["volcanic-pumice"],
        ["abrasive", "lightweight-concrete"], None, "Q193459"),
    ("quartz", ["mineral"], ["solid", "crystal"], ["silica"],
        ["watches", "countertops"], ["countertop"], "Q193459"),
    ("flint", ["mineral"], ["solid"], ["knapping-stone"],
        ["fire-starting", "tools"], None, "Q193459"),
    ("gravel", ["mineral"], ["grain"], ["pebbles"],
        ["drainage", "roads"], ["road"], "Q193459"),
    ("sand", ["mineral"], ["grain"], ["silica-sand"],
        ["glass-making", "concrete", "beaches"], ["glass", "concrete"], "Q193459"),
    ("soil", ["mineral", "biological"], ["grain"], ["dirt", "earth"],
        ["gardening", "farming"], None, "Q193459"),
    ("mud", ["mineral", "biological"], ["solid"], ["wet-soil"],
        ["adobe", "clay-mortar"], None, "Q193459"),
    ("concrete", ["mineral", "synthetic"], ["block", "solid"], ["cement-mix"],
        ["buildings", "sidewalks", "bridges"], ["construction"], "Q193459"),
    ("cement", ["mineral", "synthetic"], ["powder"], ["portland-cement"],
        ["binding", "mortar"], ["construction"], "Q193459"),
    ("mortar", ["mineral"], ["solid"], ["masonry-mortar"],
        ["brick-laying"], ["construction"], "Q193459"),
    ("plaster", ["mineral"], ["powder", "solid"], ["gypsum"],
        ["walls", "sculpture"], ["wall"], "Q193459"),
    ("stucco", ["mineral"], ["solid"], ["exterior-plaster"],
        ["exterior-walls"], ["wall"], "Q193459"),
    ("drywall", ["mineral", "synthetic"], ["sheet"], ["gypsum-board", "sheetrock"],
        ["interior-walls"], ["wall"], "Q193459"),
    ("asphalt", ["petroleum"], ["solid"], ["blacktop", "bitumen"],
        ["roads", "roofing"], ["road", "roofing"], "Q193459"),
    ("tar", ["petroleum"], ["liquid", "solid"], ["pitch"],
        ["roofing", "sealing"], None, "Q193459"),
    ("brick", ["mineral"], ["block"], ["clay-brick"],
        ["walls", "chimneys"], ["wall"], "Q193459"),
    ("adobe", ["mineral"], ["block"], ["sun-dried-brick"],
        ["walls"], ["wall"], "Q193459"),
    ("cob", ["mineral"], ["solid"], ["earth-and-straw"],
        ["walls", "traditional-building"], None, "Q193459"),
]
for c in CERAM:
    NODES.append(mat(c[0], c[1], c[2], c[3], c[4], material_for=c[5], qid=c[6]))

# ----- Plastics + rubbers + resins -----
POLY = [
    ("plastic", ["synthetic", "petroleum"], ["solid", "sheet", "block"], ["polymer"],
        ["packaging", "containers", "toys"], ["container", "toy"], "Q11474"),
    ("polyethylene", ["synthetic", "petroleum"], ["sheet", "solid"], ["pe"],
        ["bags", "bottles"], ["bag", "bottle"], "Q193459"),
    ("polypropylene", ["synthetic", "petroleum"], ["solid", "fiber"], ["pp"],
        ["containers", "rope"], ["container"], "Q193459"),
    ("pvc", ["synthetic", "petroleum"], ["solid", "sheet"], ["polyvinyl-chloride"],
        ["pipes", "flooring", "records"], ["pipe"], "Q193459"),
    ("polystyrene", ["synthetic", "petroleum"], ["solid", "foam"], ["ps"],
        ["packaging", "cups"], ["cup"], "Q193459"),
    ("polycarbonate", ["synthetic", "petroleum"], ["sheet"], ["pc"],
        ["eyewear", "cds", "greenhouse-panels"], ["eyewear"], "Q193459"),
    ("acrylic-plastic", ["synthetic", "petroleum"], ["sheet"], ["plexiglass", "perspex"],
        ["signs", "aquariums"], ["sign"], "Q193459"),
    ("teflon", ["synthetic"], ["sheet"], ["ptfe"],
        ["non-stick-pans", "coatings"], ["cookware"], "Q193459"),
    ("silicone-material", ["synthetic"], ["solid", "gel"], ["silicone"],
        ["kitchenware", "sealants", "implants"], ["cookware"], "Q193459"),
    ("epoxy", ["synthetic"], ["liquid", "solid"], ["epoxy-resin"],
        ["adhesive", "coating"], None, "Q193459"),
    ("rubber", ["plant", "synthetic"], ["solid", "sheet"], ["natural-rubber", "latex"],
        ["tires", "gloves", "balloons"], ["tire", "glove"], "Q193459"),
    ("neoprene", ["synthetic"], ["sheet"], ["synthetic-rubber"],
        ["wetsuits", "gaskets"], ["wetsuit"], "Q193459"),
    ("latex", ["plant"], ["liquid", "solid"], ["natural-latex"],
        ["gloves", "mattresses", "balloons"], ["glove"], "Q193459"),
    ("foam-material", ["synthetic"], ["foam"], ["polyfoam"],
        ["cushions", "insulation"], ["cushion"], "Q193459"),
    ("styrofoam", ["synthetic"], ["foam"], ["extruded-polystyrene"],
        ["coolers", "packaging"], ["cooler"], "Q193459"),
    ("resin-natural", ["plant"], ["solid"], ["tree-resin"],
        ["varnish", "incense"], None, "Q193459"),
    ("amber", ["plant"], ["solid"], ["fossilized-resin"],
        ["jewelry"], ["jewelry"], "Q193459"),
    ("gum-arabic", ["plant"], ["solid", "powder"], ["acacia-gum"],
        ["food-thickener", "ink-binder"], None, "Q193459"),
]
for c in POLY:
    NODES.append(mat(c[0], c[1], c[2], c[3], c[4], material_for=c[5], qid=c[6]))

# ----- Paper + pulp -----
PAPER = [
    ("paper", ["plant"], ["sheet"], ["writing-paper"],
        ["writing", "printing", "packaging"], ["book", "packaging"], "Q11472"),
    ("cardboard", ["plant"], ["sheet"], ["corrugated-board"],
        ["boxes", "packaging"], ["box"], "Q193459"),
    ("newsprint", ["plant"], ["sheet"], ["newspaper-paper"],
        ["newspapers"], None, "Q193459"),
    ("tissue-paper", ["plant"], ["sheet"], ["tissue"],
        ["wrapping", "cleaning"], None, "Q193459"),
    ("parchment", ["animal"], ["sheet"], ["vellum"],
        ["historic-manuscripts", "diplomas"], None, "Q193459"),
    ("vellum", ["animal"], ["sheet"], ["fine-parchment"],
        ["historic-manuscripts"], None, "Q193459"),
    ("papyrus-material", ["plant"], ["sheet"], ["ancient-paper"],
        ["ancient-egyptian-writing"], None, "Q193459"),
    ("kraft-paper", ["plant"], ["sheet"], ["brown-paper"],
        ["bags", "wrapping"], None, "Q193459"),
    ("washi", ["plant"], ["sheet"], ["japanese-paper"],
        ["origami", "traditional-crafts"], None, "Q193459"),
]
for c in PAPER:
    NODES.append(mat(c[0], c[1], c[2], c[3], c[4], material_for=c[5], qid=c[6]))

# ----- Elements / atoms (a few kid-recognizable) -----
ELEM = [
    ("hydrogen", ["atmospheric"], ["gas"], ["h", "h2"],
        ["water-component", "fuel"], None, "Q556", "element"),
    ("helium", ["atmospheric"], ["gas"], ["he"],
        ["balloons", "cryogenics"], None, "Q560", "element"),
    ("carbon", ["biological", "geological"], ["solid"], ["c"],
        ["graphite", "diamond", "coal"], None, "Q623", "element"),
    ("nitrogen", ["atmospheric"], ["gas"], ["n2"],
        ["atmosphere", "fertilizer"], None, "Q627", "element"),
    ("oxygen", ["atmospheric"], ["gas"], ["o2"],
        ["breathing", "burning"], None, "Q629", "element"),
    ("sodium", ["mineral"], ["solid"], ["na"],
        ["salt", "streetlights"], None, "Q658", "element"),
    ("magnesium-el", ["mineral"], ["solid"], ["mg"],
        ["flares", "alloys"], None, "Q660", "element"),
    ("aluminum-el", ["mineral"], ["solid"], ["al"],
        ["foil", "cans"], None, "Q663", "element"),
    ("silicon", ["mineral"], ["solid"], ["si"],
        ["glass", "chips"], None, "Q670", "element"),
    ("phosphorus", ["mineral", "biological"], ["solid"], ["p"],
        ["fertilizer", "matches"], None, "Q674", "element"),
    ("sulfur", ["mineral"], ["solid", "powder"], ["s", "sulphur"],
        ["gunpowder", "vulcanization"], None, "Q682", "element"),
    ("chlorine", ["mineral"], ["gas"], ["cl2"],
        ["pool-water", "bleach"], None, "Q688", "element"),
    ("potassium", ["mineral"], ["solid"], ["k"],
        ["fertilizer", "banana-mineral"], None, "Q703", "element"),
    ("calcium", ["mineral"], ["solid"], ["ca"],
        ["bones", "shells"], None, "Q706", "element"),
    ("iron-el", ["mineral"], ["solid"], ["fe-element"],
        ["blood", "steel"], None, "Q677", "element"),
    ("gold-el", ["mineral"], ["solid"], ["au-element"],
        ["jewelry", "electronics"], None, "Q897", "element"),
    ("silver-el", ["mineral"], ["solid"], ["ag-element"],
        ["jewelry", "electronics"], None, "Q1090", "element"),
    ("mercury-el", ["mineral"], ["liquid"], ["hg"],
        ["thermometers"], None, "Q925", "element"),
    ("uranium-el", ["mineral"], ["solid"], ["u-element"],
        ["nuclear"], None, "Q1098", "element"),
]
for c in ELEM:
    NODES.append(mat(c[0], c[1], c[2], c[3], c[4], material_for=c[5], qid=c[6], category=c[7]))

# ----- Minerals + gems (as :mineral category) -----
MIN = [
    ("diamond", ["mineral"], ["crystal"], ["diamond-crystal"],
        ["jewelry", "industrial-cutting"], ["jewelry"], "Q5283", "mineral"),
    ("ruby", ["mineral"], ["crystal"], ["red-corundum"],
        ["jewelry"], ["jewelry"], "Q193459", "mineral"),
    ("sapphire", ["mineral"], ["crystal"], ["corundum"],
        ["jewelry", "watches"], ["jewelry"], "Q193459", "mineral"),
    ("emerald", ["mineral"], ["crystal"], ["green-beryl"],
        ["jewelry"], ["jewelry"], "Q193459", "mineral"),
    ("topaz", ["mineral"], ["crystal"], ["topaz-gem"],
        ["jewelry"], ["jewelry"], "Q193459", "mineral"),
    ("amethyst", ["mineral"], ["crystal"], ["purple-quartz"],
        ["jewelry", "geodes"], ["jewelry"], "Q193459", "mineral"),
    ("citrine", ["mineral"], ["crystal"], ["yellow-quartz"],
        ["jewelry"], ["jewelry"], "Q193459", "mineral"),
    ("opal", ["mineral"], ["solid"], ["precious-opal"],
        ["jewelry"], ["jewelry"], "Q193459", "mineral"),
    ("turquoise", ["mineral"], ["solid"], ["turquoise-stone"],
        ["jewelry"], ["jewelry"], "Q193459", "mineral"),
    ("jade", ["mineral"], ["solid"], ["nephrite", "jadeite"],
        ["jewelry", "carving"], ["jewelry"], "Q193459", "mineral"),
    ("agate", ["mineral"], ["solid"], ["banded-agate"],
        ["jewelry", "decoration"], ["jewelry"], "Q193459", "mineral"),
    ("onyx", ["mineral"], ["solid"], ["black-onyx"],
        ["jewelry"], ["jewelry"], "Q193459", "mineral"),
    ("garnet", ["mineral"], ["crystal"], ["garnet-gem"],
        ["jewelry"], ["jewelry"], "Q193459", "mineral"),
    ("peridot", ["mineral"], ["crystal"], ["olivine"],
        ["jewelry"], ["jewelry"], "Q193459", "mineral"),
    ("aquamarine", ["mineral"], ["crystal"], ["blue-beryl"],
        ["jewelry"], ["jewelry"], "Q193459", "mineral"),
    ("tanzanite", ["mineral"], ["crystal"], ["blue-zoisite"],
        ["jewelry"], ["jewelry"], "Q193459", "mineral"),
    ("moonstone", ["mineral"], ["solid"], ["adularia"],
        ["jewelry"], ["jewelry"], "Q193459", "mineral"),
    ("labradorite", ["mineral"], ["solid"], ["iridescent-feldspar"],
        ["jewelry"], ["jewelry"], "Q193459", "mineral"),
    ("lapis-lazuli", ["mineral"], ["solid"], ["lapis"],
        ["jewelry", "blue-pigment"], ["jewelry"], "Q193459", "mineral"),
    ("malachite", ["mineral"], ["solid"], ["copper-carbonate"],
        ["jewelry", "green-pigment"], ["jewelry"], "Q193459", "mineral"),
    ("hematite", ["mineral"], ["solid"], ["iron-oxide-mineral"],
        ["jewelry", "pigment"], None, "Q193459", "mineral"),
    ("pyrite", ["mineral"], ["crystal"], ["fools-gold"],
        ["collecting"], None, "Q193459", "mineral"),
    ("magnetite", ["mineral"], ["solid"], ["lodestone"],
        ["compasses"], None, "Q193459", "mineral"),
    ("mica", ["mineral"], ["sheet"], ["muscovite"],
        ["insulation", "cosmetics"], None, "Q193459", "mineral"),
    ("talc", ["mineral"], ["powder"], ["talcum"],
        ["baby-powder", "lubricant"], None, "Q193459", "mineral"),
    ("gypsum", ["mineral"], ["solid", "powder"], ["gypsum-rock"],
        ["plaster", "drywall"], None, "Q193459", "mineral"),
    ("halite", ["mineral"], ["crystal"], ["rock-salt"],
        ["salt-mining", "cooking"], None, "Q193459", "mineral"),
    ("calcite", ["mineral"], ["crystal"], ["calcium-carbonate"],
        ["cement", "chalk"], None, "Q193459", "mineral"),
    ("fluorite", ["mineral"], ["crystal"], ["fluorspar"],
        ["glassmaking"], None, "Q193459", "mineral"),
    ("azurite", ["mineral"], ["solid"], ["blue-copper-mineral"],
        ["blue-pigment", "jewelry"], ["jewelry"], "Q193459", "mineral"),
    ("selenite", ["mineral"], ["crystal"], ["gypsum-crystal"],
        ["decoration"], None, "Q193459", "mineral"),
    ("tigers-eye", ["mineral"], ["solid"], ["chatoyant-quartz"],
        ["jewelry"], ["jewelry"], "Q193459", "mineral"),
    ("iron-ore", ["mineral"], ["ore"], ["hematite-magnetite-ore"],
        ["steelmaking"], None, "Q193459", "mineral"),
    ("copper-ore", ["mineral"], ["ore"], ["chalcopyrite"],
        ["copper-production"], None, "Q193459", "mineral"),
    ("bauxite", ["mineral"], ["ore"], ["aluminum-ore"],
        ["aluminum-production"], None, "Q193459", "mineral"),
    ("coal", ["geological"], ["block", "solid"], ["black-coal"],
        ["fuel", "power-plants"], ["fuel"], "Q193459", "mineral"),
    ("anthracite", ["geological"], ["block"], ["hard-coal"],
        ["heating-fuel"], None, "Q193459", "mineral"),
    ("lignite", ["geological"], ["block"], ["brown-coal"],
        ["fuel"], None, "Q193459", "mineral"),
    ("peat", ["biological"], ["block"], ["peat-turf"],
        ["fuel", "gardening"], None, "Q193459", "mineral"),
    ("petroleum-liquid", ["petroleum"], ["liquid"], ["crude-oil", "oil"],
        ["fuel", "plastics"], None, "Q193459", "substance"),
    ("natural-gas", ["atmospheric", "petroleum"], ["gas"], ["methane-mix"],
        ["heating", "cooking"], None, "Q193459", "substance"),
    ("gasoline", ["petroleum"], ["liquid"], ["petrol", "gas"],
        ["fuel"], None, "Q193459", "substance"),
    ("diesel-fuel", ["petroleum"], ["liquid"], ["diesel"],
        ["fuel"], None, "Q193459", "substance"),
    ("kerosene", ["petroleum"], ["liquid"], ["paraffin-fuel"],
        ["lamps", "jet-fuel"], None, "Q193459", "substance"),
    ("propane", ["petroleum"], ["gas"], ["lpg"],
        ["heating", "grilling"], None, "Q193459", "substance"),
    ("water-substance", ["atmospheric", "biological"], ["liquid", "gas"], ["h2o"],
        ["drinking", "washing", "everything"], None, "Q193459", "substance"),
    ("ice", ["atmospheric"], ["solid", "crystal"], ["frozen-water"],
        ["cooling", "sculpture"], None, "Q193459", "substance"),
    ("steam", ["atmospheric"], ["gas"], ["water-vapor"],
        ["heating", "cooking"], None, "Q193459", "substance"),
    ("snow-substance", ["atmospheric"], ["solid"], ["snow-crystal-mass"],
        ["skiing", "packing"], None, "Q193459", "substance"),
    ("salt", ["mineral"], ["crystal", "powder"], ["sodium-chloride"],
        ["food-seasoning", "de-icing"], None, "Q193459", "substance"),
    ("sugar", ["plant"], ["crystal", "powder"], ["sucrose"],
        ["baking", "sweetening"], None, "Q193459", "substance"),
    ("honey-substance", ["animal"], ["liquid"], ["natural-honey"],
        ["food"], None, "Q193459", "substance"),
    ("wax", ["animal", "plant", "synthetic"], ["solid"], ["candle-wax"],
        ["candles", "sealing"], None, "Q193459", "substance"),
    ("chalk", ["mineral"], ["solid", "powder"], ["calcium-chalk"],
        ["writing", "gymnastics"], None, "Q193459", "substance"),
    ("graphite", ["mineral"], ["solid"], ["pencil-lead"],
        ["pencils", "lubricant"], None, "Q193459", "substance"),
    ("charcoal-substance", ["plant"], ["solid"], ["char"],
        ["cooking", "drawing"], None, "Q193459", "substance"),
    ("ash", ["mineral", "plant"], ["powder"], ["cinder"],
        ["fertilizer", "cleanser"], None, "Q193459", "substance"),
    ("soot", ["synthetic"], ["powder"], ["carbon-particulate"],
        ["ink-source-historic"], None, "Q193459", "substance"),
    ("ink", ["plant", "synthetic"], ["liquid"], ["writing-ink"],
        ["writing", "printing"], None, "Q193459", "substance"),
    ("dye", ["plant", "synthetic"], ["liquid", "powder"], ["textile-dye"],
        ["coloring-fabric"], None, "Q193459", "substance"),
    ("pigment", ["mineral", "synthetic"], ["powder"], ["color-source"],
        ["paint", "art"], None, "Q193459", "substance"),
    ("paint", ["synthetic"], ["liquid"], ["wall-paint"],
        ["coloring-surfaces"], None, "Q193459", "substance"),
    ("varnish", ["plant", "synthetic"], ["liquid"], ["wood-finish"],
        ["wood-finishing"], None, "Q193459", "substance"),
    ("lacquer", ["plant", "synthetic"], ["liquid"], ["shellac", "urushi"],
        ["furniture-finish"], None, "Q193459", "substance"),
    ("glue", ["synthetic"], ["liquid"], ["adhesive"],
        ["binding"], None, "Q193459", "substance"),
    ("oil-cooking", ["plant"], ["liquid"], ["vegetable-oil"],
        ["cooking"], None, "Q193459", "substance"),
    ("vinegar", ["biological"], ["liquid"], ["acetic-acid-solution"],
        ["cooking", "cleaning"], None, "Q193459", "substance"),
    ("alcohol", ["biological", "synthetic"], ["liquid"], ["ethanol"],
        ["disinfectant", "fuel"], None, "Q193459", "substance"),
    ("soap", ["synthetic"], ["solid", "liquid"], ["cleansing-soap"],
        ["washing"], None, "Q193459", "substance"),
    ("baking-soda", ["mineral"], ["powder"], ["sodium-bicarbonate"],
        ["baking", "cleaning"], None, "Q193459", "substance"),
]
for c in MIN:
    NODES.append(mat(c[0], c[1], c[2], c[3], c[4], material_for=c[5], qid=c[6], category=c[7]))
