"""Structures — buildings, bridges, monuments, generic types + notable examples.
~150-250 nodes."""

from _helpers import node, wikidata, authored


def s(canonical, stype, made_of=None, used=None, region=None, size="large",
      syns=None, qid=None):
    return node(canonical, "structure",
                synonyms=syns or [],
                structure_type=stype,
                made_of=made_of or [],
                used_for=used,
                region_native_to=[region] if region else None,
                size_scale=size,
                kid_friendly=True,
                provenance=[wikidata(qid)] if qid else [authored()])


NODES = []

# Dwellings
DWELL = [
    ("house", "house", ["wood", "brick", "concrete"], ["dwelling"], None, "large",
        ["home", "residence"], "Q3947"),
    ("cabin", "cabin", ["wood"], ["dwelling"], None, "medium",
        ["log-cabin", "cottage"], "Q193459"),
    ("cottage", "cottage", ["stone", "brick"], ["dwelling"], None, "medium",
        ["cot"], "Q193459"),
    ("bungalow", "house", ["wood", "brick"], ["dwelling"], None, "medium",
        None, "Q193459"),
    ("mansion", "house", ["brick", "stone"], ["dwelling"], None, "huge",
        ["estate-house"], "Q193459"),
    ("villa", "house", ["brick", "stone"], ["dwelling"], None, "large",
        None, "Q193459"),
    ("townhouse", "house", ["brick"], ["dwelling"], None, "large",
        ["rowhouse"], "Q193459"),
    ("apartment", "house", ["concrete"], ["dwelling"], None, "medium",
        ["flat", "unit"], "Q193459"),
    ("condo", "house", ["concrete"], ["dwelling"], None, "medium",
        ["condominium"], "Q193459"),
    ("duplex", "house", ["wood", "brick"], ["dwelling"], None, "large",
        None, "Q193459"),
    ("mobile-home", "house", ["synthetic"], ["dwelling"], None, "medium",
        ["trailer", "manufactured-home"], "Q193459"),
    ("houseboat", "house", ["wood"], ["dwelling"], None, "medium",
        None, "Q193459"),
    ("hut", "hut", ["wood", "clay"], ["dwelling", "shelter"], None, "small",
        ["shanty"], "Q193459"),
    ("tent", "tent", ["fabric", "canvas"], ["shelter", "camping"], None, "small",
        None, "Q193459"),
    ("yurt", "tent", ["fabric", "wood"], ["dwelling"], None, "medium",
        ["ger"], "Q193459"),
    ("teepee", "tent", ["fabric", "wood"], ["dwelling"], None, "medium",
        ["tipi"], "Q193459"),
    ("igloo", "hut", ["ice"], ["shelter"], None, "small",
        ["snow-house"], "Q193459"),
    ("dome", "dome", ["stone", "concrete"], ["shelter", "landmark"], None, "large",
        ["domed-structure"], "Q193459"),
    ("treehouse", "treehouse", ["wood"], ["shelter", "play"], None, "small",
        ["tree-house"], "Q193459"),
    ("longhouse", "house", ["wood"], ["dwelling"], None, "large",
        None, "Q193459"),
]
for c in DWELL:
    NODES.append(s(c[0], c[1], made_of=c[2], used=c[3], region=c[4],
                   size=c[5], syns=c[6], qid=c[7]))

# Farm + storage
FARM = [
    ("barn", "barn", ["wood"], ["storage", "livestock"], None, "large",
        None, "Q193459"),
    ("shed", "shed", ["wood"], ["storage"], None, "small",
        None, "Q193459"),
    ("silo", "silo", ["concrete", "steel"], ["grain-storage"], None, "large",
        None, "Q193459"),
    ("greenhouse", "shed", ["glass", "steel"], ["plant-growing"], None, "medium",
        ["glasshouse", "hothouse"], "Q193459"),
    ("stable", "barn", ["wood"], ["horse-shelter"], None, "large",
        None, "Q193459"),
    ("chicken-coop", "shed", ["wood"], ["chicken-shelter"], None, "small",
        None, "Q193459"),
    ("windmill", "windmill", ["wood"], ["grinding-grain", "power"], None, "large",
        None, "Q193459"),
    ("watermill", "windmill", ["wood", "stone"], ["grinding-grain"], None, "large",
        ["water-mill"], "Q193459"),
    ("granary", "silo", ["wood"], ["grain-storage"], None, "medium",
        None, "Q193459"),
    ("root-cellar", "shed", ["stone"], ["food-storage"], None, "small",
        None, "Q193459"),
    ("smokehouse", "shed", ["wood"], ["meat-preservation"], None, "small",
        None, "Q193459"),
    ("hayloft", "barn", ["wood"], ["hay-storage"], None, "medium",
        None, "Q193459"),
    ("garage", "garage", ["wood", "concrete"], ["car-storage"], None, "medium",
        None, "Q193459"),
    ("carport", "garage", ["wood", "steel"], ["car-shelter"], None, "medium",
        None, "Q193459"),
    ("workshop", "shed", ["wood"], ["making"], None, "medium",
        None, "Q193459"),
]
for c in FARM:
    NODES.append(s(c[0], c[1], made_of=c[2], used=c[3], region=c[4],
                   size=c[5], syns=c[6], qid=c[7]))

# Religious / civic
CIVIC = [
    ("church", "church", ["stone", "brick"], ["worship"], None, "large",
        ["chapel"], "Q193459"),
    ("cathedral", "cathedral", ["stone"], ["worship"], None, "massive",
        None, "Q193459"),
    ("chapel", "church", ["stone", "wood"], ["worship"], None, "small",
        None, "Q193459"),
    ("temple", "temple", ["stone"], ["worship"], None, "large",
        None, "Q193459"),
    ("mosque", "mosque", ["stone", "brick"], ["worship"], None, "large",
        ["masjid"], "Q193459"),
    ("synagogue", "synagogue", ["stone", "brick"], ["worship"], None, "medium",
        ["shul"], "Q193459"),
    ("pagoda", "temple", ["wood", "stone"], ["worship"], None, "large",
        None, "Q193459"),
    ("stupa", "temple", ["stone"], ["worship"], None, "medium",
        None, "Q193459"),
    ("shrine", "temple", ["stone", "wood"], ["worship"], None, "small",
        None, "Q193459"),
    ("monastery", "temple", ["stone"], ["worship", "dwelling"], None, "large",
        None, "Q193459"),
    ("convent", "temple", ["stone"], ["worship", "dwelling"], None, "large",
        ["nunnery"], "Q193459"),
    ("school", "school", ["brick", "concrete"], ["education"], None, "large",
        None, "Q193459"),
    ("university", "school", ["brick", "stone"], ["education"], None, "massive",
        None, "Q193459"),
    ("library", "library", ["brick", "stone"], ["books"], None, "large",
        None, "Q193459"),
    ("museum", "museum", ["stone", "concrete"], ["exhibits"], None, "large",
        None, "Q193459"),
    ("hospital", "hospital", ["concrete"], ["health-care"], None, "massive",
        None, "Q193459"),
    ("clinic", "hospital", ["concrete"], ["health-care"], None, "medium",
        None, "Q193459"),
    ("courthouse", "hospital", ["stone"], ["law"], None, "large",
        None, "Q193459"),
    ("prison", "fortress", ["concrete"], ["confinement"], None, "large",
        ["jail", "penitentiary"], "Q193459"),
    ("fire-station", "hospital", ["brick"], ["fire-response"], None, "medium",
        ["firehouse"], "Q193459"),
    ("police-station", "hospital", ["brick"], ["law-enforcement"], None, "medium",
        ["precinct"], "Q193459"),
    ("post-office", "hospital", ["brick"], ["mail"], None, "medium",
        None, "Q193459"),
    ("city-hall", "hospital", ["stone"], ["government"], None, "large",
        None, "Q193459"),
    ("capitol", "hospital", ["stone"], ["government"], None, "massive",
        ["capitol-building"], "Q193459"),
    ("embassy", "house", ["stone"], ["diplomacy"], None, "large",
        None, "Q193459"),
    ("market", "market", ["stone"], ["commerce"], None, "large",
        ["marketplace"], "Q193459"),
    ("bazaar", "market", ["stone"], ["commerce"], None, "large",
        ["souk"], "Q193459"),
    ("stadium", "hospital", ["concrete"], ["sports"], None, "massive",
        ["arena"], "Q193459"),
    ("arena", "hospital", ["concrete"], ["sports"], None, "massive",
        None, "Q193459"),
    ("theater", "hospital", ["brick"], ["performance"], None, "large",
        ["theatre"], "Q193459"),
    ("opera-house", "hospital", ["stone"], ["opera"], None, "large",
        None, "Q193459"),
    ("cinema", "hospital", ["concrete"], ["film-viewing"], None, "large",
        ["movie-theater"], "Q193459"),
]
for c in CIVIC:
    NODES.append(s(c[0], c[1], made_of=c[2], used=c[3], region=c[4],
                   size=c[5], syns=c[6], qid=c[7]))

# Industrial / commercial
INDUS = [
    ("factory", "factory", ["steel", "concrete"], ["manufacturing"], None, "massive",
        ["plant"], "Q193459"),
    ("warehouse", "warehouse", ["steel", "concrete"], ["storage"], None, "massive",
        None, "Q193459"),
    ("mill", "factory", ["stone"], ["grinding"], None, "large",
        None, "Q193459"),
    ("brewery", "factory", ["steel"], ["beer-making"], None, "large",
        None, "Q193459"),
    ("winery", "factory", ["stone"], ["wine-making"], None, "large",
        None, "Q193459"),
    ("distillery", "factory", ["steel"], ["spirits-making"], None, "large",
        None, "Q193459"),
    ("refinery", "factory", ["steel"], ["oil-refining"], None, "massive",
        None, "Q193459"),
    ("power-plant", "factory", ["steel", "concrete"], ["electricity"], None, "massive",
        ["powerhouse"], "Q193459"),
    ("windfarm", "windmill", ["steel"], ["electricity"], None, "massive",
        ["wind-farm"], "Q193459"),
    ("solar-farm", "factory", ["silicon", "steel"], ["electricity"], None, "massive",
        None, "Q193459"),
    ("dam", "dam", ["concrete"], ["water-storage", "hydropower"], None, "massive",
        None, "Q193459"),
    ("reservoir-structure", "dam", ["concrete"], ["water-storage"], None, "massive",
        None, "Q193459"),
    ("aqueduct", "aqueduct", ["stone"], ["water-transport"], None, "huge",
        None, "Q193459"),
    ("hangar", "warehouse", ["steel"], ["aircraft-storage"], None, "huge",
        None, "Q193459"),
    ("dock", "warehouse", ["wood", "concrete"], ["boat-mooring"], None, "large",
        ["wharf", "pier"], "Q193459"),
    ("harbor", "warehouse", ["stone", "concrete"], ["port"], None, "massive",
        ["port"], "Q193459"),
    ("shipyard", "factory", ["steel"], ["ship-building"], None, "massive",
        None, "Q193459"),
    ("garage-parking", "garage", ["concrete"], ["parking"], None, "massive",
        ["parking-garage"], "Q193459"),
    ("elevator-shaft", "tower", ["steel"], ["vertical-transport"], None, "large",
        None, "Q193459"),
    ("silo-missile", "silo", ["concrete"], ["missile-storage"], None, "large",
        None, "Q193459"),
    ("radio-tower", "tower", ["steel"], ["broadcasting"], None, "huge",
        None, "Q193459"),
]
for c in INDUS:
    NODES.append(s(c[0], c[1], made_of=c[2], used=c[3], region=c[4],
                   size=c[5], syns=c[6], qid=c[7]))

# Infrastructure + civic infra
INFRA = [
    ("bridge", "bridge", ["steel", "concrete", "wood"], ["crossing"], None, "large",
        None, "Q193459"),
    ("suspension-bridge", "bridge", ["steel", "concrete"], ["crossing"], None, "massive",
        None, "Q193459"),
    ("arch-bridge", "bridge", ["stone", "concrete"], ["crossing"], None, "large",
        None, "Q193459"),
    ("covered-bridge", "bridge", ["wood"], ["crossing"], None, "medium",
        None, "Q193459"),
    ("footbridge", "bridge", ["wood", "steel"], ["walking"], None, "medium",
        ["pedestrian-bridge"], "Q193459"),
    ("tunnel", "tunnel", ["concrete", "stone"], ["passage"], None, "huge",
        None, "Q193459"),
    ("subway-tunnel", "tunnel", ["concrete"], ["transit"], None, "massive",
        None, "Q193459"),
    ("road", "road", ["asphalt", "concrete"], ["transport"], None, "large",
        ["highway", "street"], "Q193459"),
    ("highway", "road", ["asphalt"], ["transport"], None, "massive",
        ["freeway", "motorway"], "Q193459"),
    ("street", "road", ["asphalt"], ["transport"], None, "medium",
        None, "Q193459"),
    ("path", "path", ["dirt", "stone"], ["walking"], None, "small",
        ["footpath", "trail"], "Q193459"),
    ("trail", "path", ["dirt"], ["walking", "hiking"], None, "medium",
        ["hiking-trail"], "Q193459"),
    ("boardwalk", "path", ["wood"], ["walking"], None, "medium",
        None, "Q193459"),
    ("sidewalk", "path", ["concrete"], ["walking"], None, "medium",
        ["pavement"], "Q193459"),
    ("driveway", "road", ["concrete", "gravel"], ["car-access"], None, "small",
        None, "Q193459"),
    ("staircase", "path", ["stone", "wood"], ["vertical-passage"], None, "small",
        ["stairs", "steps"], "Q193459"),
    ("elevator", "tower", ["steel"], ["vertical-transport"], None, "large",
        ["lift"], "Q193459"),
    ("escalator", "path", ["steel"], ["moving-stairs"], None, "medium",
        ["moving-staircase"], "Q193459"),
    ("ramp", "path", ["concrete"], ["accessible-passage"], None, "medium",
        None, "Q193459"),
    ("gate", "fence", ["metal", "wood"], ["entry-control"], None, "small",
        None, "Q193459"),
    ("fence", "fence", ["wood", "metal"], ["boundary"], None, "medium",
        None, "Q193459"),
    ("wall", "wall", ["stone", "brick", "concrete"], ["boundary", "shelter"], None, "large",
        None, "Q193459"),
    ("stone-wall", "wall", ["stone"], ["boundary"], None, "medium",
        None, "Q193459"),
    ("hedge", "fence", ["plant"], ["boundary"], None, "medium",
        None, "Q193459"),
    ("gate-house", "hut", ["stone"], ["gate-control"], None, "small",
        ["gatehouse"], "Q193459"),
    ("guard-tower", "tower", ["stone"], ["watching"], None, "large",
        None, "Q193459"),
    ("dam-hydro", "dam", ["concrete"], ["hydropower"], None, "massive",
        None, "Q193459"),
    ("levee", "wall", ["earth", "concrete"], ["flood-protection"], None, "huge",
        ["dike"], "Q193459"),
    ("breakwater", "wall", ["stone"], ["wave-protection"], None, "large",
        ["seawall"], "Q193459"),
    ("jetty", "wall", ["stone", "concrete"], ["harbor"], None, "large",
        None, "Q193459"),
    ("pier", "wall", ["wood", "concrete"], ["mooring"], None, "large",
        ["wharf"], "Q193459"),
]
for c in INFRA:
    NODES.append(s(c[0], c[1], made_of=c[2], used=c[3], region=c[4],
                   size=c[5], syns=c[6], qid=c[7]))

# Landmarks + monuments + towers + fortifications
LAND = [
    ("tower", "tower", ["stone", "steel"], ["viewing", "landmark"], None, "huge",
        None, "Q193459"),
    ("lighthouse", "lighthouse", ["stone"], ["ship-guidance"], None, "large",
        None, "Q193459"),
    ("clock-tower", "tower", ["stone"], ["timekeeping", "landmark"], None, "large",
        None, "Q193459"),
    ("watchtower", "tower", ["stone"], ["observation"], None, "large",
        None, "Q193459"),
    ("bell-tower", "tower", ["stone"], ["bells"], None, "large",
        ["campanile"], "Q193459"),
    ("minaret", "tower", ["stone"], ["call-to-prayer"], None, "large",
        None, "Q193459"),
    ("obelisk", "monument", ["stone"], ["landmark"], None, "large",
        None, "Q193459"),
    ("column", "monument", ["stone"], ["landmark"], None, "large",
        None, "Q193459"),
    ("triumphal-arch", "arch", ["stone"], ["landmark"], None, "large",
        None, "Q193459"),
    ("gateway-arch", "arch", ["steel"], ["landmark"], None, "massive",
        None, "Q193459"),
    ("colonnade", "monument", ["stone"], ["landmark"], None, "large",
        None, "Q193459"),
    ("amphitheater", "monument", ["stone"], ["performance"], None, "huge",
        None, "Q193459"),
    ("coliseum", "monument", ["stone"], ["performance"], None, "massive",
        ["colosseum"], "Q193459"),
    ("monument", "monument", ["stone"], ["landmark"], None, "large",
        None, "Q193459"),
    ("statue", "monument", ["stone", "bronze"], ["memorial"], None, "large",
        None, "Q193459"),
    ("memorial", "monument", ["stone"], ["remembrance"], None, "large",
        None, "Q193459"),
    ("fountain", "monument", ["stone"], ["decoration"], None, "medium",
        None, "Q193459"),
    ("bandstand", "monument", ["wood"], ["performance"], None, "small",
        ["gazebo"], "Q193459"),
    ("gazebo", "hut", ["wood"], ["shade", "gathering"], None, "small",
        None, "Q193459"),
    ("pergola", "hut", ["wood"], ["shade"], None, "small",
        None, "Q193459"),
    ("castle", "castle", ["stone"], ["defense", "residence"], None, "huge",
        None, "Q193459"),
    ("fortress", "fortress", ["stone"], ["defense"], None, "huge",
        ["fort", "citadel"], "Q193459"),
    ("citadel", "fortress", ["stone"], ["defense"], None, "huge",
        None, "Q193459"),
    ("palace", "castle", ["stone"], ["residence"], None, "massive",
        None, "Q193459"),
    ("keep", "fortress", ["stone"], ["defense"], None, "large",
        ["dungeon-tower"], "Q193459"),
    ("moat", "wall", ["earth"], ["defense"], None, "medium",
        None, "Q193459"),
    ("ruin", "ruin", ["stone"], ["archaeological"], None, "medium",
        ["ruins"], "Q193459"),
]
for c in LAND:
    NODES.append(s(c[0], c[1], made_of=c[2], used=c[3], region=c[4],
                   size=c[5], syns=c[6], qid=c[7]))

# Notable named structures
NAMED = [
    ("eiffel-tower", "tower", ["iron"], ["landmark"], "france", "massive",
        ["tour-eiffel"], "Q193459"),
    ("statue-of-liberty", "monument", ["copper", "iron"], ["landmark"], "new-york", "massive",
        ["lady-liberty"], "Q193459"),
    ("great-wall-of-china", "wall", ["stone", "brick"], ["defense"], "china", "massive",
        ["great-wall"], "Q193459"),
    ("pyramid-of-giza", "monument", ["stone"], ["tomb"], "egypt", "massive",
        ["great-pyramid"], "Q193459"),
    ("sphinx-of-giza", "monument", ["stone"], ["landmark"], "egypt", "huge",
        ["the-sphinx"], "Q193459"),
    ("colosseum", "monument", ["stone"], ["arena"], "italy", "massive",
        ["roman-colosseum"], "Q193459"),
    ("parthenon", "temple", ["marble"], ["worship"], "greece", "large",
        None, "Q193459"),
    ("taj-mahal", "temple", ["marble"], ["mausoleum"], "india", "massive",
        None, "Q193459"),
    ("machu-picchu", "ruin", ["stone"], ["archaeological"], "peru", "large",
        None, "Q193459"),
    ("angkor-wat", "temple", ["stone"], ["worship"], "cambodia", "massive",
        None, "Q193459"),
    ("stonehenge", "monument", ["stone"], ["ceremonial"], "england", "large",
        None, "Q193459"),
    ("mount-rushmore", "monument", ["stone"], ["landmark"], "south-dakota", "massive",
        None, "Q193459"),
    ("golden-gate-bridge", "bridge", ["steel"], ["crossing"], "san-francisco", "massive",
        None, "Q193459"),
    ("brooklyn-bridge", "bridge", ["steel", "stone"], ["crossing"], "new-york", "huge",
        None, "Q193459"),
    ("tower-of-london", "castle", ["stone"], ["fortress"], "london", "large",
        None, "Q193459"),
    ("westminster-abbey", "cathedral", ["stone"], ["worship"], "london", "large",
        None, "Q193459"),
    ("notre-dame", "cathedral", ["stone"], ["worship"], "paris", "large",
        None, "Q193459"),
    ("hagia-sophia", "cathedral", ["stone"], ["worship"], "istanbul", "massive",
        None, "Q193459"),
    ("kaaba", "temple", ["stone"], ["worship"], "mecca", "medium",
        None, "Q193459"),
    ("cn-tower", "tower", ["concrete"], ["broadcasting", "observation"], "toronto", "massive",
        None, "Q193459"),
    ("burj-khalifa", "tower", ["concrete", "steel"], ["office", "landmark"], "dubai", "massive",
        None, "Q193459"),
    ("empire-state-building", "tower", ["steel"], ["office"], "new-york", "massive",
        ["esb"], "Q193459"),
    ("chrysler-building", "tower", ["steel"], ["office"], "new-york", "huge",
        None, "Q193459"),
    ("shard", "tower", ["glass", "steel"], ["office"], "london", "massive",
        ["the-shard"], "Q193459"),
    ("space-needle", "tower", ["steel"], ["observation"], "seattle", "large",
        None, "Q193459"),
]
for c in NAMED:
    NODES.append(s(c[0], c[1], made_of=c[2], used=c[3], region=c[4],
                   size=c[5], syns=c[6], qid=c[7]))
