"""Habitats + biomes + generic places + rooms + everyday spaces.
~150-250 nodes covering habitat, place categories."""

from _helpers import node, wikidata, authored


def h(canonical, cat, syns=None, region=None, sensory=None, qid=None):
    return node(canonical, cat,
                synonyms=syns or [],
                region_native_to=[region] if region else None,
                sensory_signatures=sensory,
                kid_friendly=True,
                provenance=[wikidata(qid)] if qid else [authored()])


NODES = []

# Biomes / habitats
BIOMES = [
    ("forest", "habitat", ["woods", "woodland", "arboretum"], None,
        ["dappled-light", "leaf-litter"], "Q4421"),
    ("temperate-forest", "habitat", ["deciduous-forest", "hardwood-forest"], "north-hemisphere",
        None, "Q193459"),
    ("boreal-forest", "habitat", ["taiga", "snow-forest"], "high-north",
        None, "Q193459"),
    ("rainforest", "habitat", ["tropical-forest", "jungle"], "equatorial",
        ["dense-canopy", "constant-rain"], "Q193459"),
    ("cloud-forest", "habitat", ["montane-rainforest", "misty-forest"], "highlands",
        ["cool-mist"], "Q193459"),
    ("mangrove", "habitat", ["mangrove-forest", "tidal-forest"], "tropical-coast",
        ["salty-tidal-mud"], "Q193459"),
    ("swamp-biome", "habitat", ["wetland-forest"], "worldwide-warm",
        None, "Q193459"),
    ("jungle", "habitat", ["dense-tropical-forest"], "tropics-worldwide",
        None, "Q193459"),
    ("grassland", "habitat", ["prairie", "steppe", "pampas", "savanna"], None,
        None, "Q193459"),
    ("savanna", "habitat", ["tropical-grassland", "veld"], "africa",
        None, "Q193459"),
    ("prairie", "habitat", ["tallgrass-shortgrass-prairie"], "north-america",
        None, "Q193459"),
    ("steppe", "habitat", ["temperate-grassland"], "eurasia",
        None, "Q193459"),
    ("pampas", "habitat", ["temperate-grassland"], "south-america",
        None, "Q193459"),
    ("desert-biome", "habitat", ["arid-region"], None,
        ["dry", "temperature-swing"], "Q193459"),
    ("hot-desert", "habitat", ["desert-hot"], None,
        None, "Q193459"),
    ("cold-desert", "habitat", ["desert-cold", "polar-desert"], "poles",
        None, "Q193459"),
    ("tundra-biome", "habitat", ["arctic-tundra", "alpine-tundra"], "arctic-alpine",
        ["treeless"], "Q193459"),
    ("alpine", "habitat", ["mountain-habitat"], "high-elevation",
        None, "Q193459"),
    ("subalpine", "habitat", ["treeline-forest"], "high-elevation",
        None, "Q193459"),
    ("chaparral", "habitat", ["mediterranean-scrubland"], "mediterranean-climate",
        None, "Q193459"),
    ("scrubland", "habitat", ["shrubland"], None,
        None, "Q193459"),
    ("heathland", "habitat", ["moorland"], "britain",
        None, "Q193459"),
    ("bog", "habitat", ["peat-bog", "muskeg"], "north-hemisphere",
        ["sphagnum-carpet"], "Q193459"),
    ("marsh-biome", "habitat", ["freshwater-marsh"], None,
        None, "Q193459"),
    ("fen-biome", "habitat", ["alkaline-fen"], "north-hemisphere",
        None, "Q193459"),
    ("estuary-habitat", "habitat", ["brackish-water"], None,
        None, "Q193459"),
    ("tidepool-habitat", "habitat", ["intertidal-pool"], "rocky-coast",
        ["barnacle-crusted"], "Q193459"),
    ("kelp-forest", "habitat", ["giant-kelp-forest"], "cold-temperate-ocean",
        None, "Q193459"),
    ("coral-reef", "habitat", ["reef", "reef-system"], "tropical-warm",
        None, "Q193459"),
    ("seagrass-meadow", "habitat", ["seagrass-bed"], "shallow-marine",
        None, "Q193459"),
    ("mangrove-swamp", "habitat", ["mangrove-forest"], "tropical-coast",
        None, "Q193459"),
    ("deep-sea", "habitat", ["abyssal-zone", "hadal-zone"], "worldwide",
        ["cold", "dark", "high-pressure"], "Q193459"),
    ("open-ocean", "habitat", ["pelagic-zone"], "worldwide",
        None, "Q193459"),
    ("continental-shelf-habitat", "habitat", ["neritic-zone"], "coastal",
        None, "Q193459"),
    ("littoral-zone", "habitat", ["intertidal-zone", "shore-zone"], "worldwide",
        None, "Q193459"),
    ("polar-region", "habitat", ["poles"], "poles",
        ["ice", "cold"], "Q193459"),
    ("cave-habitat", "habitat", ["cavern-habitat", "subterranean"], "worldwide",
        ["dark", "cool"], "Q193459"),
    ("underground", "habitat", ["subterranean-habitat"], "worldwide",
        None, "Q193459"),
    ("urban-habitat", "habitat", ["urban-environment", "city"], "worldwide",
        None, "Q193459"),
    ("suburban", "habitat", ["suburb"], "worldwide",
        None, "Q193459"),
    ("rural", "habitat", ["countryside"], "worldwide",
        None, "Q193459"),
    ("agricultural-land", "habitat", ["farmland"], "worldwide",
        None, "Q193459"),
    ("orchard-habitat", "habitat", ["orchard"], "worldwide",
        None, "Q193459"),
    ("vineyard-habitat", "habitat", ["vineyard"], "wine-regions",
        None, "Q193459"),
    ("pasture", "habitat", ["grazing-land"], "worldwide",
        None, "Q193459"),
    ("hedgerow", "habitat", ["hedge-line"], "europe",
        None, "Q193459"),
    ("garden-habitat", "habitat", ["cultivated-garden"], "worldwide",
        None, "Q193459"),
    ("meadow-habitat", "habitat", ["wildflower-meadow"], "worldwide-temperate",
        None, "Q193459"),
    ("rice-paddy", "habitat", ["paddy-field"], "asia",
        None, "Q193459"),
    ("terraced-farm", "habitat", ["hillside-farm"], "asia-andes",
        None, "Q193459"),
    ("volcanic-vent", "habitat", ["hydrothermal-vent"], "deep-sea",
        ["hot", "sulfur"], "Q193459"),
]
for c in BIOMES:
    NODES.append(h(c[0], c[1], syns=c[2], region=c[3], sensory=c[4], qid=c[5]))

# Rooms + interior places
ROOMS = [
    ("kitchen", "place", ["cookery"], None, ["food-smells"], "Q193459"),
    ("bathroom", "place", ["restroom", "washroom", "loo"], None, None, "Q193459"),
    ("bedroom", "place", ["sleeping-room"], None, ["quiet"], "Q193459"),
    ("living-room", "place", ["sitting-room", "lounge", "parlor"], None, None, "Q193459"),
    ("dining-room", "place", ["dining-area"], None, None, "Q193459"),
    ("den", "place", ["family-room"], None, None, "Q193459"),
    ("study-room", "place", ["office-room", "library-room"], None, None, "Q193459"),
    ("office-space", "place", ["workspace"], None, None, "Q193459"),
    ("nursery", "place", ["baby-room"], None, None, "Q193459"),
    ("playroom", "place", ["kids-room"], None, None, "Q193459"),
    ("attic", "place", ["loft"], None, ["dust"], "Q193459"),
    ("basement", "place", ["cellar"], None, ["cool"], "Q193459"),
    ("cellar", "place", ["root-cellar"], None, None, "Q193459"),
    ("garage-interior", "place", ["car-garage"], None, ["oil-smell"], "Q193459"),
    ("laundry-room", "place", ["utility-room"], None, ["detergent"], "Q193459"),
    ("mudroom", "place", ["entryway"], None, None, "Q193459"),
    ("foyer", "place", ["entry-hall", "vestibule"], None, None, "Q193459"),
    ("hallway", "place", ["corridor", "passageway"], None, None, "Q193459"),
    ("stairwell", "place", ["staircase-space"], None, None, "Q193459"),
    ("closet", "place", ["wardrobe"], None, None, "Q193459"),
    ("pantry", "place", ["larder"], None, None, "Q193459"),
    ("porch", "place", ["veranda", "stoop"], None, None, "Q193459"),
    ("balcony", "place", ["terrace"], None, None, "Q193459"),
    ("terrace", "place", ["patio"], None, None, "Q193459"),
    ("patio", "place", ["backyard-patio"], None, None, "Q193459"),
    ("deck", "place", ["wooden-deck"], None, None, "Q193459"),
    ("rooftop", "place", ["roof-deck"], None, None, "Q193459"),
    ("greenhouse-space", "place", ["hothouse"], None, ["humid"], "Q193459"),
    ("workshop-space", "place", ["makerspace"], None, ["sawdust"], "Q193459"),
    ("garden-yard", "place", ["backyard", "front-yard", "lawn"], None, None, "Q193459"),
    ("classroom", "place", ["schoolroom"], None, None, "Q193459"),
    ("auditorium", "place", ["lecture-hall"], None, None, "Q193459"),
    ("gymnasium", "place", ["gym"], None, None, "Q193459"),
    ("cafeteria", "place", ["lunchroom", "canteen"], None, None, "Q193459"),
    ("waiting-room", "place", ["reception"], None, None, "Q193459"),
    ("lobby", "place", ["hotel-lobby"], None, None, "Q193459"),
    ("boardroom", "place", ["conference-room"], None, None, "Q193459"),
    ("cubicle", "place", ["office-cubicle"], None, None, "Q193459"),
    ("cell", "place", ["prison-cell"], None, None, "Q193459"),
    ("dungeon", "place", ["oubliette"], None, None, "Q193459"),
    ("altar", "place", ["worship-space"], None, None, "Q193459"),
    ("chancel", "place", ["church-front"], None, None, "Q193459"),
    ("nave", "place", ["church-body"], None, None, "Q193459"),
    ("choir-loft", "place", ["choir-space"], None, None, "Q193459"),
    ("crypt", "place", ["underground-tomb"], None, None, "Q193459"),
    ("cloister", "place", ["monastery-courtyard"], None, None, "Q193459"),
    ("courtyard", "place", ["quadrangle"], None, None, "Q193459"),
    ("plaza", "place", ["square"], None, None, "Q193459"),
    ("marketplace-space", "place", ["market-square"], None, None, "Q193459"),
    ("piazza", "place", ["italian-square"], "italy", None, "Q193459"),
    ("boulevard", "place", ["tree-lined-street"], None, None, "Q193459"),
    ("avenue", "place", ["broad-street"], None, None, "Q193459"),
    ("alley", "place", ["back-alley", "lane"], None, None, "Q193459"),
    ("cul-de-sac", "place", ["dead-end-street"], None, None, "Q193459"),
    ("intersection", "place", ["crossroads"], None, None, "Q193459"),
    ("roundabout", "place", ["traffic-circle"], None, None, "Q193459"),
    ("crosswalk", "place", ["pedestrian-crossing", "zebra-crossing"], None, None, "Q193459"),
    ("park", "place", ["public-park"], None, None, "Q193459"),
    ("playground", "place", ["play-area"], None, None, "Q193459"),
    ("cemetery", "place", ["graveyard", "burial-ground"], None, None, "Q193459"),
    ("orchestra-pit", "place", ["pit"], None, None, "Q193459"),
    ("stage", "place", ["performance-stage"], None, None, "Q193459"),
    ("backstage", "place", ["backstage-area"], None, None, "Q193459"),
    ("aisle", "place", ["store-aisle"], None, None, "Q193459"),
    ("checkout", "place", ["checkout-counter"], None, None, "Q193459"),
    ("dressing-room", "place", ["changing-room"], None, None, "Q193459"),
    ("locker-room", "place", ["change-room"], None, None, "Q193459"),
    ("sauna", "place", ["steam-room"], None, ["hot", "humid"], "Q193459"),
    ("spa", "place", ["day-spa"], None, None, "Q193459"),
]
for c in ROOMS:
    NODES.append(h(c[0], c[1], syns=c[2], region=c[3], sensory=c[4], qid=c[5]))

# Broader place types
PLACES = [
    ("city", "place", ["urban-area", "metropolis"], None, None, "Q515"),
    ("town", "place", ["township"], None, None, "Q3957"),
    ("village", "place", ["hamlet"], None, None, "Q532"),
    ("suburb", "place", ["bedroom-community"], None, None, "Q193459"),
    ("neighborhood", "place", ["borough", "district"], None, None, "Q193459"),
    ("downtown", "place", ["city-center", "cbd"], None, None, "Q193459"),
    ("chinatown", "place", ["chinese-district"], None, None, "Q193459"),
    ("countryside", "place", ["rural-area"], None, None, "Q193459"),
    ("wilderness", "place", ["backcountry"], None, None, "Q193459"),
    ("nature-reserve", "place", ["preserve"], None, None, "Q193459"),
    ("national-park", "place", ["parkland"], None, None, "Q193459"),
    ("state-park", "place", ["state-parkland"], None, None, "Q193459"),
    ("botanical-garden", "place", ["botanic-garden"], None, None, "Q193459"),
    ("zoo", "place", ["zoological-park"], None, None, "Q193459"),
    ("aquarium-place", "place", ["public-aquarium"], None, None, "Q193459"),
    ("amusement-park", "place", ["fair", "theme-park"], None, None, "Q193459"),
    ("water-park", "place", ["waterpark"], None, None, "Q193459"),
    ("ski-resort", "place", ["ski-area"], None, None, "Q193459"),
    ("beach-resort", "place", ["seaside-resort"], None, None, "Q193459"),
    ("campground", "place", ["campsite"], None, None, "Q193459"),
    ("summer-camp", "place", ["day-camp"], None, None, "Q193459"),
    ("scenic-overlook", "place", ["viewpoint", "vista-point"], None, None, "Q193459"),
    ("trailhead", "place", ["trail-start"], None, None, "Q193459"),
    ("rest-stop", "place", ["service-area"], None, None, "Q193459"),
    ("truck-stop", "place", ["service-station"], None, None, "Q193459"),
    ("gas-station", "place", ["petrol-station", "filling-station"], None, None, "Q193459"),
    ("airport", "place", ["airfield"], None, None, "Q193459"),
    ("train-station", "place", ["railway-station"], None, None, "Q193459"),
    ("bus-station", "place", ["coach-station"], None, None, "Q193459"),
    ("ferry-terminal", "place", ["ferry-dock"], None, None, "Q193459"),
    ("cruise-terminal", "place", ["cruise-port"], None, None, "Q193459"),
    ("marina", "place", ["yacht-basin"], None, None, "Q193459"),
    ("port-city", "place", ["seaport"], None, None, "Q193459"),
    ("military-base", "place", ["base"], None, None, "Q193459"),
    ("air-base", "place", ["air-force-base"], None, None, "Q193459"),
    ("shipping-yard", "place", ["docks", "port"], None, None, "Q193459"),
    ("industrial-park", "place", ["industrial-estate"], None, None, "Q193459"),
    ("shopping-mall", "place", ["mall"], None, None, "Q193459"),
    ("strip-mall", "place", ["strip-center"], None, None, "Q193459"),
    ("public-square", "place", ["plaza"], None, None, "Q193459"),
    ("waterfront", "place", ["shorefront"], None, None, "Q193459"),
]
for c in PLACES:
    NODES.append(h(c[0], c[1], syns=c[2], region=c[3], sensory=c[4], qid=c[5]))
