"""Additional mammal + bird + reptile species — expansion pass.
~250-400 more animals, focusing on high-cultural-recognition names not
already covered in files 01-06.
"""

from _helpers import node, wikidata, tax, authored


def a(canonical, sci, family, order, class_, phylum, diet, habitat, region,
      size, syns=None, behavior=None, qid=None):
    return node(canonical, "animal",
                synonyms=syns or [],
                scientific_name=sci,
                taxonomy=tax(kingdom="Animalia", phylum=phylum, class_=class_,
                             order=order, family=family,
                             genus=sci.split()[0] if sci else None,
                             species=sci, common_name=canonical),
                diet=diet,
                lives_in=[habitat] if isinstance(habitat, str) else habitat,
                region_native_to=[region] if isinstance(region, str) else region,
                size_scale=size, behavior_notes=behavior,
                kid_friendly=True,
                provenance=[wikidata(qid)] if qid else [authored()])


NODES = []

# ---------- Extra mammals ----------
MORE_MAMMALS = [
    ("hedgehog", "Erinaceus europaeus", "Erinaceidae", "Eulipotyphla", "Mammalia", "Chordata",
        ["insectivore"], "garden", "europe", "small",
        ["spiny", "nocturnal"], None, "Q193459"),
    ("mole", "Talpa europaea", "Talpidae", "Eulipotyphla", "Mammalia", "Chordata",
        ["insectivore"], "underground", "europe", "small",
        ["burrower", "blind"], None, "Q193459"),
    ("shrew", "Sorex", "Soricidae", "Eulipotyphla", "Mammalia", "Chordata",
        ["insectivore"], "forest-floor", "worldwide", "tiny",
        ["voracious"], None, "Q193459"),
    ("armadillo", "Dasypus novemcinctus", "Dasypodidae", "Cingulata", "Mammalia", "Chordata",
        ["insectivore"], "grassland", "americas", "small",
        ["armored", "burrower"], ["nine-banded-armadillo"], "Q193459"),
    ("giant-armadillo", "Priodontes maximus", "Chlamyphoridae", "Cingulata", "Mammalia", "Chordata",
        ["insectivore"], "jungle", "south-america", "medium",
        ["largest-armadillo"], None, "Q193459"),
    ("sloth", "Bradypus", "Bradypodidae", "Pilosa", "Mammalia", "Chordata",
        ["folivore"], "canopy", "central-america", "medium",
        ["slow", "arboreal"], ["three-toed-sloth"], "Q193459"),
    ("two-toed-sloth", "Choloepus didactylus", "Megalonychidae", "Pilosa", "Mammalia", "Chordata",
        ["folivore"], "canopy", "south-america", "medium",
        ["slow", "arboreal"], None, "Q193459"),
    ("anteater", "Myrmecophaga tridactyla", "Myrmecophagidae", "Pilosa", "Mammalia", "Chordata",
        ["insectivore"], "grassland", "americas", "medium",
        ["long-tongue", "no-teeth"], ["giant-anteater"], "Q193459"),
    ("tamandua", "Tamandua mexicana", "Myrmecophagidae", "Pilosa", "Mammalia", "Chordata",
        ["insectivore"], "jungle", "americas", "small",
        ["arboreal"], ["collared-anteater"], "Q193459"),
    ("pangolin", "Manis javanica", "Manidae", "Pholidota", "Mammalia", "Chordata",
        ["insectivore"], ["jungle", "savanna"], "africa-asia", "small",
        ["scaled", "curls-into-ball"], ["scaly-anteater"], "Q193459"),
    ("aardvark", "Orycteropus afer", "Orycteropodidae", "Tubulidentata", "Mammalia", "Chordata",
        ["insectivore"], "savanna", "africa", "medium",
        ["burrower"], None, "Q193459"),
    ("aardwolf", "Proteles cristatus", "Hyaenidae", "Carnivora", "Mammalia", "Chordata",
        ["insectivore"], "savanna", "africa", "small",
        ["termite-eater"], None, "Q193459"),
    ("wombat", "Vombatus ursinus", "Vombatidae", "Diprotodontia", "Mammalia", "Chordata",
        ["herbivore"], "grassland", "australia", "medium",
        ["burrower", "cube-shaped-scat"], ["common-wombat"], "Q193459"),
    ("koala", "Phascolarctos cinereus", "Phascolarctidae", "Diprotodontia", "Mammalia", "Chordata",
        ["folivore"], "eucalyptus-forest", "australia", "small",
        ["arboreal", "eucalyptus-eater"], None, "Q193459"),
    ("kangaroo", "Macropus giganteus", "Macropodidae", "Diprotodontia", "Mammalia", "Chordata",
        ["herbivore"], "grassland", "australia", "large",
        ["hopping", "pouched"], ["eastern-grey-kangaroo"], "Q193459"),
    ("red-kangaroo", "Osphranter rufus", "Macropodidae", "Diprotodontia", "Mammalia", "Chordata",
        ["herbivore"], "outback", "australia", "large",
        ["largest-marsupial"], None, "Q193459"),
    ("wallaby", "Macropus", "Macropodidae", "Diprotodontia", "Mammalia", "Chordata",
        ["herbivore"], "grassland", "australia", "small",
        ["small-kangaroo"], None, "Q193459"),
    ("quokka", "Setonix brachyurus", "Macropodidae", "Diprotodontia", "Mammalia", "Chordata",
        ["herbivore"], "scrubland", "western-australia", "small",
        ["smiling-face"], None, "Q193459"),
    ("tasmanian-devil", "Sarcophilus harrisii", "Dasyuridae", "Dasyuromorphia", "Mammalia", "Chordata",
        ["carnivore"], "forest", "tasmania", "small",
        ["scavenger", "loud-call"], None, "Q193459"),
    ("bandicoot", "Isoodon obesulus", "Peramelidae", "Peramelemorphia", "Mammalia", "Chordata",
        ["omnivore"], "scrubland", "australia", "small",
        None, ["southern-brown-bandicoot"], "Q193459"),
    ("opossum", "Didelphis virginiana", "Didelphidae", "Didelphimorphia", "Mammalia", "Chordata",
        ["omnivore"], "forest", "north-america", "small",
        ["playing-dead", "nocturnal"], ["virginia-opossum", "possum"], "Q193459"),
    ("platypus", "Ornithorhynchus anatinus", "Ornithorhynchidae", "Monotremata", "Mammalia", "Chordata",
        ["carnivore"], "river", "australia", "small",
        ["egg-laying", "duck-bill", "venomous-spurs"], None, "Q193459"),
    ("echidna", "Tachyglossus aculeatus", "Tachyglossidae", "Monotremata", "Mammalia", "Chordata",
        ["insectivore"], ["forest", "grassland"], "australia", "small",
        ["egg-laying", "spiny"], ["short-beaked-echidna"], "Q193459"),
    ("bat", "Chiroptera", "Vespertilionidae", "Chiroptera", "Mammalia", "Chordata",
        ["insectivore"], "worldwide", "worldwide", "tiny",
        ["only-flying-mammal", "echolocation"], None, "Q193459"),
    ("vampire-bat", "Desmodus rotundus", "Phyllostomidae", "Chiroptera", "Mammalia", "Chordata",
        ["carnivore"], "jungle", "central-america", "tiny",
        ["blood-feeder"], None, "Q193459"),
    ("fruit-bat", "Pteropus", "Pteropodidae", "Chiroptera", "Mammalia", "Chordata",
        ["frugivore"], "jungle", "tropics-worldwide", "small",
        ["large-bat"], ["flying-fox"], "Q193459"),
    ("flying-fox", "Pteropus vampyrus", "Pteropodidae", "Chiroptera", "Mammalia", "Chordata",
        ["frugivore"], "jungle", "southeast-asia", "small",
        ["largest-bat"], None, "Q193459"),
    ("chipmunk", "Tamias striatus", "Sciuridae", "Rodentia", "Mammalia", "Chordata",
        ["omnivore"], "forest", "north-america", "tiny",
        ["cheek-pouches", "striped"], ["eastern-chipmunk"], "Q193459"),
    ("prairie-dog", "Cynomys ludovicianus", "Sciuridae", "Rodentia", "Mammalia", "Chordata",
        ["herbivore"], "prairie", "north-america", "small",
        ["colonial", "burrower"], ["black-tailed-prairie-dog"], "Q193459"),
    ("groundhog", "Marmota monax", "Sciuridae", "Rodentia", "Mammalia", "Chordata",
        ["herbivore"], "meadow", "north-america", "small",
        ["hibernator", "burrower"], ["woodchuck"], "Q193459"),
    ("marmot", "Marmota marmota", "Sciuridae", "Rodentia", "Mammalia", "Chordata",
        ["herbivore"], "mountain", "europe", "small",
        ["hibernator"], ["alpine-marmot"], "Q193459"),
    ("beaver", "Castor canadensis", "Castoridae", "Rodentia", "Mammalia", "Chordata",
        ["herbivore"], "river", "north-america", "medium",
        ["dam-builder"], ["north-american-beaver"], "Q193459"),
    ("porcupine", "Erethizon dorsatum", "Erethizontidae", "Rodentia", "Mammalia", "Chordata",
        ["herbivore"], "forest", "north-america", "small",
        ["quills"], ["north-american-porcupine"], "Q193459"),
    ("mouse", "Mus musculus", "Muridae", "Rodentia", "Mammalia", "Chordata",
        ["omnivore"], "worldwide", "worldwide", "tiny",
        ["nocturnal", "prolific"], ["house-mouse"], "Q193459"),
    ("rat", "Rattus norvegicus", "Muridae", "Rodentia", "Mammalia", "Chordata",
        ["omnivore"], "worldwide", "worldwide", "small",
        ["intelligent", "prolific"], ["brown-rat", "norway-rat"], "Q193459"),
    ("hamster", "Mesocricetus auratus", "Cricetidae", "Rodentia", "Mammalia", "Chordata",
        ["omnivore"], "pet", "middle-east", "tiny",
        ["cheek-pouches"], ["syrian-hamster"], "Q193459"),
    ("gerbil", "Meriones unguiculatus", "Muridae", "Rodentia", "Mammalia", "Chordata",
        ["omnivore"], "desert", "central-asia", "tiny",
        ["desert-adapted"], ["mongolian-gerbil"], "Q193459"),
    ("guinea-pig", "Cavia porcellus", "Caviidae", "Rodentia", "Mammalia", "Chordata",
        ["herbivore"], "pet", "south-america", "small",
        ["social"], ["cavy"], "Q193459"),
    ("capybara", "Hydrochoerus hydrochaeris", "Caviidae", "Rodentia", "Mammalia", "Chordata",
        ["herbivore"], ["wetland", "grassland"], "south-america", "medium",
        ["largest-rodent", "semi-aquatic"], None, "Q193459"),
    ("chinchilla", "Chinchilla lanigera", "Chinchillidae", "Rodentia", "Mammalia", "Chordata",
        ["herbivore"], "mountain", "andes", "small",
        ["soft-fur", "dust-bathing"], None, "Q193459"),
    ("mara", "Dolichotis patagonum", "Caviidae", "Rodentia", "Mammalia", "Chordata",
        ["herbivore"], "steppe", "argentina", "small",
        ["hare-like"], ["patagonian-mara"], "Q193459"),
    ("naked-mole-rat", "Heterocephalus glaber", "Heterocephalidae", "Rodentia", "Mammalia", "Chordata",
        ["herbivore"], "underground", "east-africa", "tiny",
        ["eusocial", "long-lived", "cold-blooded"], None, "Q193459"),
    ("degus", "Octodon degus", "Octodontidae", "Rodentia", "Mammalia", "Chordata",
        ["herbivore"], "scrubland", "chile", "tiny",
        ["diurnal", "social"], None, "Q193459"),
    ("rabbit", "Oryctolagus cuniculus", "Leporidae", "Lagomorpha", "Mammalia", "Chordata",
        ["herbivore"], "meadow", "worldwide", "small",
        ["burrower", "prolific"], ["bunny", "european-rabbit"], "Q193459"),
    ("hare", "Lepus europaeus", "Leporidae", "Lagomorpha", "Mammalia", "Chordata",
        ["herbivore"], "field", "europe", "small",
        ["fast-runner"], ["european-hare"], "Q193459"),
    ("jackrabbit", "Lepus californicus", "Leporidae", "Lagomorpha", "Mammalia", "Chordata",
        ["herbivore"], "desert", "north-america-west", "small",
        ["long-ears"], ["black-tailed-jackrabbit"], "Q193459"),
    ("pika", "Ochotona princeps", "Ochotonidae", "Lagomorpha", "Mammalia", "Chordata",
        ["herbivore"], "alpine-rocks", "north-america-west", "tiny",
        ["haypile-maker"], ["american-pika"], "Q193459"),
    ("gazelle", "Gazella dorcas", "Bovidae", "Artiodactyla", "Mammalia", "Chordata",
        ["herbivore"], "savanna", "africa", "medium",
        ["fast-runner"], ["dorcas-gazelle"], "Q193459"),
    ("thompsons-gazelle", "Eudorcas thomsonii", "Bovidae", "Artiodactyla", "Mammalia", "Chordata",
        ["herbivore"], "savanna", "east-africa", "small",
        ["stotting"], None, "Q193459"),
    ("impala", "Aepyceros melampus", "Bovidae", "Artiodactyla", "Mammalia", "Chordata",
        ["herbivore"], "savanna", "africa", "medium",
        ["leaping"], None, "Q193459"),
    ("springbok", "Antidorcas marsupialis", "Bovidae", "Artiodactyla", "Mammalia", "Chordata",
        ["herbivore"], "grassland", "southern-africa", "medium",
        ["pronking"], None, "Q193459"),
    ("wildebeest", "Connochaetes taurinus", "Bovidae", "Artiodactyla", "Mammalia", "Chordata",
        ["herbivore"], "savanna", "east-africa", "large",
        ["migratory"], ["gnu", "blue-wildebeest"], "Q193459"),
    ("hartebeest", "Alcelaphus buselaphus", "Bovidae", "Artiodactyla", "Mammalia", "Chordata",
        ["herbivore"], "savanna", "africa", "medium",
        None, None, "Q193459"),
    ("oryx", "Oryx gazella", "Bovidae", "Artiodactyla", "Mammalia", "Chordata",
        ["herbivore"], "desert", "africa", "large",
        ["long-horns"], ["gemsbok"], "Q193459"),
    ("eland", "Taurotragus oryx", "Bovidae", "Artiodactyla", "Mammalia", "Chordata",
        ["herbivore"], "savanna", "africa", "large",
        ["largest-antelope"], ["common-eland"], "Q193459"),
    ("kudu", "Tragelaphus strepsiceros", "Bovidae", "Artiodactyla", "Mammalia", "Chordata",
        ["herbivore"], "woodland", "africa", "large",
        ["spiral-horns"], ["greater-kudu"], "Q193459"),
    ("nyala", "Tragelaphus angasii", "Bovidae", "Artiodactyla", "Mammalia", "Chordata",
        ["herbivore"], "woodland", "southern-africa", "medium",
        None, None, "Q193459"),
    ("bongo", "Tragelaphus eurycerus", "Bovidae", "Artiodactyla", "Mammalia", "Chordata",
        ["herbivore"], "jungle", "central-africa", "large",
        ["striped"], None, "Q193459"),
    ("buffalo", "Syncerus caffer", "Bovidae", "Artiodactyla", "Mammalia", "Chordata",
        ["herbivore"], "savanna", "africa", "large",
        ["aggressive"], ["cape-buffalo", "african-buffalo"], "Q193459"),
    ("water-buffalo", "Bubalus bubalis", "Bovidae", "Artiodactyla", "Mammalia", "Chordata",
        ["herbivore"], ["wetland", "farm"], "asia", "large",
        ["domesticated"], None, "Q193459"),
    ("bison", "Bison bison", "Bovidae", "Artiodactyla", "Mammalia", "Chordata",
        ["herbivore"], "prairie", "north-america", "large",
        ["herd-forming"], ["american-buffalo"], "Q193459"),
    ("yak", "Bos grunniens", "Bovidae", "Artiodactyla", "Mammalia", "Chordata",
        ["herbivore"], "highland", "tibet", "large",
        ["high-altitude"], None, "Q193459"),
    ("musk-ox", "Ovibos moschatus", "Bovidae", "Artiodactyla", "Mammalia", "Chordata",
        ["herbivore"], "tundra", "arctic", "large",
        ["defensive-circles"], None, "Q193459"),
    ("mountain-goat", "Oreamnos americanus", "Bovidae", "Artiodactyla", "Mammalia", "Chordata",
        ["herbivore"], "mountain", "north-america-west", "medium",
        ["climber"], None, "Q193459"),
    ("bighorn-sheep", "Ovis canadensis", "Bovidae", "Artiodactyla", "Mammalia", "Chordata",
        ["herbivore"], "mountain", "north-america", "medium",
        ["large-horns"], None, "Q193459"),
    ("goat", "Capra aegagrus hircus", "Bovidae", "Artiodactyla", "Mammalia", "Chordata",
        ["herbivore"], "worldwide", "worldwide", "medium",
        ["domesticated"], None, "Q193459"),
    ("sheep", "Ovis aries", "Bovidae", "Artiodactyla", "Mammalia", "Chordata",
        ["herbivore"], "worldwide", "worldwide", "medium",
        ["domesticated", "flock-animal"], None, "Q193459"),
    ("cow", "Bos taurus", "Bovidae", "Artiodactyla", "Mammalia", "Chordata",
        ["herbivore"], "worldwide", "worldwide", "large",
        ["domesticated", "milk-producer"], ["cattle", "bull", "heifer"], "Q193459"),
    ("pig", "Sus scrofa domesticus", "Suidae", "Artiodactyla", "Mammalia", "Chordata",
        ["omnivore"], "worldwide", "worldwide", "medium",
        ["domesticated", "intelligent"], ["hog", "swine"], "Q193459"),
    ("wild-boar", "Sus scrofa", "Suidae", "Artiodactyla", "Mammalia", "Chordata",
        ["omnivore"], "forest", "eurasia", "medium",
        ["tusked"], ["boar"], "Q193459"),
    ("warthog", "Phacochoerus africanus", "Suidae", "Artiodactyla", "Mammalia", "Chordata",
        ["omnivore"], "savanna", "africa", "medium",
        None, None, "Q193459"),
    ("peccary", "Pecari tajacu", "Tayassuidae", "Artiodactyla", "Mammalia", "Chordata",
        ["omnivore"], "jungle", "americas", "small",
        ["gregarious"], ["javelina"], "Q193459"),
    ("hippopotamus", "Hippopotamus amphibius", "Hippopotamidae", "Artiodactyla", "Mammalia", "Chordata",
        ["herbivore"], "river", "africa", "huge",
        ["semi-aquatic", "aggressive"], ["hippo"], "Q193459"),
    ("pygmy-hippo", "Choeropsis liberiensis", "Hippopotamidae", "Artiodactyla", "Mammalia", "Chordata",
        ["herbivore"], "jungle", "west-africa", "medium",
        None, None, "Q193459"),
    ("okapi", "Okapia johnstoni", "Giraffidae", "Artiodactyla", "Mammalia", "Chordata",
        ["herbivore"], "jungle", "central-africa", "large",
        ["giraffe-relative"], None, "Q193459"),
    ("chameleon-lizard", "Chamaeleo", "Chamaeleonidae", "Squamata", "Reptilia", "Chordata",
        ["insectivore"], "forest", "africa", "small",
        ["color-changing"], None, "Q193459"),
]
for e in MORE_MAMMALS:
    NODES.append(a(e[0], e[1], e[2], e[3], e[4], e[5], e[6], e[7], e[8], e[9],
                   syns=e[10], behavior=e[11], qid=e[12]))

# ---------- Extra birds ----------
MORE_BIRDS = [
    ("robin", "Turdus migratorius", "Turdidae", "Passeriformes", "Aves", "Chordata",
        ["omnivore"], "garden", "north-america", "tiny",
        ["red-breast"], ["american-robin"], "Q193459"),
    ("european-robin", "Erithacus rubecula", "Muscicapidae", "Passeriformes", "Aves", "Chordata",
        ["insectivore"], "garden", "europe", "tiny",
        ["red-breast"], None, "Q193459"),
    ("bluebird", "Sialia sialis", "Turdidae", "Passeriformes", "Aves", "Chordata",
        ["insectivore"], "meadow", "north-america", "tiny",
        None, ["eastern-bluebird"], "Q193459"),
    ("mockingbird", "Mimus polyglottos", "Mimidae", "Passeriformes", "Aves", "Chordata",
        ["omnivore"], "garden", "north-america", "tiny",
        ["mimic-calls"], ["northern-mockingbird"], "Q193459"),
    ("finch", "Fringillidae", "Fringillidae", "Passeriformes", "Aves", "Chordata",
        ["granivore"], "garden", "worldwide", "tiny",
        None, None, "Q193459"),
    ("goldfinch", "Spinus tristis", "Fringillidae", "Passeriformes", "Aves", "Chordata",
        ["granivore"], "garden", "north-america", "tiny",
        ["yellow-plumage"], ["american-goldfinch"], "Q193459"),
    ("cardinal", "Cardinalis cardinalis", "Cardinalidae", "Passeriformes", "Aves", "Chordata",
        ["granivore"], "garden", "north-america-east", "tiny",
        ["red-plumage"], ["northern-cardinal"], "Q193459"),
    ("bluejay", "Cyanocitta cristata", "Corvidae", "Passeriformes", "Aves", "Chordata",
        ["omnivore"], "forest", "north-america-east", "small",
        ["crest", "vocal"], ["blue-jay"], "Q193459"),
    ("magpie", "Pica pica", "Corvidae", "Passeriformes", "Aves", "Chordata",
        ["omnivore"], "field", "eurasia", "small",
        ["intelligent"], ["european-magpie"], "Q193459"),
    ("crow", "Corvus brachyrhynchos", "Corvidae", "Passeriformes", "Aves", "Chordata",
        ["omnivore"], "worldwide", "worldwide", "small",
        ["intelligent"], ["american-crow"], "Q193459"),
    ("raven", "Corvus corax", "Corvidae", "Passeriformes", "Aves", "Chordata",
        ["omnivore"], "forest", "worldwide", "medium",
        ["intelligent", "large-corvid"], ["common-raven"], "Q193459"),
    ("rook", "Corvus frugilegus", "Corvidae", "Passeriformes", "Aves", "Chordata",
        ["omnivore"], "farmland", "eurasia", "small",
        ["colonial"], None, "Q193459"),
    ("jackdaw", "Corvus monedula", "Corvidae", "Passeriformes", "Aves", "Chordata",
        ["omnivore"], "town", "eurasia", "small",
        ["gregarious"], None, "Q193459"),
    ("starling", "Sturnus vulgaris", "Sturnidae", "Passeriformes", "Aves", "Chordata",
        ["omnivore"], "worldwide", "eurasia-invasive", "tiny",
        ["murmurations", "mimic"], ["european-starling"], "Q193459"),
    ("sparrow", "Passer domesticus", "Passeridae", "Passeriformes", "Aves", "Chordata",
        ["granivore"], "worldwide", "worldwide", "tiny",
        None, ["house-sparrow"], "Q193459"),
    ("song-sparrow", "Melospiza melodia", "Passerellidae", "Passeriformes", "Aves", "Chordata",
        ["omnivore"], "garden", "north-america", "tiny",
        ["vocal"], None, "Q193459"),
    ("wren", "Troglodytes aedon", "Troglodytidae", "Passeriformes", "Aves", "Chordata",
        ["insectivore"], "garden", "americas", "tiny",
        ["loud-song"], ["house-wren"], "Q193459"),
    ("chickadee", "Poecile atricapillus", "Paridae", "Passeriformes", "Aves", "Chordata",
        ["omnivore"], "forest", "north-america", "tiny",
        None, ["black-capped-chickadee"], "Q193459"),
    ("nuthatch", "Sitta europaea", "Sittidae", "Passeriformes", "Aves", "Chordata",
        ["insectivore"], "forest", "eurasia", "tiny",
        ["climbs-down-trees"], ["eurasian-nuthatch"], "Q193459"),
    ("titmouse", "Baeolophus bicolor", "Paridae", "Passeriformes", "Aves", "Chordata",
        ["insectivore"], "forest", "north-america-east", "tiny",
        None, ["tufted-titmouse"], "Q193459"),
    ("warbler", "Parulidae", "Parulidae", "Passeriformes", "Aves", "Chordata",
        ["insectivore"], "forest", "americas", "tiny",
        ["migratory", "colorful"], None, "Q193459"),
    ("hummingbird", "Trochilidae", "Trochilidae", "Apodiformes", "Aves", "Chordata",
        ["nectarivore"], "garden", "americas", "tiny",
        ["hovering", "rapid-wingbeat"], None, "Q193459"),
    ("ruby-throated-hummingbird", "Archilochus colubris", "Trochilidae", "Apodiformes", "Aves", "Chordata",
        ["nectarivore"], "garden", "north-america-east", "tiny",
        None, None, "Q193459"),
    ("swift", "Apus apus", "Apodidae", "Apodiformes", "Aves", "Chordata",
        ["insectivore"], "air", "eurasia", "tiny",
        ["aerial-life"], ["common-swift"], "Q193459"),
    ("swallow", "Hirundo rustica", "Hirundinidae", "Passeriformes", "Aves", "Chordata",
        ["insectivore"], "farm", "worldwide", "tiny",
        ["fork-tail"], ["barn-swallow"], "Q193459"),
    ("martin", "Progne subis", "Hirundinidae", "Passeriformes", "Aves", "Chordata",
        ["insectivore"], "garden", "americas", "tiny",
        None, ["purple-martin"], "Q193459"),
    ("kingfisher", "Alcedo atthis", "Alcedinidae", "Coraciiformes", "Aves", "Chordata",
        ["piscivore"], "river", "eurasia", "tiny",
        ["diving"], ["common-kingfisher"], "Q193459"),
    ("belted-kingfisher", "Megaceryle alcyon", "Cerylidae", "Coraciiformes", "Aves", "Chordata",
        ["piscivore"], "river", "north-america", "small",
        None, None, "Q193459"),
    ("hornbill", "Bucerotidae", "Bucerotidae", "Bucerotiformes", "Aves", "Chordata",
        ["omnivore"], "jungle", ["africa", "asia"], "medium",
        ["large-beak", "casque"], None, "Q193459"),
    ("toucan", "Ramphastos toco", "Ramphastidae", "Piciformes", "Aves", "Chordata",
        ["frugivore"], "jungle", "south-america", "small",
        ["large-beak", "colorful"], ["toco-toucan"], "Q193459"),
    ("woodpecker", "Picidae", "Picidae", "Piciformes", "Aves", "Chordata",
        ["insectivore"], "forest", "worldwide", "small",
        ["drumming"], None, "Q193459"),
    ("pileated-woodpecker", "Dryocopus pileatus", "Picidae", "Piciformes", "Aves", "Chordata",
        ["insectivore"], "forest", "north-america", "small",
        ["large-woodpecker"], None, "Q193459"),
    ("flicker", "Colaptes auratus", "Picidae", "Piciformes", "Aves", "Chordata",
        ["insectivore"], "field", "north-america", "small",
        ["ground-feeder"], ["northern-flicker"], "Q193459"),
    ("parrot", "Psittaciformes", "Psittacidae", "Psittaciformes", "Aves", "Chordata",
        ["frugivore"], "jungle", "tropics-worldwide", "small",
        ["vocal", "intelligent"], None, "Q193459"),
    ("cockatoo", "Cacatuidae", "Cacatuidae", "Psittaciformes", "Aves", "Chordata",
        ["frugivore"], "forest", "australia", "small",
        ["crest"], None, "Q193459"),
    ("macaw", "Ara macao", "Psittacidae", "Psittaciformes", "Aves", "Chordata",
        ["frugivore"], "jungle", "central-america", "small",
        ["colorful", "long-tail"], ["scarlet-macaw"], "Q193459"),
    ("budgerigar", "Melopsittacus undulatus", "Psittaculidae", "Psittaciformes", "Aves", "Chordata",
        ["granivore"], ["grassland", "pet"], "australia", "tiny",
        None, ["budgie", "parakeet"], "Q193459"),
    ("cockatiel", "Nymphicus hollandicus", "Cacatuidae", "Psittaciformes", "Aves", "Chordata",
        ["granivore"], ["scrubland", "pet"], "australia", "tiny",
        None, None, "Q193459"),
    ("owl", "Strigiformes", "Strigidae", "Strigiformes", "Aves", "Chordata",
        ["carnivore"], "worldwide", "worldwide", "small",
        ["nocturnal"], None, "Q193459"),
    ("great-horned-owl", "Bubo virginianus", "Strigidae", "Strigiformes", "Aves", "Chordata",
        ["carnivore"], "forest", "americas", "medium",
        ["ear-tufts"], None, "Q193459"),
    ("barn-owl", "Tyto alba", "Tytonidae", "Strigiformes", "Aves", "Chordata",
        ["carnivore"], "farm", "worldwide", "small",
        ["heart-shaped-face"], None, "Q193459"),
    ("snowy-owl", "Bubo scandiacus", "Strigidae", "Strigiformes", "Aves", "Chordata",
        ["carnivore"], "tundra", "arctic", "medium",
        ["white-plumage"], None, "Q193459"),
    ("eagle", "Aquila chrysaetos", "Accipitridae", "Accipitriformes", "Aves", "Chordata",
        ["carnivore"], "mountain", "north-hemisphere", "large",
        None, ["golden-eagle"], "Q193459"),
    ("bald-eagle", "Haliaeetus leucocephalus", "Accipitridae", "Accipitriformes", "Aves", "Chordata",
        ["piscivore"], ["coast", "river"], "north-america", "large",
        None, None, "Q193459"),
    ("harpy-eagle", "Harpia harpyja", "Accipitridae", "Accipitriformes", "Aves", "Chordata",
        ["carnivore"], "jungle", "americas", "large",
        ["largest-eagle"], None, "Q193459"),
    ("hawk", "Buteo jamaicensis", "Accipitridae", "Accipitriformes", "Aves", "Chordata",
        ["carnivore"], "worldwide", "worldwide", "medium",
        None, ["red-tailed-hawk"], "Q193459"),
    ("falcon", "Falco peregrinus", "Falconidae", "Falconiformes", "Aves", "Chordata",
        ["carnivore"], "worldwide", "worldwide", "small",
        ["fastest-animal"], ["peregrine-falcon"], "Q193459"),
    ("kestrel", "Falco tinnunculus", "Falconidae", "Falconiformes", "Aves", "Chordata",
        ["carnivore"], "farmland", "eurasia", "small",
        ["hovering"], ["common-kestrel"], "Q193459"),
    ("osprey", "Pandion haliaetus", "Pandionidae", "Accipitriformes", "Aves", "Chordata",
        ["piscivore"], ["river", "coast"], "worldwide", "medium",
        ["fish-hunter"], ["fish-hawk"], "Q193459"),
    ("vulture", "Cathartes aura", "Cathartidae", "Cathartiformes", "Aves", "Chordata",
        ["scavenger"], "worldwide", "americas", "medium",
        None, ["turkey-vulture"], "Q193459"),
    ("condor", "Vultur gryphus", "Cathartidae", "Cathartiformes", "Aves", "Chordata",
        ["scavenger"], "mountain", "andes", "large",
        None, ["andean-condor"], "Q193459"),
    ("california-condor", "Gymnogyps californianus", "Cathartidae", "Cathartiformes", "Aves", "Chordata",
        ["scavenger"], "mountain", "north-america-west", "large",
        None, None, "Q193459"),
    ("stork", "Ciconia ciconia", "Ciconiidae", "Ciconiiformes", "Aves", "Chordata",
        ["carnivore"], "wetland", "eurasia", "large",
        None, ["white-stork"], "Q193459"),
    ("heron", "Ardea", "Ardeidae", "Pelecaniformes", "Aves", "Chordata",
        ["piscivore"], "wetland", "worldwide", "medium",
        None, None, "Q193459"),
    ("great-blue-heron", "Ardea herodias", "Ardeidae", "Pelecaniformes", "Aves", "Chordata",
        ["piscivore"], "wetland", "north-america", "large",
        None, None, "Q193459"),
    ("egret", "Ardea alba", "Ardeidae", "Pelecaniformes", "Aves", "Chordata",
        ["piscivore"], "wetland", "worldwide", "medium",
        ["white-plumage"], ["great-egret"], "Q193459"),
    ("ibis", "Eudocimus albus", "Threskiornithidae", "Pelecaniformes", "Aves", "Chordata",
        ["omnivore"], "wetland", "americas", "medium",
        None, ["white-ibis"], "Q193459"),
    ("spoonbill", "Platalea alba", "Threskiornithidae", "Pelecaniformes", "Aves", "Chordata",
        ["omnivore"], "wetland", "africa", "medium",
        ["spatulate-beak"], None, "Q193459"),
    ("flamingo", "Phoenicopterus roseus", "Phoenicopteridae", "Phoenicopteriformes", "Aves", "Chordata",
        ["filter-feeder"], "lake", "africa", "medium",
        ["pink-plumage", "one-legged-stand"], ["greater-flamingo"], "Q193459"),
    ("pelican", "Pelecanus", "Pelecanidae", "Pelecaniformes", "Aves", "Chordata",
        ["piscivore"], "coast", "worldwide", "large",
        ["pouched-beak"], None, "Q193459"),
    ("cormorant", "Phalacrocorax", "Phalacrocoracidae", "Suliformes", "Aves", "Chordata",
        ["piscivore"], ["coast", "river"], "worldwide", "medium",
        ["diving"], None, "Q193459"),
    ("gannet", "Morus bassanus", "Sulidae", "Suliformes", "Aves", "Chordata",
        ["piscivore"], "coast", "north-atlantic", "medium",
        ["plunge-diver"], ["northern-gannet"], "Q193459"),
    ("albatross", "Diomedea exulans", "Diomedeidae", "Procellariiformes", "Aves", "Chordata",
        ["piscivore"], "ocean", "southern-ocean", "large",
        ["largest-wingspan"], ["wandering-albatross"], "Q193459"),
    ("petrel", "Fulmarus glacialis", "Procellariidae", "Procellariiformes", "Aves", "Chordata",
        ["piscivore"], "ocean", "north-atlantic", "small",
        None, ["northern-fulmar"], "Q193459"),
    ("puffin", "Fratercula arctica", "Alcidae", "Charadriiformes", "Aves", "Chordata",
        ["piscivore"], "coast", "north-atlantic", "small",
        ["colorful-beak"], ["atlantic-puffin"], "Q193459"),
    ("penguin", "Aptenodytes forsteri", "Spheniscidae", "Sphenisciformes", "Aves", "Chordata",
        ["piscivore"], "antarctica", "antarctica", "medium",
        ["flightless", "swimming"], ["emperor-penguin"], "Q193459"),
    ("king-penguin", "Aptenodytes patagonicus", "Spheniscidae", "Sphenisciformes", "Aves", "Chordata",
        ["piscivore"], "subantarctic", "subantarctic-islands", "medium",
        None, None, "Q193459"),
    ("adelie-penguin", "Pygoscelis adeliae", "Spheniscidae", "Sphenisciformes", "Aves", "Chordata",
        ["piscivore"], "antarctica", "antarctica", "small",
        None, None, "Q193459"),
    ("gull", "Larus", "Laridae", "Charadriiformes", "Aves", "Chordata",
        ["omnivore"], "coast", "worldwide", "small",
        None, ["seagull"], "Q193459"),
    ("tern", "Sterna hirundo", "Laridae", "Charadriiformes", "Aves", "Chordata",
        ["piscivore"], "coast", "worldwide", "small",
        None, ["common-tern"], "Q193459"),
    ("sandpiper", "Actitis macularius", "Scolopacidae", "Charadriiformes", "Aves", "Chordata",
        ["insectivore"], "beach", "americas", "tiny",
        None, ["spotted-sandpiper"], "Q193459"),
    ("plover", "Charadrius vociferus", "Charadriidae", "Charadriiformes", "Aves", "Chordata",
        ["insectivore"], "field", "north-america", "tiny",
        None, ["killdeer"], "Q193459"),
    ("duck", "Anas platyrhynchos", "Anatidae", "Anseriformes", "Aves", "Chordata",
        ["omnivore"], "pond", "worldwide", "small",
        None, ["mallard"], "Q193459"),
    ("wood-duck", "Aix sponsa", "Anatidae", "Anseriformes", "Aves", "Chordata",
        ["omnivore"], "pond", "north-america", "small",
        ["colorful-male"], None, "Q193459"),
    ("teal", "Anas crecca", "Anatidae", "Anseriformes", "Aves", "Chordata",
        ["omnivore"], "wetland", "north-hemisphere", "small",
        None, ["green-winged-teal"], "Q193459"),
    ("pintail", "Anas acuta", "Anatidae", "Anseriformes", "Aves", "Chordata",
        ["omnivore"], "wetland", "north-hemisphere", "small",
        None, ["northern-pintail"], "Q193459"),
    ("goose", "Anser anser", "Anatidae", "Anseriformes", "Aves", "Chordata",
        ["herbivore"], "wetland", "eurasia", "medium",
        ["migratory"], ["greylag-goose"], "Q193459"),
    ("canada-goose", "Branta canadensis", "Anatidae", "Anseriformes", "Aves", "Chordata",
        ["herbivore"], "wetland", "north-america", "medium",
        ["v-formation"], None, "Q193459"),
    ("swan", "Cygnus olor", "Anatidae", "Anseriformes", "Aves", "Chordata",
        ["herbivore"], "lake", "eurasia", "large",
        ["long-neck"], ["mute-swan"], "Q193459"),
    ("trumpeter-swan", "Cygnus buccinator", "Anatidae", "Anseriformes", "Aves", "Chordata",
        ["herbivore"], "lake", "north-america", "large",
        None, None, "Q193459"),
    ("black-swan", "Cygnus atratus", "Anatidae", "Anseriformes", "Aves", "Chordata",
        ["herbivore"], "wetland", "australia", "large",
        None, None, "Q193459"),
    ("chicken", "Gallus gallus domesticus", "Phasianidae", "Galliformes", "Aves", "Chordata",
        ["omnivore"], "farm", "worldwide", "small",
        ["domesticated"], ["hen", "rooster", "chick"], "Q193459"),
    ("turkey", "Meleagris gallopavo", "Phasianidae", "Galliformes", "Aves", "Chordata",
        ["omnivore"], "forest", "north-america", "medium",
        ["domesticated-and-wild"], ["wild-turkey"], "Q193459"),
    ("pheasant", "Phasianus colchicus", "Phasianidae", "Galliformes", "Aves", "Chordata",
        ["omnivore"], "farmland", "eurasia", "small",
        None, ["common-pheasant"], "Q193459"),
    ("quail", "Coturnix coturnix", "Phasianidae", "Galliformes", "Aves", "Chordata",
        ["granivore"], "grassland", "eurasia", "tiny",
        None, ["common-quail"], "Q193459"),
    ("partridge", "Perdix perdix", "Phasianidae", "Galliformes", "Aves", "Chordata",
        ["omnivore"], "farmland", "eurasia", "small",
        None, ["grey-partridge"], "Q193459"),
    ("grouse", "Tetrao urogallus", "Phasianidae", "Galliformes", "Aves", "Chordata",
        ["omnivore"], "boreal-forest", "eurasia", "medium",
        None, ["capercaillie"], "Q193459"),
    ("dove", "Streptopelia decaocto", "Columbidae", "Columbiformes", "Aves", "Chordata",
        ["granivore"], "worldwide", "eurasia", "tiny",
        None, ["eurasian-collared-dove"], "Q193459"),
    ("mourning-dove", "Zenaida macroura", "Columbidae", "Columbiformes", "Aves", "Chordata",
        ["granivore"], "worldwide", "north-america", "tiny",
        ["mournful-call"], None, "Q193459"),
    ("pigeon", "Columba livia", "Columbidae", "Columbiformes", "Aves", "Chordata",
        ["granivore"], "urban", "worldwide", "small",
        None, ["rock-dove", "rock-pigeon"], "Q193459"),
    ("cuckoo", "Cuculus canorus", "Cuculidae", "Cuculiformes", "Aves", "Chordata",
        ["insectivore"], "forest", "eurasia", "small",
        ["brood-parasite"], ["common-cuckoo"], "Q193459"),
    ("roadrunner", "Geococcyx californianus", "Cuculidae", "Cuculiformes", "Aves", "Chordata",
        ["carnivore"], "desert", "north-america-southwest", "small",
        ["fast-runner"], ["greater-roadrunner"], "Q193459"),
    ("ostrich", "Struthio camelus", "Struthionidae", "Struthioniformes", "Aves", "Chordata",
        ["omnivore"], "savanna", "africa", "huge",
        ["largest-bird", "flightless", "fast-runner"], None, "Q193459"),
    ("emu", "Dromaius novaehollandiae", "Dromaiidae", "Casuariiformes", "Aves", "Chordata",
        ["omnivore"], "grassland", "australia", "large",
        ["flightless"], None, "Q193459"),
    ("cassowary", "Casuarius casuarius", "Casuariidae", "Casuariiformes", "Aves", "Chordata",
        ["omnivore"], "jungle", "australia-new-guinea", "large",
        ["flightless", "dangerous"], ["southern-cassowary"], "Q193459"),
    ("kiwi", "Apteryx mantelli", "Apterygidae", "Apterygiformes", "Aves", "Chordata",
        ["insectivore"], "forest", "new-zealand", "small",
        ["flightless"], ["north-island-brown-kiwi"], "Q193459"),
    ("rhea", "Rhea americana", "Rheidae", "Rheiformes", "Aves", "Chordata",
        ["omnivore"], "grassland", "south-america", "large",
        ["flightless"], ["greater-rhea"], "Q193459"),
    ("kakapo", "Strigops habroptilus", "Strigopidae", "Psittaciformes", "Aves", "Chordata",
        ["herbivore"], "forest", "new-zealand", "medium",
        ["flightless", "nocturnal", "critically-endangered"], None, "Q193459"),
    ("kea", "Nestor notabilis", "Strigopidae", "Psittaciformes", "Aves", "Chordata",
        ["omnivore"], "mountain", "new-zealand", "small",
        ["intelligent", "playful"], None, "Q193459"),
    ("bird-of-paradise-species", "Paradisaea", "Paradisaeidae", "Passeriformes", "Aves", "Chordata",
        ["frugivore"], "jungle", "new-guinea", "small",
        ["ornate-plumage"], None, "Q193459"),
    ("secretary-bird", "Sagittarius serpentarius", "Sagittariidae", "Accipitriformes", "Aves", "Chordata",
        ["carnivore"], "savanna", "africa", "large",
        ["long-legs", "snake-hunter"], None, "Q193459"),
    ("shoebill", "Balaeniceps rex", "Balaenicipitidae", "Pelecaniformes", "Aves", "Chordata",
        ["carnivore"], "wetland", "east-africa", "large",
        ["shoe-shaped-beak"], ["whalehead"], "Q193459"),
    ("kookaburra", "Dacelo novaeguineae", "Halcyonidae", "Coraciiformes", "Aves", "Chordata",
        ["carnivore"], "forest", "australia", "small",
        ["laughing-call"], ["laughing-kookaburra"], "Q193459"),
    ("lyrebird", "Menura novaehollandiae", "Menuridae", "Passeriformes", "Aves", "Chordata",
        ["omnivore"], "forest", "australia", "medium",
        ["mimic", "elaborate-tail"], ["superb-lyrebird"], "Q193459"),
]
for e in MORE_BIRDS:
    NODES.append(a(e[0], e[1], e[2], e[3], e[4], e[5], e[6], e[7], e[8], e[9],
                   syns=e[10], behavior=e[11], qid=e[12]))
