"""Explicit cross-graph edges. Complements the auto-generated cross-refs
that come from :material-for and :has-products-in facets on individual nodes.

Focus: hand-authored high-value edges into graph-of-store, graph-of-life,
graph-of-science, graph-of-event.
"""

NODES = []  # this file emits no nodes


CROSS_EDGES = []

# ----- world → store: material sourcing edges -----
STORE_MATERIAL_EDGES = [
    # (world-material, store-category, weight)
    ("wood", "furniture", 1.0),
    ("wood", "toys", 0.8),
    ("wood", "kitchenware", 0.6),
    ("oak-wood", "furniture", 1.0),
    ("oak-wood", "flooring", 0.9),
    ("pine-wood", "furniture", 0.9),
    ("pine-wood", "construction-materials", 0.9),
    ("maple-wood", "furniture", 0.8),
    ("maple-wood", "musical-instruments", 0.7),
    ("cherry-wood", "furniture", 0.8),
    ("walnut-wood", "furniture", 0.7),
    ("cedar-wood", "closets", 0.7),
    ("bamboo-material", "furniture", 0.7),
    ("bamboo-material", "flooring", 0.7),
    ("cotton", "shirts", 1.0),
    ("cotton", "sheets", 1.0),
    ("cotton", "towels", 1.0),
    ("cotton", "socks", 0.8),
    ("linen", "clothing", 0.7),
    ("silk", "scarves", 0.9),
    ("silk", "ties", 0.9),
    ("wool", "sweaters", 1.0),
    ("wool", "carpets", 0.8),
    ("wool", "coats", 0.9),
    ("cashmere", "sweaters", 0.8),
    ("mohair", "sweaters", 0.7),
    ("alpaca-fiber", "sweaters", 0.7),
    ("leather", "shoes", 1.0),
    ("leather", "belts", 1.0),
    ("leather", "wallets", 0.9),
    ("leather", "jackets", 0.9),
    ("leather", "handbags", 0.9),
    ("suede", "shoes", 0.7),
    ("suede", "jackets", 0.7),
    ("fur", "coats", 0.6),
    ("down-fiber", "jackets", 0.7),
    ("down-fiber", "pillows", 0.8),
    ("down-fiber", "comforters", 0.9),
    ("feather", "pillows", 0.8),
    ("polyester", "shirts", 0.8),
    ("polyester", "jackets", 0.7),
    ("nylon", "backpacks", 0.8),
    ("nylon", "stockings", 0.7),
    ("spandex", "leggings", 0.9),
    ("rayon", "linings", 0.8),
    ("acrylic-fiber", "sweaters", 0.7),
    ("polar-fleece", "jackets", 0.8),
    ("canvas", "bags", 0.9),
    ("canvas", "tents", 0.8),
    ("canvas", "shoes", 0.6),
    ("denim", "jeans", 1.0),
    ("denim", "jackets", 0.7),
    ("felt", "hats", 0.7),
    ("felt", "crafts", 0.6),
    ("velvet", "upholstery", 0.7),
    ("iron", "tools", 0.9),
    ("iron", "cookware", 0.7),
    ("steel", "tools", 0.9),
    ("steel", "kitchenware", 0.9),
    ("steel", "furniture", 0.6),
    ("stainless-steel", "cookware", 0.9),
    ("stainless-steel", "sinks", 0.9),
    ("cast-iron", "cookware", 0.9),
    ("aluminum", "cookware", 0.7),
    ("aluminum", "cans", 0.9),
    ("copper", "cookware", 0.7),
    ("copper", "wiring", 0.9),
    ("brass", "instruments", 0.7),
    ("brass", "hardware", 0.7),
    ("bronze", "sculpture", 0.8),
    ("gold", "jewelry", 1.0),
    ("silver", "jewelry", 0.9),
    ("silver", "silverware", 0.9),
    ("platinum", "jewelry", 0.7),
    ("sterling-silver", "jewelry", 0.8),
    ("clay", "pottery", 1.0),
    ("clay", "bricks", 0.8),
    ("ceramic", "dinnerware", 0.9),
    ("ceramic", "tiles", 0.8),
    ("porcelain", "dinnerware", 0.9),
    ("stoneware", "dinnerware", 0.8),
    ("earthenware", "planters", 0.7),
    ("terracotta", "planters", 0.9),
    ("glass", "windows", 0.9),
    ("glass", "bottles", 0.9),
    ("glass", "vases", 0.8),
    ("crystal", "glassware", 0.7),
    ("tempered-glass", "phone-screens", 0.7),
    ("stone", "sculpture", 0.7),
    ("granite", "countertops", 0.9),
    ("marble", "sculpture", 0.8),
    ("marble", "countertops", 0.7),
    ("slate", "roofing", 0.7),
    ("plastic", "toys", 0.9),
    ("plastic", "containers", 0.9),
    ("rubber", "tires", 1.0),
    ("rubber", "gloves", 0.8),
    ("silicone-material", "cookware", 0.7),
    ("teflon", "cookware", 0.8),
    ("paper", "books", 0.9),
    ("paper", "packaging", 0.8),
    ("cardboard", "boxes", 1.0),
    # animal-derived
    ("pearl", "jewelry", 0.8),
    ("mother-of-pearl", "jewelry", 0.7),
    ("amber", "jewelry", 0.7),
    ("ivory", "jewelry", 0.5),
    ("beeswax", "candles", 0.9),
    ("horn", "buttons", 0.5),
    ("bone", "buttons", 0.4),
    ("shell-material", "jewelry", 0.6),
    # gems + minerals
    ("diamond", "jewelry", 1.0),
    ("ruby", "jewelry", 1.0),
    ("sapphire", "jewelry", 1.0),
    ("emerald", "jewelry", 1.0),
    ("topaz", "jewelry", 0.9),
    ("amethyst", "jewelry", 0.9),
    ("opal", "jewelry", 0.9),
    ("turquoise", "jewelry", 0.9),
    ("jade", "jewelry", 0.8),
    ("garnet", "jewelry", 0.8),
    ("moonstone", "jewelry", 0.7),
    ("labradorite", "jewelry", 0.7),
    ("lapis-lazuli", "jewelry", 0.7),
    ("malachite", "jewelry", 0.6),
    ("agate", "jewelry", 0.7),
    ("onyx", "jewelry", 0.7),
    ("peridot", "jewelry", 0.6),
    ("aquamarine", "jewelry", 0.7),
    ("tanzanite", "jewelry", 0.5),
    ("citrine", "jewelry", 0.7),
    ("obsidian", "jewelry", 0.5),
    ("tigers-eye", "jewelry", 0.5),
    ("azurite", "jewelry", 0.4),
]

for src, tgt, w in STORE_MATERIAL_EDGES:
    CROSS_EDGES.append({
        "type": "material-for",
        "from": "world/" + src,
        "to": "store/" + tgt,
        "from_graph": "graph-of-world",
        "to_graph": "store-objects",
        "weight": w,
    })
    CROSS_EDGES.append({
        "type": "made-of",
        "from": "store/" + tgt,
        "to": "world/" + src,
        "from_graph": "store-objects",
        "to_graph": "graph-of-world",
        "weight": w,
    })

# ----- world → store: species → products for species -----
SPECIES_PRODUCT_EDGES = [
    # (world-species, store-category, weight)
    ("dog", "dog-food", 1.0),
    ("dog", "dog-collar", 1.0),
    ("dog", "dog-leash", 0.9),
    ("dog", "dog-toys", 0.9),
    ("dog", "dog-bed", 0.9),
    ("dog", "dog-crate", 0.7),
    ("dog", "dog-harness", 0.8),
    ("cat", "cat-food", 1.0),
    ("cat", "cat-litter", 1.0),
    ("cat", "cat-toys", 0.9),
    ("cat", "cat-tree", 0.9),
    ("cat", "cat-collar", 0.8),
    ("cat", "cat-carrier", 0.8),
    ("rabbit", "rabbit-food", 0.9),
    ("rabbit", "rabbit-hutch", 0.9),
    ("hamster", "hamster-cage", 0.9),
    ("hamster", "hamster-wheel", 0.9),
    ("guinea-pig", "guinea-pig-cage", 0.9),
    ("bird", "bird-cage", 0.8),
    ("bird", "bird-feeder", 0.9),
    ("bird", "bird-seed", 0.9),
    ("parrot", "parrot-food", 0.9),
    ("parrot", "parrot-cage", 0.9),
    ("goldfish", "aquarium", 0.9),
    ("goldfish", "fish-food", 0.9),
    ("betta", "betta-tank", 0.9),
    ("horse", "horse-saddle", 0.9),
    ("horse", "horse-bridle", 0.9),
    ("horse", "horse-blanket", 0.8),
    ("horse", "horseshoes", 0.9),
    ("horse", "horse-brush", 0.8),
    ("chicken", "chicken-feed", 0.9),
    ("chicken", "chicken-coop", 0.9),
    ("cow", "cattle-feed", 0.9),
    ("bee", "beekeeping-supplies", 0.9),
    ("honey-bee", "beekeeping-supplies", 0.9),
    ("silkworm", "silkworm-food", 0.6),
]
for src, tgt, w in SPECIES_PRODUCT_EDGES:
    CROSS_EDGES.append({
        "type": "sold-for-species",
        "from": "world/" + src,
        "to": "store/" + tgt,
        "from_graph": "graph-of-world",
        "to_graph": "store-objects",
        "weight": w,
    })
    CROSS_EDGES.append({
        "type": "for-species",
        "from": "store/" + tgt,
        "to": "world/" + src,
        "from_graph": "store-objects",
        "to_graph": "graph-of-world",
        "weight": w,
    })

# ----- world → store: seasonal-for edges -----
SEASONAL_EDGES = [
    ("winter", "coats", 0.9),
    ("winter", "scarves", 0.9),
    ("winter", "gloves", 0.9),
    ("winter", "boots", 0.8),
    ("winter", "sweaters", 0.9),
    ("winter", "hats", 0.7),
    ("winter", "snow-shovels", 0.9),
    ("winter", "ice-skates", 0.8),
    ("winter", "ski-equipment", 0.9),
    ("summer", "swimwear", 0.9),
    ("summer", "sandals", 0.8),
    ("summer", "sunglasses", 0.7),
    ("summer", "beach-towels", 0.9),
    ("summer", "cooler", 0.7),
    ("summer", "air-conditioners", 0.8),
    ("summer", "grills", 0.8),
    ("summer", "outdoor-furniture", 0.7),
    ("spring", "rain-boots", 0.7),
    ("spring", "umbrellas", 0.7),
    ("spring", "gardening-tools", 0.9),
    ("spring", "seeds", 0.9),
    ("autumn", "rakes", 0.9),
    ("autumn", "pumpkin-decorations", 0.8),
    ("autumn", "back-to-school-supplies", 0.9),
    ("cherry-blossom-season", "picnic-blankets", 0.6),
    ("harvest-season", "canning-jars", 0.7),
    ("harvest-season", "baskets", 0.7),
]
for src, tgt, w in SEASONAL_EDGES:
    CROSS_EDGES.append({
        "type": "seasonal-for",
        "from": "world/" + src,
        "to": "store/" + tgt,
        "from_graph": "graph-of-world",
        "to_graph": "store-objects",
        "weight": w,
    })

# ----- world → life: setting-for edges -----
SETTING_EDGES = [
    # (world-node, life-scenario, weight)
    ("kitchen", "cooking-scenario", 1.0),
    ("kitchen", "morning-coffee", 0.9),
    ("kitchen", "family-dinner", 0.9),
    ("bedroom", "sleeping-scenario", 1.0),
    ("bedroom", "morning-alarm", 0.9),
    ("living-room", "family-time", 0.9),
    ("living-room", "movie-night", 0.9),
    ("bathroom", "morning-routine", 0.9),
    ("bathroom", "bath-time", 0.9),
    ("garden-yard", "gardening", 1.0),
    ("garden-yard", "outdoor-play", 0.9),
    ("park", "picnic", 0.9),
    ("park", "dog-walking", 0.9),
    ("beach", "beach-day", 1.0),
    ("beach", "sandcastle-building", 0.8),
    ("forest", "hiking", 0.9),
    ("forest", "camping", 0.8),
    ("mountain", "hiking", 0.9),
    ("mountain", "skiing", 0.9),
    ("river", "fishing", 0.9),
    ("river", "kayaking", 0.8),
    ("lake", "swimming", 0.8),
    ("morning", "wake-up", 1.0),
    ("morning", "school-run", 0.9),
    ("evening", "dinner-time", 0.9),
    ("evening", "bedtime-routine", 0.8),
    ("night", "sleeping", 1.0),
    ("rain", "staying-inside", 0.8),
    ("snow", "snow-day", 0.9),
    ("winter", "cozy-fireside", 0.8),
    ("summer", "vacation", 0.9),
    ("spring", "spring-cleaning", 0.8),
    ("autumn", "leaf-raking", 0.8),
]
for src, tgt, w in SETTING_EDGES:
    CROSS_EDGES.append({
        "type": "setting-for",
        "from": "world/" + src,
        "to": "life/" + tgt,
        "from_graph": "graph-of-world",
        "to_graph": "graph-of-life",
        "weight": w,
    })

# ----- world → science: natural phenomena → laws -----
SCIENCE_EDGES = [
    # (world-phenomenon, science-topic, weight)
    ("rainbow", "light-refraction", 0.9),
    ("lightning", "electrical-discharge", 0.9),
    ("thunder", "sound-propagation", 0.8),
    ("earthquake", "plate-tectonics", 0.9),
    ("tsunami", "wave-mechanics", 0.9),
    ("aurora", "solar-wind-magnetosphere", 0.9),
    ("volcanic-eruption", "plate-tectonics", 0.9),
    ("hurricane", "atmospheric-dynamics", 0.9),
    ("tornado", "atmospheric-dynamics", 0.9),
    ("tide", "gravitational-effects", 0.9),
    ("solar-eclipse", "orbital-mechanics", 0.9),
    ("lunar-eclipse", "orbital-mechanics", 0.9),
    ("equinox", "earths-axial-tilt", 0.9),
    ("solstice", "earths-axial-tilt", 0.9),
    ("photosynthesis", "biochemistry", 0.9),
    ("fog", "condensation", 0.8),
    ("snow", "crystallization", 0.7),
    ("hail", "atmospheric-convection", 0.8),
    ("cloud", "water-cycle", 0.9),
    ("rain", "water-cycle", 0.9),
    ("dew", "condensation", 0.8),
    ("frost", "sublimation-condensation", 0.7),
    ("wind", "atmospheric-pressure", 0.9),
    ("mirage", "atmospheric-refraction", 0.8),
    ("green-flash", "atmospheric-refraction", 0.6),
    ("halo", "ice-crystal-optics", 0.7),
]
for src, tgt, w in SCIENCE_EDGES:
    CROSS_EDGES.append({
        "type": "phenomenon-of",
        "from": "world/" + src,
        "to": "science/" + tgt,
        "from_graph": "graph-of-world",
        "to_graph": "graph-of-science",
        "weight": w,
    })

# ----- world → life: species → common human relationship -----
LIFE_RELATION_EDGES = [
    ("dog", "companion-animal", 1.0),
    ("cat", "companion-animal", 1.0),
    ("horse", "companion-animal", 0.8),
    ("horse", "working-animal", 0.7),
    ("cow", "livestock", 0.9),
    ("sheep", "livestock", 0.9),
    ("goat", "livestock", 0.9),
    ("chicken", "livestock", 0.9),
    ("pig", "livestock", 0.9),
    ("bee", "beneficial-insect", 0.9),
    ("ladybug", "beneficial-insect", 0.7),
    ("butterfly", "beneficial-insect", 0.7),
    ("earthworm", "beneficial-invertebrate", 0.8),
    ("spider", "helpful-in-garden", 0.7),
    ("mosquito", "pest", 0.8),
    ("housefly", "pest", 0.6),
    ("rat", "pest", 0.7),
    ("mouse", "pest", 0.7),
    ("termite", "structural-pest", 0.8),
    ("bed-bug", "structural-pest", 0.9),
    ("wolf", "wildlife-large-predator", 0.8),
    ("bear", "wildlife-large-predator", 0.8),
    ("lion", "wildlife-large-predator", 0.9),
    ("tiger", "wildlife-large-predator", 0.9),
    ("elephant", "wildlife-flagship-species", 0.9),
    ("giraffe", "wildlife-flagship-species", 0.9),
    ("panda", "wildlife-flagship-species", 0.9),
    ("polar-bear", "wildlife-flagship-species", 0.9),
    ("whale", "wildlife-marine-flagship", 0.9),
    ("dolphin", "wildlife-marine-flagship", 0.9),
    ("penguin", "wildlife-cold-flagship", 0.8),
]
for src, tgt, w in LIFE_RELATION_EDGES:
    CROSS_EDGES.append({
        "type": "human-relationship",
        "from": "world/" + src,
        "to": "life/" + tgt,
        "from_graph": "graph-of-world",
        "to_graph": "graph-of-life",
        "weight": w,
    })
